- clib/gc_chooser.h
- src/compiler/separate_erasure_compiler.nit
Fix two warnings in the C code.
> Less CC warnings

- contrib/jwrapper/README.md
- contrib/jwrapper/src/code_generator.nit
- contrib/jwrapper/src/jtype_converter.nit
- contrib/jwrapper/src/types.nit
Simplify a lot the code, but will strike a single item from the TODO list #794.
@Freddrickk j'efface toute la logique de gestion des arrays car #1079 wrap les array Java. Est-ce que j'ai ai trop enlevé, ou oublié?
> jwrapper: use the latest Java collections and other updates

- lib/standard/collection/array.nit
- src/annotation.nit
- src/compiler/abstract_compiler.nit
- src/compiler/compiler_ffi.nit
- src/compiler/separate_compiler.nit
- src/ffi/header_dependency.nit
- src/loader.nit
- src/modelbuilder.nit
- src/modelize/modelize_class.nit
- src/nitlight.nit
- src/nitpretty.nit
- src/testing/testing_doc.nit
- tests/sav/test_new_native_alt1.res
Looked at http://jenkins.gresil.org/jenkins/job/nit/tasks and did some work.
> Less fixme and todo

- contrib/jwrapper/Makefile
- contrib/jwrapper/README.md
- contrib/jwrapper/grammar/javap.sablecc
- contrib/jwrapper/src/code_generator.nit
- contrib/jwrapper/src/javap_visitor.nit
- contrib/jwrapper/src/model.nit
- contrib/jwrapper/src/types.nit
More clean up on jwrapper, improve terminology and add one feature from #794.
> More jwrapper: fix terminology and add a single feature from the TODO list

- src/doc/doc_pages.nit
> nitdoc: do not repeat intro comment in mpropdef lists

- lib/array_debug.nit
- lib/bucketed_game.nit
- lib/curl/curl.nit
- lib/filter_stream.nit
- lib/ini.nit
- lib/nitcc_runtime.nit
- lib/opts.nit
- lib/scene2d.nit
- lib/symbol.nit
> Fix more warnings

- lib/github/api.nit
> GitHub api: Issues and PRs

- lib/socket/socket.nit
- lib/standard/string.nit
- lib/websocket/examples/websocket_server.nit
- lib/websocket/websocket.nit
- src/interpreter/debugger_socket.nit
- src/interpreter/primitive_types.nit
Fixed websockets with the new and improved sockets.
While I'm at it, changed a bit the way it works, the old one was a bit (a lot ?) quick and dirty, so here's that.
> Websockets

- lib/github/api.nit
This time for comments:
* commit comments
* issue comments
* diff comments
> GitHub API: handles comments

- src/doc/doc_pages.nit
- src/loader.nit
- src/model/mmodule.nit
Do not display test suite modules in Nitdoc
Fixes #779
> Do not display test suite modules in Nitdoc

- lib/github/api.nit
This time it's all about:
* issue events
* contributor stats
* files
> GitHub api: Issue events, contributor stats, files

- lib/github/events.nit
First step to GitHubAPI hooks.
> lib/github: introduces Github hook events

- contrib/nitiwiki/src/wiki_html.nit
- contrib/nitiwiki/tests/res/nitiwiki_render.res
- contrib/nitiwiki/tests/res/nitiwiki_status.res
> Fix nitiwiki: Fixes auto-index links.

- src/semantize/typing.nit
- tests/base_attr_init_val_block.nit
- tests/sav/base_attr_init_val_block_alt1.res
- tests/sav/base_attr_init_val_block_alt2.res
> Check missing return in attributes with a block

- .gitignore
- lib/github/api.nit
- lib/github/cache.nit
- lib/github/github.nit
Using JsonStore to save data locally and lighten the stress on API rate limit.
> lib/github: implements caching to maximize rate limit.

- src/changelog.sh
Don't count merges and display number of commits
> improve changelog.sh

- lib/counter.nit
- lib/poset.nit
- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/array.nit
- lib/standard/collection/hash_collection.nit
- lib/standard/collection/union_find.nit
Since keys of Maps can now be null, it enables the same rule with the Sets
> Set accept null

- lib/github/api.nit
Some fixes for the Github API.
Also introduce `Repo::search_issues` which allow to list specific issues with an advanced query.
> GitHub misc

- contrib/nitrpg/src/statistics.nit
- contrib/nitrpg/src/templates/panels.nit
Some changes on the stats API and new stats for Players.
> nitrpg: more statistics

- contrib/nitrpg/src/game.nit
- contrib/nitrpg/src/listener.nit
- contrib/nitrpg/src/reactors.nit
- contrib/nitrpg/src/statistics.nit
- contrib/nitrpg/src/templates/panels.nit
- contrib/nitrpg/src/templates/templates_base.nit
Some fixes before next feature.
> Nitrpg: minor fixes

- contrib/nitrpg/src/events.nit
- contrib/nitrpg/src/game.nit
- contrib/nitrpg/src/reactors.nit
- contrib/nitrpg/src/templates/panels.nit
- contrib/nitrpg/src/templates/templates_events.nit
- contrib/nitrpg/src/web.nit
Events allow us to keep track of the history.
> Nitrpg: introduce game events

- lib/android/aware.nit
- lib/android/gamepad.nit
- lib/android/platform.nit
- lib/json/dynamic.nit
- lib/more_collections.nit
The gamepad events are based on 2 different gamepads. They will probably need to be revisited with different layouts.
> Misc commits to android, json::dynamic and more_collections

- share/libgc/android-setup-libgc.sh
- src/platform/android.nit
Tested on ARM v7 and x86. MIPS on Android is more rare but it is used on some low-cost phones.
Each extra architecture use less than 1 mo in the release APK, but MIPS is the largest one. I could add an annotation or something else if we ever need smaller APK files. Mineit VR release with the 4 architectures and its textures takes only 2.5 mo.
> Support Android on 2 different ARMs, x86 and even MIPS

- lib/github/cache.nit
- src/testing/testing_doc.nit
This is a very small commit, but it may reveal some previously ignored nitunits.
> nitunit: fix running last test of a module, it was previously ignored

- src/parser/parser_nodes.nit
A simple helper to debug AST. I used it to debug auto-serialization in #1159
> parser: add `ASTDump` and `ANode::dump_tree`

- contrib/nitrpg/nitrpg.user.js
A script to use with [user-script][1] compliant plugin for your browser to enhance the user experience on github for nitrpg players.
[1]: http://en.wikipedia.org/wiki/Greasemonkey
> nitrpg: add nitrpg.user.js for enhanced user experience

- benchmarks/bench_engines.sh
> Add tasks in benchmark/bench_engines

- contrib/nitrpg/src/achievements.nit
- contrib/nitrpg/src/listener.nit
- contrib/nitrpg/src/statistics.nit
- contrib/nitrpg/src/templates/panels.nit
- contrib/nitrpg/src/templates/templates.nit
- contrib/nitrpg/src/templates/templates_base.nit
- contrib/nitrpg/src/templates/templates_events.nit
- contrib/nitrpg/src/web.nit
Not much achievements in this PR:
* Counting issues and rewarding at 1, 100, 1000
* Counting PR and rewarding at 1, 100, 1000
* Counting commits and rewarding at 1, 100, 1000, 10000
* Two achievements based on regexp, just for demo: Nitdoc and FFI
Partially fixes #1165: I fixed the typo in "complaint" and the first playre to unlock the achievement. But the related issue stills not linked for now.
Démo: http://nitlanguage.org/rpg/games/privat/nit (sorry, I had to reset the scores...)
> Nitrpg: add achievements

- lib/standard/kernel.nit
- lib/standard/stream.nit
- lib/standard/string.nit
- tests/sav/nituml_args3.res
- tests/sav/nituml_args4.res
While thinking about the remaining task of #466 (simple parsing), I though that there useful functions where missing in order to have a sane `Reader::read_word` method
> Extends chars, string and stream with some whitespace-related function

- lib/poset.nit
- src/astvalidation.nit
- src/compiler/abstract_compiler.nit
- src/phase.nit
Some minor optimizations after looking at reports of valgrind.
> Optimize nitc

- lib/standard/stream.nit
- lib/standard/string.nit
Make flatbuffers a little faster on substrings
for nitc/nitc/nitc
before: 0m7.168s
after: 0m7.068s (-1.4%)
> Faster buffers

- lib/mnit/numbers.nit
- lib/mnit/tileset.nit
Features from WBTW, used mainly to set the size of in-game hints and events boxes.
These modules are for Mnit but will be ported to Gamnit someday...
> mnit tileset and numbers

- lib/standard/exec_nit.c
- lib/standard/exec_nit.h
- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
This PR improves slightly the handling of signal by providing better defaults.
A side effect is that this close #754
> Handle signal

- lib/string_experimentations/utf8_noindex.nit
- src/compiler/separate_compiler.nit
--no-union-attributes was broken since the tagging of primitive. This PR fix it.
> Fix --no-union-attributes

- src/nit.nit
- src/nitvm.nit
- src/vm/variables_numbering.nit
- src/vm/virtual_machine.nit
- src/vm/vm.nit
- src/vm/vm_optimizations.nit
This small PR creates a directory for all vm files and a unique entry point.
Signed-off-by: Julien Pagès <julien.projet@gmail.com>
> Some cleaning in vm files

- lib/standard/string.nit
- tests/sav/test_parser_args1.res
> Fix escape to c

- src/compiler/separate_compiler.nit
Thus fix --trampoline-call (and --link-boost)
> sepcomp: fixup trampoline with tagged primitive values

- benchmarks/markdown/README.md
- benchmarks/markdown/bench_markdown.sh
- benchmarks/markdown/engines/pandoc/Makefile
- benchmarks/markdown/engines/pandoc/pandoc.hs
- bin/Makefile
Here the result for 5 consecutive runs.
> benches/markdown: add `pandoc` engine.

- benchmarks/bench_engines.sh
- benchmarks/markdown/.gitignore
- benchmarks/markdown/Makefile
- benchmarks/markdown/benches/Makefile
- benchmarks/markdown/engines/nitmd/Makefile
- benchmarks/strings/.gitignore
- benchmarks/strings/Makefile
- lib/ai/examples/puzzle.nit
Some janitoring in the benchmarks directory
> Clean benches

- lib/pthreads/examples/threaded_example.nit
- lib/pthreads/pthreads.nit
- src/frontend/frontend.nit
- src/frontend/parallelization_phase.nit
- tests/sav/threaded_example.res
Introduces the begining of the parallelization in Nit !
For now, only accepts the "threaded" annotation on methods without return value and without parameters.
Coming next : 
Parametrized methods,
methods with return value,
for loops.
> Parallelization phase introduction

- lib/geometry/quadtree.nit
Still a lot of warning remains...
> miniclean quadtrees

- lib/pthreads/README.md
- lib/pthreads/examples/threaded_example.nit
- src/frontend/parallelization_phase.nit
- tests/sav/threaded_example.res
The "threaded" annotation now supports functions with parameters ! 
Still need to check for eventual self calls in the body of the annotated function
> Improved parallelization phase

- lib/standard/collection/array.nit
- src/compiler/abstract_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/semantize/typing.nit
- tests/sav/test_new_native_alt1.res
Provide an abstraction `SingatureMap` to factorize (and simplify) the association between arguments and parameters (not that easy in the context of varargs).
This PR is also required by a future PR.
> Signature map

- share/man/nitc.md
- src/toolcontext.nit
- tests/sav/test_toolcontext_args1.res
- tests/sav/test_toolcontext_args2.res
Follow up of #959 and #1241. Now an option is exposed so people can happily try to use it on various tools that will turn them berserk and make them want to kill you.
> Option --keep-going

- contrib/nitrpg/README.md
- contrib/nitrpg/src/achievements.nit
- contrib/nitrpg/src/game.nit
- contrib/nitrpg/src/listener.nit
- contrib/nitrpg/src/statistics.nit
- contrib/nitrpg/src/templates/panels.nit
- contrib/nitrpg/src/web.nit
Mainly designed to fully close #1168 and work on #1161.
> nitrpg: minor enhancements

- src/doc/doc_phases/doc_html.nit
- src/doc/html_templates/html_model.nit
Démos:
* [stdlib](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/index.html)
* [nitc](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/nitc/index.html)
> Nitdoc: more cleaning and uniformize method names

- share/man/nitpretty.md
- src/nitpretty.nit
> share/man: Update man for `nitpretty`

- src/modelbuilder.nit
- src/modelize/modelize_class.nit
This was missing, I don't understand why but I need it.
> Model: add mclassdef2node

- contrib/nitrpg/src/templates/panels.nit
- contrib/nitrpg/src/web.nit
Improve the dashboard on the player page with `request_for_comment` things, and assigned work
> Nitrpg work

- contrib/nitrpg/src/achievements.nit
- contrib/nitrpg/src/events.nit
- contrib/nitrpg/src/game.nit
- contrib/nitrpg/src/statistics.nit
- lib/counter.nit
This will be used to display periodic stats about players and games.
> nitrpg: periodize stats

- lib/bucketed_game.nit
- lib/java/java.nit
- lib/standard/collection/abstract_collection.nit
- misc/vim/plugin/nit.vim
- src/platform/android.nit
- src/transform.nit
Fix typos in doc and help, improve doc, fix error in Android projects, clean up bucketed_game and add an option for #1300.
> Fix a bit of everything: typos, doc, android, bucketed_game and vim

- examples/rosettacode/balanced_brackets.nit
- lib/mnit/mnit_injected_input.nit
- lib/standard/environ.nit
- lib/standard/math.nit
- tests/sav/balanced_brackets.res
- tests/tests.sh
The PR started as a simple implementation for the task http://rosettacode.org/wiki/Balanced_brackets but some improvements on the lib and tests.sh where also added
> Balanced brackets

- lib/bitmap/bitmap.nit
- lib/bitmap/test_bitmap.nit
An implementation of Rosettacode's grayscale task (http://rosettacode.org/wiki/Grayscale_image) with additional features, including creating a Bitmap from scratch and manipulating its individual pixels.
> Rosettacode grayscale implementation

- lib/c.nit
- lib/mongodb/mongodb.nit
- lib/mongodb/native_mongodb.nit
This is my first real use of the FFI, @xymus you input on that?
Also poking @BlackMinou because he likes to review C code.
> lib: introduce MongoDB wrapper

- contrib/nitrpg/src/achievements.nit
- contrib/nitrpg/src/reactors.nit
- contrib/nitrpg/src/statistics.nit
- lib/github/api.nit
Consider :shipit: and :+1: to also be the acknowledgment of reviewers.
> nit rpg ack

- lib/gtk/v3_6.nit
I don't have any immediate use for this features but it was interesting to see what GTK had to offer in this regard.
> lib/gtk: add `GtkEntry::input_purpose`

- src/location.nit
- src/neo.nit
Useful to build a Location from it's string representation.
> location: introduce `from_string` constructor

- src/doc/console_templates/console_model.nit
- src/doc/console_templates/console_templates.nit
- src/doc/doc_base.nit
- src/doc/doc_phases/doc_console.nit
- src/doc/html_templates/html_templates.nit
This PR introduces the base rendering services for doc in console.
This will be used in the next version of `nitx` to benefit fron the new nitdoc architecture.
> nitx: start migration to `doc_phases`

- lib/standard/file.nit
So I can use it during the bootstrap (thanks #1323)
> lib/standard: reimplement `files` with light FFI

- contrib/nitiwiki/src/wiki_links.nit
- lib/markdown/decorators.nit
- lib/markdown/markdown.nit
- lib/markdown/wikilinks.nit
Misc modification to markdown lib to facilitate custon Markdown parsing from external tools.
> Markdown: some improvement and fixes

- lib/binary/binary.nit
- lib/libevent.nit
- lib/socket/socket_c.nit
Add services to write strings in binary streams and better support for binary in network modules.
> Binary over network

- src/compiler/separate_compiler.nit
The bug was revelated by #1385
> sepcomp: fix hardening related to the instantiation of dead types

- src/doc/doc_base.nit
- src/doc/doc_phases/doc_concerns.nit
- src/doc/doc_phases/doc_console.nit
- src/doc/doc_phases/doc_extract.nit
- src/doc/doc_phases/doc_graphs.nit
- src/doc/doc_phases/doc_hierarchies.nit
- src/doc/doc_phases/doc_html.nit
- src/doc/doc_phases/doc_intros_redefs.nit
- src/doc/doc_phases/doc_lin.nit
- src/doc/doc_phases/doc_pages.nit
- src/doc/doc_phases/doc_poset.nit
- src/doc/doc_phases/doc_structure.nit
- src/doc/html_templates/html_model.nit
Some services needed for next PRs
No diff to HTML output
> nitdoc: introduce useful services

- benchmarks/polygons/Makefile
- benchmarks/polygons/java/Makefile
- benchmarks/polygons/java/bench_polygon.sh
- benchmarks/polygons/java/code/AntiClockSort.java
- benchmarks/polygons/java/code/BenchPolygon.java
- benchmarks/polygons/java/code/ClockSort.java
- benchmarks/polygons/java/code/ConvexPolygon.java
- benchmarks/polygons/java/code/PointDouble.java
- benchmarks/polygons/java/code/PointXCompare.java
- benchmarks/polygons/java/code/PolygonSorter.java
- benchmarks/polygons/java/code/Projection.java
- benchmarks/polygons/nit/Makefile
- benchmarks/polygons/nit/bench_polygon.nit
- benchmarks/polygons/nit/bench_polygon.sh
- lib/geometry/polygon.nit
Nit implementation of the convex polygon data structure.
It's based on the java implementation done during the data structures course. 
There also are benchmarks for the Nit implementation and the Java implementation to compare them
> Introduction of convex polygons in geometry + benchmarks

- lib/android/bundle/bundle.nit
- lib/android/intent/intent_api10.nit
- lib/cpp.nit
- src/compiler/abstract_compiler.nit
- src/compiler/compiler_ffi/light.nit
- src/compiler/separate_compiler.nit
- src/ffi/java.nit
- src/ffi/light_ffi_base.nit
- src/nitni/nitni_base.nit
- tests/sav/neo_doxygen_dump_args4.res
- tests/sav/neo_doxygen_dump_args5.res
- tests/test_ffi_cpp_duplicated_callback_a.nit
- tests/test_ffi_cpp_duplicated_callback_b.nit
Since we plan on conforming with UTF-8, chars can no longer be of C char type, this PR changes the internal representation of a Char to become capable of holding an arbitrary Unicode code point.
Since chars become unsigned entities, and since NativeString will hold Byte values soon, its c type has been changed to unsigned char* as preparation for the migration
This is all related and necessary for #1262.
> Native Types

- src/frontend/simple_misc_analysis.nit
- tests/base_do_block.nit
- tests/sav/base_do_block.res
Warn useless do block, like
~~~nit
loop do 
print 1
end
~~~
Close #1437
> Warn useless do block

- src/semantize/scope.nit
- src/semantize/typing.nit
- src/ssa.nit
- src/vm/compilation.nit
- src/vm/variables_numbering.nit
- src/vm/vm.nit
This PR introduces a SSA-algorithm implementation in the nitvm.
First, basic blocks are generated. A basic block is a sequence of instructions without a jump inside.
In this version, basic blocks are generated from the AST and so they contain only the first instruction and the last one.
Then, SSA-algorithm (Single-Static Assignment) is implemented. In SSA algorithm, variables are renamed to have only one assignment per variable.
Each time an assignment is made, a new version of a variable is made.
Some variables (phi-functions) have several assignment and so, several dependances.
The basic block generation and SSA are computed for each method in a lazy way in the nitvm.
The main objective of SSA is to give the dependances for each variable (this will be used in further PR). 
This module …
> nitvm: Basic blocks generation and SSA-algorithm

- lib/java/collections.nit
This PR complete the java collections : ``` int[], short[], long[], boolean[], byte[], char[] ```
> Add some collections for java/collections.nit

- lib/cpp.nit
- lib/sdl.nit
- lib/sha1.nit
- lib/socket/socket_c.nit
- lib/standard/file.nit
- lib/standard/time.nit
- src/c_tools.nit
- src/nitni/nitni_base.nit
The revert commit is partial, it affects only NativeString and does not touch Char.
> Activate C warnings in FFI code and revert `NativeString` to `char *`

- contrib/nitiwiki/src/wiki_base.nit
- contrib/nitiwiki/src/wiki_html.nit
- contrib/nitiwiki/src/wiki_links.nit
- lib/ini.nit
- lib/markdown/wikilinks.nit
- lib/standard/file.nit
Some fixes for nitiwiki in prevision for the nitlanguage.org site migration and the resolution of #824.
Do not consider b481cea since it belongs to #1368 (and break the loader)
Feature summary:
* ini accept array notation
* customizable sidebar content
* customizable sidebar position
* wikilinks support external links
* better search by title
* better search by path
* make breadcrumbs and summaries optionnal
* add link to github for last_changes and edit mode
> Nitiwiki next

- contrib/nitrpg/src/reactors.nit
So @ventilooo won't cheat again!
> nitrpg: remove points if a PR is closed without merge

- contrib/friendz/src/friendz.nit
- contrib/friendz/src/friendz_android.nit
- examples/mnit_simple/src/test_assets_and_resources.nit
- examples/mnit_simple/src/test_audio.nit
- lib/android/assets_and_resources.nit
- lib/android/audio.nit
- lib/app/audio.nit
friendz now uses the Android Audio API 
+ fixed the new_global_ref functions in Assets and Resources
> friendz with Android Audio API

- lib/standard/collection/array.nit
> lib/array: remove useless cast to comparable.

- examples/rosettacode/bottles_of_beer.nit
- tests/sav/bottles_of_beer.res
> examples: Add 99_Bottles_of_Beer rosetta code example

- examples/rosettacode/here_document.nit
- tests/sav/here_document.res
> rosetta code: here_document

- examples/rosettacode/letter_frequency.nit
- tests/exec.skip
Signed-off-by: Jean-Philippe Caissy <jean-philippe.caissy@shopify.com>
> example: Rosetta Code example for letter frequency

- examples/rosettacode/symmetric_difference.nit
- tests/sav/symmetric_difference.res
Signed-off-by: Renata Carvalho <renatawm@gmail.com>
> rosetta: symmetric_difference

- examples/rosettacode/caesar_cipher.nit
- tests/sav/caesar_cipher.res
> example: add caesar cipher example from rosetta code

- lib/standard/collection/sorter.nit
- lib/standard/file.nit
- lib/standard/ropes.nit
- src/compiler/coloring.nit
- src/toolcontext.nit
- tests/sav/nitpick_args1.res
They where detected since #1332 is merged
> code: cleanup some docunits

- src/frontend/frontend.nit
- src/frontend/regex_phase.nit
- tests/sav/test_regex_check.res
- tests/sav/test_regex_check_alt1.res
- tests/sav/test_regex_check_alt2.res
- tests/sav/test_regex_check_alt3.res
- tests/test_regex_check.nit
This is the first part for #1511.
> Check for errors in regex within string literals at compilation 

- contrib/friendz/src/friendz_linux.nit
- lib/linux/audio.nit
fixes #1527.
The ideal solution would still be to implement SDL sounds but for now, this will be sufficient
> Audio API implementation for linux

- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/meetup_creation.po
- contrib/opportunity/src/templates/meetup_creation.nit
- contrib/pep8analysis/www/index.html
- examples/nitcorn/src/xymus_net.nit
Adds templates to the Opportunity meetup creation page. The default software provides: 4 kinds of pizzas, 5 days work week and 7 days week. The software customized for xymus.net also provides: pizzas special LATECE and meeting hours for UQAM Sciences.
It is already available at http://xymus.net/opportunity/.
> Opportunity templates and pizzas

- contrib/opportunity/src/templates/meetup_confirmation.nit
Signed-off-by: Alexis Laferrière <alexis.laf@xymus.net>
> contrib/opportunité: prevent useless xss exploit in meetup confirmation

- examples/rosettacode/json_output.nit
- tests/sav/json_output.res
> examples: add json example from rosetta code

- src/frontend/parallelization_phase.nit
Support modules without a module declaration and nullable types in threaded methods.
---
Don't worry, it's the last PR for today and my dev branches are getting short.
> Minor Improvements to the Parallelisation Phase

- tests/tests.sh
The main issue was that args where no more tested because of a bad variable scoping in bash
> Fix issues in tests introduced by previous series

- lib/geometry/angles.nit
- lib/geometry/geometry.nit
- lib/geometry/points_and_lines.nit
Some useful services for games and other geometry heavy applications.
I must say that I'm getting tired of the points API. Dealing with both the numeric complexity and the 2/3D is unpleasant. I will probably remove/separate the 3D part in the near future.
> lib/geometry: intro more services on points and for angles

- examples/rosettacode/s_exp.nit
- lib/sexp.nit
- tests/sav/s_exp.res
Simple S-Expressions parser, take only the two last commits into account, as the rest belongs to #1448.
> Rosetta Code: S-Expressions

- lib/android/activities.nit
- lib/android/input_events.nit
- lib/android/landscape.nit
- lib/mnit_android/android_app.nit
- src/platform/android.nit
Fixes multi-pointers support, intro `NativeActivity::finish`, landscape mode use the sensor and find the assets folder using the project location.
> Tweaks to the Android support

- lib/performance_analysis.nit
This should be enough to fix #1562.
> lib/performance_analysis: relax nitunit expected results

- lib/curl/native_curl.nit
> curl: implement CURLOPT_TIMEOUT and CURLOPT_TIMEOUT_MS

- contrib/github_merge.nit
- lib/curl/native_curl.nit
- lib/github/github_curl.nit
Nothing fancy but I wanted to merge PR tonight and I found the oauth token requirement a bit harsh
> Can use lib/github/github_curl without a oauth token

- lib/standard/math.nit
> lib/maths: add `nan` and `inf` as special Float

- lib/standard/bytes.nit
Simple addition to the Bytes module, to build one from any Text type
> Text::to_bytes

- tests/sav/test_autoinit_optional.res
- tests/test_autoinit_optional.nit
This one comes from a discussion with @R4PaSs 
I'm not sure I want to really expose it as I still think that current constructors need more love and work.
So at least test the current behavior.
If you people have other alternatives, you can show them.
> example: optional attribute with a default value

- lib/dom/parser.nit
- lib/dom/xml_entities.nit
- tests/sav/test_xml_read_args15.res
- tests/sav/test_xml_read_args18.res
- tests/sav/test_xml_read_args4.res
- tests/sav/test_xml_read_args7.res
This part was required while developing some change in the spec of default parameter (see #1453)
But this series of commit seems good enough and could be independently useful.
It also remove all warnings in the lib/dom directory
> Cleanup lib/dom

- contrib/benitlux/Makefile
- contrib/benitlux/src/benitlux_db.nit
- contrib/benitlux/src/report.nit
Intro a tool to print a pretty report on the availability of beers at the excellent Brasserie Bénélux.
> Benitlux report tool

- src/astbuilder.nit
- src/astutil.nit
- src/ffi/c_compiler_options.nit
- src/frontend/regex_phase.nit
- src/metrics/detect_covariance.nit
- src/parser/nit.sablecc3xx
- src/parser/parser.nit
- src/parser/parser_abs.nit
- src/parser/parser_nodes.nit
- src/parser/parser_prod.nit
- src/parser/parser_work.nit
- src/pretty.nit
- src/semantize/scope.nit
- src/semantize/typing.nit
- tests/sav/nitmetrics_args1.res
- tests/sav/test_parser_args1.res
- tests/sav/test_parser_args6.res
- tests/sav/test_parser_args7.res
First step to solve #1260: do not lose qualifiers in the AST.
This is just a API change without new features. qualifiers are still ignored but now they are in the AST.
> Prepare qualified identifiers

- contrib/tinks/src/client/client.nit
The sequence of `isa` is redundant with the polymorphic calls client_react. Possibly an unfinished refactorization or some git rebase issue.
ping @xymus
> Tinks! remove duplicated code in event reaction

- src/loader.nit
- src/nitls.nit
- src/nitserial.nit
Because #1250 is starting to stall and that my rewrite of the loader is not going well, I started last night an alternative approach: improve the existing loader in small steps.
This PR contains small cleaning on the loader, mainly documentation, small refactorization and bugfixes.
This is a small part of bigger modification still in progress, but I expect these commits to be good enough to be merged.
> Cleanup loader

- Makefile
- contrib/crazy_moles/org.nitlanguage.moles_android.txt
- contrib/friendz/org.nitlanguage.friendz_android.txt
- contrib/github_merge.nit
- contrib/nitrpg/README.md
- contrib/nitrpg/nitrpg.user.js
- contrib/nitrpg/src/game.nit
- contrib/online_ide/www/js/functions.js
- contrib/opportunity/README.md
- contrib/pep8analysis/www/index.html
- contrib/tnitter/src/action.nit
- examples/emscripten/fibonacci/www/index.html
- examples/mnit_ballz/org.nitlanguage.ballz_android.txt
- examples/mnit_dino/org.nitlanguage.dino.txt
- examples/mnit_simple/org.nitlanguage.test_all.txt
- examples/shoot/org.nitlanguage.shoot_android.txt
- lib/github/api.nit
- lib/github/cache.nit
- lib/github/test_github_curl.nit
- lib/graphs/digraph.nit
- share/man/nitdoc.md
Migrate references from https://github.com/privat/nit to https://github.com/nitlang/nit
> GitHub nitlang

- Makefile
Some cleanup since the new loader landed (cf. #1654)
> After new loader

- contrib/friendz/README.md
- examples/circular_list.nit
- examples/clock.nit
- examples/clock_more.nit
- examples/fibonacci.nit
- examples/print_arguments.nit
- examples/procedural_array.nit
- examples/rosettacode/README.md
- examples/shoot/README.md
- lib/ai/README.md
- lib/cartesian.nit
- lib/combinations.nit
- lib/deriving.nit
- lib/ordered_tree.nit
- lib/scene2d.nit
- lib/standard/README.md
- lib/symbol.nit
Improve (or create) the short description of some random projects.
Note that using the fist line of the `README.md` is maybe not the best approach since the first line of a README is often a short title (approx 30 chars) whereas, to be informative the short description (synopsis) is often a long title (approx 70 chars).
> projects: update some short descriptions

- lib/core/text/flat.nit
- lib/core/text/ropes.nit
As a small optimization, accesses to private attributes in Text are replaced by direct accesses as in `file` or `collection`.
On the compiler this yields between 3 and 4% improvement in performances, however in some programs like nitmd, this yields around 15% optimization.
> Text attribute accesses optimization

- contrib/opportunity/src/opportunity_model.nit
- lib/core/text/abstract_text.nit
- lib/nitcorn/examples/Makefile
Fix #1695. It is already deployed on http://xymus.net/opportunity/ (Take a look at http://xymus.net/opportunity/?meetup_id=B962ECD89E0AE40FF888569AE8D816B36F128E10)
> Fix Opportunity behavior with unicode characters

- src/nitcatalog.nit
Two improvements:
* content list (example: see end of page <http://nitlanguage.org/catalog/android.html>, section *content*)
* command-line options
> nitcatalog: content and options

- contrib/friendz/src/friendz.nit
- contrib/friendz/src/grid.nit
- contrib/friendz/src/level.nit
Save the state of the sound and the levels in the data store.
If you leave a level and come back, your grid in the level is no more lost
> Friendz: save states

- lib/android/audio.nit
Asked by @privat because friendz's app played multiple musics when pausing/resuming the app
> android/audio: fix multiple music playing when pausing app

- contrib/crazy_moles/Makefile
- contrib/mnit_test/org.nitlanguage.test_minimal.txt
- contrib/tinks/net.xymus.tinks.txt
- examples/calculator/Makefile
- examples/calculator/org.nitlanguage.calculator.txt
- misc/jenkins/check_contrib.sh
Finish the job of #1710 by adding missing `make android-release`, F-Droid metadata and simplifying the check_contrib script.
ping @xymus for review
> Prepare FDroid deployment

- benchmarks/.gitignore
- benchmarks/Makefile
- benchmarks/bench_common.sh
- benchmarks/bench_engines.sh
- benchmarks/bench_languages.sh
- benchmarks/bench_nitdoc.sh
- benchmarks/bench_nitunit.sh
- benchmarks/bench_plot.sh
- benchmarks/markdown/Makefile
- benchmarks/markdown/bench_markdown.sh
- benchmarks/polygons/Makefile
- benchmarks/polygons/nit/Makefile
- benchmarks/polygons/nit/bench_polygon.sh
- benchmarks/strings/Makefile
- benchmarks/strings/bench_strings.sh
Some work in the benchmarks directory. The most important stuff is some `make check` to test the brokenness of specific benches.
> Some improvement of benchmarks

- lib/ordered_tree.nit
This add services to the class OrderedTree
> Beef up OrderedTree API

- lib/ordered_tree.nit
Some fixes related of the last changes
> Fixes for ordered trees

- src/semantize/auto_super_init.nit
- src/semantize/typing.nit
A minor cleanup in the model that reduces the coupling of the model and the AST.
> Detach CallSite from the AST

- lib/graphs/digraph.nit
- lib/graphs/pagerank.nit
Implement famous Google's `PageRank` algorithm for directed graphs.
Ping @ablondin
> lib/graphs: introduce PageRank computation on digraphs

- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
This PR does two things:
* Define `FlatText` as a private class. Since every clients were using an intrude import, their code do not change.
* Remove nullable warning in text::flat
> FlatText is a private class

- lib/core/collection/hash_collection.nit
Other specific iterators are private. So this PR uniformize with HashMapIterator.
@privat you should check this.
> Set HashMapIterator as a private class.

- src/metrics/metrics_base.nit
Skip `nan` values in metrics so the sum and std_div still have sense.
Also change `Metric::collect` to accept any kind of `Collection`.
> metrics: not a number fix

- lib/nlp/README.md
- lib/nlp/nitnlp.nit
- lib/nlp/nlp.nit
- lib/nlp/package.ini
- lib/nlp/stanford.nit
- lib/nlp/vsm.nit
Stanford CoreNLP provides a set of natural language analysis tools which can take
raw text input and give the base forms of words, their parts of speech, whether
they are names of companies, people, etc., normalize dates, times, and numeric
quantities, and mark up the structure of sentences in terms of phrases and word
dependencies, indicate which noun phrases refer to the same entities, indicate
sentiment, etc.
This wrapper needs the Stanford CoreNLP jars that run on Java 1.8+.
See http://nlp.stanford.edu/software/corenlp.shtml.
~~~nit
var proc = new NLPProcessor("path/to/StanfordCoreNLP/jars")
var doc = proc.process("String to analyze")
for sentence in doc.sentences do
for token in sentence.tokens do
print "{token.lemma}: {token.pos}"
end
end
~~~
> lib: Introduce Stanford CoreNLP wrapper

- src/doc/doc_phases/doc_html.nit
- src/doc/doc_phases/doc_phases.nit
- src/doc/doc_phases/doc_test.nit
- src/nitdoc.nit
- tests/nitdoc.args
> nitdoc: opts --no-render and --test

- lib/core/text/flat.nit
As @privat requested, a byte-oriented optimized version of `FlatText` for `FlatString` as it is the most common case, like `escape_to_c`, it works at the byte level to accelerate fetching of characters.
On a short test program
~~~nit
var s = ""
for i in [0 .. 2000[ do s = "&lt;STRING&#47;&rt;".html_escape
~~~
Valgrind reports an old runtime of 18.208 MIr with a 8856 Ir/call to `html_escape`; the new runtime is 3.093 MIr, which translates to a 1298 Ir/call.
> lib/core: Optimized `html_escape` for FlatText variants

- lib/niti_runtime.nit
- src/loader.nit
- tests/nit.args
- tests/niti.skip
- tests/nitvm.skip
- tests/sav/nit_args5.res
- tests/sav/nit_args6.res
These options where broken, and nobody complained.
Now they works again.
> Fix `-e` and `-n` on nit

- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/model/mmodule.nit
- src/model/model.nit
- src/model/model_viz.nit
- src/modelize/modelize_property.nit
Some small warning reductions while wandering in the source code of src/
> Less null warnings in src/

- contrib/benitlux/src/report.nit
- lib/core/collection/abstract_collection.nit
This PR adds customizable width to the graph generated by the benitlux report tool and displays short lived beer batches. Previously, some beers could not appear if they lasted less than a week on the menu.
> benitlux: produce better reports

- lib/trees/abstract_tree.nit
- lib/trees/rbtree.nit
Add `depth` and `Comparable` services to abstract Trees.
Also enhance the abstract_tree module documentation.
> lib/trees: more services and documentation

- lib/core/package.ini
- lib/nitcorn/README.md
- lib/nitcorn/package.ini
- src/nitcatalog.nit
add metadata `package.more_contributors` for lib/core and lib/nitcorn.
> More contributors

- src/nitcatalog.nit
Because you do not deserve privacy.
> add piwik to the nitcatalog

- tests/sav/test_sort_perf.res
- tests/sav/test_sort_perf_args1.res
- tests/test_sort_perf.args
- tests/test_sort_perf.nit
This test illustrate a current issue with string comparisons.
On my machine, a valgrind of it gives 80+% on BOX_Byte.
> tests: add test_sort_perf.nit

- contrib/jwrapper/src/code_generator.nit
- contrib/jwrapper/src/model.nit
Fixes the nested classes bug in jwrapper.
Splits JNI full name and java full name.
Generated comments use JNI full name.
> Jwrapper: Fix bug with nested classes

- src/model/model.nit
The implementation was an old code that did not use modern facilities,
moreover it was broken anyway.
Reported-by: Lucas Bajolet <r4pass@hotmail.com>
> model: fix `try_get_primitive_method`

- lib/curl/curl.nit
- lib/curl/examples/curl_http.nit
- lib/neo4j/curl_json.nit
- lib/neo4j/neo4j.nit
This is still far from an ideal doc but its better than nothing.
This doc will be useful for #1845.
> Improve the doc of `CurlHTTPRequest`

- contrib/nitrpg/nitrpg.user.js
Basically a rewrite, but it works on my computer
> nitrpg: update the userscript to the new github layout and fix todos

- lib/pthreads/concurrent_collections.nit
- lib/pthreads/examples/threadpool_example.nit
- lib/pthreads/threadpool.nit
- tests/exec.skip
A really basic implementation of a threadpool, using an array as queue for now.
> Simple threadpool implementation

- contrib/nitrpg/src/achievements.nit
- contrib/nitrpg/src/events.nit
- contrib/nitrpg/src/game.nit
- contrib/nitrpg/src/reactors.nit
- contrib/nitrpg/src/statistics.nit
- contrib/nitrpg/src/templates/templates_base.nit
Many fixes for NitRPG in prepatation for the next PR wich introduces the use of MongoDB.
> nitrpg: misc fixes

- contrib/nitiwiki/examples/nitiwiki/pages/section/other_section/first.md
- contrib/nitiwiki/examples/nitiwiki/pages/section/other_section/index.md
- contrib/nitiwiki/examples/nitiwiki/pages/section/other_section/second.md
- contrib/nitiwiki/src/wiki_html.nit
Fix a bug where independent trails could have been merged into a big one.
> nitiwiki: fix multiple trails

- lib/github/api.nit
> github/api: avoid crashes with unparsable responses

- lib/libevent.nit
Signed-off-by: Philippe Pepos Petitclerc <ppeposp@gmail.com>
> Add error instead of segfault on gethostbyname fail

- lib/core/collection/list.nit
this should have been done a long time ago
> core/list: add length as attribute

- contrib/nitiwiki/examples/default/config.ini
- contrib/nitiwiki/examples/default/templates/header.html
- contrib/nitiwiki/examples/nitiwiki/templates/menu.html
- contrib/nitiwiki/src/wiki_html.nit
- contrib/nitiwiki/src/wiki_links.nit
close #1872 
Can you try it @Morriar ?
> Nitiwiki: fix isues with relative paths and the root href

- contrib/nitrpg/Makefile
- contrib/nitrpg/src/achievements.nit
- contrib/nitrpg/src/events.nit
- contrib/nitrpg/src/events_generator.nit
- contrib/nitrpg/src/game.nit
- contrib/nitrpg/src/statistics.nit
- contrib/nitrpg/src/templates/templates_base.nit
- contrib/nitrpg/src/test_achievements.nit
- contrib/nitrpg/src/test_events.nit
- contrib/nitrpg/src/test_game.nit
- contrib/nitrpg/src/test_helper.nit
- contrib/nitrpg/src/test_listener.nit
- contrib/nitrpg/src/test_statistics.nit
- contrib/nitrpg/src/web.nit
Depends on #1759, #1760 and #1761.
> nitrpg: data management uses `mongodb` instead of `json_store`

- lib/pthreads/concurrent_collections.nit
- lib/pthreads/examples/jointask_example.nit
- lib/pthreads/examples/threadpool_example.nit
- lib/pthreads/threadpool.nit
- tests/sav/jointask_example.res
> Introduces JoinTask, joinabale tasks

- lib/gamnit/examples/triangle/src/portable_triangle.nit
- lib/gamnit/examples/triangle/src/standalone_triangle.nit
- lib/glesv2/examples/opengles2_hello_triangle.nit
- lib/glesv2/glesv2.nit
As usual, the new features and changes aim to follow as closely as possible the C API.
With this PR, we have pretty much all the OpenGL ES 2.0 features needed for mineit and for a first version of gamnit.
> glesv2: new services for uniforms, query info and glDrawElements! also update the API

- lib/core/text/abstract_text.nit
Simple addition to the services of `Char`, might be useful
> Added new `is_hexdigit` service on `Char`

- lib/nitcorn/examples/src/nitcorn_reverse_proxy.nit
- lib/nitcorn/nitcorn.nit
- lib/nitcorn/proxy.nit
For now anything proxied using this action is blocking.
close #1845
> Add simple proxy action

- contrib/nitrpg/src/test_achievements.nit
- contrib/nitrpg/src/test_events.nit
- contrib/nitrpg/src/test_game.nit
- contrib/nitrpg/src/test_helper.nit
- contrib/nitrpg/src/test_listener.nit
- contrib/nitrpg/src/test_statistics.nit
- src/testing/testing_suite.nit
- tests/nitunit.args
- tests/sav/nitunit_args9.res
- tests/test_nitunit4/nitunit4.nit
- tests/test_nitunit4/test_nitunit4.nit
- tests/test_nitunit4/test_nitunit4_base.nit
As asked by @privat, the nitrpg test suite now uses random db names
> nitrpg: avoid race conditions in tests that imply database

- src/model/model.nit
- src/model/model_views.nit
- src/model/model_visitor.nit
- src/test_model_visitor.nit
- tests/sav/test_model_visitor_args1.res
Add usefull services to model visitor and introduce a model view based on it.
> model: Beefup model visitor

- src/highlight.nit
> hightlight: correctly highlight loose comments

- src/compiler/abstract_compiler.nit
- src/loader.nit
- src/model/mmodule.nit
- src/testing/testing_doc.nit
- tests/sav/nitx_args3.res
This mainly close a undocumented issue where `mmodule.location.source` is wrong
> Better mmodule location

- lib/core/math.nit
> lib/core/math: add `Collection::sample`

- src/parser/nit.sablecc3xx
- src/parser/parser_nodes.nit
Introduce the `yield` keyword in Nit grammar
@privat, @egagnon
> Introduction to Nit generators

- lib/core/kernel.nit
- lib/core/math.nit
- lib/core/text/native.nit
- tests/sav/error_class_glob.res
- tests/sav/nitce/fixme/base_gen_reassign_alt4.res
- tests/sav/nitce/fixme/base_gen_reassign_alt5.res
- tests/sav/nitce/fixme/base_gen_reassign_alt6.res
- tests/sav/nituml_args3.res
This is a cosmetic change, you should not see differences
> lib/core: use intern && ffi since it is now allowed by `c_src`

- contrib/memory/src/memory.nit
- lib/mnit/numbers.nit
when playing, the number of the shape is shown.
> flying numbers in memory

- lib/event_queue.ini
- lib/event_queue.nit
The objective is to be simple to use, powerful, efficient and flexible.
* simple to use:  no framework, only two public concrete classes, a lot of documentation
* powerful: instant, infinite and timed events, dynamic addition and removal of events, a lot of event information (time, duration, completion ration) , fluent-programming-capable
* efficient: internal use of heap and deadlines
* flexible: agnostic of time units, generic (use whatever you want in your events)
It initially targeted the management of the orchestration of graphical effects in a videogame, but become more general and useful.
> lib: add new lib `event_queue` a data-structure to manage queue of events

- examples/mnit_dino/src/game_logic.nit
- lib/sdl.nit
- src/compiler/abstract_compiler.nit
- src/compiler/java_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/modelize/modelize_property.nit
- src/rapid_type_analysis.nit
Nothing fancy. Just small things extracted from a massive wip branch
> Small cleanups related to constructors

- contrib/nitcc/src/grammar.nit
- lib/core/collection/abstract_collection.nit
- tests/test_regex_check.nit
> more work on nitcc

- contrib/jwrapper/src/model.nit
- contrib/nitiwiki/src/wiki_links.nit
- contrib/nitrpg/src/statistics.nit
- contrib/pep8analysis/src/flow_analysis/range_analysis.nit
- contrib/pep8analysis/src/flow_analysis/reaching_defs.nit
- lib/core/collection/abstract_collection.nit
- lib/core/collection/array.nit
- lib/core/collection/hash_collection.nit
- lib/mongodb/mongodb.nit
- lib/neo4j/graph/json_graph_store.nit
- lib/nitcorn/http_request.nit
- lib/sax/helpers/namespace_support.nit
> Recover `recover_with`

- contrib/opportunity/src/templates/boilerplate.nit
- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/boilerplate.po
- contrib/opportunity/src/templates/meetup.nit
http://xymus.net/opportunity/ has already been updated with the fix.
> contrib/opportunity: fix usage of % format, now indexed from 0

- lib/core/math.nit
Primality test should also test the sqrt of the number.
> fix Int::is_prime

- contrib/benitlux/Makefile
- contrib/benitlux/src/benitlux_controller.nit
- contrib/benitlux/src/benitlux_daily.nit
- contrib/benitlux/src/benitlux_db.nit
- contrib/benitlux/src/benitlux_model.nit
- contrib/benitlux/src/benitlux_web.nit
- contrib/benitlux/src/correct.nit
- contrib/opportunity/src/opportunity_web.nit
- contrib/tnitter/src/tnitter.nit
This is in preparation to the introduction of all the social network features.
I expect to have some .sav to update because of the commit removing the check of NIT_TESTING.
> Benitlux: Minor improvements to the server

- contrib/benitlux/.gitignore
- contrib/benitlux/Makefile
- contrib/benitlux/src/benitlux_controller.nit
- contrib/benitlux/src/benitlux_daily.nit
- contrib/benitlux/src/benitlux_db.nit
- contrib/benitlux/src/benitlux_model.nit
- contrib/benitlux/src/benitlux_social.nit
- contrib/benitlux/src/benitlux_web.nit
- contrib/benitlux/src/correct.nit
- contrib/benitlux/src/report.nit
- lib/nitcorn/examples/src/xymus_net.nit
- lib/nitcorn/sessions.nit
- lib/nitcorn/token.nit
- lib/sqlite3/native_sqlite3.nit
- lib/sqlite3/sqlite3.nit
- tests/test_sqlite3_native.nit
This PR extends the Benitlux web server with a RESTful interface for a social network. This interface will be used by the mobile client, which will be introduced in a future PR.
The new module `benitlux_social` implements all the core logic and SQL request to implement the database. It uses existing services of `benitlux_db` which only keeps track of the beers and their availability.
Most of this code is already deployed on xymus.net and used by the commuNity using the alpha version of the mobile app. Also note that this is the first real-world use of nitrestful, which handles very well all the `restful` methods of `benitlux_controller`.
> Benitlux: intro server side of social network

- lib/core/bytes.nit
> lib/core/bytes: add `Int::to_bytes` and `Bytes::to_i`

- src/nitweb.nit
- src/uml/uml_class.nit
- src/uml/uml_module.nit
- src/web/web_actions.nit
- src/web/web_views.nit
Allows nitweb to display UML.
Thanks @R4PaSs!
> nitweb: uml graphs route

- lib/core/codecs/codec_base.nit
- lib/core/codecs/codecs.nit
- lib/core/codecs/iso8859_1.nit
- lib/core/codecs/utf8.nit
- lib/core/stream.nit
- lib/core/text/native.nit
- tests/sav/test_iso88591_codec.res
- tests/test_iso88591_codec.nit
Sub-part of #2006 since @privat asked for it to be split, here's one part concerning the addition of a few services to NativeString and Byte, along with the refactor of the Codec API
> Codec refactor

- lib/core/text/abstract_text.nit
Added convenience feature to `Text` objects: `pack`.
These new methods pack the content of a `Text` object into an array of `n` elements of length up to `ln`.
> Pack Strings

- lib/poset.nit
- src/model/model_collect.nit
- src/model/model_views.nit
Just some services that work on flattened views of the model that I will need soon.
> model_collect: add more services

- src/modelbuilder_base.nit
- src/modelize/modelize_property.nit
- tests/error_unk_class2.nit
- tests/sav/error_unk_class2.res
Add hints when a class name cause an error.
Basically 3 cases are considered: spellign, bad visibility and not imported. e.g.
~~~
Error: class `Fail` not found in module `error_unk_class`.
Error: class `Boolean` not found in module `error_unk_class`. Did you mean `Bool`?
Error: class `core::list::ListNode` not visible in module `error_unk_class`.
Error: class `POSet` not found in module `error_unk_class`. Maybe import `poset`?
~~~
> Hint to bad class names

- src/interpreter/naive_interpreter.nit
Previous PR #2011 introduced the `do ... catch ... end` bloc in the interpreter and the compiler.
This one makes it so the interpreter is using the mecanism (longjmp) from the compiler
> interpreter use the catch from the compiler

- src/compiler/abstract_compiler.nit
> nitc: use Array instead of List

- lib/logic/lexpr.nit
- lib/logic/logic.nit
- lib/logic/package.ini
After cleaning some CTF code.
More code,  like a parser and generation of common format might come
> lib: add logic library

- benchmarks/bench_engines.sh
- contrib/jwrapper/src/model.nit
Also improve jwrapper a little
> Add nitlight and jwrapper to the benchbed

- lib/core/text/flat.nit
This PR introduces a bit of a performance improvement to `FlatBuffer` by limiting the number of reallocations for common cases.
> Perfize FlatBuffer

- benchmarks/json/.gitignore
- benchmarks/json/Makefile
- benchmarks/json/bench_json.sh
- benchmarks/json/inputs/multiply_gov.sh
- benchmarks/markdown/bench_markdown.sh
- benchmarks/markdown/benches/gen_benches.nit
- benchmarks/polygons/.gitignore
add html output for json and fix two issues in http://gresil.org/jenkins/job/nit_bench/120/testReport/
> Clean some errors in benches

- lib/core/text/flat.nit
- tests/test_flatbuf_from.nit
Fix a bug at initialization of a flat buffer from a string.
Reported by @BlackMinou
> Flatbuffer fix

- lib/crypto.nit
Needed a new constructor for `Bytes` to facilitate things.
> Added a service to xor `Bytes`

- lib/crapto/crapto.nit
- lib/crapto/english_utils.nit
- lib/crapto/package.ini
Introduce a frequency analysis service for the english language.
> Introduce crapto modules for cryptographic attacks.

- lib/rubix.ini
- lib/rubix.nit
A .ini file has been added for support in catalog, along with some module documentation for `lib/rubix.nit`
Close #2076.
> Rubix cube - Catalog and documentation update

- contrib/benitlux/src/benitlux_controller.nit
- contrib/benitlux/src/benitlux_db.nit
- contrib/benitlux/src/benitlux_model.nit
- contrib/benitlux/src/benitlux_web.nit
- lib/nitcorn/restful.nit
- lib/sqlite3/sqlite3.nit
This PR adds a RESTful admin interface to the Benitlux server. This interface is used to trigger sending out the daily menu notifications from an external program / cron.
As a fix to the diff showing everything as new on the menu, the server now standardizes the received dates to the format expected by SQLite. There is also a small fix to the library used by the code generated by nitrestful to correctly check for errors.
> Admin interface for Benitlux and fixes

- lib/rubix.ini
Wrong email in the package, fixed with this PR
> Rubix: Fix package

- lib/android/ui/ui.nit
- lib/app/ui.nit
- lib/ios/ui/ui.nit
- lib/linux/ui.nit
This PR adds an event when a checkbox is toggled. `ToggleEvent` is similar to the only previously existing event, `ButtonPressEvent`.
> app.nit: intro `ToggleEvent`

- .gitignore
> .gitignore: ignore .swo files

- misc/docker/Dockerfile
- misc/docker/full/Dockerfile
I splitted the image in a light and a full one: https://hub.docker.com/r/privat/mynit/tags/
* the light one contains only the nit tools the the packages to build them. 225MB
* the full one contains most libraries, tools like inkscape, and the android sdk. 2GB
> Split and improve Docker

- src/nitweb.nit
- src/web/web_actions.nit
- src/web/web_base.nit
- src/web/web_views.nit
Get rid of plain corn boiler plate code from nitweb.
Consider only the last two commits since the others are from #2094 and #2110.
> Nitweb uses popcorn

- src/platform/app_annotations.nit
The _app.nit_ annotation `version` sets the version of mobile app packages (.apk and .app). For example, `version(1, 5, git_revision)` may produce the version string "1.5.6b42a7c".
This PR fixes an error when asking for a `git_revision` but the call to `git rev-parse` fails.
Note that the normal git error is printed before the nitc warning message, so debugging should be easy.
Close #2111
> src/platforms: fallback to version field "0" on error when asking for a git_revision

- misc/docker/Dockerfile
- misc/docker/README.md
- misc/docker/hello/Dockerfile
- misc/docker/hello/src/hello.nit
Add documentation and an example of a docker image for a Nit application
> Document Docker

- NOTICE
Commands used:
* `git shortlog -sne <commit range> -- benchmarks/ contrib/ c_src/ examples/ misc/ share/man/ src/ tests/ Changelog LICENSE LICENSE-BSD LICENSE-GPL-2 Makefile NOTICE README.md VERSION .gitattributes .gitignore .gitmodules .mailmap .project`
* `git shortlog -sne <commit range> -- lib/ clib/ share/nitdoc/`
* To check the first commit date of an author: `git log --author=<author BRE> --reverse --date-order | less`
> NOTICE: Update author list and years

- src/testing/testing_base.nit
- src/testing/testing_doc.nit
- src/testing/testing_suite.nit
- tests/sav/nitunit_args1.res
- tests/sav/nitunit_args4.res
- tests/sav/nitunit_args5.res
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args7.res
- tests/sav/nitunit_args8.res
- tests/sav/nitunit_args9.res
- tests/test_nitunit.nit
This series move more information in the UnitTest class, this allow specific and unified way of displaying the test results.
See the asciinema: https://asciinema.org/a/108jd2a3tkfifg3wzoacg0a65
Comments? Needs? Ideas?
> make nitunit  more colorful (and useful?)

- src/model/model_collect.nit
Build a new hierarchy poset from MClass inheritance
> model_collect: add services for module importation

- lib/nitcorn/file_server.nit
- lib/popcorn/README.md
- lib/popcorn/examples/angular/example_angular.nit
- lib/popcorn/examples/static_files/example_static_default.nit
- lib/popcorn/examples/static_files/public/default.html
- lib/popcorn/pop_handlers.nit
- lib/popcorn/tests/res/test_example_angular.res
- lib/popcorn/tests/res/test_example_static_default.res
- lib/popcorn/tests/test_example_angular.nit
- lib/popcorn/tests/test_example_static_default.nit
This PR introduce the concept of default file in `FileServer`. This allow the user to specify what file to return instead of the 404 page if no file matches the query.
> nitcorn: FileServer default file

- share/man/nitunit.md
- src/nitunit.nit
- src/testing/testing_base.nit
- src/testing/testing_doc.nit
- src/testing/testing_suite.nit
- tests/nitunit.args
- tests/sav/nitunit_args1.res
- tests/sav/nitunit_args4.res
- tests/sav/nitunit_args5.res
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args7.res
- tests/sav/nitunit_args8.res
- tests/sav/nitunit_args9.res
Small last nitpicks on nitnuit
* --no-color mode
* better summary at the end
* working dir no more hidden and removed on success
> Docunit --no-color

- examples/fibonacci.nit
Signed-off-by: Tony Gaetani <tony.gaetani@gmail.com>
> examples/fibonacci: fix off-by-one fibonacci

- NOTICE
> NOTICE: Update

- src/catalog.nit
- tests/sav/nitcatalog_args1.res
especially, private things, redefinitions and test_suites count for peanuts.
> catalog: tweak documentation score

- README.md
> README: Update libgc's URL

- contrib/nitiwiki/src/wiki_base.nit
- contrib/nitiwiki/src/wiki_html.nit
- contrib/nitiwiki/src/wiki_links.nit
This PR gets rid of the last warnings in nitiwiki.
> nitiwiki: fix warnings

- contrib/simplan/simplan.nit
> contrib/simplan: fix `call on nullable receiver` warnings

- share/man/nitc.md
> man/nitc: Remove duplicate option description

- share/nitweb/directives/entity/card.html
- share/nitweb/directives/entity/list.html
- share/nitweb/directives/entity/location.html
- share/nitweb/directives/entity/tag.html
- share/nitweb/directives/ui-filter-button-vis.html
- share/nitweb/directives/ui-filter-field.html
- share/nitweb/directives/ui-filter-form.html
- share/nitweb/directives/ui-filter-group-vis.html
- share/nitweb/index.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/ui.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/class.html
- share/nitweb/views/group.html
- share/nitweb/views/module.html
- share/nitweb/views/package.html
Add more content to mentities pages.
Packages list inner groups
* http://nitweb.moz-code.org/package/core
Groups show parent and list inner groups/modules
* http://nitweb.moz-code.org/group/core%3E
* http://nitweb.moz-code.org/group/core%3Ecollection%3E
Modules show imported modules, introduced classes and redefinitions
* http://nitweb.moz-code.org/module/core::array
Classes show super classes, introduced properties, redefined properties
* http://nitweb.moz-code.org/class/core::Array
Bonus, all lists are filterable by raw string or visibility.
> nitweb: show mentities details

- contrib/benitlux/src/client/base.nit
- contrib/benitlux/src/client/features/translations.nit
- contrib/benitlux/src/client/views/user_views.nit
- contrib/benitlux/src/server/benitlux_social.nit
The new signup screen shows more feedback and requires to write the password twice.
> Benitlux app: improve signup screen

- src/testing/testing_base.nit
- src/testing/testing_doc.nit
- src/testing/testing_suite.nit
- tests/sav/nitunit_args1.res
- tests/sav/nitunit_args4.res
- tests/sav/nitunit_args5.res
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args7.res
- tests/sav/nitunit_args8.res
- tests/sav/nitunit_args9.res
The results are printed progressively instead of at the end of each test-suite.
The progress bar in therefore displayed below the results.
See it in action: https://asciinema.org/a/17u9jwts0nz5dfpxp8p9aab0f
> nitunit: improve progress display

- share/nitweb/directives/entity/card.html
- share/nitweb/directives/entity/list.html
- share/nitweb/directives/entity/location.html
- share/nitweb/directives/entity/tag.html
- share/nitweb/directives/ui-filter-button-vis.html
- share/nitweb/directives/ui-filter-field.html
- share/nitweb/directives/ui-filter-form.html
- share/nitweb/directives/ui-filter-group-vis.html
- share/nitweb/index.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/model.js
- share/nitweb/javascripts/ui.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/class.html
- share/nitweb/views/group.html
- share/nitweb/views/module.html
- share/nitweb/views/package.html
- src/web/model_api.nit
* Introduce a search field in the top navbar connected to the `/search` service.
* Added a stub implementation of a search service depending on APIList.
Demo: http://nitweb.moz-code.org/
> nitweb: search field

- share/nitweb/directives/contributor-list.html
- share/nitweb/index.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/index.js
- share/nitweb/javascripts/model.js
- share/nitweb/javascripts/nitweb.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/index.html
- src/nitweb.nit
- src/web/api_catalog.nit
- src/web/model_api.nit
- src/web/web.nit
- src/web/web_base.nit
Used the Catalog API with Nitweb to provide a homepage.
Demo: http://nitweb.moz-code.org/
> nitweb: use catalog as homepage

- src/nitweb.nit
> nitweb: use ConsoleLog middleware

- share/man/nitunit.md
- src/testing/testing_suite.nit
> nitunit: Fix documentation to reflect actual test discovery algorithm

- share/nitweb/directives/entity/defcard.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/model.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/class.html
- share/nitweb/views/module.html
- src/nitweb.nit
- src/web/model_api.nit
A little of everything in this PR:
* show all properties of a class: http://nitweb.moz-code.org/class/core::Array (see all props tab)
* show code into linearization card: http://nitweb.moz-code.org/class/core::Array (see linearization tab)
* show class definitions for modules: http://nitweb.moz-code.org/module/core::array
> nitweb: add misc features

- CONTRIBUTING.md
- README.md
As discussed in #2133, contribution guidelines are hard to find.
This PR is an attempt to ease the process by giving newcomer friendly advices and some more insight on the contribution process for Nit.
@tonygaetani, do you think a document like this one would have been helpful for you ? Is there anything you would change to make it friendlier/clearer ?
Close #2133
> Added contributing guidelines and link from readme

- contrib/online_ide/sources/nit/pnacl_nit.nit
- src/examples/nitlight_as_a_service.nit
- src/highlight.nit
- src/loader.nit
- src/toolcontext.nit
Some small adaptation to make the various tools less command-line dependent.
As a proof a concept, there is a simple nitlight&nitpick online tools.
Maybe a future nit online validador (nitltn?)
http://pratchett.info.uqam.ca:8081/
It seems that the machine is no more accessible from outside :/
> hightlight as a service

- contrib/action_nitro/Makefile
- contrib/asteronits/Makefile
- contrib/benitlux/Makefile
- contrib/crazy_moles/Makefile
- contrib/friendz/Makefile
- contrib/github_search_for_jni/Makefile
- contrib/header_keeper/Makefile
- contrib/inkscape_tools/Makefile
- contrib/jwrapper/Makefile
- contrib/memory/Makefile
- contrib/mnit_test/Makefile
- contrib/model_viewer/Makefile
- contrib/neo_doxygen/Makefile
- contrib/nitester/Makefile
- contrib/nitiwiki/Makefile
- contrib/nitrpg/Makefile
- contrib/objcwrapper/Makefile
- contrib/online_ide/Makefile
- contrib/opportunity/Makefile
- contrib/pep8analysis/Makefile
- contrib/refund/Makefile
- contrib/rss_downloader/Makefile
- contrib/simplan/Makefile
- contrib/sort_downloads/Makefile
- contrib/tinks/Makefile
- contrib/tnitter/Makefile
- contrib/xymus_net/Makefile
- lib/markdown/Makefile
- lib/popcorn/Makefile
> makefiles: simplify them and assume that Nit tools are in the PATH

- src/web/web_base.nit
Demo: http://nitweb.moz-code.org/class/nitcorn::FileServer
Closes #2176
> nitweb: add signatures to mproperties lists

- lib/dot/dot.nit
- lib/dot/exemples/clusters.nit
- lib/dot/exemples/hello.nit
- lib/dot/exemples/undirected_clusters.nit
- lib/dot/package.ini
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/model.js
- share/nitweb/views/class.html
- share/nitweb/views/group.html
- share/nitweb/views/module.html
- share/nitweb/views/package.html
- src/model/model_collect.nit
- src/nitweb.nit
- src/web/api_graph.nit
- src/web/model_api.nit
- src/web/web.nit
- src/web/web_base.nit
Add some very simple graphs tabs to nitweb:
* Packages: http://nitweb.moz-code.org/package/popcorn
* Groups: http://nitweb.moz-code.org/group/popcorn%3E
* Modules: http://nitweb.moz-code.org/module/core::array
* Classes: http://nitweb.moz-code.org/class/core::Array
> nitweb: add graphs stubs

- src/model/model.nit
> model: Fix spelling mistake

- share/nitweb/index.html
- share/nitweb/javascripts/docdown.js
- share/nitweb/javascripts/model.js
- share/nitweb/javascripts/nitweb.js
- share/nitweb/views/docdown.html
- src/doc/doc_commands.nit
- src/nitweb.nit
- src/web/api_docdown.nit
- src/web/web.nit
Documentation of this PR is [here](http://nitweb.moz-code.org/docdown?snippet=IyBIZWxsbyBHaXRodWIKClRoaXMgaXMgYSBkb2N1bWVudGF0aW9uIHNuaXBwZXQuCllvdSBjYW4gdXNlIGl0IHRvIGRvY3VtZW50IHRoaW5ncyBvbiB0aGUgZmx5IGFuZCBzaGFyZSBpdCB3aXRoIG90aGVyIE5pdCB1c2Vycy4KCiMjIEJhc2ljcwoKQmFzaWNhbGx5LCBEb2Nkb3duIGFsbG93cyB5b3UgdG8gd3JpdGUgbWFyZG93biBkb2N1bWVudGF0aW9uIHVzaW5nIHRoZSBbbWFya2Rvd25dKGh0dHBzOi8vZGFyaW5nZmlyZWJhbGwubmV0L3Byb2plY3RzL21hcmtkb3duLykgZm9ybWF0LgoKU29tZSBleGFtcGxlczoKCn5%2BfnJhdwoqIHRoaXMKKiBpcyBhCiogbGlzdAp%2Bfn4KCj4gVGhpcyBpcyBhIGNpdGF0aW9uLgoKIyMgV3JpdGluZyBuaXQgY29kZQoKRG9jZG93biBkZXBlbmRzIG9uIHRoZSBuaXQgaGlnaGxpZ2h0ZXIgc28geW91IGNhbiB3cml0ZSBOaXQgd2l0aGluIHlvdXIgZG9jIHNuaXBwZXQ6Cgp%2Bfn4KcHJpbnQgImhlbGxvIHdvcmxkIgp%2Bfn4KCiMjIExpbmtpbmcgbW9kZWwgZW50aXRpZXMKCkRvY2Rvd24gdXNlcyBgW1t3aWtpbG …
> Nitweb snippets

- src/examples/nitlight_as_a_service.nit
- src/highlight.nit
It is less and less an example but nitlight_as_a_service now features a client-side editor (http://codemirror.net/) and update the page with some crappy ajax code.
http://test.nitlanguage.org/
> nitlight as a service with embedded editor and ajax updates

- contrib/action_nitro/src/action_nitro.nit
- contrib/asteronits/src/game_logic.nit
- contrib/tinks/src/client/client.nit
- contrib/tinks/src/game/tanks.nit
- lib/core/math.nit
- lib/mpd.nit
The `clamp` service restricts a value within a given range. It is a common service in GLSL and it is especially useful for games. Even though the alternative is short: `x = x.min(1.0).max(0.0)`, it is quite confusing and the simple `x = x.clamp(0.0, 1.0)` is easier to read.
> math: Intro `Comparable::clamp`

- src/model/model.nit
> model: Fix minor documentation mistakes

- src/modelize/modelize_class.nit
> modelize_class: Fix a verb tense

- src/model/model_collect.nit
> model_collect: Fix a spelling mistake

- src/model/model.nit
> model: Fix a minor documentation mistake

- share/nitweb/directives/entity/doc.html
- share/nitweb/directives/entity/stars.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/model.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/class.html
- share/nitweb/views/property.html
- src/nitweb.nit
- src/web/api_feedback.nit
- src/web/api_model.nit
- src/web/web.nit
Add discrete stars rating system in top right corner of each documentation card.
Can be seen here: http://nitweb.moz-code.org/doc/core::Array
> nitweb: stars rating system

- src/model/model.nit
> model: Write errors to stderr

- src/model/model.nit
> model: Fix a spelling mistake

- NOTICE
There is at least one commit from @calestar in 2008.
> NOTICE: Fix years

- src/compiler/separate_compiler.nit
> separate_compiler: Write errors to stderr

- src/compiler/global_compiler.nit
> global_compiler: Write errors to stderr

- src/modelize/modelize_class.nit
> modelize_class: Remove a dead check

- src/modelize/modelize_class.nit
- tests/sav/test_object_class_kind_alt1.res
- tests/sav/test_object_class_kind_alt2.res
- tests/sav/test_object_class_kind_alt3.res
- tests/sav/test_object_class_kind_alt4.res
- tests/test_object_class_kind.nit
> modelize_class: Force `Object` to be an interface

- lib/popcorn/pop_middlewares.nit
> lib/popcorn: generalize colors for status codes

- lib/mongodb/mongodb.nit
- lib/mongodb/native_mongodb.nit
> mongodb: wrap `Collection::aggregate` function

- lib/popcorn/pop_handlers.nit
- lib/popcorn/pop_validation.nit
Validators can be used in Popcorn apps to valid your json inputs before
data processing and persistence.
Here an example with a Book management app. We use an ObjectValidator to validate
the books passed to the API in the `POST /books` handler.
~~~nit
import popcorn
import serialization
class Book
super Jsonable
var isbn: String
var title: String
var img: nullable String
var price: Float
end
class BookValidator
super ObjectValidator
redef init do
add new ISBNField("isbn")
add new StringField("title", min_size=1, max_size=255)
add new StringField("img", required=false)
add new FloatField("price", min=0.0, max=999.0)
end
end
class BookHandler
super Handler
redef fun post(req, res) do
var validator = new BookValidator
if not validator.validate(req.body) then …
> Popcorn valid

- lib/mongodb/mongodb.nit
- lib/mongodb/native_mongodb.nit
- lib/popcorn/pop_repos.nit
Repositories are used to apply persistence on instances (or **documents**).
Using repositories one can store and retrieve instance in a clean and maintenable
way.
This module provides the base interface `Repository` that defines the persistence
services available in all kind of repos.
`JsonRepository` factorizes all repositories dedicated to Json data or objects
serializable to Json.
`MongoRepository` is provided as a concrete example of repository.
It implements all the services from `Repository` using a Mongo database as backend.
Repositories can be used in Popcorn app to manage your data persistence.
Here an example with a book management app:
~~~nit
import popcorn
import popcorn::pop_repos
class Book
serialize
super Jsonable
var id: String = (new MongoObjectId).id is serialize_as …
> Popcorn repos

- lib/github/wallet.nit
When using batch mode with the `github` API, we can rapidly reach the rate
limit allowed by Github.
One solution consists in using a wallet of tokens so we can rely on more than
one token and switch them when one become exhausted.
One functionality of the wallet is to check the validity of a token against
the API. `check_token` will return false if a token is invalid or exhausted.
~~~nit
var wallet = new GithubWallet
assert not wallet.check_token("this is a bad token")
~~~
The wallet can also be used to store tokens and check all of them.
~~~nit
wallet = new GithubWallet
wallet.add "some token"
wallet.add "some other token"
~~~
or
~~~nit
wallet = new GithubWallet.from_tokens(["token 1", "token 2"])
~~~
The `show_status` method can be used to display a summary of the validity of
each token …
> lib/github: introduce GithubWallet

- lib/popcorn/pop_middlewares.nit
Add some logger capabilities to ConsoleLog so it can be shared with the rest of the popcorn app as a classic logger.
> popcorn: enhance ConsoleLog

- misc/docker/full/Dockerfile
- misc/docker/tests/Dockerfile
We have a lot of timeout with a big Dockerfile
> docker: move the test part in another Dockerfile

- src/nitweb.nit
- src/web/api_catalog.nit
- src/web/api_docdown.nit
- src/web/api_feedback.nit
- src/web/api_graph.nit
- src/web/api_metrics.nit
- src/web/api_model.nit
- src/web/web_base.nit
- tests/sav/nitweb.res
Nitweb use popconfig
No changes on the output.
> nitweb: use pop_config

- contrib/nitrpg/src/achievements.nit
- contrib/nitrpg/src/events_generator.nit
- contrib/nitrpg/src/reactors.nit
- contrib/nitrpg/src/templates/panels.nit
- contrib/nitrpg/src/templates/templates_base.nit
- contrib/nitrpg/src/templates/templates_events.nit
- contrib/nitrpg/src/test_listener.nit
- lib/github/api.nit
- lib/github/cache.nit
- lib/github/events.nit
- lib/github/hooks.nit
- lib/popcorn/pop_auth.nit
> lib/github: use serialization

- lib/mongodb/queries.nit
- lib/popcorn/pop_repos.nit
A small abstraction of JsonObject dedicated to repo queries.
Just because I'm fed up with writing my JsonObjects by hand...
> lib/mongo: introduce mongo queries

- share/nitweb/directives/user/user-menu.html
- share/nitweb/index.html
- share/nitweb/javascripts/model.js
- share/nitweb/javascripts/nitweb.js
- share/nitweb/javascripts/users.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/user.html
- src/nitweb.nit
Nitweb users can open sessions with Github Auth.
For now, instances are useless and the User profile page displays only `nothing to display yet`.
Demo is here: http://nitweb.moz-code.org/
> Nitweb sessions

- contrib/nitcc/.gitignore
- contrib/nitcc/examples/blob.nit
- contrib/nitcc/examples/blob.sablecc
- contrib/nitcc/src/Makefile
- lib/nitcc_runtime.nit
Proof of concept of how a nitcc lexer can be monkey-patched.
maybe not enough for @ppepos, but it's something.
> Nitcc custom lexer

- lib/popcorn/pop_repos.nit
Provide boiler plate implementation of all object serializable to json.
`id` is used as a primary key for `find_by_id`.
Subclassing RepoObject makes it easy to create a serializable class:
~~~nit
import popcorn::pop_repos
class Album
super RepoObject
serialize
var title: String
var price: Float
end
~~~
Do not forget the `serialize` annotation else the fields will not be serialized.
It is also possible to redefine the `id` primary key to use your own:
~~~nit
import popcorn::pop_repos
class Order
super RepoObject
serialize
redef var id = "order-{get_time}"
end
~~~
> lib/popcorn: introduce RepoObject in pop_repos

- lib/popcorn/pop_repos.nit
> lib/popcorn: add `remove_all` service to pop repos

- lib/mongodb/queries.nit
- lib/popcorn/pop_repos.nit
Add some features used to paginate results:
* allow pop repos to query with a limit and skip
* makes Pipeline API cleaner with limit and skip
* allows user to count entities from a Repo
> Mongo: limit queries

- lib/popcorn/pop_auth.nit
Inherit this handler to access to session user from your custom handler.
For example, you need a profile handler that checks if the user is logged
before returning it in json format.
~~~nit
import popcorn::pop_auth
class ProfileHandler
super AuthHandler
redef fun get(req, res) do
var user = check_session_user(req, res)
if user == null then return
res.json user.json
end
end
~~~
By using `check_session_user`, we delegate to the `AuthHandler` the responsability
to set the HTTP 403 error.
We then check is the user is not null before pursuing.
> lib/popcorn: introduce AuthHandler to check user session

- lib/popcorn/README.md
- lib/popcorn/pop_auth.nit
- lib/popcorn/pop_logging.nit
- lib/popcorn/pop_repos.nit
- lib/popcorn/pop_sessions.nit
- lib/popcorn/popcorn.nit
Just some cleaning in popcorn modules
Also introducing mongo options for pop_repos.
> Popcorn clean

- lib/mongodb/queries.nit
Add some features to Mongo queries
> lib/mongo: improve queries

- lib/popcorn/pop_logging.nit
> lib/popcorn: also log query string in console

- lib/github/api.nit
Fix the wrong url in issue comment.
Also set the `Issue::is_pull_request` value with custom deserialization.
> lib/github: fix load issue comments and issue pull request

- src/modelize/modelize_property.nit
> modelize_property: Remove a unnecessary pre-condition

- lib/pipeline.nit
Add a generalization of `PipeJoin`.
> pipeline: Introduce `Iterator2`

- src/modelize/modelize_property.nit
- tests/base_virtual_type4.nit
- tests/sav/base_virtual_type4.res
- tests/sav/base_virtual_type4_alt1.res
> modelize_property: Promote `refine-type` to an error

- src/semantize/typing.nit
> typing: Fix minor mistakes in documentation

- share/nitweb/views/classdef.html
- share/nitweb/views/propdef.html
- src/model/model_json.nit
- src/web/api_model.nit
- src/web/web_base.nit
Nitweb was returning insane amount of data (~2mo of json by request). The new version (http://nitweb.moz-code.org/) is a little more perf.
> nitweb: light responses

- share/nitweb/directives/entity/card.html
- share/nitweb/directives/entity/defcard.html
- share/nitweb/directives/entity/namespace.html
- share/nitweb/directives/metrics/metrics_list.html
- share/nitweb/directives/search/card.html
- share/nitweb/index.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/ui.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/class.html
- share/nitweb/views/doc.html
- share/nitweb/views/group.html
- share/nitweb/views/module.html
- share/nitweb/views/package.html
- share/nitweb/views/property.html
- src/model/mmodule.nit
- src/model/model.nit
- src/model/mpackage.nit
- src/web/api_docdown.nit
- src/web/api_graph.nit
- src/web/api_metrics.nit
- src/web/api_model.nit
- src/web/web_base.nit
This PR use the `model_index` API to provide better quicksearch in nitweb.
Demo: http://nitweb.moz-code.org/
Will maybe close a shitstorm of quicksearch related issues but I'm to lazy to check the numbers...
> nitweb: use index for quick search

- src/doc/doc_down.nit
- src/nitweb.nit
- src/web/api_docdown.nit
This PR allows nitweb to render wikilinks from README.md files.
Here the demo with the lib/core/README.md file: http://nitweb.moz-code.org/doc/core
> nitweb: render wikilinks

- lib/core/math.nit
> lib/math: fix some nitunits

- lib/github/api.nit
> lib/github: load more user data

- src/model/model_collect.nit
> src/model: collect package modules

- src/web/api_model.nit
> nitweb: /random apply limit after random

- lib/mongodb/queries.nit
* Fix query prefixes
* Add Array related queries
> mongo: More queries

- share/nitweb/directives/entity/link.html
- share/nitweb/javascripts/nitweb.js
> nitweb: encode URIs

- share/nitweb/directives/entity/location.html
- share/nitweb/views/classdef.html
- share/nitweb/views/propdef.html
- src/model/model_json.nit
- src/model/test_model_json.sav/test_classdefs_to_full_json.res
- src/model/test_model_json.sav/test_classes_to_full_json.res
- src/model/test_model_json.sav/test_modules_to_full_json.res
- src/model/test_model_json.sav/test_packages_to_full_json.res
- src/model/test_model_json.sav/test_props_to_full_json.res
- src/web/api_model.nit
Should fix more points from #2177
* Sort list by alphabetical order
* Remove useless links on doc location
* Remove useless code tabs when the code linearization tab exists
Demo here: http://nitweb.moz-code.org/
> nitweb: misc fixes

- share/nitweb/directives/entity/rating.html
- share/nitweb/directives/entity/stars.html
- share/nitweb/index.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/grades.js
- share/nitweb/javascripts/model.js
- share/nitweb/javascripts/nitweb.js
- share/nitweb/javascripts/users.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/grades.html
- share/nitweb/views/user.html
- src/web/api_feedback.nit
- src/web/web_base.nit
Upgrade the feedback stars form.
More stars and more details:
Demo here: http://nitweb.moz-code.org/
> nitweb: rewritte stars

- lib/mongodb/mongodb.nit
- lib/postgresql/postgres.nit
- src/test_neo.nit
- tests/test_neo4j.nit
- tests/test_neo4j_batch.nit
- tests/test_postgres_native.nit
- tests/test_postgres_nity.nit
> tests: use NIT_TESTING_ID in neo4j tests

- lib/counter.nit
Added Counter::pack to separate values by occurence into a final 2D array of values
> lib/counter: Added pack function

- examples/calculator/Makefile
- examples/calculator/src/android14.nit
- examples/calculator/src/android21/android21.nit
- examples/calculator/src/calculator_logic.nit
- examples/calculator/src/ios.nit
Fix a bug where numbers would be limited to a single digit after some operations.
Improve the look of the calculator under iOS.
> calculator: bug fix and small tweaks to the iOS adaptation

- share/nitweb/directives/search/field.html
- share/nitweb/index.html
- share/nitweb/javascripts/ui.js
* Add some crappyjs(TM) to autoclose the search box when the user click somewhere else.
* Also autoclose the box when the user click on a link from the list (unwanted js sideeffects are sometimes wanted)
Checks one more box from #2178
Demo: http://nitweb.moz-code.org
> nitweb: close quicksearch box when clicking outside of it

- lib/mongodb/queries.nit
Also fix `op` method so it matches the specification in the comment
> mongo::queries: add unwind method

- lib/github/api.nit
- lib/github/github_curl.nit
- lib/github/loader.nit
- lib/json/serialization_write.nit
- lib/json/store.nit
Helper tool to download a Github repo and store it in a Mongo database.
Features:
* supports github wallets
* save current job and restore jobs after failure
* options to enable branches, commits, issues, pulls, comments and events loading
> lib/github: GitHub loader

- lib/counter.nit
Hey there,
Some fixes to counter:
* the first one should not be subject to discussion since it only fix the to_s nullable elements.
* the second one is more tricky. I propose to change the add_all behavior to increment all values instead of just rewriting them.
@privat, you are the main user of the `counter` lib, what is you feeling about that?
> Counter: fixes

- misc/jenkins/unitrun.sh
- tests/tests.sh
This could help to track why jenkins runs on osx are so slow
> OSX use gtime

- lib/core/collection/hash_collection.nit
> hash_collections: Fix the documentation of `Set::new`

- src/doc/console_templates/console_model.nit
- src/doc/html_templates/model_html.nit
- src/highlight.nit
- src/model/mdoc.nit
- src/model/model.nit
Centralize its definition and update its documentation.
> mdoc_or_fallback: Refactor

- src/compiler/abstract_compiler.nit
- src/compiler/java_compiler.nit
- src/compiler/separate_compiler.nit
- src/model/model.nit
- src/semantize/typing.nit
Various minor refactorings done for PR #2397.
> compiler: Refactor

- src/interpreter/naive_interpreter.nit
> intrepreter: Fix the documentation of `Instance::is_true`

- src/interpreter/naive_interpreter.nit
> intrepreter: Fix the documentation of `PrimitiveInstance`

- contrib/nitin/Makefile
- contrib/nitin/README.md
- contrib/nitin/nitin.nit
- contrib/nitin/nitin_readline.nit
- contrib/nitin/package.ini
- src/interpreter/naive_interpreter.nit
- src/loader.nit
- src/toolcontext.nit
This tool is outside src/ because:
1. Is is greatly experimental
2. It can depend on readline (GPL3) whereas the rest of nitc is Apache2.
Both are compatible but the final binary result is GLP3.
* use GNU readline to read lines
* use importation/refinement to handle incremental execution (so basically everything works out of the box)
* maintain an interpreter and live objects (the model grows but the interpreter and runtime data are reused)
Main missing features
* top-level variables are local
* runtime error/aborts just abort the interactive loop
* FFI is strange
* No model/object inspection
`-->` is the prompt, `...` the continuation prompt. What follows is the user input.
The rest is the output.
~~~raw
$ nitin
--> print 5+2
7
~~~
~~~raw
-->for i in [0..5[ do
...print i
...end
0
1
2
3
4 …
> nitin, an interactive interpreter

- contrib/nitin/nitin.nit
- tests/listfull.sh
- tests/niti.skip
- tests/nitin.inputs
- tests/nitvm.skip
- tests/sav/nitin.res
- tests/tests.sh
Add a basic test for the nit interactive interpreter.
I also added a new engine but most test fails because:
Local variables in main are too much local, so the following fail because `a` is unknown in the second line. I plan to solve this problem.
~~~
var a = 1
print a
~~~
Classes and top-level methods are analysed one after the other so the following fails because `B` is unknown while processing the first class. I do not plan to solve this problem as I think this is the expected behavior when interactive.
~~~
class A
var b: B
end
class B
end
~~~
> Nitin tests

- LICENSE-GPL-3
- NOTICE
> Update legal stuff

- Makefile
- contrib/tinks/Makefile
- tests/Makefile
> makefiles: Remove dead code

- lib/popcorn/pop_handlers.nit
- lib/popcorn/pop_validation.nit
> lib/popcorn: replace json_error method by something more useful

- contrib/neo_doxygen/src/model/descriptions.nit
- contrib/neo_doxygen/src/model/location.nit
- contrib/shibuqam/examples/shibuqamoauth.nit
- lib/github/api.nit
- lib/github/events.nit
- lib/github/github_curl.nit
- lib/json/static.nit
- lib/json/store.nit
- lib/json/string_parser.nit
- lib/mongodb/queries.nit
- lib/neo4j/curl_json.nit
- lib/neo4j/error.nit
- lib/neo4j/graph/graph.nit
- lib/neo4j/graph/json_graph_store.nit
- lib/neo4j/neo4j.nit
- lib/popcorn/pop_repos.nit
- lib/popcorn/pop_validation.nit
- src/doc/doc_phases/doc_indexing.nit
- src/examples/nitwebcrawl.nit
- src/model/model_json.nit
- src/web/api_catalog.nit
- src/web/api_metrics.nit
- src/web/web_base.nit
- tests/sav/nitserial_args1.res
Remove the now useless Jsonable class.
Let's see if something is broken.
> lib/json: remove Jsonable and replace it by Serializable

- src/compiler/separate_compiler.nit
> separate_compiler: Fix a spelling mistake in a comment

- src/model/model.nit
> model: Specify `MClassDef`s’ order once

- lib/more_collections.nit
> MultiHashMap: Provide the converse of `add_one`

- src/vm/virtual_machine.nit
> nitvm: Factorize the loading of superclasses

- src/parser/parser_nodes.nit
> parser_nodes: Fix documentation

- examples/rosettacode/align_columns.nit
> rosettacode: Fix spelling mistakes

- src/rapid_type_analysis.nit
> rapid_type_analysis: Fix a spelling mistake

- src/model/model.nit
> model: Remove truthful conditions

- contrib/shibuqam/examples/shibuqamoauth.nit
- lib/popcorn/examples/angular/example_angular.nit
- lib/popcorn/pop_auth.nit
- lib/popcorn/pop_handlers.nit
- lib/popcorn/pop_json.nit
- lib/popcorn/pop_repos.nit
- lib/popcorn/pop_templates.nit
- lib/popcorn/pop_tracker.nit
- lib/popcorn/pop_validation.nit
- src/web/web_base.nit
This PR introduces a way to validate and deserialize requests bodies with some shortcuts.
I'm not a big fan of the `new_body_object` but I don't see how to do this elegantly...
~~~nit
class MyJsonHandler                                                            
super Handler                                                                
redef var validator = new MyFormValidator                                    
redef type BODY: MyForm                                                      
redef fun new_body_object(d) do return new MyForm.from_deserializer(d)       
redef fun post(req, res) do                                                  
var post = validate_body(req, res)                                       
if post == null then return # Validation error: let popcorn return a …
> popcorn: some useful services for JSON related REST API

- src/parser/parser_nodes.nit
> parser_nodes: Fix spelling mistakes

- lib/gmp/native_gmp.nit
- lib/gmp/test_native_gmp.nit
gmp: Initial implementation of the GMP wrapper and simple test for it.
> Wrapper gmp

- lib/meta.nit
may be used to improve deserialization?
> lib/meta: add a *goret* approach to get the name of random types.

- lib/popcorn/pop_validation.nit
> lib/popcorn: introduce BoolValidator in popcorn::pop_validation

- bin/nit-makepackage
- contrib/nitrpg/package.ini
- examples/calculator/package.ini
- lib/actors/package.ini
- lib/gmp/package.ini
package.ini file are not mandatory, so to convince people to use then, here is a new tool.
> More package.ini

- src/model/model.nit
Just create standalone pre-constructed models already filled with entities that are exposed as attributes.
Then use these models to test various services.
In the prof-of-concept PR, I just added 2 simple docunits.
> testmodel: what about docunits to test model-related services?

- src/modelize/modelize_class.nit
- tests/error_formal_super.nit
- tests/sav/error_formal_super.res
Various refactorings that will be useful for later.
> modelize_class: Refactor

- misc/jenkins/unitrun.sh
- tests/tests.sh
This will help to identify where the real elapsed time is going.
> tests: measure time with elapsed time instead of user-mode time

- src/modelize/modelize_property.nit
> modelize_property: Remove an unreachable case

- tests/test_neo4j.nit
- tests/test_neo4j_batch.nit
The issue was related to a non-cleaned DB, so we try to force-clean.
> Attempt to fix the tests neo4j

- contrib/oot.sh
- contrib/oot.txt
They seems to be free software, so I think it is ok to include them...
> oot: add 2 random projects found on the Internet.

- src/modelize/modelize_property.nit
> modelize_property: Add a variable to shorten some code

- lib/neo4j/neo4j.nit
> neo4j: Add a fluent interface to set queries’ parameters

- lib/neo4j/neo4j.nit
- tests/test_neo4j.nit
- tests/test_neo4j_batch.nit
> neo4j: Prevent accidental code injections in the tests

- misc/docker/Dockerfile
- misc/docker/full/Dockerfile
* stretch (thus java8)
* new libs
* better usable android
* better usable java
* opengl validator
> some Docker update

- lib/gmp/gmp.nit
Signed-off-by: PatrickBlanchette <PatrickBlanchette@users.noreply.github.com>
> gmp: Introduce Long and Ratio

- lib/geometry/quadtree.nit
Replace the 4 attributes by an array of all the children. This new structure lightens the code and allows to fix 65 `method call on a nullable receiver` warnings. As this is already a significant refactor, I avoided modifying further the implementations to avoid breaking things.
> quadtree: use an array, fix warnings and standardize the doc

- contrib/benitlux/src/server/benitlux_daily.nit
- lib/curl/native_curl.nit
- lib/gamnit/network/client.nit
- lib/nitcorn/examples/src/htcpcp_server.nit
- src/interpreter/naive_interpreter.nit
- src/metrics/codesmells_metrics.nit
- src/metrics/detect_covariance.nit
- src/metrics/method_analyze_metrics.nit
- src/model/model.nit
- src/semantize/typing.nit
- src/vm/virtual_machine.nit
- tests/sav/warn_truism.res
- tests/test_postgres_native.nit
- tests/test_postgres_nity.nit
- tests/warn_truism.nit
Warning on `if a == true then` constructions.
> typing: new warning `useless-truism` to catch trainees.

- lib/core/bytes.nit
- lib/core/stream.nit
- lib/core/text/flat.nit
> core: intro BytesWriter and BytesReader

- .gitignore
> .gitignore: ignore more vim files

- lib/nlp/README.md
- lib/nlp/nlp.nit
- lib/vsm/README.md
- lib/vsm/examples/example_vsm.nit
- lib/vsm/vsm.nit
- tests/sav/example_vsm.res
Vector Space Model (VSM) is an algebraic model for representing text documents
(and any objects, in general) as vectors of identifiers, such as, for example,
index terms.
It is used in information filtering, information retrieval, indexing and
relevancy rankings.
The `vsm` package provides the following features:
* Vector comparison with cosine similarity.
* Vector indexing and matching with tf * idf.
* File indexing and matching to free text queries.
With VSM, documents are represented by a n-dimensions vector.
Each dimension represent an attribute of the document or object.
For text document, the count of each term found in the document if often used to
build vectors.
~~~nit
var vector = new Vector
vector["term1"] = 2.0
vector["term2"] = 1.0
assert vector["term1"] == 2.0
assert …
> Vector Space Model

- src/model/model.nit
- src/modelize/modelize_property.nit
Add a way to associate attributes and their getters/setters.
This will be useful for filtering things and groupings properties together.
> model: is_accessor

- src/model/model_collect.nit
- src/web/api_model.nit
> model_collect: collect more things

- contrib/nitiwiki/src/wiki_html.nit
- contrib/nitiwiki/src/wiki_links.nit
- lib/markdown/README.md
- lib/markdown/decorators.nit
- lib/markdown/markdown.nit
- lib/markdown/nitmd.nit
- lib/markdown/test_markdown.nit
- lib/markdown/wikilinks.nit
- src/doc/doc_down.nit
- src/doc/doc_phases/doc_readme.nit
- src/doc/html_templates/html_templates.nit
- src/nitcatalog.nit
- src/testing/testing_doc.nit
- src/web/api_docdown.nit
The emitter was unecessary.
Also done some cleaning.
> markdown: merge MDProcessor and MDEmitter

- lib/config.nit
> lib/config: fix doc

- src/doc/doc_base.nit
- src/doc/doc_phases/doc_readme.nit
- src/doc/vim_autocomplete.nit
- src/metrics/codesmells_metrics.nit
- src/metrics/inheritance_metrics.nit
- src/metrics/mclasses_metrics.nit
- src/metrics/mendel_metrics.nit
- src/metrics/method_analyze_metrics.nit
- src/metrics/mmodules_metrics.nit
- src/metrics/nullables_metrics.nit
- src/metrics/rta_metrics.nit
- src/model/model_collect.nit
- src/model/model_index.nit
- src/model/model_json.nit
- src/model/model_views.nit
- src/model/test_model_json.nit
- src/model/test_model_json.sav/test_classes_to_full_json.res
- src/nituml.nit
- src/test_model_index.nit
- src/web/api_catalog.nit
- src/web/api_metrics.nit
- src/web/api_model.nit
- src/web/web_base.nit
ModelView uses a mainmodule to flatten mclass hierarchies.
> model: ModelView uses mainmodule

- benchmarks/microbenches/catches.nit
It's just the program, not the bench scripts. Maybe also compare with other languages try/catch
> benches: add a simple microbenches for nit try/catch

- lib/gamnit/depth/more_models.nit
- lib/gamnit/flat/flat_core.nit
- lib/gamnit/gamnit.nit
- lib/gamnit/model_parsers/obj.nit
- lib/gamnit/programs.nit
- lib/gamnit/virtual_gamepad/virtual_gamepad.nit
- lib/glesv2/glesv2.nit
- misc/docker/full/Dockerfile
This PR brings miscellaneous improvements to the `gamnit` graphics framework, see each commit description for more details.
> gamnit: bug fixes, updated doc and prepare iOS support

- .gitignore
- share/man/picnit.md
- src/Makefile
- src/loader.nit
- src/picnit.nit
- src/picnit_shared.nit
- tests/README.md
- tests/picnit.args
- tests/sav/picnit.res
- tests/sav/picnit_args2.res
- tests/sav/picnit_args3.res
- tests/sav/picnit_args4.res
- tests/sav/picnit_args5.res
- tests/tests.sh
picnit is a command line tool to install Nit packages, it supports the following actions:
* `picnit install <package or git-repository>` Install a package by name or from a git-repository
* `picnit list`    List installed packages
* `picnit upgrade <package>`  Upgrade a package
* `picnit uninstall <package>`  Uninstall a package
* `picnit help [command]`    Show general help message or the help for a command
The Nit loader has been modified to search for packages where picnit puts them.
You can try picnit with:
~~~
picnit install hello_picnit
picnit list
nit hello_picnit
~~~
The install command clones the Git repo to `~/.local/lib/nit/hello_picnit/` where it will be found by all Nit tools. It can then be interpreted directly by nit (as in the above) or imported by any Nit module.
The …
> Intro picnit, the (minimal) Nit package manager

- Makefile
- src/Makefile
* nitc_0 is rebuild when needed
* tools are spited into two groups to lighten the initial build
Close #2619
> Fix regressions in make

- lib/curl/curl.nit
- lib/curl/native_curl.nit
Support using a Unix socket to send an HTTP request.
~~~
var request = new CurlHTTPRequest("http://localhost/")
request.unix_socket_path = "/tmp/nginx.sock"
var response = request.execute
~~~
@matthmsl Is this what you needed for #2623?
> curl: basic Unix domain socket support

- src/compiler/abstract_compiler.nit
- tests/base_autocast_prim.nit
- tests/sav/base_autocast_prim.res
> nitc: do not autocast primitive types

- src/model/model_collect.nit
> model_collect: collect all modules from a package

- lib/msgpack/read.nit
Some cases were treated independently while retaining mostly the same
code.
This commit tries to unite such cases into a single branch.
Doing so helps readability, reduces code duplication and should
hopefully improve performance as the number of tests to be performed is
lower.
> lib/msgpack: unify several cases for deserialization

- tests/sav/nitunit_args1.res
- tests/test_nitunit.nit
The code date from #360
close #1603
> tests/nitunit: test that private methods are nitunited

- lib/ini/ini.nit
This PR changes three things:
* remove `nullable` warnings
* keep the keys in the same order than they are added to the config file
* group keys in the ini output
> lib/ini: better output

- lib/bitmap/bitmap.nit
Some checks were missing after fixing some warnings in PR #2658, we add these checks here.
Note: the last commit only is relevant, the other comes from #2658
> Bitmap fix missing checks

- clib/traces.c
- clib/traces.h
- share/man/nitc.md
- src/compiler/abstract_compiler.nit
- src/compiler/separate_compiler.nit
To install lttng: https://lttng.org/docs/v2.10/#doc-installing-lttng
To compile using the trace system: add -t or --trace
To test tracing some instances :
lttng create "Nom de la session"
lttng enable-event --userspace Nit_Compiler:Object_Instance
lttng start
--> run your program
lttng stop
To read your CTF trace file:
babeltrace ~/lttng-traces/nom_de_la_session
> Trace system

- contrib/nitiwiki/README.md
> contrib/nitiwiki: protect non-nit code blokcs in README

- src/nitls.nit
> nitls: option -M escapes characters in paths

- src/Makefile
I wanted to have it in my path
> Makefile: add nitpackage

- src/compiler/abstract_compiler.nit
Add the `--shared-lib` command line option for `nitc` to generate a native library (.so or .dll). It is hidden because by itself it is not very useful. This is a first step to create polyglot programs where Nit is not the entrypoing.
I currently use such a DLL by first calling `nit_main` and then invoking callbacks generated by the FFI for a dummy method. Once we have a better way to generate the callbacks (or entrypoint actually) and maybe generate a .h, we could make this an official feature.
> nitc: intro hidden option to compile to a shared native lib (.so/.dll)

- contrib/model_viewer/README.md
- examples/calculator/README.md
- lib/app/README.md
- lib/gamnit/README.md
- lib/serialization/README.md
nitunit in jenkins did not test READMEs (cf #2313)
In order to test them, first fix them!
> lib&contrib: add some raw and nitish in READMEs

- src/astbuilder.nit
Adding new nodes creation services.
Signed-off-by: Florian Deljarry <deljarry.florian@gmail.com>
> astbuilder: Adding new nodes makers(assert, method, or, and,...)

- lib/pthreads/concurrent_collections.nit
Adding the implementation of the has method to call the has on the `real_collection`
> concurrent_collections: Add implementation of has method

- src/semantize/typing.nit
Split the get_method to three different entry points. These new entry points make it possible to adapt the treatment to the actual context. This avoids creating callsites manually and in the same time do the verification if the researched method exist (display an error if not exist)
Signed-off-by: Florian Deljarry <deljarry.florian@gmail.com>
> typing: get_method refactoring

- src/compiler/abstract_compiler.nit
- tests/nit.args
- tests/nitc.args
- tests/niti.skip
- tests/nitvm.skip
- tests/sav/nit_args9.res
- tests/sav/nitc_args12.res
Also add tests to avoid that again
> nitc: fix --keep-going in the compiler broken by 539ca148d

- src/metrics/readme_metrics.nit
- tests/sav/nitmetrics_args3.res
Some leftovers introducing the new markdown parser.
> metrics: ReadmeMetrics uses markdown2

- .gitlab-ci.yml
Results for nitmetrics should be easily available.
> ci: generate metrics output in an artifact file

- src/model/model.nit
Currently, the constructor of `MClassDef` would directly add itself in the `MModule`, like so:
`mmodule.mclassdefs.add(self)`. However, this could out of date `MModule:flatten_mclass_hierarchy`.
If we want better support for model manipulation after all the semantic phases, we need more logic when adding a new `MClassDef` in the hierarchy.
Moreover,  this allows better protection since `MClassDef` no longer needs to know `mmodule.mclassdefs`.
Signed-off-by: Louis-Vincent Boudreault <lv.boudreault95@gmail.com>
> MModule: new method `add_mclassdef` to avoid incoherent cache state.

- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
Removed duplicate code across all the compiler and made
`AbstractRuntimeFunction` implement Template Design pattern.
This allows for better code reuse and easier customization.
Removed the notion of "virtual function" and unified it with the concept
of thunk function. A thunk is an intermediary function between a caller
and a callee whose purpose is to compute thing before or after the
callee gets invoke. Currently, the only usages of thunks are to do conversions (casting)
before calling the actual callee. Thunks can be created by inheriting
`abstract_compiler::ThunkFunction` which provides a default
implementation. Furthermore, this class simplify the old code of
`SeparateRuntimeFunction` by replacing `if` with actual polymorphism.
Finally, thunks will be used to implement callref …
> compiler: Refactored `AbstractRuntimeFunction`

- lib/core/text/abstract_text.nit
Add a method `to_se` to get the string representation of float in scientific notation.
```
123.45.to_se == "1.2345e+02"
0.001234.to_se  == "1.234e-03"
10860460000.0.to_se == "1.086046e+10"
```
The to_se method have a precision between 1 to 6 max decimal. The precision is adapted in function of the number.
Add a `to_precision_size_with_format` and `to_precision_fill_with_format` method to get the representation in a specific given format
> Abstract_text: Add a method to get string representation of float in scientific notation

- lib/graph/digraph.nit
Add the implementation of a reflexive directed graph. Added element is in relation with itself (ie if the graph has `u` node is implies `self.has_arc(u,u) == true`)
> digraph: Implementation of a reflexive directed graph

- src/parser/nit.sablecc3xx
- src/parser/parser.nit
- src/parser/tables_nit.c
- tests/syntax_annotations2.nit
This was hard but the solution is easier than expected.
Annotations accepted documentation comments but other comments were refused. This should allow all configuration of comments.
close #2786
> Can comment annotations

- src/contracts.nit
- tests/contracts_generic_type.nit
- tests/contracts_virtual_type.nit
- tests/sav/contracts_generic_type.res
- tests/sav/contracts_virtual_type.res
This pr fix the bug when the contract is apply with generic or virtual type.
> Contract: bug fix

- src/contracts.nit
Moving the check if a contract is needed in the visitor to avoid the property creation without definition.
> contracts: fix usage of contract with `--erasure`

- tests/sav/curl_http_args1.res
- tests/sav/curl_http_args2.res
- tests/sav/curl_http_args3.res
The site example.org was modified on October 18th, so that the tests no longer work. This pr fix this problem.
> tests: Test result update for `curl_http`

- src/rapid_type_analysis.nit
I was reading that file recently and noticed this empty line :p
> Remove useless empty line

- src/neo.nit
Move neo node creation in her respective class.
> neo: Move neo node creation

- src/astbuilder.nit
Add new make method for three kind of nodes (AAttrPropdef, ACallAssignExpr)
> src/astbuilder: Add new nodes makers

- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
Before this update, the method `compile_class_to_c` handled every part
of the class compilation process even special case (universal class).
By doing so, we can't refined this method efficiently without
reimplementing the entire method. This is a pain since each time we
need to add universal class we have to modify the original code instead
of refining the compiler.
The method `compile_class_to_c` has been divided in three main parts:
1. the class's vft compilation (same for every type of class)
2. the compilation of universal class specifics (change alot through
time). This part must managed every part of a universal type, except its
vft compilation which already handled by the 1st step.
3. the compilation of the default `NEW` allocator (apply only for
non-universal type).
Moreover, the …
> separate_compiler: Refactored class compilation

- src/semantize/typing.nit
Add a mechanism to suppress warnings during the typing phase. I also took the opportunity to modify a bad indentation in the file :smile: .
> typing: Add a mechanism to disable warnings

- src/modelize/modelize_property.nit
Define a small fluent API in order to modify easily AAttrPropdef.
> modelize_property: Define a new API to modify AAttrPropdef

- src/astbuilder.nit
Add two new services in the astbuilder module:
- Add a way in ModelBuilder to create AST and module entity at same time (`create_method`, `create_class`, `create_attribute`).
- Add a new property in MEntity `create_ast_representation` to return a ast representation of `self`.
> astbuilder: Introduction of new construction services

- src/astbuilder.nit
- src/contracts.nit
This pr :
- move `do_all` method into ASTBuilder. 
- generalize `create_callsite` to take into consideration AAttrPropdef
> Astbuilder improvement

- contrib/nitcc/src/autom.nit
- contrib/nitcc/src/re2nfa.nit
- contrib/nitcc/src/regexparser.nit
regexparser parses ERE-like regular expression and compute information and graphs.
> nitcc: new tool regexparser

- contrib/nitin/Makefile
- contrib/nitin/tests.sav
- contrib/nitin/tests.sh
- contrib/nitin/tests/attribute_initialization.nit
- contrib/nitin/tests/hello.nit
- contrib/nitin/tests/importation.nit
- contrib/nitin/tests/refinement.nit
- contrib/nitin/tests/specialization_refinement.nit
- contrib/nitin/tests/variables.nit
#2852 shown that nitin is a good program to test the interpreter. So beef up the tests!
> nitin: add some tests to the nit interactive interpreter
