- contrib/friendz/src/friendz_android.nit
- lib/android/input_events.nit
- lib/mnit_android/android_app.nit
Extract `input_events` from `android_app` so it is independant of the display part of Mnit. It now relies only on `mnit_input`, which will probably be kept around for Gamnit.
The extraction has been organized in three commits for easier review:
* Extract the code with minimal modifications.
* Update the style of the new module (this may be the first module that used the FFI, its style was outdated).
* Improve the doc and fix warnings in the new module.
> Android: extract input_events and clean up

- src/frontend/no_warning.nit
Rationale: the presence of a `module` clause is a good heuristic to
discriminate quick and dirty prototypes from nice and clean modules
> no_warning: modules without a module clause do not cause `missing-doc`

- lib/android/cardboard.nit
- lib/java/collections.nit
- src/compiler/android_platform.nit
- src/ffi/java.nit
Use the same approach to copy the "libs" dir to the Android project than the "res" dir.
Extern Java types for primitive arrays is a bit tricky to convert to JNI format. For example, `Object[]` in Java is represented by `[Ljava.lang.Object;` in JNI format, and `int[]` is `[I`.
Add some primitive Java arrays, will add more as needed. Will also need to update jwrapper to use those.
The last commit hints at my next demo. It is mostly generated with jwrapper.
> Support for Java arrays, Java libs on Android and Google Cardboard head tracking

- src/loader.nit
- src/nitdoc.nit
- src/nitlight.nit
- src/nitmetrics.nit
- src/nitpick.nit
- src/nitserial.nit
- src/nituml.nit
- src/nitunit.nit
Make Nit tools more POLA when projects (or groups) are given on the command line.
eg. people using `nitunit ../lib/mylib` may expect that all the unit tests of the lib are executed, not just those from the default module `../lib/mylib/mylib.nit` (that often is basically an empty bottom module)
So this PR introduces `parse_full` in the loader that loads and returns all the modules of given groups, then adapt most tools to use `parse_full`.
No more crazy shell pipelines with `nitls` or `find` to use nitunit, nitpick and other on all the modules of your libs or programs.
> Tools works with groups

- lib/standard/exec_nit.c
- tests/sav/error_annot_c_compiler_alt5.res
- tests/sav/test_exec.res
- tests/test_exec.nit
When a bad command is passed to Process, the child-process will `C-abort()`, displaying frightening messages on the screen and causing confusion to the user.
Instead, just `_exit(127)` to terminate the child silently and let the parent do its things.
TODO better error management to not lose the error of the failed `execvp` system call.
> No abort() on bad execvp

- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/rapid_type_analysis.nit
- src/semantize/typing.nit
- tests/base_null.nit
- tests/sav/base_null.res
Accepts literal `null` as a receiver of `==`, `!=` and `is_same_instance`.
This could help to finish #1041
Does people need other methods of Object available for `null`?
> null as receiver

- contrib/pep8analysis/src/pep8analysis_web.nit
- lib/string_experimentations/utf8.nit
- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/loader.nit
- src/model/mmodule.nit
- src/modelize/modelize_class.nit
- src/modelize/modelize_property.nit
- src/test_docdown.nit
Enforce rules indicated in #1047.
So, having homonymous public modules and classes in a same project raises an error.
In the current code there was no conflicting modules. It is not surprising because for a long time the compilers refused homonymous modules even in different projects.
There was only 2 conflicting classes (on a total of 3640). This is more a good surprise since I expected a lot of conflicts. It is some kind of prof that the proposed policy is not that crazy. The two pairs of conflicting classes were `UnicodeChar` in `lib/string_experimentations/utf8.nit` and `lib/string_experimentations/utf8_noindex.nit`, and `Frame` in `naive_interpreter` and `abstract_compiler`. Some commits in the PR rename one of each pair to solve the conflicts.
For public properties, the proposed …
> Enforce namespace rules

- lib/socket/socket.nit
- lib/socket/socket_c.nit
- lib/standard/gc.nit
Additionnal notes:
* `FinalizableOnce` will probably be the most common `Finalizable`, but it wouldn't cover all cases.
* Remove some unused features from `socket` to make it compatible with Android.
* Fix an illegal extern class by making it a pointer.
* Do not `exit 1` on socket error.
> More on Sockets and FinalizableOnce

- share/man/nitc.md
- src/compiler/abstract_compiler.nit
- src/compiler/android_platform.nit
- src/compiler/emscripten_platform.nit
- src/compiler/separate_compiler.nit
- src/platform.nit
Genuine constant static variables are used to store the colors used in OO mechanisms.
This makes the compiler program slower since additional indirections are required to get the values.
It also produces a little bit larger executables since static memory has to store the colors.
This PR introduce a trick user in the original PRM that uses linker symbols to encode the colors.
It is not completely portable so it must be activated with the option `--colors-are-symbols`
For numbers (with the traditional nitc/nitc/nitc)
before: 0m7.544s
after: 0m7.228s (so -4%)
> Use linker symbols to encode colors

- src/compiler/compiler_ffi.nit
- src/ffi/cpp.nit
- src/ffi/ffi.nit
- src/ffi/ffi_base.nit
- src/ffi/objc.nit
- src/nitni/nitni_base.nit
This prevents conflicts between two modules using the FFI and with the same short name. It follows the same change for all generated files.
> FFI use `MModule::cname`

- lib/more_collections.nit
- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/array.nit
- lib/standard/collection/hash_collection.nit
- lib/standard/string.nit
- src/semantize/typing.nit
I need at least the first commit since MapIterators can be used with non-maps. The second commit is more for consistency. Note that HashMap keys are still non-null.
If this is of interest to you, I'll complete and publish my `NullableMap` in `more_collection`.
> Allow keys to be nullable in `Map` and `MapIterator`

- src/model/mmodule.nit
- src/model/model.nit
- src/model/mproject.nit
- tests/sav/nitunit_args4.res
- tests/sav/nitunit_args5.res
Better implementation for `full_name` and `c_name` that make them shorter and use the project as the namespace of public entities.
Examples of fullnames of entities used in messages
* A public class `A` defined in the module `m` of the project `p` was `p::m::A`, now it is `p::A`.
* A public method `x` defined in a class `A` in the module `m` of the project `p` was `p::m::A::x`, now it is `p::A::x`
Exeaple of fullnames for entities that are used internally:
* The refinement of `A` in a module `p::n` was `p::n#p::m::A`, now it is `p::n#A`
* The redefinition of `x` in a class `B` in `p::n` was `p::n#p::m::B#p::m::A::x`, now it is `p::n#B#A::x`
The `c_name` get some comparable simplifications, so C identifiers will be simpler and will less overflow in unwind or in valgrind.
Note: please …
> Namespace for

- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
Refactor SeparateRuntimeFunction and related services in the separate compiler.
This simplify the compiler and improve the efficiency of the generated code a little.
Before: 0m7.588s
After: 0m7.364s (-3%)
This refactorisation is required for some next PR that will improve polymorphic calls
> Runtime function

- src/doc/doc_down.nit
> nitdoc: does not apply header style to span elements anymore.

- lib/android/native_app_glue.nit
- lib/android/ui.nit
- share/libgc/.gitignore
- share/libgc/android-setup-libgc.sh
- src/platform/android.nit
Adds a script to fetch, configure and compile libgc to be deployed on Android. This script will have to be tweaked and improved, but this version works.
_nitc_ will execute the script once before compiling your first Android program.
I still have to look at the possibility to release memory on explicit OS calls to do so. it will be for a future PR.
> libgc on Android

- contrib/pep8analysis/src/pep8analysis_web.nit
- lib/cocoa/app_kit.nit
- lib/cocoa/cocoa.nit
- lib/cocoa/foundation.nit
- lib/cpp.nit
- lib/java/java.nit
- lib/jvm.nit
- lib/mpi.nit
- lib/pthreads/extra.nit
- lib/pthreads/pthreads.nit
- lib/realtime.nit
- lib/sdl.nit
- lib/sdl2/image.nit
- src/compiler/compiler_ffi.nit
- src/ffi/c.nit
- src/ffi/c_compiler_options.nit
- src/ffi/cpp.nit
- src/ffi/ffi.nit
- src/ffi/java.nit
- src/ffi/objc.nit
- src/frontend/check_annotation.nit
- tests/error_annot_c_compiler.nit
- tests/sav/error_annot_c_compiler_alt1.res
- tests/sav/error_annot_c_compiler_alt2.res
- tests/sav/error_annot_c_compiler_alt3.res
- tests/sav/error_annot_c_compiler_alt4.res
- tests/sav/error_annot_c_compiler_alt5.res
- tests/sav/error_annot_c_compiler_alt6.res
- tests/test_annot_c_compiler.nit
The new name is shorter, easier to remember and more standard. I may soon extend these annotations to provide information per platform, mainly to provide ldflags for Android only.
> Rename annotations for the C/C++ compilers and linker to `cflags` and `ldflags`

- lib/github/hooks.nit
This module introduces an abstract listener for Github hooks with nitcorn.
PS: OMG first PR with syntax highligh!!!! Thx @R4PaSs !
> lib/github: uses nitcorn to listen Github hook events.

- src/interpreter/naive_interpreter.nit
- src/nit.nit
- src/nitvm.nit
- src/vm.nit
- src/vm_optimizations.nit
This PR introduces some change in the implementation of object mechanisms in the nitvm.
Now, the dispatch between several mechanisms is made directly in the AST nodes instead of in runtime mechanisms themselves.
This PR is preliminary work before the implementation of complex optimization systems, but now the nitvm is sligtly more efficent than before because the choice between implementations is only made once (the first time).
I use a workaround in AST nodes to avoid conflict with refinements between the interpreter and the vm.
In the future this will need to be well implemented, maybe by creating a sort of ```CallSite``` for subtyping test and attribute access and store informations into them instead of into the nodes.
> Optimizations in nitvm

- lib/android/aware.nit
- lib/android/log.nit
- lib/android/native_app_glue.nit
- lib/egl.nit
- lib/glesv2/glesv2.nit
- lib/mnit_android/android_assets.nit
- lib/mnit_android/android_opengles1.nit
- src/c_tools.nit
- src/compiler/abstract_compiler.nit
- src/compiler/compiler_ffi.nit
- src/ffi/c.nit
- src/ffi/c_compiler_options.nit
- src/ffi/cpp.nit
- src/ffi/ffi.nit
- src/ffi/java.nit
- src/ffi/objc.nit
- src/platform/android.nit
- src/platform/emscripten.nit
- src/platform/platform.nit
- src/platform/pnacl.nit
For the same module, cflags and ldflags can vary per platform. This new annotation on annotations targets a platform for each cflags or ldflags. By default, the target platform is that of the host. It will probably need to be clarified on more modules once we support more platforms.
It will be used to load (or not load) OpenGL ES v1.0 vs 2.0 and libandroid in future PR. For now, only `calculator` should save on linking with OpenGL.
I hesitated between different annotations before settling on `@android`:
* `@target(android)` makes it clear that it is the target, but it gets a bit heavy to read: `module android_opengles1 is ldflags("-lEGL -lGLESv1_CM")@target(android)`
* `@only(android)` makes it clear that only Android is affected by this annotation.
* but `@android` is easy to read and …
> ldflags for Android

- examples/mnit_simple/src/simple_android.nit
- examples/mnit_simple/src/test_bundle.nit
- lib/android/activities.nit
- lib/android/bundle/bundle.nit
- lib/android/native_app_glue.nit
- lib/android/ui.nit
This PR cleans the way to replace our current use of `NativeActivity` by our own `NitActivity` a direct subclass to `Activity`. The result of this PR that we are less dependent on `NativeActivity` and the `native_app_glue` module.
Notable modifications:
* Use Java `Activity` instead of `NativeActivity` wherever possible.
* Rename, to follow convention, Nit `NativeActivity` to `NativeNativeActivity` and `Activity` to `NativeActivity`. Thus all previous Java code using the Java `NativeActivity`, will now use Java `Activity`. The name `NativeNativeActivity` is weird, but temporary as the class will be removed once we have our `NitActivity`.
> Clean up to prepare for NitActivity

- lib/standard/string.nit
- lib/standard/string_search.nit
`SELFTYPE` in String is used to dintinguish buffers from strings. Unfortunately it is sometime badly used.
This series try to at least improve thing so that operations on buffers do not crash at runtime.
Still, I think there is something fishy in the String vs Buffer API
> Fix virtual types in string

- examples/rosettacode/doors_with_classes.nit
- lib/more_collections.nit
- lib/standard/collection/hash_collection.nit
- src/model/model.nit
Recent profiling of the interpreter nit shows that a lof of time is used in hashmaps. This PR improves the standard use-path with the safe method `get_or_null` that is more efficient (and simple) than `has_key` followed by `[]`.
The time for `nit doors_with_classes.nit 5000` give
before: 0m5.592s
after: 0m5.208s (-6,7%)
Note: by comparison, the ruby version is 0m2.284s, and the python is 0m0.116s ; there is still a lot of work
> Optimize get_or_null

- src/loader.nit
Was asked by @xymus in #1134 to be able to do `nitls -M standard`
> loader: get_mgroup look in path

- lib/standard/string.nit
- lib/standard/string_nit.c
- lib/standard/string_nit.h
- lib/standard/time.nit
- src/interpreter/naive_interpreter.nit
Another step towards the closure of #1106 and #69, this PR removes several calls to `malloc` in `lib/standard` C code and replaces them by some of the solutions proposed in #1106 to handle the allocation of Strings.
@xymus: Your review is more than welcome since we're dealing with extern code, it might be a good time to specify and document how to properly allocate extern data structures to avoid leaking code such as the ones we had.
> String memory fixes

- src/compiler/abstract_compiler.nit
- src/loader.nit
This PR remove the remaining big variability for nitc when generating separate files: the path of nit module in runtime error messages.
When compiling a same module but from different current working directories, the relative path of the module changed. Thus causing unnecessary difference in the generated C source code that made ccache unhappy.
Before
~~~
$ ccache -C
$ time nitc src/nitc.nit
user	2m8.264s
$ cd src
$ time nitc nitc.nit
user	2m8.676s
~~~
After
~~~
$ ccache -C
$ time nitc src/nitc.nit
user	2m9.180s
$ cd src
$ time nitc nitc.nit
user	0m9.812s
~~~
Note: some files are still different after the PR
* main.c because it contains the real filepath
* c_function_hash.c same
* _ffi.? because the pragma lines indicate the original relative file
Note 2: `.nit_compile` directories are …
> Global for filenames

- src/Makefile
The produced tools in bin/ should be faster to use then.
> Makefile: initial make use --semi-global

- misc/README.md
- misc/vim/plugin/nit.vim
- src/doc/vim_autocomplete.nit
The main improvement is the knowledge of constructors. They will be suggested along with their class after a `new`, ex: `new Arr`, it will autocomplete to `Array[E]`, `Array[E].with_items`, etc. It will also show their corresponding documentation.
Also detect the keywords `isa` and `as`.
> Vim omnifunc diffentiate between types, class declaration and instanciation

- lib/glesv2/glesv2.nit
The main point of this PR is to try a new naming convention for the glesv2 module.
Ideas behind this convention:
1. Be as close as possible to the C API: use the same function and macro names. 
2. Modify those names only for compatibility with the Nit language: the macros cannot begin with `GL_` so use `gl_` instead.
3. Apply types and other Nity features when they can help and don't interfere with the original API.
It differs from the previous convention of renaming all entities to the Nit style. It is not heavier in the module definition but should be easier for the users.
In practice, to convert OpenGL ES C code to Nit you would need to change the prefix `GL_` to `gl_`, and remove `;`.
In C:
~~~
glBindFramebuffer(GL_FRAMEBUFFER, my_fbo);
glBindRenderbuffer(GL_RENDERBUFFER, …
> lib/glesv2: intro framebuffer related services and try a new style

- benchmarks/bench_engines.sh
- src/compiler/separate_compiler.nit
Add option `--guard-call` as an alternative implementation of the link-time optimization `--substitute-monomorph`
The idea is to have the standard VFT call guarded by a symbol when the call is monomorphic.
So the sequence is independent of any client and is roughly
~~~
if SYMBOL != null then
SYMBOL(ARGS)
else
(SELF->VFT[COLOR])(ARGS)
end
~~~
where the value of the SYMBOL is set for each specific program at link-time: null when the call is polymorphic and the address of the single target when the call is monomorphic.
Benches show that, on my computer, there is from 0% to 10% in loss so this alternative implementation is pure overcost :)
Still keep it because, I coded it and works, and it may worth something on other architectures.
The benchs shows some quick results:
* first (sc, red) is …
> Guard call

- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/array.nit
- lib/standard/kernel.nit
- tests/sav/nitg-e/fixme/base_gen_reassign_alt4.res
- tests/sav/nitg-e/fixme/base_gen_reassign_alt5.res
- tests/sav/nitg-e/fixme/base_gen_reassign_alt6.res
- tests/sav/nituml_args3.res
- tests/sav/nituml_args4.res
- tests/sav/test_new_native_alt1.res
As exposed by #917 a standard API to clone objects could be useful.
This PR propose a Cloneable interface that class can implement.
The specif semantic of what a clone is is domain-dependent, the only suggestion I define is to be POLA and to consider the post condition `self == clone`. It seems sane since the precise semantic of `==` is also domain-dependent. The post-condition is not mandatory since not all classes redefines `==` and maybe some classes could be cloneable without being `==`-able. The reason is that `clone` is instantaneous but the semantic `==` should remain valid all the time. For instance, It could make sense to clone some Iterators but I am not sure what is a sane definition of `==` on them.
As a POC, clone is implemented is the three Array-related classes, Array, …
> Introduce Cloneable interface

- src/compiler/separate_compiler.nit
- tests/sav/nitg-sg/fixme/test_gen.res
Those in primitive types where already inlined, this time it is the ones in Object, NativeArray and other.
A special case remain for `object_id` since the value in standard objects is redefined in primitive type.
So this one is not inlined.
The gain in nitc/nitc/nitc is less that I expected but not that bad.
before: 0m7.276s
after: 0m7.100s (-2.5%)
Bonus: an old bug related to native arrays in --semi-global related to inlining is also fixed.
> Inline intern methods in standard objects

- src/compiler/abstract_compiler.nit
`once` structure and literal strings are implemented with a guard so that
onced-expression and literal strings are evaluated/created once then
stored in a static variable.
This patch just informs GCC that the fast path (get the saved value)
it the frequent path. It's up to GCC to do something useful with this
information.
It seems it does since number for nitc/nitc/nitc are
before: 0m7.324s
after: 0m7.156s (-2.3%)
> compiler: fast path is the hot path in once and literal strings

- src/parser/parser_nodes.nit
- src/semantize/auto_super_init.nit
- tests/base_init_raf2.nit
- tests/sav/base_init_raf2.res
Remove an old FIXME for compatibility with the old nitc that prevents the inclusion of autosuperinit calls in refinements.
Close #1186 (thus bring back the the feature from #916)
> Autosuperinit in refinements

- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/array.nit
- lib/standard/collection/hash_collection.nit
- lib/standard/file.nit
- lib/standard/string.nit
Make lazy some attributes of often used classes. So that the attribute creation cost only when they are really used.
More impact that initially imagined:
for nitc/nitc/nitc
before: 7.188
after: 7.008 (-2.5%)
> More lazyness in standard

- lib/standard/collection/array.nit
- tests/sav/test_new_native_alt1.res
on nitc/nitc/nit this reduce a lot the number of allocated iterators.
before:
* 0m7.168s
* 2,706,498 new ArrayIterator
* the second most allocated class (after NativeArray)
after:
* 0m7.060s (-1.5%)
* 785,781 new ArrayIterator (-70%)
* the 7th most allocated class
> Reuse Array Iterators

- misc/README.md
- misc/vim/plugin/nit.vim
- src/doc/vim_autocomplete.nit
* The omnifunc for Nit search for autocomplete suggestions in the doc. So if you write `12.modulo`, then hit `Ctrl-X Ctrl-O` (launching the omnifunc), it will suggest `%` to replace the `modulo` part. This is useful when guessing the name of the wanted entity.
* The Nitdoc function can be mapped to `Ctrl-D` to show the doc associated to the word under the cursor. There is still no semantic analysis here, so it will list all possible docs.
* The NitGitGrep function can be mapped to `Ctrl-G` to find instances of the word under the cursor in the currect directory using `git grep`. It will first try to display any definitions and then its uses. This one is a bit trickier to use, but it can be very useful.
----
Bonus hint! You can select the size of the preview window to 5 lines with `set …
> Vim autocomplete search in doc and 2 new useful Vim functions

- lib/standard/collection/abstract_collection.nit
- misc/vim/plugin/nit.vim
- src/doc/vim_autocomplete.nit
- src/model/model.nit
Calling Nitdoc() or Ctrl-D on the word `Container` will now display the following in the preview window.
~~~
A collection that contains only one item.
Used to pass arguments by reference.
Also used when one want to give a single element when a full
collection is expected
* Direct super classes: Collection
* All super classes: Collection, Object
* Direct sub classes: ListNode
* All sub classes: ListNode
+ count(item: E): Int  # How many occurrences of `item` are in the collection?
+ first: E  # Return the first item of the collection
+ has(item: E): Bool  # Is `item` in the collection ?
+ has_all(other: Collection[E]): Bool  # Does the collection contain at least each element of `other`?
+ has_exactly(other: Collection[E]): Bool  # Does the collection contain exactly all the elements of …
> Better Vim documentation on classes (with special attention to the doc of Container)

- src/interpreter/debugger.nit
- src/interpreter/naive_interpreter.nit
- src/nit.nit
- src/nitvm.nit
- src/variables_numbering.nit
The first commit change the way variables are accessed in the vm.
For each method or attribute block (to init them), we recursively go into the AST to find each variable declaration in order to give them a fixed position (in the environment).
This is a small recursion since we only need to go deeper for block constructions.
During execution, the access are made by using this position instead of using the old ```HashMap[Variable, Instance]``` of the interpreter. 
The second commit completely replace the frames of the interpreter to avoid allocation of these hashmaps in the virtual machine, the commit is pretty verbose but this is mainly code from the interpreter.
The overall gain is good since the vm is now faster than the interpreter :)
For the small benchmark ```nitvm src/nit.nit …
```
> Optimize variable access in the nitvm

- share/man/nitunit.md
- src/loader.nit
- src/location.nit
- src/model/mdoc.nit
- src/modelbuilder_base.nit
- src/neo.nit
- src/nitunit.nit
- src/testing/testing_doc.nit
- tests/nitunit.args
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args7.res
- tests/test_nitunit3/README.md
- tests/test_nitunit3/test_nitunit3.nit
- tests/test_nitunit_md.md
A lot of work but quite straightforward. Nit can be a really nice language when doing maintenance of old code.
The first part ot the PR updates the nitdoc to test documentation of groups (as requested by #1201)
The second part of the PR (I planned to do 2 PR but the second was more easy to do than expected) makes that nitunit can also process sand-alone markdown files (documentation, wiki pages, etc.).
Example:
~~~
-- foo/
|-- README.md
`-- foo.nit
~~~
~~~sh
$ nitunit foo/foo.nit
$ nitunit foo
$ nitunit foo/README.md
~~~
Close: #1201
> Nitunit works with groups and markdown files

- lib/deriving.nit
- lib/standard/collection/abstract_collection.nit
- src/frontend/check_annotation.nit
- src/frontend/deriving.nit
- src/frontend/frontend.nit
- tests/sav/nitg-g/fixme/test_deriving_alt1.res
- tests/sav/test_deriving.res
- tests/sav/test_deriving_alt1.res
- tests/sav/test_deriving_alt2.res
- tests/sav/test_deriving_alt3.res
- tests/sav/test_deriving_alt4.res
- tests/test_deriving.nit
This PR is crazy and inspired by https://github.com/privat/nit/pull/1202#discussion_r26359435
Basically, you will find here some hackish user-level pseudo meta-programming with optional unsafe support from the execution engines trough injection of code in the AST.
The idea is a generalization (and a basic simplification) of the approach or @xymus for serialization.
If fact, there is 2 level of generalizations.
In the compiler, a new phase `deriving` offers a static deriving mechanism. For instance, the annotation `auto_inspect` will implements the `inspect` method with a simple recursive inspection of attributes.
In the standard library, a new module `deriving` offers a general mechanism with a new standard `derive_to_map` method that is expected to dump attributes in a simple HashMap. …
> Derive all the things

- benchmarks/bench_engines.sh
- share/man/nitc.md
- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
- tests/base_attr.nit
- tests/base_attr_def.nit
- tests/base_attr_init_val2.nit
- tests/base_empty_module.nit
- tests/base_eq_null_notnull.nit
- tests/base_gen.nit
- tests/base_gen2.nit
- tests/base_gen_int.nit
- tests/base_simple.nit
- tests/base_types_formal_and_virtual.nit
- tests/base_types_formal_and_virtual2.nit
- tests/base_types_formal_and_virtual4.nit
- tests/base_var_type_evolution_null5.nit
- tests/base_var_type_evolution_null_while.nit
- tests/base_var_type_evolution_nullable.nit
- tests/error_constraint_raf.nit.broken
- tests/error_needed_types.nit
- tests/error_prop_glob.nit
- tests/test_prog/platform/platform.nit
Another old optimization since it was present in PRM, the Australopithecus compiler.
This PR bring back tagging of the primitives types Int, Bool and Char.
Previously, all primitive types where boxed. 
It means that when a Bool, or any primitive object, must be manipulated in a polymorphic way (i.e. as an Object in a `val*`), a small box is allocated that contain the value and the reference (the `val*`) points to the box.
The boxes use the layout of real objects (with a pointer to the class table and everything) so that boxes are compatible with the various implementation of OO mechanism, eg `obj->class->vtf[METHODID]` to implement a method invocation.
Basically boxes work like Java auxiliary classes (eg. `Integer`) except that they are fully transparent for the user and, more important, …
> Enable tagging of primitive types

- lib/standard/string.nit
Valgrid said it is used a lot.
So I mixed (`-m`) nitc with the following module
~~~nit
import counter
redef class Int
redef fun to_s
do
sys.itos_cpt.inc(self)
return super
end
end
redef class Sys
var itos_cpt = new Counter[Int]
redef fun run
do
super
itos_cpt.print_summary
itos_cpt.print_elements(10)
end
end
~~~
The result shows that `0` and `1` are the top `to_s`-ized numbers.
~~~
0: 13554 (9.29%)
1: 10012 (6.86%)
2: 5671 (3.88%)
~~~
So I just shortcut-them to reduce allocations.
With nitc/nitc/nitc:
before: 0m6.756s
after: 0m6.632s (-2%)
> lib/string: `Int::to_s` shortcuts 0 and 1

- examples/calculator/Makefile
- examples/calculator/src/calculator_android.nit
- examples/calculator/src/calculator_logic.nit
- lib/android/NitActivity.java
- lib/android/README.md
- lib/android/aware.nit
- lib/android/dalvik.nit
- lib/android/native_app_glue.nit
- lib/android/nit_activity.nit
- lib/android/ui.nit
- lib/jvm.nit
- src/platform/android.nit
- src/platform/android_annotations.nit
This PR could be described in 3 steps.
* Clean up lib/android and move up `dalvik` in the module hierarchy.
* Intro NitActivity.java (the most important commit)
* Update calculator (only) to use the new NitActivity with all its perks.
See the doc of the nit_activity module for the details on the polyglot implementation, copied hre for your convenience:
This module is implemented in 3 languages:
* The Java code, in `NitActivity.java` acts as the entry point registered
to the Android OS. It relays most of the Android callbacks to C.
In theory, there may be more than one instance of `NitActivity` alive at
a given time. They hold a reference to the corresponding Nit `Activity`
in the attribute `nitActivity`.
* The C code is defined in the top part of this source file. It acts as a
glue …
> Intro NitActivity an Android entry point in pure Nit, Java, and C (almost no NDK)

- contrib/opportunity/src/opportunity_controller.nit
This error crashed the server 52 times in the last month.
Opportunity on xymus.net has already been updated.
Thanks to @isra17 and @ageei exec members for forging broken requests and revealing this problem.
> contrib/opportunity: prevent null receiver error

- lib/meta.nit
- tests/sav/nitg-e/test_meta.res
- tests/sav/nitg-g/fixme/test_meta.res
- tests/sav/nitg-s/fixme/test_meta.res
- tests/sav/nitg-sg/fixme/test_meta.res
- tests/sav/test_meta.res
- tests/test_meta.nit
Cleaning from old branches: a small useless meta-level.
The lib define meta-objects as some kind of multiton so you have a specific object to represent each class in the runtime-system (in fact each types because of genericity).
You can even define complex meta-deep hierarchy of meta-classes (with meta-loops).
The only issue is that these meta-objects are empty so basically useless (and meta-useless).
> lib: add `meta` as a user-level empty shell for meta-classes

- contrib/header_keeper/Makefile
- contrib/header_keeper/src/header_keeper.nit
This is needed by @Tagachi for the Objective-C wrapper.
Once again, everything is in the doc:
This tool is used in the process of parsing header files to extract
information on the declared services (the functions and structures).
This information is then used to generate bindings for Nit code
to access these services.
The C preprocessor extends macros, inline files marked with `#include`,
and more. This tool acts after the C preprocessor, in a way to keep
everything but the included files. It searches for line pragmas
to identify the source of each line. The result is printed to stdout.
Typical usage on the output of `gcc -E` (it would be the same with `clang`):
~~~
gcc -E /usr/include/SDL/SDL_image.h | header_keeper SDL_image.h > preprocessed_header.h
~~~
This module can also be used as …
> contrib/header_keeper: a cog in the toolchains to generate FFI wrapper for C-like languages

- src/compiler/separate_compiler.nit
Instead of doing the full matrix mtypes X cast_types, a grouping is done by the base classes of the types so that we compare only types whose base classes are in inheritance.
For nitc/nitc/nitc the result is not that bad:
before:
0m6.584s
17.605 GIr
time passed in poset_from_mtypes: 26.01% (4.579 GIr)
now:
0m5.880s (-10%)
15.088 GIr (-14%)
time passed in poset_from_mtypes: 11.72% (1.768 GIr)
In the best condition, I can now expect to compile in less than 6s.
Note that coloring is still a MAJOR issue in term of compile time since 1/4 of the Ir are used to compute coloration.
* type_coloring: 17.23%
* property_coloring: 9.35%
> compiler: improve `poset_from_mtypes` used for type coloring.

- src/astbuilder.nit
- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/model/model.nit
- src/rapid_type_analysis.nit
- src/transform.nit
- src/vm.nit
Add direct methods to access primitive types
Simplify and improve the generation of primitive values in the compiler.
More (and improved) `*_instance` methods are now available in AbstractCompilerVisitor.
One of the point is the simplification of the generated C so that less local variables are generated, maybe this will also help the C compiler to work faster.
> Simplify management of primitive types

- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
Thus remove all comparaison to "val*" in the code, this is cleaner.
> compiler: introduce and use `MType::is_c_primitive`

- lib/standard/exec.nit
- lib/standard/file.nit
Flushing for each small element of an output made things too slow.
real (not user) time for nitc/nitc/nitc:
before: 0m7.373s
after: 0m5.901s (-20%)
> lib/std/file: do not flush on each write

- benchmarks/bench_engines.sh
Last week benches shows some failures on some options due to recent commits.
This PR add a `--fast --fast` option that test only `hello_world` so it could be used in continuous integration to test the various meaningful combination of compiling options.
Moreover, the script is simplified to be more simple to use and extends with new options or combination of options,
> Fast benches

- lib/standard/string.nit
- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/rapid_type_analysis.nit
- tests/sav/nitg-e/error_needed_method_alt4.res
Superstrings, like "a{b}c", are managed in the AST as a special group of sub-expression nodes that are either literal string parts or standard expressions.
The previous example is basically `["a", b, "c"]`
Previously, the compilation of super-strings was direct: the values are grouped in an array and `to_s` is called on it.
So in fact `"a{b}c"` was compiled as `["a", b, "c"].to_s`.
This basic implementation is simple and correct. But it has some drawbacks:
* a new Array[Object] (and a NativeArray[Object]) is allocated each time the super-string is evaluated.
* all elements are to_s-ized in `Array::to_s`, even the literal parts.
* an additional NativeArray[String] is allocated in `Array:to_s` to do the fast concatenation.
Because of the numerous allocations, superstrings caused a lot of …
> Fast super strings

- lib/ios/app.nit
- lib/ios/examples/hello_ios.nit
- lib/ios/ios.nit
- lib/ios/platform.nit
- src/compiler/abstract_compiler.nit
- src/compiler/compiler.nit
- src/platform/android.nit
- src/platform/emscripten.nit
- src/platform/ios.nit
- src/platform/pnacl.nit
- src/platform/xcode_templates.nit
- tests/Linux.skip
- tests/test_platform_ios.nit
Adds a target platform in the compiler which generates an XCode project for iOS applications.
Intro the `ios` projet to group services for iOS. It implements the callbacks expected by the iOS system for a basic graphical application. It also triggers compilation for the iOS platform.
Adds one example of a graphical application `hello_ios` and a very minimal test for the iOS platform.
This is still very much a work in progress, you will notice many TODO in the code. Here are some of the next features to implement:
* Extend support to all iOS devices, not only the iPhone in the simulator.
* Reorganize annotations for app.nit: app_name, package_name, and maybe organization_name.
* Add more services of the Cocoa touch library and rewrite the `hello_ios` app in Nit.
* Support assets and other …
> iOS support

- src/compiler/abstract_compiler.nit
- src/compiler/coloring.nit
- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
- src/model/model.nit
- src/modelize/modelize_property.nit
This introduce a new colorer, `POSetGroupColorer` that colors elements introduced by the classes in a class-hierarchy.
The advantage of this new colorer is that it uses conflict graphs of classes to colorize elements.
By comparison, the previously used colorers work with conflict graphs of elements; that are therefore much larger.
An other advantage is that only the introductions of elements are needed by the colorer, so filling the information from the model is far more easier.
The construction of the poset of types is also removed.
Instead, subtyping tables are computed with a more standard way:
* target cast types are grouped by classes: a map class->types is created
* the map is colored: a table layout by class is computed
* for each live type, the table layout of the associated class …
> Rewrite the coloration for properties and types.

- lib/standard/collection/union_find.nit
Just because I need it.
I'm still not sure about what is the best way to deal with the various copy-constructors and clone methods. I think the following make sense:
A copy constructor named `from` that takes, if possible a general classifier (like an interface). This named constructor may use `nosuper` to avoid the automatic invocation of the standard init method if this cause a useless complex initialization that will be throw away by the copy.
A direct copy `clone` than can just return `new SELFTYPE.from(self)`
The advantage is that for simple clone, the `clone` method do the job.
If one want to change the class but keep the data, then the `from` constructor can be used. Like `new HashSet.from([1,2,3])`
> lib/std/union_find: make DisjointSet Cloneable

- src/loader.nit
- src/test_phase.nit
This PR improves the loader that can now accepts
* directories of projects: to load all modules of all projects (eg `contrib`)
* root directories of groups: to load all modules of the groups (eg `contrib/benitlux`).
Previously, this worked if there was no `src` subdirectory)
This works for tools that rely on full_parse (basically all tools except the engines).
~~~sh
$ ./test_test_phase ../lib -q
It works
I have 89 projects
I have 285 modules
I have 1038 classes
For 1366 definitions of classes
I have 7101 methods
For 9098 definitions of methods
~~~
Note that if any files has an error most tools will just stop.
> Improve loader

- lib/standard/string.nit
- src/compiler/abstract_compiler.nit
- src/interpreter/naive_interpreter.nit
Adds a service for quick cstring in `FlatTexts`, this is mainly to speedup some methods like `write_native`, which takes a cstring in input.
This just creates a new pointer to the same `char*` with an offset.
Since no copy is ever made, its use is highly discouraged in extern code or in cases other than ephemereal uses of the resulting `NativeString`.
Since it adds a new intern service, it cannot be used as is in the standard library as it will need a regeneration of c_src beforehand.
> lib/standard/string: Added faster to_cstring method on FlatText.

- tests/sav/hello_ios.res
- tests/sav/test_platform_ios.res
- tests/testosx.sh
- tests/tests.sh
The results of the compilation of iOS apps by XCode are directories. This PR fix tests.sh to detect those directory and report them cleanly.
Also intro a script for running OS X specific tests.
> Test compilation of OS X and iOS programs, on OS X

- benchmarks/markdown/bench_markdown.sh
- benchmarks/markdown/engines/nitmd/Makefile
Add a second nitmd engine compiled with --semi-global.
One can see that it helps to win against some java impl.
> Bench markdown --semi-global

- examples/calculator/src/calculator_android.nit
- examples/mnit_dino/src/dino_android.nit
- examples/mnit_simple/src/complete_simple_android.nit
- lib/android/README.md
- lib/android/aware.nit
- lib/android/examples/src/ui_test.nit
- lib/app/app_base.nit
- lib/ios/examples/hello_ios.nit
- src/compiler/abstract_compiler.nit
- src/model/mmodule.nit
- src/platform/android.nit
- src/platform/android_annotations.nit
- src/platform/app_annotations.nit
- src/platform/ios.nit
- src/platform/xcode_templates.nit
* Rename the annotation `java_package` to `app_namespace`.
* Move up `app_name`, `app_version` and `app_namespace` and their default values from the Android platform.
* Apply these annotations in iOS too.
* Use the annotations in Hello iOS.
> Unite app.nit metadata annotations common to Android and iOS

- src/parser/.gitignore
- src/parser/Makefile
- src/parser/README.md
- src/parser/org/nitlanguage/gen/TestParser.java
So one can more easily play and compare parsers.
Sometime, when I have issues with the parser, it helps to understand if it is nit-related, sablecc-related or grammar-relater.
> parser: add a basic sabblecc3 parser in Java

- src/ffi/extern_classes.nit
- src/frontend/check_annotation.nit
- src/frontend/div_by_zero.nit
- src/frontend/no_warning.nit
- src/frontend/serialization_phase.nit
- src/loader.nit
- src/model/model.nit
- src/modelbuilder.nit
- src/modelbuilder_base.nit
- src/modelize/modelize_class.nit
- src/modelize/modelize_property.nit
- src/phase.nit
- src/semantize/auto_super_init.nit
- src/semantize/typing.nit
- src/toolcontext.nit
- tests/sav/error_needed_method_alt4.res
- tests/sav/error_needed_method_alt7.res
Detection and resolution of crashes or irrelevant error messages with tools that keeps going (eg. nitpick).
Historically, the compiler just exited at the end on a step when an error occured. The ToolContext#keep_going flag disable this automatic exit and was introduced for tool that are expected to be launched on broken code: nitpick and nitlight. However most parts of the code expected that:
* the previous steps where completed successfully, and expected information where available and correct.
* they are that special important snowflake can just exit the whole program when they are unhappy.
These rules can make sense for a compiler but are to strict for most SE tools that need to work (or continue working) when some random module contain an error.
Thus this PR improve the robustness of …
> Robust keep-going

- src/modelize/modelize_property.nit
- tests/error_virtual_type.nit
- tests/error_virtual_type2.nit
- tests/sav/base_virtual_type7.res
- tests/sav/error_virtual_type2.res
- tests/sav/error_virtual_type2_alt1.res
- tests/sav/error_virtual_type2_alt2.res
- tests/sav/error_virtual_type2_alt3.res
- tests/sav/error_virtual_type2_alt4.res
- tests/sav/error_virtual_type2_alt5.res
- tests/sav/error_virtual_type2_alt6.res
- tests/sav/error_virtual_type_alt1.res
- tests/sav/error_virtual_type_alt2.res
- tests/sav/error_virtual_type_alt3.res
- tests/sav/error_virtual_type_alt4.res
- tests/sav/error_virtual_type_alt5.res
This PR does 2 things to avoid runtime errors during nitc. Invalid programs that crashed the compiler now display errors messages.
* improve the static detection of loops in virtual types.
* consider types in the signatures of properties to be fragile since they contains potentially bad virtual types.
If merged with #1241 then nitpick can process the whole tests directory without crashing (impressive, since there is 1584 border-case files).
~~~
$ ./nitpick ../tests/*.nit ../tests/alt/*.nit -I ../lib/standard/ -I ../lib/standard/collection/
[... lots of errors ...]
Errors: 1766. Warnings: 195.
~~~
> Improve checking of virtual types

- src/platform/ios.nit
- src/platform/xcode_templates.nit
I originally incorporated the test project in the generated XCode workspace thinking that we could use it somehow. But it duplicates services from nitunits and it would be much more complex to use.
I remove the test project now because it is incomplete and raise errors from the XCode GUI.
> Make the generated iOS project compilable in the XCode GUI

- misc/README.md
- misc/vim/plugin/nit.vim
You can now use Nitdoc as a command in Vim.
* Search the doc for the word under the cursor with `:Nitdoc` 
* Display the doc of the `String` class (followed by all docs using the word "String", case-insensitive) with `:Nitdoc String`
* Display the doc of `Int::%` with `:Nitdoc modulo`
* Search for a string of words (in the given order) with `:Nitdoc not null`
Some query can produce quite a lot results. `:Nitdoc the` will fill the preview window with 33 379 lines of doc, but there no noticeable delay.
Navigate in the doc by moving the cursor above a word in the preview window and using ctrl-D (or `:Nitdoc`), exactly as you would do in Nit code.
> Vim plugin fixes and make Nitdoc a command with search capabilities

- tests/tests.sh
Advantages:
* avoid manual error-prone update (especially on large tests)
* diffs on the sav/ files may be easier to see with git tools
Drawbacks:
* the wrong sav dir can by used for specific engines/uname/etc.
* manual inspection still required
Is used for #1253 because manual updates are a PITA
> tests: add --autosav to automatically update the sav directory.

- contrib/header_keeper/Makefile
- contrib/inkscape_tools/Makefile
- contrib/nitcc/src/Makefile
- contrib/nitiwiki/Makefile
- contrib/pep8analysis/Makefile
- misc/jenkins/check_contrib.sh
Add a script `misc/jenkins/check_contrib.sh` to automatically compile and tests things in contrib and examples.
New (and existing) programs in these directory should try to add some basic (or extensive) checking.
Note that I used the name `check` that is the standard name for Makefiles (`tests` seems to be an invention of myself) http://www.gnu.org/software/make/manual/make.html#Standard-Targets
> Check contrib

- src/modelize/modelize_property.nit
- tests/error_operators.nit
- tests/sav/error_operators.res
- tests/sav/test_ffi_c_operators.res
- tests/test_ffi_c_operators.nit
Previously, no checking was done on the signature of operators.
While this is not an issue for the model nor the tools this could yield to not POLA error messages when the operator is used. eg.
~~~nit
class A
fun +(other: A) do print "hello"
end
var a = new A
var b = a + a # Error expected expression
a + a # Error unexpected operator +
~~~
With the PR, we have
~~~
Error: mandatory return type for `+`.
fun +(other: A) do print "hello"
^
~~~
The following errors are added by the PR:
* mandatory return
* not enough parameters
* too much parameters
* illegal variadic parameter
> Check operator

- lib/standard/string_search.nit
- src/metrics/detect_covariance.nit
- src/rapid_type_analysis.nit
- src/semantize/typing.nit
- src/transform.nit
- tests/base_autocast_array.nit
- tests/sav/base_autocast_array.res
- tests/sav/base_autocast_array_alt1.res
- tests/sav/base_autocast_array_alt2.res
- tests/sav/base_autocast_array_alt3.res
- tests/sav/nitg-e/base_autocast_array_alt2.res
Small bugfixes
* forbid autocasts in combined assignments and literal arrays
* keep autocast information in transform
* rta visits implicit methods of literal arrays
Only the first one was the original bug I wanted to fix, the two others where discovered and solved while writing the PR.
> Autocast and literal arrays

- lib/standard/string.nit
- src/phase.nit
Default name of phases where based on a lower cased version of their classnames.
That was bad. eg `FFILanguageAssignationPhase` -> `ffilanguageassignation`
So this PR snakecase them instead.
But the spec of `to_snake_case` was awful: `f_f_i_language_assignation`
So also fix the spec of this method and get something nice `ffi_language_assignation`.
> Snake phase names

- lib/mnit/opengles1.nit
- lib/mnit_android/android_assets.nit
- lib/mnit_linux/linux_opengles1.nit
The new OpenGL parameters affect the display of images for a better pixelated look:
* When zoomed out, the image is smoother, the color values are interpolated from the nearest source pixels.
* When zoomed in, the image is displayed pixelated.
You may recognize the `Int::next_pow` method, `inkscape_tools` use something similar for the same purpose. Actually, with this PR, `inkscape_tools` may not need it anymore and produce smaller PNG files.
> Small clean up and improvements to MNit from WBTW

- src/semantize/typing.nit
- tests/sav/base_vararg3_alt1.res
- tests/sav/base_vararg3_alt3.res
Improve the error message so that user that try to pass an array as is instead of elements is hinted about the `...` reverse-vararg operator.
~~~
fun foo(xs: Int...) do end
foo(1,2,3) # OK
var a = [1,2,3]
foo(a) # Error, expected `Int`; got `Array[Int]`. Is `...` missing?
foo(a...) # OK
~~~
close #98 (quite old bug)
> Hint vararg

- src/doc/doc_phases/doc_html.nit
- src/doc/html_templates/html_model.nit
- src/doc/html_templates/html_templates.nit
Only internal modification, no diff with the generated HTML of the previous version.
If you don't trust me (I you shouldn't), the demos will be [there](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/index.html) and [there](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/nitc/index.html) in a few minutes.
> Brace yourself, next PR on that subject will be big.
> nitdoc: prepare the migration of nitdoc component to new phases

- lib/pthreads/README.md
- lib/pthreads/examples/threaded_example.nit
- lib/pthreads/pthreads.nit
- src/frontend/parallelization_phase.nit
- tests/sav/threaded_example.res
Adds the support of methods with return value
If you use `is threaded` on a method with a return, it will instead return you a custom instance of `Thread` class on which you can use the method `join` to retrieve the return of the annotated method. `join` waits for the method to end before returning.If you want to make sure that the method has done his work before trying to retrieve it's return value, you can check it with the boolean `is_done`
> Parallelization phase improvement

- examples/langannot.nit
- examples/languages/en/LC_MESSAGES/langannot.po
- examples/languages/fr/LC_MESSAGES/langannot.po
- examples/languages/ja/LC_MESSAGES/langannot.po
- examples/languages/langannot.pot
- lib/gettext.nit
- src/frontend/frontend.nit
- src/frontend/i18n_phase.nit
- tests/exec.skip
So here's the POC of a new annotation for the compiler: i18n !
Right now, you can append it to a module declaration with the locale of your choice.
It then generates a .pot template file and a .po file for the language you chose when defining your module.
The generation of the corresponding .mo (using msgfmt) file is still of the responsability of the user.
There's still several modifications to do for real usability, namely the support of superstrings, the possibility to untranslate a literal string via some kind of notranslate annotation (though if no translation is found, the key is kept as argument, so this should not be an issue).
So now, when using another value for the $LANGUAGE environment value, a different message will be printed when executing a Nit program, have fun !
NOTE: I …
> i18n annotation

- src/nitpretty.nit
- src/pretty.nit
Some bugfixes, improvements and workaround for nitprettty.
The two options `--no-inline` and `--line-width` allow to control some rules about line-breaks.
This can be useful especially for people that want more relaxed rules.
~~~sh
$ ./nitpretty --check ../lib | wc -l
224
$ ./nitpretty --check ../lib --line-width 0 --no-inline | wc -l
188
~~~
So 36 more files are identical to their pretty printing with those relaxed rules.
For information, the tool crashed on some files in lib with the version before the PR.
Note that a lot of more work is still needed, one can see very strange and inconsistent results if the line width is forced to 1.
> Prettier pretty printing

- lib/standard/stream.nit
- tests/sav/test_bufferedfilereader.res
- tests/test_bufferedfilereader.nit
Since 39fcf4a75aaec646f0b60d404dfcc5cb63dcb473 and because people prefer the Python/Ruby semantic to the C semantic, eof is blocking.
This PR rewrite `BufferedReader.read` to follow the Python/Ruby semantic: if there is 1 character in the system buffer, and that the programmer asks for 2, the program will wait to have 1 more character, that can block the whole program if we are waiting the missing character from some keyboard, pipe or tcp connection.
Here a comparaison of the various specifications:
The protocol is the following: I `read(4)` bytes from stdin and print them. On stdin, I write `ab\n` (3 bytes) then `cd\n` (3 other bytes) and see when the the read does Its job.
In the following, I only give the outputs since the input will be the same and adding it will require to …
> Filereader fix

- src/doc/doc_phases/doc_graphs.nit
- src/doc/doc_phases/doc_html.nit
- src/doc/html_templates/html_components.nit
- src/doc/html_templates/html_model.nit
- src/doc/html_templates/html_templates.nit
This PR starts the migration of HTML rendering from old components to new DocComposite rendering.
Some minor differences can be seen in the output.
Démos: [stdli](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/index.html) and [nitc](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/nitc/index.html).
> nitdoc: start using DocComponent rendering

- examples/calculator/Makefile
- examples/calculator/src/calculator_gtk.nit
- lib/gtk/v3_4/gdk_enums.nit
- lib/gtk/v3_4/gtk_assistant.nit
- lib/gtk/v3_4/gtk_core.nit
- lib/gtk/v3_4/gtk_dialogs.nit
- lib/gtk/v3_4/gtk_widgets_ext.nit
- lib/gtk/v3_4/v3_4.nit
- lib/gtk/v3_6.nit
- lib/gtk/v3_8.nit
- tests/test_gtk.nit
You should read this PR commit by commit as the style update touches almost every line. The style update adds and removes spaces, and it removes empty and commented methods. It does not touch the documentation, there is still a lot of work to do there.
Please read the commit description of "lib/gtk: ignore deprecated warnings" for the rationale of the change.
GTK will be used to implement the abstract UI on GNU/Linux.
> GTK clean up and a few new features

- examples/langannot.nit
- examples/languages/en/LC_MESSAGES/langannot.po
- examples/languages/fr/LC_MESSAGES/langannot.po
- examples/languages/ja/LC_MESSAGES/langannot.po
- examples/languages/langannot.pot
- lib/standard/string.nit
- src/frontend/i18n_phase.nit
Added the support of superstrings in the i18n annotation.
The first commit introduces a string format to use when replacing superstrings.
The second and third commits are updates to the i18n annotation and the test that goes along with it.
> i18n annot: superstrings

- misc/vim/syntax/nit.vim
so `"C"` is now contextually highlighted.
Note: `\ze` means the end mark. What follows is looked for to be matched but is not considered in the token (some kind of lookahead)
> vim: look for `{ in deciding to highlight ffi language name. eg "C".

- examples/mnit_simple/src/test_intent.nit
- lib/android/android.nit
- lib/android/data_store.nit
- lib/android/intent/intent_api10.nit
- lib/android/shared_preferences/shared_preferences_api10.nit
- lib/android/toast.nit
- lib/android/ui/native_ui.nit
- lib/android/ui/ui.nit
- lib/android/vibration.nit
- lib/linux/data_store.nit
- lib/linux/linux.nit
The prefix in `linux_data_store` and `android_data_store` is no longer needed.
Importing only `dalvik` from an Android module makes it compatible with both implementations: the newer nit_activity and the older native_app_glue still used by games.
> Clean up Android and Linux app.nit libraries

- src/c_tools.nit
- src/ffi/java.nit
The generated C code used `static JNIEXPORT`, when the macro was expanded it duplicated the visibility attribute. It was reported by the C compiler as a warning. This PR removes the `static` part.
> Fix C compiler warning on Java FFI and Android apps

- share/nitdoc/css/nitdoc.css
- src/doc/doc_phases/doc_graphs.nit
- src/doc/doc_phases/doc_hierarchies.nit
- src/doc/doc_phases/doc_intros_redefs.nit
- src/doc/doc_phases/doc_structure.nit
- src/doc/html_templates/html_components.nit
- src/doc/html_templates/html_templates.nit
This PR introduce discrete tabs in the Nitdoc HTML output to hidde less important data like linearization tree, subclasses list etc.
This makes the main page more clean and readable.
Just pass the mouse over a definition to make the tab menu appear and select the details you want to see.
I also moved the source link here.
One can see the difference on [`Array[E]::SELF`](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/class_standard__collection__array__Array.html#article:standard__collection__array__Array__SELF.definition). Notice the little burger menu on the right of the signature.
Démos:
* [stdlib](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/index.html)
* [nitc](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/nitc/index.html)
> nitdoc: introduce tabbed view to hidde less important data

- lib/buffered_ropes.nit
- lib/standard/ropes.nit
- lib/standard/string.nit
Added copy_to_native method in Text, also its optimized versions for subclasses
As a bonus (and because it simplified my task here), substrings now return FlatTexts only instead of simple Text.
The latter will permit the implementation of StringReader as BufferedReader later in an optimized way
> Copy to native

- lib/standard/string.nit
Since the code block was badly indented, it was not tested by `nitunit`.
Once the indentation was corrected, `nitunit` found that the test was failing.
> Fix nitunit for `String::format`

- contrib/friendz/src/friendz.nit
- contrib/friendz/src/friendz_android.nit
- contrib/inkscape_tools/tests/app/src/s2pn.nit
- examples/mnit_ballz/src/ballz_android.nit
- examples/mnit_dino/src/dino.nit
- examples/mnit_moles/src/moles.nit
- examples/mnit_simple/src/simple.nit
- examples/mnit_simple/src/test_audio.nit
- examples/mnit_simple/src/test_data_store.nit
- examples/shoot/src/shoot.nit
- lib/android/android.nit
- lib/android/assets_and_resources.nit
- lib/android/audio.nit
- lib/android/nit_activity.nit
- lib/app/app_base.nit
- lib/mnit/mnit_null.nit
- lib/mnit_linux/linux_app.nit
The names of callbacks on the life cycle have been inspired by Android's. There is an equivalent to each of them in iOS, their naming is more precise but more complicated, so they looked less nity.
As of now, only `App` specialize `AppComponent`, but more users in the UI module will soon be introduced.
The implementation of this life cycle in mnit and the old Android implementation using the NDK is a bit awkward. But you will notice that it is much better in the newer NitActivity based implementation, which is the future!
> Intro AppComponent to notify all elements of an app of its life cycle

- src/compiler/separate_erasure_compiler.nit
In commit [12aa160](https://github.com/privat/nit/commit/12aa16093122a9f55976585b76b01869d6899634) by @xymus, the signature of a BOX was updated to the ctype_extern, i.e. void\* for all pointers.
The callsite was modified to ctype_extern in separate compiler but was not updated in separate erasure compiler.
This caused a bug in #1309 when NativeString was introduced in BufferedStream as the buffer, since the callsite and signature were defined with different signatures, the prototype with void\*, the implementation with char\*.
This PR fixes the bug by setting both to void\* as in separate compiler.
> Separate Erasure Compiler bugfix

- src/doc/doc_phases/doc_structure.nit
- src/doc/html_templates/html_model.nit
- src/doc/html_templates/html_templates.nit
Nitdoc now displays a list of available constructors for a class.
Fixes #875
Fixes #1195
Demos from [Jenkins::CI-nitdoc](http://gresil.org/jenkins/job/CI-nitdoc):
* [Standard library](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/index.html)
* [Nit compilers and tools](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/nitc/index.html)
> nitdoc: display constructors list in MClass page

- lib/bucketed_game.nit
- lib/json_serialization.nit
- lib/serialization/serialization.nit
- lib/standard/kernel.nit
- src/frontend/serialization_phase.nit
- tests/sav/nitg-e/test_serialization.res
- tests/sav/nitg-e/test_serialization_redef.res
- tests/sav/nitg-e/test_serialization_redef_alt0.res
- tests/sav/nitg-e/test_serialization_redef_alt1.res
- tests/sav/nitg-e/test_serialization_redef_alt2.res
- tests/sav/nitserial_args1.res
- tests/sav/test_deserialization_serial.res
- tests/sav/test_serialization.res
- tests/sav/test_serialization_redef.res
- tests/sav/test_serialization_redef_alt0.res
- tests/sav/test_serialization_redef_alt1.res
- tests/sav/test_serialization_redef_alt2.res
- tests/test_deserialization.nit
- tests/test_deserialization_serial.nit
This PR is the result of using Nit serialization to implement game saving/loading in WBTW.
Update the serialization to work with (or avoid) the new auto constructors.
Support serializing Sets and Maps.
The `is_same_serialized` fix a problem where two instances were wrongly serialized as being the same. Because it previously used a `HashMap` (and thus `==`), two different _empty_ arrays were serialized as one and resulted in a single object on deserialization.
Once this and #1348 are merge, I'll update the calculator example to use the serialization.
> Serialization support SimpleCollection and Map, also bug fixes

- lib/counter.nit
- lib/dummy_array.nit
- lib/neo4j/graph/graph.nit
- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/array.nit
- lib/standard/collection/hash_collection.nit
- lib/standard/collection/range.nit
- lib/standard/collection/union_find.nit
- lib/trees/bintree.nit
- src/doc/doc_phases/doc_indexing.nit
- tests/sav/test_coll_eq.res
- tests/test_coll_eq.nit
A proposition to solve an old API issue related to covariance in collections (and fix #1353)
This PR updates the signatures of access methods in collections: `has`, `[]` and anything related that takes an `E` or a `K` in read-collections.
This make these classes covariant-safe.
Previously, the signature was to strictly accepts the bound, thus making the code unsafe but has the advantage to provide static hints
~~~nit
assert [1,2,3].has("Hello") # static error, expected int got string
~~~
But this behavior had issues because:
* unsafe code, but it is not because Nit *can* be unsafe that Nit *should* be unsafe.
* a perfect semantic answer is possible, eq returning false in the previous example. thus the existing behavior is not POLA
Because the philosophy of Nit is that static types should …
> Safe collection access

- examples/rosettacode/loops_downward_for.nit
- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/range.nit
A proposal to solve some things identified in #1339
This PR does 3 things:
* extends any Iterator to locally (`next_by`) or globally (`to_step`) advance with more than a single `next`
* add `Range.step` to have a generic bidirectional and stepable iterator
So now people can write
~~~nit
for i in [1..10].step(2) do print i # in order 1 3 5 7 9
for i in [10..1].step(-2) do print i # in reverse order 10 8 6 5 2
~~~
This is a neat (over?-) engineering. A maybe non-POLA thing is that empty ranges can still be iterated with a negative step.
~~~nit
assert [5..1].is_empty # but
assert [5..1].step(-2).to_a == [5,3,1]
~~~
> Steps on iterations and ranges

- share/libgc/android-setup-libgc.sh
This is only for tests servers, and should not be of any use to the regular user who doesn't trash and reclone the Nit repo many times each day.
So on Pratchett, @privat , you could download both source packages in the home directory
and the script will use and reuse them instead of repeatedly downloading them. I can change the directory to whatever you prefer, maybe ~/Downloads? or ~/.cache?
It will save us from some false CI test failure, like in http://gresil.org/jenkins/job/CI_github/2648/, and we will stop spamming the server.
> share/libgc: option to use a local version of the source pkgs

- src/model/model.nit
An old branch that was on some disk that I forgot to PR.
While the bottom type is useless now, it should be useful on future PR.
Type theorists and lattice fanboys might like it.
> model: introduce the bottom type

- src/metrics/nullables_metrics.nit
- tests/sav/nitmetrics_args1.res
In reaction of recent updates on #394 I wanted to have some up-to-date numbers.
`nitmetrics --nullable` can count the sends on nullable receivers but safe and unsafe calls where merged. Note: safe calls on nullable are things like `x == null`, that is safe even if `x` is a nullable thing.
So this PR distinguishes safe and unsafe calls.
Some numbers:
~~~
nitmetrics --nullables ../lib ../src/nit*.nit
Total number of sends: 60262
Number of sends on a unsafe nullable receiver: 1750 (2.90%)
Number of sends on a safe nullable receiver: 2639 (4.37%)
~~~
> metrics: `--nullables` distinguishes safe and unsafe calls on `null`

- contrib/online_ide/sources/nit/pnacl_nit.nit
- lib/bitmap/bitmap.nit
- lib/pnacl.nit
- lib/socket/socket.nit
- lib/socket/socket_c.nit
- lib/standard/file.nit
- lib/standard/stream.nit
- lib/websocket/websocket.nit
A bit of a fix in the context of issues #1267 and #1262.
The bytes module has a `ByteBuffer` class, while it is still working with `Int` at the moment, when Nit correctly supports `Bytes`, we can change it to a real `ByteBuffer`
This class is highly recommended when working with byte streams and collections.
As such, file operations are related to this module since most of the operations are working on bytes, what they mean is up to the end-user to figure.
> File and Bytes

- examples/calculator/src/calculator.nit
- examples/calculator/src/calculator_logic.nit
- lib/a_star.nit
- lib/more_collections.nit
- lib/serialization/serialization.nit
- tests/sav/nitserial_args1.res
Use `auto_serialize` in the calculator example, and remove the old custom JSON serialization.
The `a_star` module needed special care and could not rely only on `auto_serialize`. This was to avoid serializing graphs as a deep tree, instead we serialize the nodes first, then the links and we rebuild the graph at deserialization.
Besides that, more collections support the serialization.
> Apply serialization in calculator, a_star, more_collections, Couple and Container

- lib/more_collections.nit
- lib/standard/collection/list.nit
- tests/test_unrolled_list.nit
An unrolled list is a sequence implemented by a linked list of arrays.
I use this list for a very long FIFO. `Array::shift` is very slow and a large `List` can create too many small nodes for the GC.
The test compares the behavior of `UnrolledList` with `List` on random data sets. It allowed me to find a bug in `List::insert`.
> Intro an unrolled linked list, and fix `List::insert`

- lib/standard/collection/range.nit
I tried to use `Int::times` but the nitunit wasn't clear enough on the expected behavior.
Thanks at @BlackMinou for is moral support on this.
> `Int::times`: clean nitunit and expose negative behavior

- lib/json/serialization.nit
- lib/serialization/caching.nit
- lib/serialization/engine_tools.nit
- lib/serialization/serialization.nit
- tests/sav/nitserial_args1.res
Duplex caching allows a client and server to keep copies of the "same" instances (same as in `is_same_serialized`) and only refer to it with an integer. This allows for lighter communication over network. I'm working on an example using `DuplexCache` with the binary serializer that I will soon PR.
Modifications to the `StrictHashMap` allow for much faster read access.
> Serialization caching and prepare for other engines

- lib/markdown/markdown.nit
- lib/markdown/test_markdown.nit
- lib/markdown/wikilinks.nit
Introduce location in markdown parser so tools can easily retrieve the original position of a block or a token in the input file/string.
Commits:
* 2d139eb introduces de Location concept and update the parser
* fda150d isn't interesting since it only update signature in the test file
* dacc7ba adds some test suites for the locations
> Markdown location

- src/vm/virtual_machine.nit
- src/vm/vm_optimizations.nit
This PR fixes a bug that was hidden in the nitvm for a too long time, the recursion in class loading was bad and is now corrected.
Then a more accurate mechanism is introduce to deal with positions of methods and attributes in internal structures of classes and objects.
When a method dispatch is performed, this mechanism allows to ask precisely for a class the position of a block of methods (or attributes). This should increase the proportion of object mechanisms "compiled" in an efficient way.
Finally, the class loading is optimized: an indirectly loaded class is not fully constructed and allocated.
Instead, its identifier is computed to allow subtyping tests.
For now, these more accurate mechanisms need recompilations of callsite. This sould be done in further PR.
> Improve internal mechanisms of the nitvm

- contrib/nitcc/examples/minilang.nit
This PR rename the visit function of the ```minilang.nit``` file. The previous name was incoherent with the module purpose.
> Rename the visit function of minilang example.

- contrib/objcwrapper/header_static/makefile
- contrib/objcwrapper/header_static/src/header_static.nit
This tool is used in the process of parsing header files to extract
information on the declared services (the functions and structures).
This information is then used to generate bindings for Nit code
to access these services.
The C header sometimes contains static code. It deletes static code of
headers, but keep their signatures. This tool is an extension of 
header_keeper. It searches the keyword static to identify 
the static code, and ignore the code into their brackets. The result is
printed to sdtout.
~~~sh
cat Pre-Processed/CGGeometry.h | header_static Pre-Processed/CGGeometry.h > Pre-Processed/static_header.h
~~~
This module can also be used as a library. 
The main service is the method `header_static`
> contrib/header_static: a cog in the toolchains to generate Objcwrapper

- lib/standard/file.nit
- lib/standard/string.nit
- src/interpreter/naive_interpreter.nit
- src/rapid_type_analysis.nit
- tests/sav/nitserial_args1.res
In order to have a more POLA `to_s` on collections, it is required that a new method with the old behavior is provided for clients that need it (especially the interpreter that use it for superstrings).
the compiler use `native_to_s` for superstrings but `c_src/nitg` still use `to_s` on array, so a regeneration of the bootstrap is required before changing the behavior of `to_s` on collections.
> introduce plain_to_s

- src/frontend/check_annotation.nit
- src/modelize/modelize_property.nit
- tests/base_init_autoinit2.nit
- tests/sav/base_init_autoinit2_alt2.res
#857 introduced `autoinit` on attributes that has a default value to initialize them latter.
This is a rarely used feature. It is also not POLA because it overloads the name `autoinit` that has a different meaning on methods cf #1308.
Thus in order to polaize the spec, the annotation is renamed `lateinit`. So close #1308.
Note: maybe the annotation will just be removed in a future PR, this one is a last attempt to keep it.
Related to #1322; required by #1311
> Annotation lateinit

- lib/a_star.nit
- lib/android/bundle/bundle.nit
- lib/android/shared_preferences/shared_preferences_api10.nit
- lib/bucketed_game.nit
- lib/json/serialization.nit
- lib/more_collections.nit
- lib/serialization/README.md
- lib/serialization/serialization.nit
- src/frontend/serialization_phase.nit
- src/nitserial.nit
- tests/sav/nitg-e/test_json_deserialization_alt1.res
- tests/sav/nitg-e/test_serialization_alt2.res
- tests/sav/nitg-e/test_serialization_alt3.res
- tests/sav/nitg-e/test_serialization_alt4.res
- tests/sav/nitg-e/test_serialization_alt5.res
- tests/sav/test_json_deserialization.res
- tests/sav/test_json_deserialization_alt1.res
- tests/sav/test_json_deserialization_alt2.res
- tests/sav/test_serialization_alt2.res
- tests/sav/test_serialization_alt3.res
- tests/sav/test_serialization_alt4.res
- tests/sav/test_serialization_alt5.res
- tests/test_deserialization.nit
- tests/test_serialization.nit
The annotation `serialize` replaces `auto_serialize` and it is also more versatile. It can annotate a module so all its class definitions are serializable. It can also annotate an attribute so only this attribute is serialized.
The `noserialize` annotation is for exceptions to `serialize`. The most common case is to mark as non-serializable an attribute such as a password or a data blob.
> Serialization: change annotation to `serialize` and intro `noserialize`

- lib/standard/string.nit
- src/modelize/modelize_property.nit
Without value, attributes in introductions does not have the same semantic that attributes in refinements
In introduction attributes are implicitly `autoinit`, in refinements they are `noautoinit`.
This is not POLA since
* this confuse beginners
* readers have to remember if they are in an intro or a refinement
* aditionnal cognitive fragility in constructors (more cases and rules to take in account)
This PR make `autoinit` the default and ask that attributes declared in refinement are either annotated `noautoinit` or have a default value.
This way, the writer has to think about the implication of adding a new attributes in existing classes, especially to think about their initialization. Thus this could help the programmer to avoid bad error.
For the moment, I just display a warning …
> modelize: ask that attributes in refinements are either noautoninit or have a value

- src/metrics/nullables_metrics.nit
- src/model/model.nit
- src/semantize/typing.nit
- tests/sav/base_adaptive_loop3_alt3.res
- tests/sav/base_var_null_alt12.res
- tests/sav/base_var_null_alt4.res
- tests/sav/base_var_null_alt8.res
- tests/sav/error_expr_not_ok_alt6.res
Followup of #1375 and #394
This introduce an advice on calls on a nullable receiver.
Since the conversion could be complex, I propose a light approach with advices (quiet warnings) instead of hard errors, so that:
1. jenkins can track them
2. nitpick (thus vim) can show them
3. mirgration can be done in an incremental and iterative way
4. issues with a strict call-on-nullable policy can be identified without breaking things
5. @Morriar can bank nitcoins in future PR
If (when?) all call on nullable can be removed, then the advice will become an error.
> Warn call on nullable receiver

- .gitignore
- Makefile
- benchmarks/bench_engines.sh
- contrib/jwrapper/Makefile
- contrib/nitcc/src/Makefile
- contrib/nitiwiki/Makefile
- contrib/online_ide/Makefile
- contrib/pep8analysis/.gitignore
- contrib/refund/Makefile
- share/man/nitc.md
- src/Makefile
- src/compiler/abstract_compiler.nit
- src/compiler/compiler_ffi/light.nit
- src/platform/android.nit
- src/platform/ios.nit
- tests/Makefile
- tests/tests.sh
This PR cause the compilation directory to be removed after compilation.
This auto-removal is disabled if `--compile-dir` or `--no-cc` is used because it is a sane default I think.
Moreover, the compilation directory is renamed by defaut to `nit_compile` because there is no more point to make it hidden since its presence means an active request (`--no-cc`).
The PR is a bit premature since the boostrap will fail since `rmdir` requires the light FFI, so it is planned to be merged after the regen of c_src.
Close #792
> Clean nit compilation directory

- share/nitdoc/css/nitdoc.css
- src/doc/console_templates/console_templates.nit
- src/doc/doc_base.nit
- src/doc/doc_phases/doc_console.nit
- src/doc/doc_phases/doc_graphs.nit
- src/doc/doc_phases/doc_hierarchies.nit
- src/doc/doc_phases/doc_html.nit
- src/doc/doc_phases/doc_indexing.nit
- src/doc/doc_phases/doc_intros_redefs.nit
- src/doc/doc_phases/doc_lin.nit
- src/doc/doc_phases/doc_poset.nit
- src/doc/doc_phases/doc_structure.nit
- src/doc/html_templates/html_model.nit
- src/doc/html_templates/html_templates.nit
Now that nitx and nitdoc are fully merged with the same structure and services, we can start the refactoring to limit the differences between both tools.
Note that the first four commits are from #1401.
Demos from [Jenkins::CI-nitdoc](http://gresil.org/jenkins/job/CI-nitdoc):
* [Standard library](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/index.html)
* [Nit compilers and tools](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/nitc/index.html)
> nitdoc: refactoring and cleaning

- lib/standard/string.nit
As @privat suggested, here's the PR that cleans the abstract Text class of the string block, this will serve as prelude for the integration of #1400
> Removed intern dependencies from abstract to flat strings

- lib/socket/socket.nit
- lib/socket/socket_c.nit
Errors on both finding a host by its name and on connection are reported with all available details as an `Error`.
> Better error handling in Socket

- src/parser/parser_nodes.nit
- src/parser/parser_work.nit
Another step to simplify the clients of AST: loose tokens.
Some tokens, correctly lexed by the lexer, are discarded by the parser because of (thanks to?) sablecc transformations. Mainly comments and new-lines (EOL) are lost but some other tokens might be also discarded (currently, commas and dots are still lost).
Previously, the full sequence of tokens can still be accessed trough `next_token` and `prev_token` but this mean that tools like nitprettty and nitlight have to maintain two cursors, one on the AST and one on this linked list of tokens and try to keep these two cursors synchronized.
This PR names the concept of *loose* tokens that are lexed tokens but absent from the AST, and attach to each (non-loose) token in the AST a list of loose tokens that precede it (`prev_looses`) and …
> Loose Tokens

- share/man/nitc.md
- src/compiler/abstract_compiler.nit
- src/mkcsrc
Most detection of the availability of libunwind and the flags to use is moved at the C compilation time (in the Makefile) instead at the Nit compilation time.
Moreover, if libunwind is not available, then stacktraces are just disabled (instead of aborting).
Another advantage is that the generated C is more portable and can be compiled in a different system.
Thus, this will help cross-compilation and should even enable the bootstrap on libunwind-less system like raspberrypi once c_src is regenerated (cf #1149).
The option `--stacktrace` is also replaced with a simpler `--no-stacktrace` for people that want to disable it completely at C-compile time.
Close #1357 and an item in #864.
> Portable stack-traces

- contrib/opportunity/src/templates/meetup.nit
As requested in #1431, this PR adds the total number of participants in a Meetup, as a number aside from the Total, like:
`Total(nb)`
Closes #1431
> Opportunity: Adds total number of participants to a meetup

- src/loader.nit
- tests/sav/base_import_alt3.res
- tests/sav/error_mod_unk.res
- tests/sav/xymus_net.res
One day, a package manager will simplify the installation and the maintenance of third-party projects, libraries and programs in Nit, so that `import foo` will import the project `foo` if installed.
Noways, `contrib` is used as a placeholder for some independent projects that are not mainly a library (or borderline). However, the nature of the Nit language, especially the refinement of class blurry the difference between libraries and programs and make it conceivable to extends an existing program by refining it (or just reuse its base libraries).
However, `import foo` will not work if foo is in contrib, this issue has two current workarounds:
* the user use `-I` with some relative path location in the Makefile, that is not practical because it should be used on each tools thus broke …
> Love contrib

- src/compiler/abstract_compiler.nit
- src/compiler/separate_compiler.nit
- src/phase.nit
- src/rapid_type_analysis.nit
- src/semantize/typing.nit
- src/transform.nit
- tests/base_adaptive_loop3.nit
- tests/base_adaptive_loop_null.nit
- tests/sav/test_keep_going.res
- tests/test_keep_going.nit
This improve the robustness of tools when given --keep-going.
Tools like nitpick, that have --keep-going by default, are more robust and collect more errors.
Moreover, the compiler can now compile simple programs with instructions that fail during the typing phase (most errors like unknown method or bad type).
These instructions are compiled with a run time error instead so the program is still expected to behave in an reliable way.
~~~nit
print 1
fail now
print 2
~~~
~~~sh
$ nitc kg.nit --keep-going 
kg.nit:2,1--4: Error: method or variable `fail` unknown in `Sys`.
$ ./kg
1
Runtime error: FATAL: bad statement executed. (kg.nit:1)
~~~
One usage would be to force `c_src` to compile things even if it lags behind.
> More keep going

- lib/standard/file.nit
Before this PR `./` was simplified in `/` which was wrong.
> file: fix `simplify_path` behavior for path starting with `.`.

- src/compiler/abstract_compiler.nit
Commit 6b52ea3d5ca77dbcc6edbbf71c1aa9419a019bac  on chars and string changed the ctype of NativeString to `unsigned char*`. This was the cause of C warnings `-Wpointer-sign` because `unsigned char*` is not a subtype of the universally used `char*` that is activated by default on clang.
So the change is reverted and NativeString become again `char*` (note that Byte and Char ctypes are not reverted)
close #1499
> compiler: NativeString is a char* to please C library.

- src/parser/parser.nit
- src/parser/xss/parser.xss
In `parser::Parser::build_reduce_table` an array is allocated with `.with_items` that takes a vararg.
The vararg used is quite large (1116 elements) and this cause that the generated C code takes 30m to compile with clang-3.6 if -O2 is used; it is likely a regression in llvm since the same code takes appreciatively 1s with clang-3.5 (and with gcc).
Unfortunately, clang-3.6 is currently provided by Apple to MacOS X users.
The proposed solution is to allocate the array then use a sequence of `add`. The generated C code is more complex but clang-3.6 can compile it.
Close #1498 (once c_src is regenerated)
> Kill big vararg in parser

- contrib/nitiwiki/src/wiki_base.nit
- contrib/nitiwiki/src/wiki_html.nit
- contrib/nitiwiki/src/wiki_links.nit
- contrib/nitiwiki/tests/res/wiki1_nitiwiki_status.res
- contrib/nitiwiki/tests/res/wiki2_nitiwiki_render.res
- contrib/nitiwiki/tests/res/wiki2_nitiwiki_status.res
- contrib/nitiwiki/tests/res/wiki3_nitiwiki_status.res
- tests/sav/nitiwiki_args1.res
Use relative links in generated documents to avoid hard_coding `root_url`.
Demo: http://nitlanguage.org/beta/
> Nitiwiki: relative links

- lib/buffered_ropes.nit
- lib/standard/text/ropes.nit
As part of the cleaning of the text group, the `RopeString` class was adding a useless extra layer of abstraction to an already sufficiently complex module, it was decided to remove it.
> Remove RopeString

- src/ssa.nit
This small PR fixes two bugs in SSA.
First: A property was unecessary specific in the hierarchy.
Second: Bad initialization of two attributes which cause runtime error in new tests.
> Bug fixes in SSA module

- src/interpreter/dynamic_loading_ffi/dynamic_loading_ffi.nit
This removes a warning during the initial make.
> niti-ffi: NativeString is re-a `char*` since #1502

- lib/markdown/markdown.nit
- src/testing/testing_doc.nit
- tests/nitunit.args
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args8.res
- tests/test_doc3.nit
Documentation that contains only bad code (not tagged) is now reported by nitunit as it should be.
> Nitunit fails bad code

- contrib/opportunity/.gitignore
- contrib/opportunity/Makefile
- contrib/opportunity/src/templates/boilerplate.nit
- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/Makefile
- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/boilerplate.po
- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/meetup.po
- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/meetup_confirmation.po
- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/meetup_creation.po
- contrib/opportunity/src/templates/languages/fr/LC_MESSAGES/welcome.po
- contrib/opportunity/src/templates/meetup.nit
- contrib/opportunity/src/templates/meetup_confirmation.nit
- contrib/opportunity/src/templates/meetup_creation.nit
- contrib/opportunity/src/templates/welcome.nit
- lib/standard/text/abstract_text.nit
- src/frontend/i18n_phase.nit
This PR brings partial i18n support to Opportunity with a french translation. Most strings from the
UI are covered but not the error messages. This PR also fixes a few bugs in the i18n phase.
I still have difficulty with the deployment. Launching my web server use `LANGUAGE=fr sudo bin/xymus_net` works, but not when using `daemonize -E LANGUAGE=fr ...`. @R4PaSs do you have an idea for a solution?
http://xymus.net/opportunity/ temporary serves the French version of the site. I may have to revert tot the English version if I need monit and I can't fix the locale issue.
> Opportunity i18n & traduction française

- lib/geometry/boxes.nit
- lib/geometry/quadtree.nit
There was a big mistake in the boxes API where you would get the bottom of a line when calling for it's top and get the top when you were calling for the bottom xD, so fixed it.
There also was a bug with the usage of the Numerics in the quadtree API.
Also implemented a to_s for quadtree, but not sure if it needs to stay here.
> Geometry fix

- tests/Darwin.skip
- tests/tests.sh
Extends the tests.sh infrastructure to be configurable by os and hostname
* handle `sav/$os`, `sav/$os/fixme`, `sav/$hostname` and `sav/$hostname/fixme` sav directories that can contains specific results `.res` when there is an expected divergence on results per architecture or machine
* specific `$hostname.skip` file to skip tests on a host basis (`$os.skip` files did already exists to filter at the architecture level)
* additional `sav/$foo/cc.skip` and `sav/$foo/exec.skip` where foo can be engines, os or hostname to fine-tune more things
> Personalized tests

- lib/markdown/test_markdown.nit
Added some test in the hope to reproduce #1059 bug. Everything is working as expected.
Closes: #1059 (can't reproduce)
> lib/markdown: add some tests for xml parsing inside a markdown block.

- src/compiler/abstract_compiler.nit
- src/interpreter/dynamic_loading_ffi/dynamic_loading_ffi.nit
- src/interpreter/dynamic_loading_ffi/on_demand_compiler.nit
- src/interpreter/naive_interpreter.nit
- tests/sav/niti/fixme/neo_doxygen_dump_args1.res
- tests/sav/niti/fixme/neo_doxygen_dump_args2.res
- tests/sav/niti/fixme/neo_doxygen_dump_args3.res
- tests/sav/niti/fixme/neo_doxygen_dump_args4.res
- tests/sav/niti/fixme/neo_doxygen_dump_args5.res
- tests/sav/niti/fixme/neo_doxygen_dump_args6.res
- tests/sav/niti/fixme/neo_doxygen_dump_args7.res
- tests/sav/niti/fixme/neo_doxygen_dump_args8.res
- tests/sav/niti/fixme/neo_doxygen_dump_args9.res
- tests/sav/niti/fixme/nitdoc_args4.res
- tests/sav/niti/fixme/nitiwiki_args1.res
- tests/sav/niti/fixme/test_binary.res
- tests/sav/niti/fixme/test_binary_alt1.res
- tests/sav/niti/fixme/test_binary_alt2.res
- tests/sav/niti/fixme/test_binary_alt3.res
- tests/sav/niti/fixme/test_exec.res
- tests/sav/niti/fixme/test_fdstream.res
Previously, the interpreter used a FlatBuffer to implement NativeString and a File to implement NativeFile. This caused issues with applications using (mostly) `is_address_null` which could not be implemented correctly with these implementations.
This PR uses a real NativeString and NativeFile to implement the same class. For NativeFile, it is handled by the FFI so removing the old code is enough. For NativeString, many of its methods are intern so they had to be updated.
> Remove niti hacks on NativeString and NativeFile

- contrib/rss_downloader/src/rss_downloader.nit
- lib/dom/dom.nit
- lib/standard/file.nit
`rss_downloader` now uses the DOM XML parser instead of regex to read RSS files. It is also easier to customize its behavior from the config class.
This PR also adds a few services to the DOM parser and fix a few bugs.
---
This PR is based on #1448 with fixed line endings.
> Use the DOM parser in the RSS Downloader contrib

- contrib/nitiwiki/src/wiki_links.nit
- lib/github/README.md
- lib/github/api.nit
- lib/github/github.nit
- lib/github/github_curl.nit
- lib/markdown/markdown.nit
- lib/markdown/test_markdown.nit
- lib/markdown/test_wikilinks.nit
- lib/markdown/wikilinks.nit
- src/doc/doc_base.nit
- src/doc/doc_commands.nit
- src/doc/doc_down.nit
- src/doc/doc_phases/doc_console.nit
- src/doc/doc_phases/doc_html.nit
- src/doc/doc_phases/doc_pages.nit
- src/doc/doc_phases/doc_readme.nit
- src/doc/html_templates/html_model.nit
- src/doc/html_templates/html_templates.nit
- src/loader.nit
- src/location.nit
- src/nitdoc.nit
- tests/sav/nitdoc_args1.res
- tests/sav/nitdoc_args2.res
- tests/sav/nitdoc_args3.res
- tests/sav/nitdoc_args4.res
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args7.res
This PR introduce the use of wikilinks in README files.
It's mainly a request for comments on what you want, what you need and what you like from Nitdoc and README writting.
0f6ff78 gives an example of README file written using wikilinks. The processed result by nitdoc is visible [here](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/group_github.html).
Supported commands for now:
* `[[doc:MEntity]]`: include the documentation article or an MEntity
* `[[list:MEntity]]`: list classes or methods from than MEntity
Old API pages still available, there are prefixed with `api_`.
Demos from [Jenkins::CI-nitdoc](http://gresil.org/jenkins/job/CI-nitdoc):
* [Standard library](http://gresil.org/jenkins/job/CI-nitdoc/ws/doc/stdlib/index.html)
* [Nit compilers and …
> nitdoc: Use wikilinks on README files

- lib/performance_analysis.nit
This modules provides simple stats (avg, min, max, count) on the execution time of categories. I use this module in my games to detect performance bottlenecks.
If anyone has an idea for a better name, I'm open to suggestions.
> Intro the performance_analysis module to gather perf stats by categories

- lib/standard/bytes.nit
- tests/sav/nitpick_args1.res
The method was missing from Bytes, I needed it so I implemented it, and here's the associated PR.
> lib/standard/bytes: Added pop method

- src/modelize/modelize_property.nit
- tests/base_init_basic.nit
- tests/sav/base_init_basic_alt3.res
- tests/sav/base_init_basic_alt5.res
On
~~~nit
class A
var x: Int
end
class B
var y: Bool
end
class C
super A
super B
end
~~~
The error message
> a.nit:9,7: Error: conflict for inherited inits a#B#init(y=) and a#A#init(x=)
now become
> a.nit:9,7: Error: cannot generate automatic init for class C. Conflict in the order in inherited initializers a#B#init(y=) and a#A#init(x=). Use `autoinit` to order initializers. eg `autoinit x=, y=`
(fell free to simplify or propose better)
Close #1549
> Better autoinit conflict message

- lib/standard/collection/array.nit
- tests/sav/test_new_native_alt1.res
Using `Array::iterator` after a finished `reverse_iterator` iterates only on the first element, or crash if array is empty. As `ReverseArrayIterator` specialize `ArrayIterator`, it can cache itself in the array to be used by `iterator`.
This PR simply disable caching for reverse iterators. We could add a distinct cache for the reverse iterator if we need the performance.
This minimal program highlights the bug:
~~~nit
var a = [1, 2, 3]
for x in a.reverse_iterator do print x
print "-"
for x in a.iterator do print x
~~~
Output:
~~~
3
2
1
-
1
~~~
> Fix bug with reverse iterators in arrays

- src/compiler/separate_compiler.nit
`autobox` (and and its cousin `autobox_extern`) where using RTA information when generating code in order to avoiding to use a C symbol (like a table identifier) that will not be defined in the final compiled program.
The problem is that the approach is incompatible with separate compilation principle where the generated code is independent or the program (thus independent of the liveness of the types of a given program).
The solution is to use symbols in the separate compilation, even for potential (or known) dead classes, and let the global phase define these symbols with invalid information.
> Separate code compilation for autobox

- examples/mnit_dino/src/dino.nit
- examples/mnit_dino/src/game_logic.nit
- examples/mnit_moles/src/moles_android.nit
- lib/curl/native_curl.nit
- lib/pthreads/concurrent_collections.nit
- lib/pthreads/redef_collections.nit
- lib/serialization/serialization.nit
- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/list.nit
- tests/base_label_for.nit
The `Container` class is widely misunderstood and underused.  However it can be very useful to implement a return parameter. This PR rename the class according to this usage. It will make some signatures easier to understand: (example inspired by a similar function from `UDPSocket`)
~~~nit
fun recv_from(buffer: NativeString, sender_info: Ref[nullable SocketAddress]): Int
~~~
`Ref` can also be used as a hackish equivalent to a `static` variable in C. This example use the dreaded `once` keyword to easily get a singleton, but it could be done cleaner with an attribute in `Sys`.
~~~nit
fun foo
...
var counter = once new Ref[Int](0)
counter.item += 1
print "foo has been executed {counter.item} times"
end
~~~
> Rename Container to Ref

- lib/noise.nit
This PR enables using noise maps in multiplayer multiplatform games.
The integers are limited to 30 bits in length to be compatible with 32 bits architectures with 2 bits for tagging. Forcing this limit allows to get the same results from the same seed on a 32 and 64 bits computers.
The random angle generation is better than previously, the repeated checker pattern is no more. However there is still a visible patterns on the main axes. Further work is need to fix it.
> lib/noise: compatibility with 32 bits arch and noisier

- src/modelize/modelize_property.nit
- tests/sav/base_attr3_alt1.res
- tests/sav/base_attr3_alt2.res
- tests/sav/base_attr3_alt3.res
- tests/sav/base_attr3_alt4.res
- tests/sav/error_ref_attr.res
- tests/sav/nitdoc_args2.res
- tests/sav/nitdoc_args4.res
- tests/sav/nitmetrics_args1.res
Setters of attributes are private by default. This cause some issue as they are exposed as initializers but still invisible in client modules.
The proposed solution to resolve this inconsistency is to make setters protected by default so they are visible in client modules but only usable in subclasses.
This is a change is the spec, to RFC label is set is people have comments on the sanity/usability/kiss/pola/etc. 
Close #1552
> Protected setters

- lib/standard/file.nit
- src/interpreter/primitive_types.nit
Allow FlatString to be directly written to files without useless copy (`to_cstring`) or useless iterator (`substrings`)
Numbers, for `nitc nitc.nit`:
* before 5.796
* after 5.440 (-6%)
Close one check-box of #1298
> Faster write

- examples/mnit_dino/src/dino.nit
- examples/mnit_dino/src/game_logic.nit
- examples/mnit_moles/src/moles_android.nit
- lib/curl/native_curl.nit
- lib/pthreads/concurrent_collections.nit
- lib/pthreads/redef_collections.nit
- lib/serialization/serialization.nit
- lib/socket/socket.nit
- lib/socket/socket_c.nit
- lib/standard/collection/abstract_collection.nit
- lib/standard/collection/list.nit
- tests/base_label_for.nit
This PR intro `UDPSocket` and cleans up a bit of the native layer of socket to avoid using callbacks when possible.
`UDPSocket` support sending messages to remote sockets without a connection and more importantly receive message from any sender. However, as of yet it does not support connections or the stream API of Nit.
Some TODO with the sockets:
* Stop using `gethostbyname` :neutral_face: 
* Decide on one or many APIs. The native layer has an API closed to the C API and to what is available in other languages, maybe it can be clean up further and exposed as is.
---
Please ignore the first 2 commits from #1573.
> Basic UDP socket

- contrib/jwrapper/src/code_generator.nit
- contrib/jwrapper/src/model.nit
- contrib/neo_doxygen/src/model/linked_text.nit
- contrib/nitiwiki/src/wiki_base.nit
- contrib/pep8analysis/src/cfg/dot_printer.nit
- examples/rosettacode/balanced_brackets.nit
- examples/rosettacode/one_dimensional_cellular_automata.nit
- lib/curl/curl.nit
- lib/dom/xml_entities.nit
- lib/linux/data_store.nit
- lib/standard/file.nit
- lib/standard/text/abstract_text.nit
- src/c_tools.nit
- src/compiler/abstract_compiler.nit
- src/ffi/cpp.nit
- src/ffi/extra_java_files.nit
- src/ffi/java.nit
- src/ffi/objc.nit
- src/loader.nit
- src/nitserial.nit
- src/platform/android.nit
- src/platform/ios.nit
- src/platform/pnacl.nit
- src/toolcontext.nit
- tests/example_string.nit
Using optional parameters, the methods `strip_extension`, `basename` and `join` have a default behavior that fit most usage.
* `Collection::join` appends all elements of the collection by default, the same as `join("")`. This is the old behavior of `Collection::to_s`.
* `String::strip_extension` removes the rightmost extension by default, the same as `s.strip_extension("." + s.file_extension)`.
* `String::basename` does not strip the extension by default.
I haven't updated any users of `strip_extension` because the default behavior requires more work. Thus changing the already existing calls to something else would slow down the programs by a very small margin.
> Apply optional params in strip_extension, basename and join

- contrib/jwrapper/.gitignore
- contrib/jwrapper/Makefile
- contrib/jwrapper/grammar/javap.sablecc
- contrib/jwrapper/src/code_generator.nit
- contrib/jwrapper/src/javap_visitor.nit
- contrib/jwrapper/src/jwrapper.nit
- contrib/jwrapper/src/model.nit
- contrib/jwrapper/tests/wildcards.javap
- lib/opts.nit
- lib/performance_analysis.nit
This PR modifies jwrapper to accept Jar archives and fix a bunch of bugs/limitations. This is probably the first of 2 PRs on jwrapper. This one targets the frontend to accept any Java classes (tested on over 25k classes) and to mass produce wrappers. It also ensures that both the generated nit code and jwrapper itself is debuggable.
Although the mass generated Nit code is syntactically valid, more work is needed so it can be usable. We will need to somehow apply Java namespace in generated Nit code, and revamp how new wrappers interact with older/custom wrappers. There is also a few missing features, such as copying the class hierarchy to Nit.
With this PR, jwrapper successfully parses 4 large Jar achives:
* OpenJDK 7 standard library `rt.jar` with 18568 classes.
* OpenJDK 7 tools …
> jwrapper accepts Jar archives

- lib/c.nit
- tests/sav/shootout_nsieve_bytes_alt.res
- tests/shootout_nsieve_bytes_alt.nit
The `shootout_nsieve` benchmark has been present in tests for a long time (longer than I can remember actually).
Up until now, its performances have been constant and quite good, since the work was done in less than 15ms.
However, due to its use of `FlatBuffer` and indexed access, it degenerates when using UTF-8 (see #1277) and the run time of `shootout_nsieve` scales from `0m0.011s` to `1m59.870s`.
This PR fixes that.
> NSieve optimization

- src/Makefile
Small improvement to make the initial make better.
For the final user perspective, an useless error message is removed and the whole process should be slightly faster.
Before:
* real time with cleared ccache: 4m46s
* user time with cleared ccache: 13m23s
* real time with full ccache: 42.5s
* user time with full ccache: 41.8s
After:
* real time with cleared ccache: 4m30s (-5.6%)
* user time with cleared ccache: 13m23s (-4.6%)
* real time with full ccache: 42.5s (-27.8%)
* user time with full ccache: 41.8s (-24.63)
> Improve initial make

- lib/realtime.nit
- src/compiler/abstract_compiler.nit
A lot of googling to solve two related issues on Mac OS X
* `clock_gettime` and cie is not provided, and one should use the more complex clock_get_time (and cie)
* the POSIX `-lrt` is refused by the linker
close #868
> Fix lib/realtime on osx

- contrib/jwrapper/Makefile
- contrib/jwrapper/examples/android_api/.gitignore
- contrib/jwrapper/examples/android_api/Makefile
- contrib/jwrapper/examples/queue/.gitignore
- contrib/jwrapper/examples/queue/Makefile
- contrib/jwrapper/examples/queue/Queue.java
- contrib/jwrapper/examples/queue/user_test.nit
- contrib/jwrapper/examples/queue/user_test.sav
- contrib/jwrapper/grammar/javap.sablecc
- contrib/jwrapper/src/code_generator.nit
- contrib/jwrapper/src/javap_visitor.nit
- contrib/jwrapper/src/jtype_converter.nit
- contrib/jwrapper/src/jwrapper.nit
- contrib/jwrapper/src/model.nit
- contrib/jwrapper/tests/inits.javap
- contrib/jwrapper/tests/long.javap
- contrib/jwrapper/tests/many.javap
- contrib/jwrapper/tests/testjvm.javap
- lib/java/java.nit
- src/ffi/java.nit
This PR is the second part to #1578, it updates the structure of jwrapper, adds a lot of features and creates usable APIs.
Main changes:
* Rewrite of the AST visitor, type conversion and entity naming.
* Generate constructors.
* Generate getter/setters to attributes.
* Add the -p option to choose the prefix of extern class names, use the namespace by default.
* Add the -i option to scan for existing wrappers in any directory or file.
* Add the -r option to filter the target classes from a Jar archive using a regular expression.
* Add more simple tests with javap outputs.
* Add a complete (and working) example of using a custom Java collection from Nit.
* Add an example of generating an API for Android using jwrapper. This API passes nitpick, but it has not been tested as it needs to be …
> jwrapper generates full APIs, with contructors, getters and setters

- contrib/friendz/src/friendz_android.nit
- lib/android/input_events.nit
Intro `AndroidPointerEvent::is_move` and tweak Chainz of Friendz so it doesn't consider the release event as a move event.
> Fix Chainz of Friendz buttons on Android

- lib/standard/stream.nit
- lib/standard/text/ropes.nit
- tests/sav/nitpick_args1.res
Added a wee bit of optimization on Ropes, indexed accesses are properly cached and file manipulations (especially `read_all`) now yields a good balanced Rope, which should reduce the degenerative cases of random indexed access whilst preserving most of the performance in local access.
This has a positive (though small) impact on a the compiler :
* Before: `I   refs:      14,286,788,827`
* After: `I   refs:      14,197,458,800` (-0.63%)
What is seen in Valgrind is unfortunately unchanged in user-time (nitc-sg compiling nitg-sg) :
* Before: `user	0m5.360s`
* After: `user	0m5.367s`
> Cached ropes

- contrib/rss_downloader/src/rss_downloader.nit
- lib/dom/examples/checker.nit
- lib/standard/exec.nit
- lib/standard/file.nit
- tests/sav/checker.res
This PR adds a few features to rss_downloader to support more RSS feeds. It can be configured to decompress the feed and to customize the tag to find the download link. The output has be improved, both on normal behavior and on errors.
As a bonus, add the program I used to debug the RSS feeds as an example for the `dom` module.
> contrib/rss_downloader: compressed feeds and report errors

- lib/android/audio.nit
- lib/app/audio.nit
As explained in PR #1587, there is a bit of a problem when making applications which runs on both linux and android about the loading of the sounds
This PR just reverse the order of the loading for the android audio API, so that if you want to use the sounds in the res folder for your android application, and the sounds in the assets folder for the linux application, you just have to create a new sound with its extension and it will work fine :)
Edit: It also enables the use of different sound formats between android and Linux
> A little fix to android::audio

- misc/vim/syntax/nit.vim
Add support for bin, oct and hex literals which are restrictive enough to detect invalid digits. Also accept `_` in all Int literals, and the suffixes `[iu]8|16|32` proposed by #1588.
Supports `_` in Float literals, it's not yet available but it can't be too far off.
> misc/vim: highlight the new Int literals

- lib/standard/text/ropes.nit
- tests/niti.skip
- tests/nitvm.skip
- tests/test_ropebuffer.nit
Early on, the `to_s` of a RopeBuffer was calling `dump_buffer`, which like to double the size of the buffered part after persisting.
By doing do, a simple program like the one submitted along with this PR was consuming an awful lot of RAM, which has the undesirable side-effect of freezing my machine after a few milliseconds of run.
By replacing it with the more memory-friendly `persist buffer`, all my troubles seem so far away !
> Remove memory leak in Ropes

- lib/standard/text/abstract_text.nit
- src/literal.nit
- tests/sav/base_error_literal.res
This PR changes the behaviour of `to_i` in Strings to support all the derivatives from the parser (hex, bin, oct and underscores)
The change in behaviour helps clean a bit of literal, though some more factorization is yet to come.
As for perfs, on Valgrind (`nitg src/nitg.nit`)
* Before : 14 289 384 832 Ir
* After : 14 348 036 981 Ir
A little slowdown, but acceptable imho since the function accepts more valid inputs and is safer.
> to_i behaviour coherent with parser

- contrib/nitrpg/src/templates/panels.nit
Nitrpg was down since last wednesday because of this. It's now back on track: http://nitlanguage.org/rpg/games/privat/nit
Since the listener didn't crash, no data were loss during the downtime.
> nitrpg: fix crash when the Reviews/Work requests return nothing

- lib/libevent.nit
- lib/nitcorn/http_response.nit
- lib/nitcorn/media_types.nit
Changes:
* use `bytelen` instead of `length` when setting `Content-Length` header
* add media types for web fonts
> Fix nitcorn `Content-Length` when working with UTF-8 files

- contrib/tinks/src/client/android_client.nit
- contrib/tinks/src/client/context.nit
- contrib/tinks/src/common.nit
- contrib/tinks/src/server/server.nit
- lib/gamnit/network/client.nit
- lib/gamnit/network/server.nit
- lib/serialization/caching.nit
- lib/socket/socket.nit
- lib/socket/socket_c.nit
This PR greatly improve multiplayer performance by removing the synchronous frames between the clients and server.
There is still a lot of stuff to do on Tinks! see the notes in #1601.
> Tinks! fix frame lock between clients and servers

- contrib/jwrapper/.gitignore
- contrib/jwrapper/Makefile
- contrib/jwrapper/examples/android_api/.gitignore
- contrib/jwrapper/examples/android_api/Makefile
- contrib/jwrapper/examples/java_api/Makefile
- contrib/jwrapper/examples/java_api/api_user.nit
- contrib/jwrapper/examples/java_api/api_user.sav
- contrib/jwrapper/grammar/javap.sablecc
- contrib/jwrapper/src/code_generator.nit
- contrib/jwrapper/src/javap_visitor.nit
- contrib/jwrapper/src/jwrapper.nit
- contrib/jwrapper/src/model.nit
- lib/performance_analysis.nit
Continuing the work of #1578, #1589 and #1599, this PR adds the last big feature missing from jwrapper: duplicating the class hierarchy from Java to the generated wrapper classes. This allows user code to benefit from polymorphism when invoking Java methods wrappers.
This is done by collecting the implements and extends declaration from the javap output, rebuilding the class hierarchy and adding the super declarations needed to reproduce the hierarchy in Nit. To support a compatible hierarchy across modules, the model can now be serialized to a file and read by the following passes. Note that jwrapper wraps classes and interfaces in the same way so the implements and the extends hierarchy are merge into one on the Nit side.
What's to do next:
* Integrate generated modules in the `::java` …
> jwrapper reproduces Java class hierarchy in Nit and serialize model

- share/man/nitc.md
- src/compiler/abstract_compiler.nit
Addition of a `-g` option to the compiler, right now it just disables gdb-side optimisation, but it may become more capable in the long run.
> Add debug option to compiler

- lib/a_star.nit
- lib/ai/backtrack.nit
- lib/bucketed_game.nit
- lib/github/hooks.nit
- lib/markdown/markdown.nit
- lib/mnit/image_set.nit
- lib/nitcc_runtime.nit
- src/parser/parser_nodes.nit
The current leniency of abstract methods (see #808) make that a lot of concrete classes inherit abstract methods (I counted 5048 cases in the whole code base).
Some trivial cases are classes that just should be abstract.
> More abstract classes

- src/compiler/separate_compiler.nit
thus always compile stub of methods to avoid unresolved symbols
weak symbols seem to cause issues on some platforms *cough mac os x cough*
> separate_compiler: remove the use of weak symbols.

- src/c_tools.nit
Just a reordering to really silent the warning on osx
> c_tool: reorder CC arguments since the semantic between gcc and clang differs

- lib/markdown/markdown.nit
Fix a small bug in Markdown, in some cases pos could be negative if `skip_spaces` at line 2093 returned -1
> Markdown fix

- lib/mongodb/mongodb.nit
- lib/mongodb/native_mongodb.nit
Everything is in the title.
For more about the crash see issue #1629.
> Mongodb: fix C warnings and avoid crash caused by GC

- lib/standard/file.nit
- lib/standard/stream.nit
As @privat notified me of yesterday, a lot of time is wasted in read_all by boxing and unboxing bytes when doing the infamous `_buffer.add` operation in `read_all_bytes`.
This PR removes the boxing operations by bulk-writing a NativeString to a Bytes.
The buffer on files is also tenfold-bigger, which cuts I/O times while still retaining a reasonable size.
On the Batmobile™
Before:
standard___standard__BufferedReader___Reader__read_all_bytes: 90.816 MIr
After:
standard___standard__BufferedReader___Reader__read_all_bytes: 7.596 MIr
Before
user	0m4.316s
After
user	0m4.182s
Close #1298
> Performance improvement in read_all_bytes

- lib/graphs/digraph.nit
As mentioned in issue #1386, I would like to introduce a graph theory module in Nit.
@Morriar : any comment about the documentation style is welcome!
Task list:
> Graph theory in Nit

- lib/markdown/Makefile
- lib/markdown/decorators.nit
- lib/markdown/man.nit
- lib/markdown/markdown.nit
- lib/markdown/nitmd.nit
- share/man/Makefile
- share/man/nit.md
- share/man/nitc.md
- share/man/nitdbg_client.md
- share/man/nitdoc.md
- share/man/nitlight.md
- share/man/nitls.md
- share/man/nitmetrics.md
- share/man/nitpick.md
- share/man/nitpretty.md
- share/man/nitserial.md
- share/man/nitunit.md
- share/man/nitx.md
A lot of things are done here:
* extension of nitmd to handle more output formats
* new man decorator to transform markdown into basic groff suitable for manpages. Close #1506
* remove dubious usage of definition list in our markdown. Close #1594
* remove the use of pandoc and use nitmd to generate our manpages. Close #824
> extends nitmd to handle manpages output format

- misc/jenkins/check_contrib.sh
- misc/jenkins/nitester-wrapper.sh
The infamous bug that caused some tests result to silently make Jenkins go mad is found.
The issue was to have a junit package named `run`; unfortunately, package names are used as is in URL by Jenkins and `run` in URL seems to have a special buggy behavior. Eg 
* http://gresil.org/jenkins/job/CI_github/lastCompletedBuild/testReport/run/foo
* http://gresil.org/jenkins/job/CI_github/lastCompletedBuild/testReport/notrun/foo
The solution is to name the pseudo-package `cmd` instead.
> jenkins: name command test results with `cmd` instead of `run`

- misc/jenkins/checklicense.sh
- misc/jenkins/checksignedoffby.sh
- misc/jenkins/checkwhitespaces.sh
- misc/jenkins/unitrun.sh
Improve scripts to make jenkins error friendlier about licenses, signed-off-bys and whitespaces.
Scripts now write sentences and add a final note in case of error to explain how to solve the issues.
Once #1639 is merged, the life of new contributors will never be that easy.
Examples of new messages:
* `./checklicense.sh v0.7 63e0f2c` gives:
~~~
checklicense v0.7 (68561eb8d91800ccb3fa289bff6721ddd11dbe25) .. 63e0f2c (63e0f2c7cd96f4c40366d92614785b1006e52367)
These files are missing their licence:
benchmarks/polygons/nit/bench_polygon.nit
Please double check that the licence text (i.e. `This file is part of NIT...`) is included at the begin of these files.
~~~
* `./checksignedoffby.sh origin/master 63e0f2c7cd96f4c40366d92614785b1006e52367` gives:
~~~
checksignedoffby origin/master …
> Friendly jenkins checks

- lib/md5.nit
- src/interpreter/dynamic_loading_ffi/on_demand_compiler.nit
- tests/sav/Darwin/todo
Fix #1623 by removing the soname declaration (the soname was more of a placeholder at this time anyway). Also take this opportunity to remove the `-g` flag.
The fixes to the md5 modules update it to the latest style and use the nity/native pattern to avoid callbacks so it is light FFI compatible. This was used to test the interpreter on OS X.
> Fix light FFI in interpreter on OS X

- tests/sav/test_glsl_validation.res
- tests/test_glsl_validation.nit
As reported in #1537, different versions of glslangValidator do not output the same error messages as they do not use the same default type for undeclared variables. This PR removes an error from the glsl code (or fix it if you prefer) so different versions of the tools have the same output. There are still many more errors to check that the integration of the tool within nitc works.
Fix #1537.
> simplify glslangValidator test to support different versions of the tool

- src/doc/vim_autocomplete.nit
When searching for a module, generate list of introduced classes and properties to add to the user module documentation.
So from within vim, when entering `:Nit opts`, it shows:
~~~
Management of options on the command line
* Option: Super class of all option's class
* OptionArray: An option with an array as parameter
* OptionBool: A boolean option, `true` when present, `false` if not
* OptionContext: Context where the options process
* OptionCount: A count option. Count the number of time this option is present
* OptionEnum: An option to choose from an enumeration
* OptionFloat: An option with a Float as parameter
* OptionInt: An option with an Int as parameter
* OptionParameter: Option with one parameter (mandatory by default)
* OptionString: An option with a `String` as parameter
* …
> Better module doc within Vim

- lib/standard/kernel.nit
Since objects are allocated on 64bit word boundaries, it made scene to remove the three 000 lower bits and increase the entropy of the hashcode.
Unfortunately, primitive objects like low Int values or Bool have a object_id lower than 8. shifting the 3 last bits was thus a bad idea.
Therefore, programs that used Int or Bool as keys (or part of keys) did have a lot of hash collisions.
For instance, before, for lib/ai/examples/puzzle.nit:
* number of collisions: 525428 (84.49%)
* average length of collisions: 12.44
After:
* number of collisions: 256223 (41.20%)
* average length of collisions: 3.16
The change have a limiting effect on programs that mainly use standard objects as keys.
Before, for nitc:
* number of collisions: 661715 (16.18%)
* average length of collisions: 2.24
After:
* …
> lib/code/standard: hash no more divides object_id by 8

- lib/standard/fixed_ints.nit
Fix a bug that caused an assert failed when accessing an empty string in `Text::is_int`
Reported by @xymus with PR #1649
> Text::is_int bugfix

- contrib/nitiwiki/tests/res/wiki1_nitiwiki_render.res
- contrib/nitiwiki/tests/res/wiki1_nitiwiki_status.res
- contrib/nitiwiki/tests/res/wiki2_nitiwiki_render.res
- contrib/nitiwiki/tests/res/wiki2_nitiwiki_status.res
- contrib/nitiwiki/tests/res/wiki3_nitiwiki_render.res
- contrib/nitiwiki/tests/res/wiki3_nitiwiki_status.res
- contrib/nitiwiki/tests/tests.sh
- contrib/pep8analysis/Makefile
- contrib/pep8analysis/test.sav
- contrib/refund/tests/tests.sh
Thanks to `misc/jenkins/check_contrib.sh`, programs in contrib can be tested for regressions.
Unfortunately, sometime the result of the test is not reported (only printed on screen). This PR update some of these to really report things.
> Report check contrib

- examples/calculator/Makefile
- examples/calculator/src/calculator.nit
- examples/calculator/src/calculator_logic.nit
- lib/app/ui.nit
- lib/standard/numeric.nit
Partial revert of cbbb5225 because the Android version of Calc need only `android::ui` and not `android`. The default entry point of `android` use `native_app_glue` as base activity/framework, whereas UI apps use `nit_activity`. This caused the apk file to show 2 activities in the launch menu.
Also recent changes (probably) make calling `to_i` and thus `to_n` on empty strings crash. I've updated the calculator to avoid this with a new friendlier behavior in such cases.
I've also updated `to_n` to return 0 on empty strings. This preserve the old behavior, it is a neutral fallback value and it fits with `"".is_numeric == true`. I did not touch `to_i`.
> Fix app.nit Calc example

- lib/cocoa/examples/cocoa_message_box.nit
- src/platform/ios.nit
Add `ONLY_ACTIVE_ARCH=NO` to the xcode call because it is required by the latest xcode.
For the iOS example, you would expect `AppKit.h` to be included by the imported module. It is, but at the same time it is ignored for performance reason since none of the imported module services are used. This will be fixed in a future PR. For now, we add the include locally as it is a better example and happen to avoid the problem.
> Small fix to iOS support

- src/README.md
- src/loader.nit
- src/project.ini
Small improvements and fixes for the ini files.
The most important change is how to associate ini file with singleton projects (no dir, only one nit file).
The proposal, from @xymus, is just to add a `.ini` file named like the `.nit`. so `lib/counter.ini` for the project `lib/counter.nit`.
I'm not sure that this feature should be official, consider it just as an easy path to update existing code.
> Improve ini

- contrib/objcwrapper/.gitignore
- contrib/objcwrapper/Makefile
- contrib/objcwrapper/README.md
- contrib/objcwrapper/grammar/objc.sablecc
- contrib/objcwrapper/src/header_static.nit
- contrib/objcwrapper/src/objc_generator.nit
- contrib/objcwrapper/src/objc_model.nit
- contrib/objcwrapper/src/objc_visitor.nit
- contrib/objcwrapper/src/objcwrapper.nit
This PR continues the good work of #1661 by improving further the code generator of _objcwrapper_. The main change is the revamp of the code generator module, the detection of unknown types so they are not used in active methods, and improvements to the gammar and preprocessor to accept some GNUStep classes.
The generated code now passes nitpick but there is some problems with the generated Objective-C. Some types are not correctly reproduced. So it is not usable as of yet, but it is not too far.
The main limiting factors at this points are functions pointers used as parameters, the class hierarchy that is not duplicated and the Objective-C FFI not working on GNU/Linux.
> objcwrapper: generate valid Nit code for large Objective-C classes

- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- lib/core/text/ropes.nit
- src/compiler/abstract_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/rapid_type_analysis.nit
- tests/sav/error_needed_method_alt3.res
- tests/sav/niti/error_needed_method_alt4.res
This PR introduces some more bookkeeping to Texts variants, some more work is to be expected at compilation-time for the generation of FlatStrings with all the information, but this should improve execution speeds in clients.
`./chain_concat -m string --loops 1000000 --strlen 15 --ccts 20`
* Before:
4.42 4.48 4.51 4.5025 "20"
* After:
2.40 2.36 2.38 2.37 "20"
`time ./bin/nitc --semi-global src/nitc.nit -o bin/nitc` best of 10:
* Before
~~~
real  0m6.075s
user  0m4.624s
sys   0m0.826s
~~~
* After
~~~
real  0m6.172s
user  0m4.751s
sys   0m0.870s
~~~
Valgrind:
* Before; GIr: 14,768,723,784
* After; GIr: 14,775,119,149
> Text optimization

- contrib/nitiwiki/src/wiki_base.nit
- lib/ini.nit
- src/loader.nit
Since the absence of a key is an ini file is an expected thing, I think it is better that the library return `null` instead of aborting.
This simplifies the library (and remove all aborts and cast on null).
This also simplify clients: a single call and use of advanced nullable features of Nit.
> lib/ini: give to the user `null` on undefined keys

- contrib/github_merge.nit
Recent changes in github API or in the @jpages account broke the script.
> githubmerge: make public name/email access of users more robust.

- .mailmap
Because the result of `git shortlog` was not OCD-compliant enough.
> mailmap: add Mehdi Ait Younes and Hervé Matysiak

- contrib/benitlux/src/benitlux_daily.nit
- contrib/benitlux/src/benitlux_model.nit
This is an ongoing effort to please GMail and the likes, so Benitlux emails are no longer sent to the spam folder. Which is vital to keep @R4PaSs happy, hydrated and productive.
This PR adds headers to the email to make it clear that it is a mailing list and to guide the assisted unsubscribe option. Specifying the street name will help differentiate between the emails from the two mailing lists. (One of which is not exposed on the website, it is available on request only.)
I've also added DKIM (to the existing SPF) as server identification, it should help a lot too.
> Benitlux mailing list: nicer and differentiate between streets

- lib/core/re.nit
- lib/saxophonit/reader_model.nit
Fix bug with sub-expressions when using a `search_from`, fix a few compiler warnings and rename `optimize_is_in` to `optimize_has` as it is closer to the public API.
> regex: bug fix, less warnings and rename

- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
All is in the title, @privat noticed me this morning that text::escape_to_c was taking around 4% of the time in nitc, taking the runtime to 15.183 GIr according to Valgrind.
By shortcutting all Unicode-related services since the C-side escaping is done on ASCII-sequences only and UTF-8 cannot contain invalid C sequences, the gain is substantial, one run of nitc is now done in 14.580 GIr, a gain of 600+ MIr (around 4%, what a coincidence !).
> Optimized use of escape_to_c

- contrib/neo_doxygen/src/neo_doxygen.nit
- lib/opts.nit
- src/toolcontext.nit
- tests/sav/test_opts_args4.res
- tests/sav/test_opts_args6.res
- tests/sav/test_opts_args7.res
- tests/sav/test_opts_args9.res
- tests/test_opts.args
- tests/test_opts.nit
`OptionString` reads the next argument to be used as its parameter. However, to detect errors it did not read parameter beginning with `-`. This PR changes this behavior to only avoid parameters that are the name of a known option in the current `OptionContext`. This should report real errors and accept parameters beginning with `-`, such parameter are useful to forward options to subprograms.
Renaming `OptionContext::get_errors` to `errors` assign the short name to the most commonly used property. `errors` was previously reserved for errors local to the context only. From the Nit repo, only 2 projects correctly used `get_errors`, 8 wrongfully used `errors` and thus did not catch all errors.
> lib/opts: accept non-conflicting parameters for OptionString and rename get_errors to errors

- contrib/inkscape_tools/.gitignore
- contrib/inkscape_tools/Makefile
Fix #1657, it was actually the test that was broken as the SVG source file is designed for the bash script that preceded inkscape_tools and not inkscape_tools itself (see examples/mnit_dino/tools/). This PR use Tinks! art instead of Dino's. It was already tested by the Tinks! project but here we use it to test the program arguments.
> contrib/inkscape_tools: use Tinks! art instead of Dino's to test args

- lib/counter.nit
- lib/text_stat.nit
- tests/niti.skip
- tests/nitvm.skip
- tests/sav/nitcg/test_text_stat.res
- tests/sav/test_text_stat.res
- tests/test_text_stat.nit
Introducing a statistics module for Text variants usage which keeps trace of the accesses and allocations of Texts in a program.
It works in a similar way to `array_debug` or `hash_debug`, and prints statistics after the execution of a module.
> String Stats

- contrib/nitcc/src/autom.nit
- contrib/nitcc/src/grammar.nit
- contrib/nitcc/src/nitcc.nit
- lib/json/json_lexer.nit
- lib/json/json_parser.nit
Some improvements and bugfixes for nitcc.
* Improve code size in C and in Nit
* Produce valid Nit code even in case of R/R, S/R or S/R/R conflicts. Close #1693
Before: compiling objc_test_parser on an old laptop
* 880.58 usertime
* 3GB memory
* produced executable: 50MB (31MB stripped)
after: same grammar, better nitcc
* 337.80usertime
* 788MB memory
* produced executable: 28MB (8,8MB stripped)
> Better nitcc

- lib/core/re.nit
- lib/core/text/flat.nit
- lib/core/text/native.nit
- src/interpreter/naive_interpreter.nit
- tests/sav/nitserial_args1.res
- tests/sav/test_regex_check.res
- tests/test_regex_check.nit
This PR closes #1684
Instead of making `byte_to_char_index` public, it has been removed as it had no real reason to live.
Names are corrected and should correctly reflect their use.
Some examples of regular expressions with UTF-8 have been included.
Note however that the C-library underneath does not have UTF-8 semantics, as such, when using repetition operators on UTF-8 strings, capture the problematic characters with parentheses as in the example, or else the result will be erroneous.
Additionally, performances should be a bit better since less allocations and copy_to should be done.
> UTF-8 Regex

- contrib/nitiwiki/examples/nitiwiki/config.ini
- contrib/nitiwiki/examples/nitiwiki/highlighter.sh
- contrib/nitiwiki/examples/nitiwiki/pages/block.md
- contrib/nitiwiki/src/markdown_highlight.nit
- contrib/nitiwiki/src/nitiwiki.nit
- contrib/nitiwiki/src/wiki_base.nit
- contrib/nitiwiki/src/wiki_links.nit
- lib/markdown/markdown.nit
- src/doc/doc_down.nit
- src/testing/testing_doc.nit
- tests/nitiwiki.args
This is a cleaned up version of what is currently doing the code highlighting and the table in the deployed http://nitlanguage.org
The basic idea here is to delegate the job to some other program. The program has to be configured in the config.ini under the key `wiki.highlighter`
This approach, while not pure nit, makes it quite easy to use whatever highlighter program the user prefer with whatever options (instead of hard-coding a specific external program in the nit source code).
An advanced way is to delegate to a shell script that checks arguments then dispatches to a real program.
ping maintainer: @Morriar
> nitiwiki: external highlighter

- misc/vim/plugin/nit.vim
The plugin was not updated with the new name for the `core` library, but it's never too late.
> misc/vim: update the vim plugin to use core instead of standard

- lib/android/native_app_glue.nit
- lib/c.nit
- lib/egl.nit
- lib/glesv2/examples/opengles2_hello_triangle.nit
- lib/glesv2/glesv2.nit
- tests/sav/Darwin/todo
This PR adds a few services to the low-level graphics modules to prepare for gamnit.
This is the 2nd PR to use a new style for the glesv2 module. The old code has not yet been fully updated, so the style may vary in the same module. The new style try to stay as close as possible to the names and signatures used by the OpenGL ES 2.0 C API and by webgl.
As usual with this module, for more documentation please refer to the official doc at https://www.khronos.org/opengles/sdk/docs/man/.
> glesv2: more services from OpenGL ES 2.0 to prepare for gamnit

- src/platform/android.nit
This allows to manually sign your release APK file.
As requested by @privat.
> android: skip signing the APK if KEY_ALIAS env var is not set

- src/compiler/compiler_ffi/compiler_ffi.nit
Just fix `--typing-test-metrics` that was broken.
A future PR (still wip) will ensure that the option will be no more broken
> nitc: fix --typing-test-metrics by using correct tags in FFI

- contrib/opportunity/src/opportunity_controller.nit
- contrib/opportunity/src/opportunity_model.nit
- examples/rosettacode/sha_1.nit
- lib/base64.nit
- lib/core/bytes.nit
- lib/core/stream.nit
- lib/core/text/flat.nit
- lib/sha1.nit
- lib/websocket/websocket.nit
- tests/sav/nitcg/test_text_stat.res
- tests/sav/nitserial_args1.res
- tests/sav/test_text_stat.res
Since quite some time now we've had the cleaning function for Bytes that ensured that what was coming from the exterior was clean and could be transformed safely to a String.
This is now generalized to any NativeString, and the clean function will be called each time a NativeString is `to_s`'d
At the same time, `clean_utf8` is now better performing (for `Files::read_all`, Ir per call is roughly 40% less than before), which limits the impacts of the new strategy.
Furthermore, the string produced by `NativeString::clean_utf8` has its length calculated which saves time on later operations on the string.
It also limits the number of calls by avoiding allocations if not necessary (if the string is already clean, which should happen a lot more often than not).
As for performances,
Valgrind …
> Clean UTF-8 string update

- src/nitcatalog.nit
HTML files are generated into a `/p/` subdirectory so they will not conflict with other generated files.
One other point is to have stable and final URL for packages in the catalog. eg http://nitlanguage.org/catalog/p/nitiwiki.html
> nitcatalog: isolate package page into a subdirectory

- misc/README.md
- misc/vim/plugin/nit.vim
Adds the `:NitExecute` command (or `:NitE` as shortcut) to interpret the current file with `nit`.
This is very similar to the manual `:!nit %` but it saves modified buffers to a temp file to execute the content of the current buffer and not the last saved content.
This is completely up to you but I recommend mapping this to `ctrl-f` to fit between `ctrl-d -> Nitdoc` and `ctrl-g -> NitGitGrep`. Here are the required lines for `.vimrc`:
~~~
" Map the Nitdoc command to Ctrl-D
map <C-d> :Nitdoc<enter>
" Map the NitGitGrep function to Ctrl-G
map <C-g> :call NitGitGrep()<enter>
" Map the NitExecute function to Ctrl-F <------- The new one
map <C-f> :NitExecute<enter>
~~~
> vim plugin: intro NitExecute to interpret the current file with `nit`

- lib/matrix/matrix.nit
- lib/matrix/package.ini
- lib/matrix/projection.nit
This PR intro `Matrix` to represent a matrix of floats. The main module offers only general services and the `projection` module adds services useful for 3D manipulations.
The package is oriented towards matrices of floats and was designed alongside Gamnit. As such, is a bit specialized and may not be appropriate for all usage of matrices (such as integer matrices). So if you prefer, I can move these back to Gamnit. But since this module does not have any dependencies and `Matrix` can be useful for a wide array of context, I chose to leave it in lib.
> lib: intro the matrix package

- contrib/benitlux/package.ini
- contrib/crazy_moles/package.ini
- contrib/friendz/package.ini
- contrib/mnit_test/package.ini
- contrib/nitrpg/package.ini
- contrib/online_ide/package.ini
- contrib/opportunity/package.ini
- contrib/pep8analysis/package.ini
- contrib/tinks/package.ini
- contrib/tnitter/package.ini
- examples/calculator/package.ini
- examples/mnit_ballz/package.ini
- examples/mnit_dino/package.ini
- examples/shoot/package.ini
- src/nitcatalog.nit
Two new package metadata are added
* `upstream.tryit` for an URL that points to a demo version or a live version of the main web service offered by the package.
* `upstream.apk` for an URL that points to a dry `apk`, or an install page on some store, for the main android application offered by the package.
Moreover, packages that have one them will be respectively tagged `tryit` and `apk`
A demo is available: http://info.uqam.ca/~privat/catalog/#tag_tryit and http://info.uqam.ca/~privat/catalog/#tag_apk
> Extends catalog with a *try it* and a *download apk* links

- lib/core/stream.nit
As @xymus requested, `Bytes` is now a subclass of `Writable`
> Bytes is now Writable

- lib/core/collection/abstract_collection.nit
- lib/core/file.nit
- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- tests/sav/test_basename_perf.res
- tests/sav/test_basename_perf_args1.res
- tests/test_basename_perf.args
- tests/test_basename_perf.nit
Should close #1736 if performances are adequate for @privat.
This PR optimizes some methods in both `SequenceRead` and `FlatString`, on the test program exposed in #1736, the valgrind runtime has gone from 418,872,526 Ir to 136,522,095 Ir (~67.5% improvement)
Some more improvements could be observed if we could get rid of some useless Boxes in `NativeString::to_s_with_copy` because of a `is_same_instance` which boxes NativeStrings (24k allocations in total to remove).
> Basename fix

- lib/core/collection/abstract_collection.nit
- lib/core/stream.nit
- misc/vim/syntax/nit.vim
- tests/sav/test_with.res
- tests/test_with.nit
As I wanted to use the `with` statement on Iterators in order to experiment with #1735, I realized that neither them not stream are usable with `with` since they lack the required methods.
> Make stream and iterators withable

- lib/gamnit/examples/triangle/src/portable_triangle.nit
- lib/gamnit/examples/triangle/src/standalone_triangle.nit
- lib/glesv2/.gitignore
- lib/glesv2/Makefile
- lib/glesv2/examples/opengles2_hello_triangle.nit
- lib/glesv2/glesv2.nit
Intro wrappers to work with textures, shaders, framebuffers and renderbuffers, synchronize with server and set clear values of buffers. Update most of the remaining enumerations and some more services to the new API style. Add a makefile to generate a wrapper stub from the local GLES2/gl2.h header file.
FYI, there's approximatly only 65 functions left to wrap, out of 141.
> glesv2: services for textures, shaders, framebuffers, renderbuffers & more, and update API

- src/modelize/modelize_property.nit
This caused most tools to crash on some useless types in redefined signatures. In my case, there was other problems in the same propdef, so it looks like it was not handling properly a "keep going" logic.
> src: fix null receiver error on useless-signature warning

- src/compiler/abstract_compiler.nit
- src/compiler/java_compiler.nit
- src/compiler/separate_compiler.nit
- src/doc/doc_phases/doc_structure.nit
- src/ffi/extern_classes.nit
- src/highlight.nit
- src/loader.nit
- src/model/model.nit
- src/model/model_base.nit
- src/modelbuilder_base.nit
- src/modelize/modelize_class.nit
- src/modelize/modelize_property.nit
- src/semantize/scope.nit
- src/semantize/typing.nit
- src/transform.nit
- tests/sav/base_attr_abstract.res
- tests/sav/base_attr_abstract_alt1.res
- tests/sav/base_attr_abstract_alt2.res
- tests/sav/base_attr_abstract_alt3.res
- tests/sav/base_attr_abstract_alt4.res
- tests/sav/error_redef_alt3.res
- tests/sav/error_redef_alt6.res
- tests/sav/error_redef_alt9.res
A pass on the various modules of `nitc` to make them more robust when `keep_going` is activated.
The main changes are the introductions of the flags `is_broken` in the root classes ANode and MEntity. This flags simplify the clients code to check the validity of entities before working with them.
> More robustness in keep going

- lib/mnit/android/android_app.nit
- lib/mnit/linux/linux_app.nit
- tests/sav/ballz_linux.res
- tests/sav/dino_linux.res
- tests/sav/shoot_linux.res
Simple fix for the "Redef Error" in mnit clients: do not redef virtual types, instead assert the types in the users methods.
> mnit: Fix error on refined virtual types

- lib/mongodb/mongodb.nit
This PR apply some fixes to the MongoDB library:
* avoids crash when `Collection::find` returns only one element
* fixes the SegFault workaround in `Collection::find`
> lib/mongodb: minor fixes

- lib/github/api.nit
- lib/github/events.nit
The first objective of this PR is to clean the `github::api` code and remove typing wranings.
It also add new services that can be useful for clients:
* `Issue::is_ull_request`
* Setters to modify GithubEntitties
> lib/github: clean code and add some services

- contrib/online_ide/sources/nit/pnacl_nit.nit
- src/loader.nit
- src/model/mmodule.nit
- src/model/model_viz.nit
- src/modelbuilder.nit
- src/nitcatalog.nit
- src/nitls.nit
- src/nitunit.nit
- tests/nitls.args
- tests/sav/base_import2_alt1.res
- tests/sav/nitls_args6.res
- tests/sav/nitmetrics_args1.res
- tests/sav/nitx_args3.res
A big refactorization of the loader
This include cleanup, renaming and documentation of the existing code.
The major change is the removal of `ModulePath` used to designate an identified module that is not yet loaded. This caused major issues since once the module was loaded, the MModule object has to be used instead.
Now, genuine `MModule` are used to also represent modules identified in the file system but not yet loaded.
This simplify the code of the loader, nitls and nitcatalog.
By the way, the option `-d` (and `-M`) of nitls that was broken by the previous changes in the loader is now fixed.
Another change is the introduction of `scan_full` that is a high-level method to be used by clients like nitls or nitcatalog that just need to identify packages, groups and modules in the …
> Loader refactor

- contrib/wiringPi/lib/wiringPi.nit
- lib/bcm2835/bcm2835.nit
- lib/core/time.nit
- lib/egl.nit
- lib/signals.nit
- src/ffi/cpp.nit
- src/ffi/light_c.nit
- src/nitni/nitni_utilities.nit
Move some methods from Object to the top-level (Sys) as they do not rely on `self` and are intended to be called from everywhere.
Beside documentation improvement, this should slightly reduce the size of tables as methods introduced in Object are inherited by all classes.
> Kill pseudo toplevel methods

- contrib/opportunity/src/templates/meetup.nit
So we don't have to write our own name every single time we participate to an event.
Already deployed on xymus.net, you can test it here: http://xymus.net/opportunity/?meetup_id=5E8F7A00589D5F567FFB07EA09A8630A8A2BA048
> contrib/opportunity: store local participant's name in a cookie

- lib/html/html.nit
This optimize clients of lib/html like highlight.
usertime for `./test_highlight ../lib/core/`:
* before: 0m2.416s
* after: 0m2.328s (-3.64%)
> lib/html: implement the tag list as an hashset instead of a array.

- src/parser/parser.nit
- src/parser/parser_work.nit
- src/parser/xss/parser.xss
This optimize multiple Parser allocation, for instance nitunit or nitdoc that need to deal with each nitunit in the documentation.
usertime for `./nitdoc ../lib/core/`:
* before: 0m2.184s
* after: 0m1.788s (-18.1%)
> parser: do not allocate a reduction table for each parser

- lib/core/collection/hash_collection.nit
- lib/hash_debug.nit
- tests/sav/test_hash_debug.res
Some optimization when dealing with empty hash-based collection
user time for nitc nitc.nit:
* before: 0m6.640s
* after: 0m6.344s (-4.5%)
> Optimize hash collection

- src/loader.nit
- tests/sav/test_test_phase_args2.res
- tests/test_test_phase.args
The last series (#1750 ) removed then silently.
A test is also added to avoid regression.
> loader: print error if bad files given to `scan_full` or `parse_full`

- lib/core/bytes.nit
Title says all, I needed this today to debug trailing zeroes in a produced string and I figured it could be PR'd
> lib/core: Added new `hexdigest` service on `Text`

- lib/serialization/serialization.nit
- tests/sav/nitce/test_binary_deserialization_alt1.res
- tests/sav/nitce/test_json_deserialization_alt1.res
Restore previous behavior of the deserialization init which should not call the default init. This caused problems on default inits that accessed not yet deserialized attributes.
This also fixes WBTW troubles with game saving and multiplayer.
> lib/serialization: fix deserialization constructor calling the default init

- lib/html/html.nit
Lazily create structures for attributes and children as most HTML nodes do not have them.
User time for `time ./nitlight ../lib -d out`:
* before 0m8.196s
* after 0m6.940s (-15%)
> More lib/html optimizations

- contrib/opportunity/src/templates/meetup.nit
Add the ∇ ratio to Opportunity with a customizable multiplier. It assigns weight to the choices of participants so that someone who select all possible answers puts less weight on each answer, and someone who choses a single answer puts her full weight on it.
It can be used to count the number of pizzas to order (with a multiplier of 0.4) and to give more importances to the available times of busy people when scheduling a meeting.
> Opportunity: intro ∇ ratio

- Makefile
- README.md
- misc/nit_env.sh
The script `nit_env.sh` tries to auto-magically configure PATH, MANPATH and bash completion for users. The point is to be as portable and simple a possible for the final used has he just has to write
~~~
$ source misc/nit_env.sh
~~~
and get a working setup.
Moreover, if `install` in given as argument, then the script register itself to the user `$HOME/.profile`.
~~~
$ source misc/nit_env.sh install
~~~
One advantage is that the script invocation is registered in `.profile`, thus future evolutions of the script will be automatically used in future sessions of the users.
> introduce nit_env.sh to setup the shell environement

- examples/shoot/src/shoot_linux.nit
> examples/shoot: fix typo in shoot_linux synopsis

- src/compiler/abstract_compiler.nit
- tests/nitc.args
- tests/sav/nitc_args10.res
nitc with --global and --semi-global tries to inline things, but methods with an explicit `constant_value` (i.e. defined with `-D`) were not recognized when asked: ``can I inline this?''
The inlining itself does not require specific code.
Close #1793
> nitc can inline redefinitions with -D

- src/model/model.nit
- src/modelize/modelize_property.nit
- tests/error_redef_vt.nit
- tests/sav/error_redef_vt.res
- tests/sav/error_virtual_type2_alt1.res
- tests/sav/error_virtual_type2_alt2.res
- tests/sav/error_virtual_type2_alt3.res
- tests/sav/error_virtual_type2_alt4.res
- tests/sav/error_virtual_type2_alt5.res
- tests/sav/error_virtual_type2_alt6.res
- tests/sav/error_virtual_type_alt3.res
Improve the handling of inconsistent model when virtual types are badly defined.
The changes are mainly done with 2 things:
* still register broken `type` definition in the property, so that properties have at least a definition
* use bottom type (also called the absurd type) to indicate inconsistency in the model (instead of aborting)
Reported-by: @Morriar
> Robust Virtual Type

- benchmarks/bench_plot.sh
- benchmarks/strings/bench_strings.sh
A few things happening here:
* Added some line-producing output to `bench_plot.sh`, use both functions to produce lines instead of histograms
* `bench_strings.sh` underwent a few transformations: now you can try with different values of `maxlen` (threshold at which a flat concatenation produces a new Concat node instead of a new FlatString), you can also work on HEAD only with a new option, also, all benches now produce lines instead of histograms
> Bench strings update

- lib/gtk/v3_10.nit
- lib/gtk/v3_4/gdk.nit
- lib/gtk/v3_4/gtk_assistant.nit
- lib/gtk/v3_4/gtk_core.nit
- lib/gtk/v3_4/v3_4.nit
- lib/linux/ui.nit
- tests/test_gtk.nit
Services from v3.10 includes the `HeaderBar` (the large window top bar with custom buttons) and the `Stack` which shows only 1 widget at a time with transition effects. The renamed services use the same name as in C.
> lib/gtk: add services from GTK+ 3.10 and rename some core services 

- contrib/nitester/src/nitester.nit
- lib/android/activities.nit
- lib/core/kernel.nit
- tests/sav/error_class_glob.res
- tests/sav/nituml_args3.res
- tests/sav/nituml_args4.res
The `Task` interface defines a fragment of Nit code to execute in its `main` method. This interface should be compatible between different platforms and parallelization engines.
`NativeActivity::run_on_ui_thread` is widely used on Android as most logic is executed on background threads but only the UI thread can modify the UI. It is a perfect example of how the `Task` interface can be used.
Future work include using `Task` in `pthreads` and `gtk::gdk`. But there a a few differences in the logic that makes it not as easy: `Thread::main` returns a `nullable object`, but is it worth keeping it? `GdkRunnable::run` returns a boolean to tell GDK if it should be called again.
> Intro `Task` and use in for Android's `run_on_ui_thread`

- lib/crypto.nit
Signed-off-by: Philippe Pepos Petitclerc <ppeposp@gmail.com>
> Introduced xoring of String and a sequence of Bytes

- clib/gc_chooser.c
- src/compiler/abstract_compiler.nit
- src/compiler/separate_compiler.nit
- src/platform/android.nit
This PR tweaks basic Nit features on Android so it is more practical on the short-middle term.
It is better to not handle signals on Android so that it falls back on the Android stacktrace, which is pretty useful for debugging. We might want to handle the signals once we successfully integrate libunwind to the Android apps.
Dropping MIPS support saves some compilation time. The related commit can be reverted when supporting MIPS is useful.
This PR also deactivates the GC on Android as it is currently broken. Unexpected behaviors happen more frequently when using the Java FFI in a threaded app. There are possible solutions to this problem; newer versions of libgc are tweaked for Android, better compilation configs may help, and double checking the Android lib for objects that should be …
> nitc/android: rely on Android's native stacktrace, drop MIPS support and temporarily disable the GC

- lib/serialization/serialization.nit
- src/nitserial.nit
This PR implements the serialization of the `Error` class manually, it is declared in `core` above the `serialization` module.
Also updates `nitserial` so that it does not attempt to instantiate abstract classes with factories.
@privat I have doubts about the use of `is_abstract` and `is_class`, is it appropriate?
> serialization: serialize the Error class and avoid  abstract classes with factories

- lib/json/serialization.nit
The services `to_json_string` and `from_json_string` should be useful for simple scripts. Both services report errors only on the console. This behavior is enough for simple scripts but more complex programs should still use `Serializer` and `Deserializer` services.
This methods may look a lot like `to_json` and `to_plain_json`. I plan to replace `to_json` with either `to_plain_json` to preserve the same behavior but with support for all serializable classes, or `to_json_string` to get JSON with metadata. Note that even if the output contains metadata, it is readable by external tools with a small overhead.
If you have a better idea for the names, please mention it. For my part, I consider these names temporary until we free the `to_json` names...
> json::serialization: intro services to easily serialize to and from Json

- lib/android/http_request.nit
- lib/app/http_request.nit
- lib/core/error.nit
- lib/gtk/v3_4/gdk.nit
- lib/java/base.nit
- lib/jvm.nit
- lib/linux/http_request.nit
This PR introduces a series of portable services to execute HTTP request asynchronously from graphical programs. These services should be independent and may be reorganized as needed by client programs.
The HTTP request services are very simple by design, it is not an attempt to define a true API to build the request. It is currently limited to GET calls to a simple URI, for example a simple use may look like:
~~~
print "http://xymus.net/rest/list?query=asdf".http_get.value
~~~
* `Text::http_get` makes an HTTP request and blocks until the response is received. It returns `HttpRequestResult`, a subclass of `MaybeError`, with a possible error, status code and response body content. This service is implemented independently on each platform, using GDK + Curl on GNU/Linux and Apache HTTP …
> app: portable services to do requests over HTTP asynchronously

- src/semantize/auto_super_init.nit
Fix the reason that the catalog is currenlty broken (maybe ironicaly related to #1816)
> autosuperinit: do not crash on broken model

- src/frontend/no_warning.nit
- src/loader.nit
The `missing-doc` advice is now conditioned to the presence of a doc on the module.
The rationale is that if the module is documented, then the programmer does care and we show places where the documentation is missing, else the programmer does not care then we do not talk about documentation in order to not alienate him.
> frontend: `missing-doc` advice is conditioned to the presence of doc on the module

- lib/android/ui/native_ui.nit
- lib/android/ui/ui.nit
- lib/app/ui.nit
- lib/linux/ui.nit
Most features are self-explanatory, but here it is anyway. `Label` defines a simple non-editable text field. And the newly public `remove` method remove views from other views (such as `Layouts`).
Other fixes clean up the relation with the Java GC and multi-threads behavior.
> app::ui: intro Label and apply many other fixes

- lib/libevent.nit
- lib/nitcorn/README.md
- lib/nitcorn/reactor.nit
The new `prepare_respond_and_close` is an advanced alternative to `answer`. It allows mainly to delay answering to some requests. I may this to implement simple push notifications. It could also be used to do some parallel or IO intensive work, while processing other requests.
The new README should be more up to date and a better support to get to know the library. I'm not sure about including a code example, but I thought it could help. The file could still benefit from some work, but it's an improvement.
> nitcorn: intro an alternative to `answer` allowing more control and revamp the README file

- lib/core/text/string_search.nit
I wanted a way to detect and possibly remove a prefix from a string but there was no straight-forward way.
So I propose one:
~~~
var str = "hello world"
var p = str.prefix("hello")
assert p != null and p.text_after == " world"
assert str.prefix("fail") == null
~~~
Same with `suffix`
> lib/core: add Text::prefix and Text::suffix

- lib/libevent.nit
- lib/nitcorn/http_request_buffer.nit
- lib/nitcorn/reactor.nit
This PR moves the implementation of libevent callbacks from C to Nit to enable specialization and refinements of the callbacks, it should help for #1803. Also the event callback closes the connection on the Nit side on errors so servers do not attempt to write on broken connections, it should fix the current crash on http://xymus.net/ with Tnitter clients.
Also update the only user of `read_callback_native` for the new API. And seize this opportunity to rename the module, replace class refinement with specialization, clean up the doc and optimize a bit how it handle strings.
> libevent & nitcorn: close connections on error and implement callbacks in Nit

- lib/core/text/flat.nit
- lib/core/text/ropes.nit
Remove useless named init when automatic-constructor are sufficient, and remove old_style_init when named init are sufficient.
This lib cleanup is part of an ongoing cleanup of constructors, see #1800
> Clean up constructors in core/text

- lib/core/text/flat.nit
- tests/sav/nitcg/test_text_stat.res
- tests/sav/test_text_stat.res
As reported in #1838, a lot of unnecessary unboxings were done when comparing bytes in FlatString, this should be fixed by short-cutting the access to the bytes of a FlatString via `_items`.
Also while I was at it, the operation is now optimized when working on any `FlatText`
> Performance fix for comparison in FlatString

- lib/mongodb/mongodb.nit
> mongodb: pin non-native instances to avoid GC crashes

- lib/console.nit
Example:
~~~nit
import console
var pb = new TermProgress(10, 0)
for i in [1..10] do
pb.update(i)
end
~~~
Will display something like:
~~~sh
20% [==========================>                                       ]
~~~
See documentation for more info about the progress bar.
> console: add simple progress bar that refreshes itself

- lib/mongodb/mongodb.nit
- lib/mongodb/native_mongodb.nit
This PR add two more fixes since #1855 :
* use `FinalizableOnce` instead of `Finalizable`
* copy bson structs returned by `mongoc_cursor_item`
> mongo: fixes more crashes from mongodb api

- lib/github/api.nit
- lib/github/events.nit
Save event IDs so the future loader will know it will not have to process it again.
> github: save Github events ids.

- lib/mongodb/mongodb.nit
- lib/mongodb/native_mongodb.nit
> mongodb: allow client to set `skip` and `limit` when calling `find`

- lib/android/audio.nit
- lib/core/collection/array.nit
- lib/core/collection/hash_collection.nit
- lib/core/text/abstract_text.nit
- src/ffi/cpp.nit
- src/modelize/modelize_property.nit
- src/rapid_type_analysis.nit
- tests/base_prot_sig.nit
- tests/sav/base_prot_sig_alt1.res
- tests/sav/base_prot_sig_alt2.res
- tests/sav/base_prot_sig_alt3.res
- tests/sav/base_prot_sig_alt4.res
- tests/sav/base_prot_sig_alt5.res
- tests/sav/base_prot_sig_alt6.res
- tests/sav/base_prot_sig_alt7.res
- tests/sav/nituml_args3.res
- tests/sav/nituml_args4.res
Forces modelize to check that the return types of methods are legal with regard to visibility.
Also fixes some code where such issues occur.
> Modelize check visibility

- lib/nitcorn/log.nit
> Adds a module for logging requests

- lib/core/bytes.nit
- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
This PR adds some String-like functions to Bytes, along with an abstraction for Byte-based patterns.
Also, a bug was found within `Bytes::is_empty` and `FlatText` is now public since there was no real rationale to keep it private
> Stringify Bytes

- contrib/nitcc/src/autom.nit
- contrib/nitcc/src/nitcc_semantic.nit
- lib/json/json_lexer.nit
- lib/nitcc_runtime.nit
Slight improvement of the work of nitcc.
Numbers with raw parsing of a 30MB json file from nitrpg (only the AST creation, no further analysis)
Before: 0m5.700s ; 25.1 GIr
After: 0m3.540s (-38%) ; 20.3 GIr (-19%)
There is still a lot (99?) of improvements to make before having reasonable numbers, but the nitcc_runtime part ain't one.
> Perfize nitcc_runtime

- contrib/nitiwiki/Makefile
- contrib/nitiwiki/README.md
- contrib/nitiwiki/src/wiki_edit.nit
- contrib/pep8analysis/www/index.html
- lib/core/file.nit
- lib/markdown/markdown.nit
- lib/nitcorn/examples/src/xymus_net.nit
This PR contains the initial work of @ablondin and integrates it further with nitiwiki.
Intro a simple nitcorn server to publish the static files generated by nitiwiki and allow modifications from a web form. It is already applied on http://xymus.net/ to manage the main page.
The server reads the `config.ini` of the target to find the path to the public files. It writes the new markdown to the source folder and regenerates the wiki on each modification. The modification forms apply the template of the current wiki. (with some imperfections)
I've added a basic password authentication system using a list of hashed passwords in a simple text file. It should be enough for simple deployment of the server and this file can be ignored by git.
Limitations:
* Not integrated with all configuration …
> nitcorn server for nitiwiki

- contrib/crazy_moles/src/moles.nit
- contrib/tinks/src/client/client.nit
- examples/mnit_ballz/src/ballz_android.nit
- examples/mnit_ballz/src/ballz_linux.nit
- examples/mnit_dino/src/dino.nit
- lib/core/time.nit
- lib/gamnit/limit_fps.nit
- lib/mnit/mnit_fps.nit
Fixed a few bugs in `mnit::mnit_fps`, a typo invalidated the value of `current_fps` and the use of long Ints were broken probably since they are tagged. Using floats should fix this last issue.
Finally, the goal of this PR is to copy the module `mnit::mnit_fps` to `gamnit::limit_fps` and adapt it to the gamnit framework. There is some code duplication, but the mnit version should be deleted with the engine when gamnit is completed.
> gamnit: use the same code to limit fps than mnit and fix errors

- src/modelize/modelize_property.nit
Until now, implicit types for class attributes are defined by literal types or new calls. This PR extends the support to `as` casts. So when an expression setting an attribute ends with a cast such as `.as(String)`, we can safely define the type of the attribute as `String`.
~~~
class A
var s: String = data_store["s"].as(String)
var s = data_store["s"].as(String)
end
~~~
I did not modify the error messages by choice, to avoid making more complex the already long error messages with a rare use case. Also since `as` casts are unsafe by definition, I would not recommend to abuse this feature.
This does not apply to `as(not null)`.
> Use `as` casts to implicitly type class attributes

- lib/core/kernel.nit
- lib/core/math.nit
- src/compiler/abstract_compiler.nit
- tests/sav/error_class_glob.res
- tests/sav/nitce/fixme/base_gen_reassign_alt4.res
- tests/sav/nitce/fixme/base_gen_reassign_alt5.res
- tests/sav/nitce/fixme/base_gen_reassign_alt6.res
- tests/sav/nituml_args3.res
This PR re-introduces several binary operations implemented as intern to avoid indirection through FFI in some specific cases to improve performance notably in `core/text/native`
Also a style change for `abs` which could easily be inlined and burned by eyes when I saw it, I can remove the commit if someone objects to the modification
> Inline binops

- misc/jenkins/check_contrib.sh
src/Makefile is already executed at the begin of the tests, so a double execution is mostly useless and time-expensive.
> check_contrib: filter-out contrib/nitc when checking Makefile of projects

- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/interpreter/naive_interpreter.nit
While working on new constructors #1800, it appeared that the compilation of signatures with more than one vararg was broken.
The current engines never compile execute such a signature; signatures with multiple varargs only exists in the model to validate the arguments of the `new` syntax. The bug cannot be exhibited (so no specific tests).
Most of the changes are the same pattern: ask each parameter if it is a vararg instead of waiting a specific one.
> engine: handle the compilation/interpretation of multiple varargs

- share/man/nitweb.md
- src/doc/html_templates/html_model.nit
- src/model/model_collect.nit
- src/modelize/modelize.nit
- src/nitweb.nit
- src/web/model_html.nit
- src/web/web.nit
- src/web/web_actions.nit
- src/web/web_base.nit
- src/web/web_views.nit
- tests/sav/nitweb.res
Description from man page:
nitweb - provide a web API to nit model and source code.
nitweb [*options*] FILE...
`nitweb` use `nitcorn` actions to provide an API to loaded model and source code.
Usage:
~~~sh
nitweb --host localhost --port 3000 lib/core/
~~~
Show the home page of the webserver.
Display all the loaded model entities in a tree.
Search all model entities matching `namespace`.
It is possible to retrieve the result as a JsonArray instead of raw html
using the uri param `json=true` (default `false`).
Display the source code of the entity matching `namespace`.
Display a short documentation page about the entity matching `namespace`.
Display a random list of entities found in the model.
The list is parametrable with the following uri params:
* `n=10` size of the list (default `10`) …
> nitweb: nitcorn based API to access model and source code

- lib/core/collection/abstract_collection.nit
- lib/core/collection/array.nit
- tests/sav/test_new_native_alt1.res
Since there is no reason to forbid it (or I have not seen one at the very least), here's a simple `clone` method that should work on any `Set`
> Make all Sets cloneable

- src/testing/testing_suite.nit
- tests/nitunit.args
- tests/sav/nitunit_args9.res
- tests/test_nitunit4/nitunit4.nit
- tests/test_nitunit4/test_nitunit4.nit
- tests/test_nitunit4/test_nitunit4_base.nit
The specification of `nitunit` states that before and after methods can be called to initialize or clean test related things:
~~~nit
module my_test_suite
class MyTestSuite
super TestSuite
redef fun before_test do
end
redef fun after_test do
end
fun test_foo do end
fun test_bar do end
end
~~~
In the above example, `nitunit` will call the methods precisely in this order:
~~~nit
test_before
test_foo
test_after
test_before
test_bar
test_after
~~~
Before this PR, the before and after methods were only call if a redefinition of the before/after method exists locally in the test suite. Inheritance was not considered:
~~~nit
module my_test_suite
class TestBase
super TestSuite
redef fun before_test do # ...
redef fun after_test do # ...
end
class MyTestSuite
super TestBase
fun test_foo do end
fun …
> niunit: fix after/before test calls

- src/astbuilder.nit
- src/frontend/parallelization_phase.nit
- src/frontend/serialization_phase.nit
- src/modelbuilder_base.nit
- src/modelize/modelize_class.nit
- src/modelize/modelize_property.nit
- src/parser/nit.sablecc3xx
- src/parser/parser.nit
- src/parser/parser_abs.nit
- src/parser/parser_nodes.nit
- src/parser/parser_prod.nit
- src/parser/tables_nit.c
- src/pretty.nit
- tests/sav/nitlight_args1.res
- tests/sav/nitmetrics_args1.res
- tests/sav/test_highlight_args1.res
- tests/sav/test_parser_args1.res
- tests/sav/test_parser_args6.res
Extends the parsed and the AST to handle qualified class identifiers.
Now you can parse
~~~nit
redef class m0::A
super m1::S
redef type m2::B::T: Int
fun foo: m3::G[m4::C] do end
end
~~~
Currently, the class qualifiers, if any, are just ignored by semantic phases. Like with method qualifiers.
> Qualified class identifiers

- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/nitni/nitni_base.nit
- tests/sav/niti/fixme/test_intern_extern.res
- tests/sav/test_intern_extern.res
- tests/test_intern_extern.nit
Improve the handling of alternative of intern methods since an extern body can be used as a fallback.
~~~
redef class Int
fun foo is intern `{ return foo(self) `}
end
~~~
Moreover, NativeArray intern alternatives is now fixed with nitc.
There is still an issue with the extern methods of NativeArray in the interpreter.
> Alternative intern

- .gitmodules
- benchmarks/json/Makefile
- benchmarks/json/bench_json.sh
- benchmarks/json/inputs/multiply_gov.sh
- benchmarks/json/inputs/multiply_twitter.sh
- benchmarks/json/scripts/c_parser.c
- benchmarks/json/scripts/json_ext.rb
- benchmarks/json/scripts/json_parse.go
- benchmarks/json/scripts/json_pure.rb
- benchmarks/json/scripts/nit_adhoc_utf_noropes.nit
- benchmarks/json/scripts/nit_adhoc_utf_ropes.nit
- benchmarks/json/scripts/nitcc_parser.nit
- benchmarks/json/scripts/python.py
Added a JSON parser benchmark between different languages and Nit using 3 variants:
* Nit/NitCC: The old parser relying on NitCC, which is slow and memory-consuming (more than 6 Gio RAM for the 100Mio escaping-intensive file)
* Nit/Ad-hoc UTF-8 no ropes: The new parser working exclusively on `FlatString`
* Nit/Ad-hoc UTF-8 with ropes: The new parser with a mix of `Concat` and `FlatString` 
I hear you all clamouring, well, here are the results (after #1885 and #1887, naturally):
So yeah, I guess we could do better when it comes to escaping since the biggest difference in runtime is in the `large_escape` benchmark which coincidentally contains mostly `\uXXXX` characters.
Other than that, we do as well as Go and better than Ruby (also worse than Python, but this does not count), which is …
> Json benchmark

- contrib/pep8analysis/src/model/operands.nit
- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- lib/json/static.nit
As said in #1895, we need faster parsing of UTF-16 escaping sequences, this PR is the answer.
It makes the runtime of the `large_escaped` benchmark go down from ~5s to ~3.5s, and with valgrind, from 26GIr to 20GIr
Note: based on #1886, only the 4 last commits are of interest here
> Faster hex parsing

- lib/core/bytes.nit
- lib/core/file.nit
- lib/core/re.nit
- lib/core/stream.nit
- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- lib/core/text/native.nit
- lib/core/text/ropes.nit
- lib/text_stat.nit
- src/compiler/abstract_compiler.nit
- src/interpreter/naive_interpreter.nit
- tests/sav/nitcg/test_text_stat.res
- tests/sav/test_text_stat.res
This stack of commits is a batch of brand-new optimisations on `String`, especially regarding the manipulation of UTF-8 characters.
As a baseline, last Tuesday @privat tried the JSON parser on a 30MiB json file, the execution took approximately 10 seconds for ~38 GIr with Valgrind, now and with his Nitcc upgrades, the total runtime is less than 2 seconds for ~11 GIr with Valgrind.
> String block optimisations

- lib/nitcorn/examples/src/nitcorn_hello_world.nit
- lib/nitcorn/examples/src/nitcorn_reverse_proxy.nit
- lib/nitcorn/examples/src/restful_annot.nit
- lib/nitcorn/reactor.nit
Until now, each nitcorn example checked if it was being tested, and if so it would quit to not block jenkins. This PR moves this check in the nitcorn module so it is the default behavior.
This should help for #1915 and future nitcorn programs.
> nitcorn: skip the listening loop when running the tests

- lib/android/android.nit
- lib/android/assets.nit
- lib/android/assets_and_resources.nit
- lib/android/ui/ui.nit
- lib/app/app.nit
- lib/app/assets.nit
- lib/core/collection/hash_collection.nit
- lib/gamnit/model_parsers/model_parser_base.nit
- lib/gamnit/model_parsers/mtl.nit
- lib/gamnit/model_parsers/obj.nit
- lib/java/io.nit
- lib/linux/linux.nit
- lib/mnit/assets.nit
- lib/parser_base.nit
Intro parsers to load 3D models from the ASCII based format of .obj and .mtl files. Also as support intro a new kind of asset, `app::TextAsset`, with lazy loading in the style of `Sound` and `Texture`.
Model parsing services will be used by the 3D API of gamnit to load 3D models generated by modeler tools like Blender.
The services in `gamnit::model_parsers` are independent of gamnit. However since they are game related, it is a nice package to classify them in. They still can be used by any other 3D graphics engine, as `gamnit::network` which is also independent but game oriented. This adds a small duplication in their representation because a model is stored differently once loaded in gamnit. But the format in gamnit is so low-level (only arrays of Float) that we need an intermediate …
> Intro parsers to load 3D models from .obj and .mtl files

- lib/gamnit/keys.nit
This simple service can be incredibly useful in games where a key held down causes an event at each frame, like walking forward by pressing `w`.
I use this in the 3D version of Tinks! Which should be ready for a PR in a near future.
> gamnit keys: simple service to keep track of pressed keys

- lib/core/collection/abstract_collection.nit
Proposed because https://github.com/nitlang/nit/pull/1920/files#diff-c6e41a937b2b8ba5e5e04bd8f49260f7R104
I'm not sure of the name `modulo`.
> lib/core: add Sequence::modulo to access with a Python-wrap semantic

- lib/nitcorn/examples/src/htcpcp_server.nit
An attempt at: https://github.com/nitlang/nit/issues/1808, a fun little example.
As a first step I haven't implemented additions, and gave as best implementation of the protocol as I could interpret it.
It's mostly based on the `file_server.nit` file. If you want to test it locally a good way is to use `curl -X <METHOD> localhost:8080`
@xymus @Bl4ckb0ne @R4PaSs
> Implemented a htcpcp server

- contrib/tinks/Makefile
This PR fix the broken Android makefile rules of Tinks!, reported by @privat.
The duplicated calls to nitserial should be temporary until we find a cleaner way to manage it.
> Fix makefile of Tinks!

- tests/tests.sh
Improve the resilience of the tests.sh script if java is not found or if ulimit is limited
> Harden tests script

- src/Makefile
Inject automatically call to peflags on the 2 first steps of the bootstrap.
Other executables (those in bin/ and those compiled by the user) are not peflaged since it does not seems that useful in general.
> src/Makefile: use peflags to bootstrap on windows

- contrib/inkscape_tools/src/svg_to_png_and_nit.nit
- lib/gamnit/depth/depth.nit
- lib/gamnit/depth/particles.nit
- lib/gamnit/flat.nit
Intro a few new features:
* `Sprite::tint` to tint the color of a sprite.
* `Sprite::invert_x` to draw a sprite with the X axis inverted.
* `App::static_program` a particle program to display simple static and long lived particles. Can be useful to display clouds.
Fix a few bugs:
* `svg_to_png_and_nit` generated invalid code for array of textures when the target was gamnit.
* `App::clock` was instantiated with `app`, this caused the first `dt` of `App::update` to be much larger than expected.
* Divide `frame_core_flat` in 2 to allow the depth framework to draw particles after the world sprites but before the UI sprites.
> gamnit: intro static particles, Sprite tint & invert_x,  and fix a few bugs

- lib/core/collection/array.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
This is a simple patch but it needed the regen of `c_src` for boostrap reason
> compiler: add a native implementation of NativeArray::memmove

- contrib/tnitter/Makefile
- lib/app/http_request.nit
- lib/cocoa/foundation.nit
- lib/ios/http_request.nit
- lib/ios/ui/ui.nit
- lib/ios/ui/uikit.nit
- lib/pthreads/pthreads.nit
- src/platform/xcode_templates.nit
This PR completes the implementation app::UI for iOS by implementing `ListLayout` using a `UITableView`. It also introduces the implementation of `http_request` using services from the foundation framework. 
These features enable the Tnitter portable application to be compiled for iOS without modification.
The remaining API of app.nit still missing on IOS are `data_store`, `audio` and maybe `assets`.  At this point, only `data_store` is required for fully featured portable applications using the native UI.
---
As with #1942, some generated code has been commented so it can be reactivated when useful and when the needed types are also wrapped.
> Intro support for async HTTP requests and ListLayout for iOS

- lib/android/README.md
- share/libgc/android-setup-libgc.sh
Update the doc of the Android package with better instructions on how to configure the host system before compiling Nit applications for Android. Also fix the libgc build script to support the latest NDKs.
@privat The change to the script may require to install the latest NDK on the test server. Current users of the Android compilation should not have to do anything, only new installations should require to also install the latest NDK.
> Android support: better doc and libgc compilation service support latest NDK

- lib/app/data_store.nit
- lib/binary/serialization.nit
- lib/cocoa/foundation.nit
- lib/ios/app.nit
- lib/ios/data_store.nit
- lib/ios/ui/ui.nit
- lib/json/serialization.nit
- lib/serialization/serialization.nit
Implement the main missing features of _app.nit_ on iOS: `data_store` and life-cycle hooks (like `on_save_state`). These changes can be seen on the calculator app, as it preserves its context using the `data_store`.
`data_store` is implemented with `NSUserDefaults` to store objects sertialized to Json. It is very similar to Android's implementation using shared preferences. This may be a bit limited as it is not meant to hold large strings, and some data objects (like game saves) should instead be saved to a file.
This PR also implements all life-cycle callbacks in iOS, until now only `on_create` was implemented. We may have to update _app.nit_ life-cycle to fit better with the life-cycle of iOS, the states between a running app and a fully stopped app are different between iOS and …
> iOS: implement data_store and missing life cycle callbacks

- lib/nitcorn/examples/src/nitcorn_reverse_proxy.nit
- lib/nitcorn/file_server.nit
- lib/nitcorn/nitcorn.nit
This PR extends `FileServer` with caching of served files and custom JavaScript code for the header. The caching is set to 1h by default, but it can be customized.
Removing the default import of the `proxy` module with nitcorn, it depends on curl, and thus adds a (small) overhead to all nitcorn programs and need the library. This could be reverted when `proxy` is updated to use only libevent.
> nitcorn: cache served files, custom JS for FileServer and do not depend on curl

- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- src/frontend/i18n_phase.nit
Change the behavior of `Text::format` so it uses an index from 0 (instead of 1), and the escape sequence to a double percentage sign (ex, `%%4` to get `%4`). Also, now `format` ignores `%` that are not followed by a number.
There were problems with the previous escape sequence (using `\%`):
1. In literal strings, the `\` itself has to be escaped, so a whole escaped sequence look like `\\%4`.
2. The extra `\\` were not removed from the resulting string, so it was still impossible to produce a `%4` because `\\%4` resulted in `\\%4`.
These changes were prompted by an error in the code generated the i18n phase on a lone `%` not related to the `format` method. Also, the index beginning at 1 were always confusing to me, it was a different behavior than `Array` and other 
@R4PaSs I would like …
> Revamp `Text::format`

- lib/core/math.nit
- lib/geometry/polygon.nit
Fix reversed axes in `atan2`, but since it is actually just a change in the name of the variables (and doc) it should not break the clients.
Also sorting points of a polygon in `triangulate` completely invalidated some complex polygons.
> Minor fix to atan2 and triangulate

- lib/sdl.nit
This was first a temporary fix for #1941 to repair Nit games on the deskop. But it is also a nice cleanup, it brings to Nit the instantiation and the implicit cast to a more general and nullable type. The casts themselves were not very pretty using FFI callbacks.
> lib/sdl: workaround to avoid constructor callback bug

- lib/core/collection/list.nit
This bug lead to segmentation faults when iterating over the items of a list after a call to `clear`.
> core/list: fix `List::clear` so it resets `length` to 0

- benchmarks/markdown/engines/nitmd/nitmd.nit
- lib/markdown/markdown.nit
- lib/markdown/test_markdown.nit
Using benchmarks/markdown:
* nitmd_master is before
* nitmd_md is this now
* nitmd_md_fast is with #1973 in addition
* the 3 same avain with with --semi-global
* 2 Java libs: txtmark, markdown4j
There is still a lot of performance improvements to do anyway.
> lib/markdown: improve performance a bit

- lib/core/text/flat.nit
- tests/sav/nitcg/test_text_stat.res
- tests/sav/test_text_stat.res
Try to improve the efficiency of the FlatText[] method by shortcuting some common and easy cases.
using benchmarks/json:
Ping @R4PaSs for review
> Faster text get

- lib/core/file.nit
- src/interpreter/dynamic_loading_ffi/on_demand_compiler.nit
Generate native files in the `/tmp/` directory and delete them after execution. The directory can be customized using `--compile-dir`.
This should fix #1974 and #1975.
To support some other OS, we will need to use something other than `getpid` and `/tmp/`. We could also improve upon this by reusing the generated libraries between executions.
> Interpreter FFI: custom compile_dir, use /tmp/ by default, and delete after execution

- lib/android/ui/ui.nit
- lib/app/ui.nit
- lib/ios/ui/ui.nit
- lib/ios/ui/uikit.nit
- lib/linux/ui.nit
The attribute `TextField::is_password` toggles hiding the content of the field using platform specific services. So on Android, not only is the text hidden but it also notifies the soft keyboard to behave accordingly.
In the future, we could add alternative modes for email entry and more.
> app.nit UI: Intro an attribute to toggle password entry on TextFields

- lib/android/assets_and_resources.nit
- lib/android/dalvik.nit
- lib/android/http_request.nit
- lib/android/intent/intent_api10.nit
- lib/android/notification/notification.nit
- lib/android/service/NitBroadcastReceiver.java
- lib/android/service/NitService.java
- lib/android/service/at_boot.nit
- lib/android/service/service.nit
- lib/android/shared_preferences/shared_preferences_api10.nit
- lib/android/toast.nit
- lib/android/vibration.nit
Add support to create Android services in Nit, working alongside activities implemented in Nit. The service can be launched on demande or at the device boot. Only one Nit service at a time can run per package. However the same service can be started more than once and you can do pretty much anything on the Nit side since it shares the same process as the activities.
Uses a broadcast receiver to launch service at boot. This receiver could be used to catch other broadcast, but it currently does not preserve the original intent.
Also updates most Android related modules to use `native_context` instead of `native_activity` so they can be called from services, when the Android API allows it. Some services had to be modified sightly, like the default `SharedPreferences` which is now named …
> Android service support: reliably run Nit code in the background

- contrib/tnitter/src/tnitter_app.nit
- lib/app/http_request.nit
Move up the delay service from Tnitter to AsyncHttpRequest. It can be useful for other apps, for regular polling or to avoid to overwhelm the server on errors.
> http_request: intro an attribute to delay sending the request

- contrib/jwrapper/examples/android_api/Makefile
- lib/android/wifi.nit
Intro a simple wrapper for Android WiFi services. It allows to list WiFi networks in range, and could be extended with more features in the future. 
It was partially generated by jwrapper (with the included command) and completed by hand. As usual with generated wrapper, the client of the library should refer to the corresponding Java/Android documentation to know more about these services.
> lib/android: intro WiFi services wrapper

- lib/serialization/README.md
- lib/serialization/serialization.nit
- src/frontend/serialization_phase.nit
- tests/sav/nitce/test_json_deserialization_alt1.res
- tests/sav/test_json_deserialization.res
- tests/sav/test_json_deserialization_alt1.res
- tests/sav/test_json_deserialization_alt2.res
- tests/test_deserialization.nit
By default, an attribute is identified in the serialization format by its Nit name. The `serialize_as` attribute changes this behavior and sets the name of an attribute in the serialization format. It works with both the JSON and the binary implementations.
This annotation can be useful to change the name of an attribute to what is expected by a remote service. Or to use identifiers in the serialization format that are reserved keywords in Nit (like `class` and `type`).
> serialization: new annotation to rename an attribute in the serialization format

- misc/vim/plugin/nit.vim
- src/modelize/modelize_property.nit
Do no show missing-doc warnings on anonymous `new` factories. These factories usually replace de default init and as such are documented with the class.
The Nit omnifunc is used to complete words in vim, it popups up when pressing Ctrl-X Ctrl-O. The default behavior was to show the doc of the highlighted suggestion in the preview window. This was not appreciated by some, and it was unneeded since the popup menu already shows the synopsis.
This can still be customized by the user by setting the `completeopt` global variable. And as before, the doc can be shown in the preview window by calling `:Nitdoc` with the cursor over the string to search for.
> frontend & vim plugin: no doc warnings on `new` factories and no doc preview with omnifunc

- contrib/tnitter/src/action.nit
- lib/libevent.nit
- lib/nitcorn/examples/src/xymus_net.nit
- lib/nitcorn/http_response.nit
- lib/nitcorn/log.nit
- lib/nitcorn/reactor.nit
- lib/nitcorn/sessions.nit
Better services to debug nitcorn servers and understand users behavior:
* Improve `nitcorn::log` with an uniform print format and the remote IP address.
* Alow custom JavaScript code in Tnitter which is used to insert Google Analytics code in xymus.net.
> nitcorn & xymus.net: better log and tracking

- lib/android/ui/native_ui.nit
- lib/android/ui/ui.nit
- lib/app/ui.nit
- lib/gtk/v3_4/gtk_widgets_ext.nit
- lib/ios/ui/ui.nit
- lib/ios/ui/uikit.nit
- lib/linux/ui.nit
The check box control varies per platform. For app.nit, we chose to implement it as a form available on Android and GNU/Linux with GTK+, the classic check box with a label.
On GNU/Linux there is the GTK+ check box widget which is used as is. On Android, there is two similar controls, the toggle (for On/Off, like in the preferences window) and the check button (which is more similar to the GTK check box). We used the check button for consistency, but it could be changed in the future. On iOS, there is only the UISwitch, an on/off button, without a label. The app.nit CheckBox is implemented by a layout composed of the UISwitch and a label.
> app.nit UI: intro the CheckBox and implementation on Android, iOS & GNU/Linux

- lib/android/http_request.nit
- lib/android/service/service.nit
- lib/android/ui/native_ui.nit
- lib/android/ui/ui.nit
This PR intro support for Andorid apps composed of multiple windows. There is now one fragment par app.nit window, and it is set as visible when assigned to `app.window=`.
Support for multi-windows apps on other platforms will be provided by future PRs, along with a portable API for the back button and to navigate between windows. This system, on Android at least, could probably be extended to show more that one window at a time on larger tablet devices.
> app.nit on Android: implement multiple windows support with fragments

- lib/gtk/v3_4/gtk_core.nit
- lib/gtk/v3_4/gtk_widgets_ext.nit
- lib/linux/ui.nit
This PR implement support for mobile-like multiple windows on GNU/Linux with GTK. It uses a single GTK window and a GtkStack showing one app.nit window at a time. This results in a single window with changing content.
The change to ListView provides a scrollable list of items, which is closer to the mobile equivalent.
Support for a back button will be introduced in a future PR.
> app.nit on GNU/Linux: implement  multiple windows support using a GtkStack

- lib/core/time.nit
- tests/sav/niti/fixme/nitiwiki_args2.res
now you can run nitiwiki with the interpreter
> lib/core/time: use lightffi for asctime, so niti can run it

- lib/core/text/abstract_text.nit
- lib/performance_analysis.nit
This PR introduces padding services ( `pad_left` and `pad_right`) to `Text` and uses it for a cleaner print in `performance_analysis`.
Seeing how the left-pad package was critical to the node.js ecosystem motivated this PR. These methods should be useful in the long term!
> Improve `Text::justify` and use it for a pretty `PerfMap::to_s`

- src/compiler/abstract_compiler.nit
- src/frontend/glsl_validation.nit
- src/frontend/i18n_phase.nit
- src/frontend/regex_phase.nit
- src/interpreter/naive_interpreter.nit
- src/literal.nit
- src/modelize/modelize_property.nit
- src/rapid_type_analysis.nit
- src/semantize/typing.nit
- tests/sav/test_augmented.res
- tests/sav/test_augmented_alt1.res
- tests/test_augmented.nit
As a follow-up to #1991, here's the support mentioned in #1734 for bytestrings, regex and raw strings
NOTE: Depends on #1991 for integration, you may review the last 3 commits while #1991 is reviewed and eventually merged
TODO: Support degraded mode (Bytes and Byte only) for byte SuperStrings instead of refusing at compile-time
> Augmented literal strings

- src/interpreter/naive_interpreter.nit
This PR fix `rand` with the interpreter so setting a seed with `srand_from` produces predictable results in the following calls to `rand`, and the same results as the same compiled program. The problem was caused by the interception of `rand` which was executed in the interpreter itself, while `srand_from` was executed on the side of the interpreted program. So setting the seed did not affect in anyway the values returned by `rand`.
> interpreter: fix rand by leaving rand methods to the FFI

- lib/core/bytes.nit
Improve and some back-and-forth transformations between Byte and Text.
~~~nit
var b = "abcd".to_bytes
assert b.chexdigest == "\\x61\\x62\\x63\\x64"
assert b.chexdigest.unescape_to_bytes == b
assert b.binarydigest == "01100001011000100110001101100100"
assert b.binarydigest.binarydigest_to_bytes == b
assert "1".binarydigest_to_bytes.hexdigest == "01"
assert "1 0 1".binarydigest_to_bytes.hexdigest == "05"
assert "7".hexdigest_to_bytes.hexdigest == "07"
assert "a B cd \\xe".hexdigest_to_bytes.hexdigest == "0ABCDE"
~~~
> More byte digests

- contrib/tnitter/src/tnitter_app.nit
- lib/app/ui.nit
- lib/gtk/v3_10.nit
- lib/linux/ui.nit
Update GNU/Linux implementation of `ListLayout` to follow the specification of `GtkListBox` which should only have children of type `GtkListBoxRow`. This was an issue in Tnitter where removing children from the `GtkListBox` was broken.
> Tnitter app: fix list layout on GNU/Linux with GTK+

- contrib/benitlux/src/benitlux_db.nit
- contrib/benitlux/src/benitlux_social.nit
- lib/core/collection/array.nit
- lib/sqlite3/sqlite3.nit
- tests/sav/test_new_native_alt1.res
Fix statements that were left open and did not remove the lock on the database. It now relies on iterators to close the statement after the end of the loop. This requires to actually complete the loop and not return before it is complete. A shortcut is to use `statement.iterator.to_a` when the result is expected to be short, like with a single row.
Note that I did not use `with` because it has the same problem with a `return` skipping the call to `finish`. Neither did I use `Finalizable` because it is invoked by the GC which may be much later.
Also fix one malformed superstring and improve the style of another one.
> Benitlux & sqlite3: fix closing SQLite statements and malformed superstring

- lib/android/ui/ui.nit
- lib/app/ui.nit
- lib/gtk/v3_4/gtk_core.nit
- lib/ios/ui/ui.nit
- lib/linux/ui.nit
Intro services to customize the size and alignment of text views. Only labels are supported on all platforms but Android also supports customizing text buttons. The behaviour on each platform varies a bit according to the available features. The goal is always to have the behaviour that is more natural on the platform instead of having the same exact look on each platform. Sticking to the recommended values should produce more consistent results, but using other values can create interesting effects.
For example, on Android and Linux, the text size is locked to a small/medium/large, but on iOS the size can be set to any variations relative to the default font size. On all platforms, 0.5 should result in a small font, 1.0 the default/medium size and 1.5 the large size. On iOS, other values …
> app.nit services to set the size and alignment of labels

- lib/ios/ui/ui.nit
- lib/ios/ui/uikit.nit
- src/platform/xcode_templates.nit
Support multiple windows on iOS by using a UINavigationController as the root controller which shows the navigation bar at the top of the screen. The navigation bar shows the "Back" button automatically when switching windows. It has room for a title, which can be set manually. This is not ideal as pure portable apps don't define a title leaving the bar mostly empty. This could be fixed either by always asking for a title or by using the app names a default title.
Rewrite the implementation of the ListLayout using a UIStackView in a UIScrollView. This implementation is easier to adapt to different content, and it much more simple than the previous one which used a UITableView. The table view implementation has been kept as a different iOS specific control, but it may be removed in the …
> iOS: support apps with multiple windows, and a better ListLayout

- src/frontend/check_annotation.nit
- src/interpreter/dynamic_loading_ffi/dynamic_loading_ffi.nit
- src/interpreter/dynamic_loading_ffi/on_demand_compiler.nit
- tests/nit.args
- tests/sav/nit_args7.res
- tests/sav/test_ffi_c_interpreter.res
- tests/test_ffi_c_interpreter.nit
Let's start with a bit of context, the interpreter supports only the light FFI, a subset of the full FFI supported by the compiler. The interpreter uses an heuristic to guess which extern methods are supported. The problem of #2018, was in this heuristic. The heuristic states that if a parameter of an extern method is a standard Nit class and not an universal or an extern class, then that method probably uses the full FFI. However, sometimes this is false, like in the interpreter where instances of Nit standard classes are stored as pointer in the C code, still without using the full FFI.
To fix #2018, this PR intro a new annotation `light_ffi` to be used on extern methods wrongly detected as full FFI. It bypasses the heuristic and force the interpreter to compile and run the method. (or …
> Interpreter FFI: fix running the interpreter FFI in the interpreter

- lib/cocoa/foundation.nit
- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
This PR fix the support for UTF-8 on iOS by simply updating the encoding and use the correct number of bytes. This does not completely resolve #1945 as the error messages are still present and I suspect that the UTF-8 cleaning does not work, however I'll update the issue (or open a different one) to reflect that.
Intro the service `to_s_with_copy_and_length` which complements `to_s_with_copy` and `to_s_with_length` . The name is a mouthful, but using optional parameters was not desirable since this service will often be used from a foreign language.
Also improves the doc of the existing services to get a Nit `String` from a `NativeString`. The new doc is more detailed and oriented towards users of the FFI by putting emphasis on where the raw data resides and wether it is cleaned or not. …
> iOS and text: fix UTF-8 support on iOS and improve doc on FFI related text services

- lib/core/fixed_ints.nit
- lib/opts.nit
- tests/sav/test_opts_args5.res
Fix #2019, `is_int` was always returning true. It was caused by the use of the wrong local variable.
Ping @R4PaSs and @Freddrickk.
> lib/core: fix `Text::is_int`

- lib/nitcorn/reactor.nit
- lib/nitcorn/vararg_routes.nit
Routes with parameters like `/blog/articles/:articleId` where not matched correctly.
It worked until today and I'm not really sure how? Anyway, this PR resolve the route with request parameters before performing the match.
Also done some cleaning in warnings and doc.
> nitcorn: fix path resolution for vararg routes

- lib/poset.nit
Extends the POSet class with some useful methods to compare and (partially) copy posets.
> Poset: add clone, ==, hash and sub

- lib/json/serialization.nit
- tests/sav/nitce/test_json_deserialization_alt1.res
- tests/sav/nitce/test_json_deserialization_alt3.res
- tests/sav/nitce/test_serialization.res
- tests/sav/nitce/test_serialization_alt2.res
- tests/sav/nitce/test_serialization_alt3.res
- tests/sav/nitce/test_serialization_alt4.res
- tests/sav/nitce/test_serialization_alt5.res
- tests/sav/nitce/test_serialization_redef.res
- tests/sav/nitce/test_serialization_redef_alt0.res
- tests/sav/nitce/test_serialization_redef_alt1.res
- tests/sav/nitce/test_serialization_redef_alt2.res
- tests/sav/test_json_deserialization.res
- tests/sav/test_json_deserialization_alt1.res
- tests/sav/test_json_deserialization_alt2.res
- tests/sav/test_json_deserialization_alt3.res
- tests/sav/test_json_deserialization_alt4.res
- tests/sav/test_serialization.res
- tests/sav/test_serialization_alt1.res
- tests/sav/test_serialization_alt2.res
- tests/sav/test_serialization_alt3.res
- tests/sav/test_serialization_alt4.res
- tests/sav/test_serialization_alt5.res
- tests/sav/test_serialization_redef.res
- tests/sav/test_serialization_redef_alt0.res
- tests/sav/test_serialization_redef_alt1.res
- tests/sav/test_serialization_redef_alt2.res
- tests/test_json_deserialization.nit
Intro an option in `JsonSerializer` to write pretty indented JSON. By default, the generated JSON is somewhat minified, this could be improved if needed.
See the generated JSON in the tests below. I chose to leave the metadata and other special short objects non-indented as they are not intended for humans. The option `plain_json` is fully compatible with `pretty_json` (see alt4.res), I expect them to be used together often.
This was requested by @Morriar and it could allow us to deprecate the `json::static` writer API.
> JSON serialization: write pretty JSON

- contrib/refund/tests/res/recl_soin_error2.res
- lib/core/text/flat.nit
- lib/core/text/ropes.nit
- lib/json/serialization.nit
- lib/text_stat.nit
- tests/sav/base_class_name.res
- tests/sav/nitce/base_class_name.res
- tests/sav/nitce/test_meta.res
- tests/sav/test_augmented.res
- tests/sav/test_deriving.res
- tests/sav/test_deriving_alt1.res
- tests/sav/test_deriving_alt2.res
- tests/sav/test_deriving_alt3.res
- tests/sav/test_deriving_alt4.res
- tests/sav/test_json_deserialization_plain.res
- tests/sav/test_meta.res
- tests/sav/test_text_stat.res
This simple PR re-introduces the concept of ASCII strings for faster no-overhead accesses to random characters in a string.
The class is private as it is to be used only internally, no client should care for the specific type of a String and all performance improvements will be automatic, should the optimization be possible.
Since we are dealing with UTF-8, the only case where O(1) access can efficiently and without much overhead (one `if` statement at creation) be determined, is when a string only contains ASCII characters.
Note that since the Buffer can change access semantics depending on what is appended during its lifetime, no ASCII-only FlatBuffer has been added.
This is implemented here by introducing two subclasses of FlatString, one for ASCII only strings, and one for regular …
> Faster ASCII-only strings

- lib/core/file.nit
- src/doc/doc_down.nit
- src/nitcatalog.nit
- tests/nitcatalog.args
- tests/sav/nit_args6.res
- tests/sav/nitcatalog_args1.res
- tests/sav/test_sort_perf_args1.res
- tests/test_prog/README.md
- tests/test_prog/package.ini
nitcatalog is extended to detect links to local images, copy the resource in the catalog directory and hijack the generated link.
This should fix #2042 and fix the images in http://nitlanguage.org/catalog/p/tinks.html
Most is done by monkey-patching (aka dirty refinement) since the doc_down model uses an internal private global markdown decorator. I'm not sure what should be the best approach here, and I had to improvise since @Morriar is MIA.
Bonus:
* `file_copy_to` is fixed and do not corrupt binary files (thanks @R4PaSs)
* `tests/test_prog` is used to test the catalog
> nitcatalog: handle local images

- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- lib/json/static.nit
- lib/json/string_parser.nit
This PR improves the speed of JSON parsing with the `string_parser` module. The new version of `parse_json_string` is heavily inspired by Python's implementation, available [here](https://github.com/python/cpython/blob/master/Modules/_json.c)
Time is usually either as performing as before or better, Valgrind also gives the new version an advantage, sometimes significant.
On `large_escaped` (~120M, lots of escaped characters), we have: 
* Before: 13 748 436 458 Ir
* After: 11 687 104 643 Ir
i.e. an improvement of ~18%
Time is:
* Before: 0m4.428s
* After: 0m3.932s
i.e. an improvement of ~13%
Note that on this particular test, although the number of allocations is limited as much as we can, Boehm still cannibalizes the runtime, seeing that the real time is ~2.6s.
Perf gives a total time of …
> JSON Parser Optimization

- .gitignore
The .DS_Store file is automatically generated by the Mac OS filesystem to keep metainformation about that directory. This files is unnecessary to the project so should be excluded in the .gitignore
@privat
> Update gitignore to exclude DS_Store

- lib/base64.nit
This allows to read directly ascii-armored blocks.
close #2069
> lib/base64: Support line breaks in base64 strings.

- src/loader.nit
- src/location.nit
- src/model/mmodule.nit
- src/model/model.nit
- src/model/model_base.nit
- src/model/mpackage.nit
- src/modelize/modelize_class.nit
- src/modelize/modelize_property.nit
- src/neo.nit
- src/semantize/typing.nit
- src/test_model_visitor.nit
- tests/sav/test_model_visitor_args1.res
- tests/sav/test_model_visitor_args2.res
For some unknown historical reasons, the location was only provided to some specific model entities. By extending it to all entities, this simplify clients that need to process, visit or filter entities.
Location is not nullable for all entities. This is simpler but need some place-holder object for fictive location. ie some location objects that mean "no location".
> Promote location in MEntity

- misc/docker/Dockerfile
The image is based on Debian stable (jessie) with a lot of packages.
I'm not sure what is the point of such images for the end-users.
My objective was just to test a Nit installation on a fresh, full & reproductible base.
Image will be available in the docker hub: https://hub.docker.com/r/nitlang/nit/
The only tests that fails are:
* ballz_android dino_android shoot_android ui_test test_platform_android: no android
* emscripten_nodejs: no emstripten
* test_neo_args1 test_neo4j test_neo4j_batch: no neo4j
* mpi_simple: bizarre error messages
* simple_file_server: the user is root so 80 can be opened :/
* test_glsl_validation: not installed
nitunit need also to be run
> Add a Dockerfile to build a full image of a Nit install

- benchmarks/csv/README.md
- benchmarks/csv/csv_bench.sh
- benchmarks/csv/scripts/JavaCSV.java
- benchmarks/csv/scripts/csv_gen.nit
- benchmarks/csv/scripts/go_csv.go
- benchmarks/csv/scripts/nit_csv.nit
- benchmarks/csv/scripts/python_csv.py
- benchmarks/csv/scripts/python_stdcsv.py
- benchmarks/csv/scripts/ruby_csv.rb
This PR introduces a new benchmark script for CSV parsers.
Are tested here:
* Nit CSV Ad-hoc parser
* Go standard parser
* Java Apache Commons CSV parser
* Python - Pandas
* Python - Standard
* Ruby - Standard
Will upload some measurements later but *spoiler alert* Python - Pandas is the fastest on large files, Ruby is the slowest by far, Java is the second slower with a big margin from the rest.
Go/Nit/Python-Standard are almost equivalent.
> CSV Benchmarks

- contrib/benitlux/src/benitlux_controller.nit
- contrib/tinks/src/client/linux_client.nit
- contrib/tnitter/src/action.nit
- contrib/tnitter/src/push.nit
- lib/json/serialization.nit
- lib/json/static.nit
- tests/sav/test_json_deserialization_plain.res
The first goal of this PR is to create a simple but customizable service to write Nit objects to JSON (replacing `to_json_string` and `to_plain_json`). It also clarifies how the serialization of a single object can be customized by refining `accept_json_serializer` which allows the same customization of the existing recursive `to_json` but on any `Serializable` objects.
The second goal is to isolate `json::serialization` from `json::static`. This allows to hide the complexity of `static` to clients of `serialization` and will help to deprecate the `static` writing services. After this PR, `serialization` uses really only one service from `static`, `String::to_json` which escapes strings. While `paser_json` uses the new @R4PaSs implementation. The types of `static` didn't add any useful …
> JSON: merge 2 services into `serialize_to_json` and isolate from `static`

- lib/sqlite3/native_sqlite3.nit
- lib/sqlite3/sqlite3.nit
- tests/test_sqlite3_native.nit
This PR updates the SQLite wrapper so it is easier to understand and maintain, and as a bonus it is now compatible with the interpreter.
The C code and native layer now uses only `NativeString`, and the calls `to_cstring` and `NativeString::to_s` are moved to the Nit code and nity layer. The error code on opening a database is kept on the C side and retrieved only as needed. This removes a lot of callbacks which simplifies the code and makes the module compatible with the interpreter.
> SQLite: update and simplify wrapper

- src/nitlight.nit
Since the loader has been upgraded, `nitlight` crashed when using the `--full` option since some modules were recognized by the model but left unparsed, causing the program to crash when fetching the `AModule` from `modelbuilder.mmodule2node`.
This PR fixes the issue by rendering only loaded and parsed modules from the importation chain.
> src/nitlight: Updated client to avoid crashes on unparsed modules

- contrib/asteronits/src/touch_ui.nit
This is a long overdue update to Asteronits, the on-screen controls for mobiles devices were broken since the inverted Y axis incident. The problem is that a correct Y axis in 3D, when sharing world coordinates with the 2D, doesn't look right in 2D. The origin is at the bottom left of the screen, and positive angles are counter-clockwise. I don't like this representation in 2D, but I don't know to improve it, so let's update the clients of `gamnit::flat` instead!
> Asteronits: fix mobile on-screen controls

- contrib/asteronits/src/android.nit
- contrib/tnitter/src/tnitter_app_android.nit
- examples/calculator/src/android_calculator.nit
- lib/android/README.md
- lib/android/game.nit
- lib/android/input_events.nit
- lib/android/landscape.nit
- lib/android/portrait.nit
- lib/android/sensors.nit
- lib/app/audio.nit
- lib/app/data_store.nit
- lib/app/ui.nit
- lib/gamnit/display_android.nit
- lib/mnit/android/android_app.nit
This PR needs some context first: there is two low-level implementations for Nit apps on Android. The oldest is based on C code and `native_app_glue`, it is used by all our game engines. The new one is based on a custom Java class `NitActivity`, it is used to implement `app::ui` and should replace the oldest one when I have time to work on it.
Prior to this PR, importing `android` imported the old C implementation, and you had to import `android::ui` to get the Java implementation.
This PR changes this behavior and uses conditional importations to choose between the two low-level implementations. So importing `android` and `gamnit` uses the old C implementation (now `android::game`) and importing `android` and `app::ui` uses the new Java implementation (`android::nit_activity`).
This …
> Android: select the low-level implementations from other importations

- src/model/model_collect.nit
- src/model/model_json.nit
This PR makes all model entities Jsonable when `model_json` is imported.
Not sure if I was supposed to use the serialization process or not in this case? @xymus what do you think?
This is mostly hand picked services chosen to provide a comprehensive model representation usable by other tools like nitdoc, nitx, web tools or else.
> model: introduce model_json

- lib/core/text/flat.nit
- tests/sav/test_substring.res
- tests/test_substring.nit
A bug in the validation part of `ASCIIFlatString::substring` caused some substrings to be created with a negative length, which could be the cause of various negative side-effects.
In the example added in the substring test, this caused `stdout` to close due to a call to `fwrite` with a negative count, which was in turn converted to unsigned (I suspect this is undefined behaviour), provoking the closure of the stream in the nit part.
Reported by @Morriar
Close #2089
> lib/core: Fix substring issue in `ASCIIFlatString`

- contrib/tnitter/src/tnitter_app.nit
- examples/calculator/src/calculator.nit
- lib/android/NitActivity.java
- lib/android/key_event.nit
- lib/android/nit_activity.nit
- lib/android/ui/ui.nit
- lib/app/ui.nit
- lib/ios/ui/ui.nit
- lib/linux/ui.nit
This should be the last big feature of _app.nit_ needed for my thesis!
Intro services to navigate between multiple windows of the same app.
Windows are added to a stack and popped back to the visible state on pressing the back key.
This behavior was implemented for Android by intercepting events raised by the "hardware" back key.
iOS offers the same features natively so there is no adaptation needed as of now.
On GNU/Linux with GTK+, a button is added to the window header when there's a window to go back to.
These feature will probably have to be tweaked in the future, but they are enough for the Benilux client app. Notably, the life-cylce of each individual window has to be reconsidered and we will probably need some adaptation on iOS to have a better integration.
This PR also fixes a …
> app.nit: navigate between windows with the back button

- src/catalog.nit
The various person-related fields were parsed verbatim.
So a slight change in spaces was enough to differentiate two persons.
Now the canonical person representation is used.
e.g. `Lucas Bajolet<r4pass@hotmail.com>` vs `Lucas Bajolet <r4pass@hotmail.com>
` is now the same person (hint: the change is the space between the `t` and the `<`).
Note that to present the original information,
names/emails/url are still distinguished.
`Lucas Bajolet <r4pass@hotmail.com>`, `R4pass <r4pass@hotmail.com>
` and `Lucas Bajolet <lucas.bajolet@hotmail.com>
` are still 3 persons.
> make the nitcatalog slightly more robust on person variations

- share/man/nitunit.md
- src/nitunit.nit
- src/testing/testing_base.nit
- src/testing/testing_doc.nit
- src/testing/testing_suite.nit
- tests/sav/nitunit_args1.res
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args7.res
- tests/sav/nitunit_args9.res
- tests/test_nitunit4/test_nitunit4.nit
- tests/test_nitunit4/test_nitunit4.sav/test_bar.res
- tests/test_nitunit4/test_nitunit4.sav/test_baz.res
- tests/test_nitunit4/test_nitunit4_base.nit
The point of this serie is to make nitunit more usable and make it more sexy than tests.sh (or ad hoc test scripts) for libraries and programs.
* black box tests with .res files
* --nitc of NITC to locate a specific binary to use
* testcases are executed with some ulimits (to limit timeouts)
* the XML generated is more robust
Sometimes, it is easier to validate a `TestCase` by comparing its output with a text file containing the expected result.
For each TestCase `test_bar` of a TestSuite `test_mod.nit`, if the corresponding file `test_mod.sav/test_bar.res` exists, then the output of the test is compared with the file.
The `diff(1)` command is used to perform the comparison.
The test is failed if non-zero is returned by `diff`.
~~~nit
module test_mod is test_suite
class TestFoo
fun …
> More nitunit improvement

- src/catalog.nit
- src/nitcatalog.nit
- tests/sav/nitcatalog_args1.res
The raw number of warnings is not that useful.
Number of warnings per 1000 lines of code make it more semantic.
> nitcatalog: count warnings per 1000 lines of code (w/kloc)

- contrib/xymus_net/.gitignore
- contrib/xymus_net/Makefile
- contrib/xymus_net/README.md
- contrib/xymus_net/package.ini
- contrib/xymus_net/xymus_net.nit
- lib/nitcorn/README.md
- lib/nitcorn/examples/Makefile
- lib/nitcorn/examples/src/xymus_net.nit
- tests/listfull.sh
This PR activates full support for the Benilux mobile app on the [xymus.net](xymus.net) production server. It was missing only the RESTful API code which is generated by nitrestful, and the admin interface.
A future PR will update the HTML interface with info on the app, or it will drop the hard coded content of the Benitlux page/views in favor of local content.
> Update xymus.net to activate the full API for the mobile client

- lib/postgresql/native_postgres.nit
- lib/postgresql/postgres.nit
- tests/test_postgres_nity.nit
This wrapper works around the `native_postgres.nit` class and implements the minimal amount of functionality of that class to start a connection, use the execution methods, and inspect the results. It's the next phase in the postgres package, I've also added tests.
@xymus
> Implementing the  Nit wrapper over the native postgres wrapper

- src/model/model.nit
- src/model/model_json.nit
- src/model/model_visitor.nit
Proposal to generalize the visibility concept to all the MEntities:
* packages, groups and modules are always public
* classes depend on the signature, classdefs return the class visibility (shortcut)
* properties depend on the signature, propdefs return the property visibility (shortcut)
Other exotic MEntities are always public.
This PR makes the changes in model and update `model_json` as PoC for the gain of the generalization.
> Generalize MEntity visibility

- share/man/nitdoc.md
- src/doc/doc_phases/doc_html.nit
- src/toolcontext.nit
So other tools than nitdoc can use it.
> toolcontext: introduce --share-dir

- contrib/nitrpg/src/test_helper.nit
- lib/core/exec.nit
- share/man/nitunit.md
- src/nitunit.nit
- tests/test_nitcorn.nit
- tests/tests.sh
Parallel executions can cause some race collisions on named resources (e.g. DB table names).
To solve this issue, `tests.sh` and `nitunit` initialize  `NIT_TESTING_ID` with a distinct integer identifier that can be used to give unique names to resources. 
`rand` is not a recommended way to get a distinct identifier because its randomness is disabled by default.
> Less randomness and race conditions in tests

- src/model/model.nit
- tests/sav/test_model_visitor_args2.res
Specify `mdoc_or_fallback` behavior in MClass and MProperty (return intro mdoc)
> src/model: fix mdoc_or_fallback for MClasses and MProperties

- lib/popcorn/README.md
- lib/popcorn/examples/middlewares/example_advanced_logger.nit
- lib/popcorn/examples/middlewares/example_simple_logger.nit
- lib/popcorn/pop_handlers.nit
- lib/popcorn/popcorn.nit
- lib/popcorn/tests/res/test_example_static_multiple.res
- lib/popcorn/tests/test_example_advanced_logger.nit
- lib/popcorn/tests/test_example_simple_logger.nit
This PR introduce two changes in the popcorn request-response cycle:
* Introduce placeholders `use_before` and `use_after` to force handler execution before or after each request. This makes the life of developer easier when using a lot of routers/routers.
* Break response cycle if a between (between as between before and after) handler gives a response then call after_handler. This encourage the use of middleware into `use_before` and `use_after` and avoid requests sent twice. Bonus the api makes more sense like this.
> Popcorn: use_before, use_after

- lib/core/file.nit
Quite self-explanatory, really it is just a simpler `Path::stat` followed by a `FileStat::is_dir`.
> lib/core: Added `is_dir` function to `Path`

- lib/readline.ini
- lib/readline.nit
- tests/sav/test_readline.res
- tests/test_readline.inputs
- tests/test_readline.nit
This is a tiny wrapper for the GNU readline library. For some reasons, pkg-config doesn't know about libreadline so I had to hardcode the cflags using the ldflags module annotation.
Signed-off-by: Frédéric Vachon <fredvac@gmail.com>
> GNU readline wrapper

- lib/core/math.nit
Simple addition to `core`, the `is_pow2` method on Int tells whether an integer is a power of two.
> Int::is_pow2

- src/nitweb.nit
- src/web/model_api.nit
- src/web/web.nit
- src/web/web_actions.nit
- src/web/web_base.nit
- src/web/web_views.nit
This PR cleans the Quick&Dirty(c) JSON API of nitweb to use the model_json one.
Modified services:
* /uml -> /api/um/:entity
* /code -> /api/code/:entity
* /random -> /api/random
* /search -> /api/search
Also do some renaming to match `popcorn` philosophy.
> nitweb: clean existing api

- lib/core/collection/abstract_collection.nit
- lib/core/collection/array.nit
- lib/core/collection/list.nit
- lib/core/error.nit
- lib/core/exec.nit
- lib/core/file.nit
- lib/core/re.nit
- lib/core/text/abstract_text.nit
- lib/core/text/ropes.nit
- tests/sav/test_new_native_alt1.res
Too tired too work but no enough to sleep...
According to Jenkins [here](http://gresil.org/jenkins/job/CI_github/4177/warnings2Result/package.795683049/), [here](http://gresil.org/jenkins/job/CI_github/4177/warnings2Result/package.-1960060028/) and [here](http://gresil.org/jenkins/job/CI_github/4177/warnings2Result/package.1056020115/), this PR should fix the remaining warning of `core/`.
The algorithm used for the human/pillow approach was:
~~~
1. can it be fixed shamelessly with a .as(not null) ?
yes: add that sweet .as(not null) and hope for the best
2. is there more than one occurrence of the variable involved?
yes: factorise with a local variable, add that sweet .as(not null) and hope for the best
3. is this code to complex for my human/pillow head?
yes: shame = false, fallback to 1. …
> core: fix some "call on nullable" warnings

- share/nitweb/directives/entity/doc.html
- share/nitweb/directives/entity/link.html
- share/nitweb/directives/entity/signature.html
- share/nitweb/directives/group-block.html
- share/nitweb/index.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/model.js
- share/nitweb/javascripts/nitweb.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/stylesheets/nitweb_bootstrap.css
- share/nitweb/views/class.html
- share/nitweb/views/classdef.html
- share/nitweb/views/group.html
- share/nitweb/views/index.html
- share/nitweb/views/module.html
- share/nitweb/views/package.html
- share/nitweb/views/propdef.html
- share/nitweb/views/property.html
- src/nitweb.nit
This PR introduces the angular-js skeleton for nitweb. It contains only one line of nit, the other modification only html/css/js code.
For now, most of the views/controllers are empty and the interface only displays the mdoc of each mentity hilighted with nitlight/doc_down.
Some demo pages:
* http://nitweb.moz-code.org/package/popcorn
* http://nitweb.moz-code.org/module/core::ropes
* http://nitweb.moz-code.org/class/core::Array
> nitweb: introduce angular skeleton

- src/rapid_type_analysis.nit
Just stop visiting abstract methods. This make RTA more robust when there is not body
> rta: do not analyze abstract methods

- contrib/nitiwiki/src/wiki_base.nit
- lib/core/text/abstract_text.nit
Merge the duplicated implementation of `String::capitalized` and `Buffer::capitalize` and extend it to accept the `keep_upper` optional parameter. This parameter triggers keeping uppercase letters as is.
It is applied in nitiwiki to preserve acronyms, like the many apparences of FFI at http://nitlanguage.org/FFI/.
> Factorize `capitalize` and add option to preserve uppercase letters

- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- lib/core/text/test_abstract_text.nit
Produce more standard-compliant code instead of relying on the default behaviour of gcc (or on its `-Wno-trigraphs` flag).
See also: https://github.com/nitlang/nit/pull/1949/commits/000ac8de3c64790b0fbb0e868e406a6a280f3fa9
> escape_to_c: Escape trigraphs

- contrib/nitrpg/src/test_helper.nit
- share/man/nitunit.md
- src/loader.nit
- src/nitunit.nit
- src/testing/testing_doc.nit
- src/testing/testing_suite.nit
- tests/nitunit.args
- tests/sav/nitunit_args1.res
- tests/sav/nitunit_args4.res
- tests/sav/nitunit_args5.res
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args8.res
- tests/sav/nitunit_args9.res
nitunit do no more try to be clever and find test-suites.
Previously, `nitunit foo.nit` caused the execution of the test suite `test_foo.nit` if it exist.
This behavior had some drawbacks:
* the test suite must follow a strict naming convention `test_*`
* the test suite must be in the same directory
* there must a an associated module. no way to create a test-suite out of thin air
* nitunit do nothing if you give the test suite instead of the module
* `-t` used to precise the location of the test suite did not work with more than one module
The proposed solution is to remove all this test-suite association with a module and asks the used to use the test-suite instead.
nitunit test_foo.nit
Because nitunit in intended to work with more than one module, there is basically no change for …
> nitunit: testsuites are explicit

- src/nitcatalog.nit
Imported packages where always shown. Not a good behavior on most command-line cases.
> catalog: only render the asked packages (not the imported ones)

- share/nitweb/directives/entity/defcard.html
- share/nitweb/directives/entity/linearization.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/model.js
- share/nitweb/views/class.html
- share/nitweb/views/classdef.html
- share/nitweb/views/propdef.html
- share/nitweb/views/property.html
- src/model/model_collect.nit
- src/nitweb.nit
- src/web/model_api.nit
Display linearization lists:
* Mclass linearize all the class definitions
* linearization of `core::Array` mclassdefs: http://nitweb.moz-code.org/class/core::Array
* MProperty linearize all the prop definitions
* linearization of `core::Object::hash`: http://nitweb.moz-code.org/property/core::Object::hash
* MClassDef linearize to intro
* linearization of `core::flat$Array`: http://nitweb.moz-code.org/classdef/core::flat$Array
* MPropdef linearize to intro
* linearization of `core$Array$Object::SELF`: http://nitweb.moz-code.org/propdef/core$Array$Object::SELF
> nitweb: list linearized definitions

- share/nitweb/directives/entity/defcard.html
- share/nitweb/directives/entity/linearization.html
- share/nitweb/javascripts/entities.js
- share/nitweb/javascripts/model.js
- share/nitweb/views/class.html
- share/nitweb/views/classdef.html
- share/nitweb/views/module.html
- share/nitweb/views/propdef.html
- share/nitweb/views/property.html
- src/model/model_collect.nit
- src/nitweb.nit
- src/web/model_api.nit
Interesting demos:
* http://nitweb.moz-code.org/module/array_debug::array_debug
* http://nitweb.moz-code.org/classdef/core$Array
* http://nitweb.moz-code.org/propdef/core::abstract_text$Object$to_s
Only the two last commits are relevant since the rest belongs to #2170
> nitweb: add `code` tab for modules, classdefs and propdefs.

- lib/base64.nit
- lib/core/kernel.nit
- tests/sav/error_class_glob.res
- tests/sav/nitce/fixme/base_gen_reassign_alt4.res
- tests/sav/nitce/fixme/base_gen_reassign_alt5.res
- tests/sav/nitce/fixme/base_gen_reassign_alt6.res
- tests/sav/nituml_args3.res
- tests/sav/nituml_args4.res
- tests/sav/test_base64.res
- tests/test_base64.nit
As talked with @ppepos, base64_decode now supports either `strict` or `non-strict`
modes when decoding a base64 string.
The `strict` mode is inspired from the `-i` option from the Unix `base64` command, which ignores non-compliant characters and non-padded `base64` strings.
This is more or less what we do now, `strict` being the default.
Since only one allocation and copy is done now, performance should be better.
There is however one pitfall of this implementation due to the `nullable Object` contract from `Collection[K]`, causing multiple boxings, some further optimization could be done on that front.
> Base64: Revamped base64_decode and added a strict mode

- lib/base64.nit
- lib/binary/binary.nit
- lib/cocoa/foundation.nit
- lib/core/bytes.nit
- lib/core/codecs/iso8859_1.nit
- lib/core/codecs/utf8.nit
- lib/core/file.nit
- lib/core/fixed_ints.nit
- lib/core/re.nit
- lib/core/stream.nit
- lib/core/text/abstract_text.nit
- lib/core/text/flat.nit
- lib/core/text/native.nit
- lib/core/text/ropes.nit
- lib/csv/csv.nit
- lib/json/static.nit
- lib/libevent.nit
- lib/nitcorn/http_response.nit
- lib/ropes_debug.nit
- lib/sha1.nit
- lib/text_stat.nit
- src/compiler/abstract_compiler.nit
- src/interpreter/naive_interpreter.nit
- tests/bench_string_super.nit
- tests/bench_string_tos.nit
- tests/sav/test_text_stat.res
- tests/test_buffer_unicode.nit
- tests/test_copy_to_native.nit
- tests/test_nativestring_fill_from.nit
As one famous man once said: "Je vous ai compris!".
So, I understood that some of us (@xymus, @ppepos, @BlackMinou, etc.) did not like the `bytelen` name, since it was not that explicit.
Well, its days are numbered and it is replaced by the longer but more explicit `byte_length`.
> lib/core: Renamed `Text::bytelen` to `Text::byte_length`

- share/man/nitunit.md
- src/nitunit.nit
- src/testing/testing_base.nit
- src/testing/testing_doc.nit
- src/testing/testing_suite.nit
- tests/sav/nitunit_args1.res
- tests/sav/nitunit_args4.res
- tests/sav/nitunit_args5.res
- tests/sav/nitunit_args6.res
- tests/sav/nitunit_args7.res
- tests/sav/nitunit_args8.res
- tests/sav/nitunit_args9.res
- tests/test_nitunit4/test_bad_comp.nit
- tests/test_nitunit4/test_bad_comp2.nit
The XML format used by Jenkins is under-specified. So after loosely googling and a lot of trials and errors here is some improvement of the XML that enhance the user experience on Jenkins.
To experiment, I used a false job to see the results of nitunit for the test cases in tests (where a lot are expected to fails)
* the (ANSI-colored) log: http://gresil.org/jenkins/job/ZZnothing/195/console
* the results: http://gresil.org/jenkins/job/ZZnothing/195/testReport/
The main improvements are:
* messages are open by default (when you click on the + of a failed tests)
* add a time (not impressive but might be useful on real tests)
* all test cases are counted
* more readable names. Compare with http://gresil.org/jenkins/job/ZZnothing/189/testReport/ for instance
> nitunit: improve generated XML

- lib/libevent.nit
The libevent wrapper did not always free and close connections on errors. These are expected errors, like when a file download is cancelled half-way through or when a push connection expires. This recently caused xymus.net to crash due to the exhaustion of file descriptors available to the process.
> libevent: force closing connections on error to fix file descriptors leak

- contrib/opportunity/src/opportunity_controller.nit
- contrib/opportunity/src/opportunity_model.nit
Log all errors to stderr and remove prints on normal behavior.
Also update the error message, as the "meetup already exists" is now impossible because we dropped the uniqueness of name/date/location a while back.
This is related to #2186, where the file descriptor leak lead to bloated log files, a disk full and failed event creation by lack of space.
> Opportunity: log errors to stderr and update message on failed event creation

- contrib/benitlux/src/client/base.nit
- contrib/benitlux/src/client/features/checkins.nit
- contrib/benitlux/src/client/features/push.nit
- contrib/benitlux/src/client/views/beer_views.nit
- contrib/benitlux/src/client/views/home_views.nit
- contrib/benitlux/src/client/views/social_views.nit
- contrib/benitlux/src/client/views/user_views.nit
- contrib/tnitter/src/tnitter_app.nit
- lib/app/README.md
- lib/app/examples/.gitignore
- lib/app/examples/Makefile
- lib/app/examples/http_request_example.nit
- lib/app/http_request.nit
This PR updates the API of `AsyncHttpRequest`, using more general names for methods and adding a new variation point `uri`. The useful `uri_root` and `uri_tail` are still available as they are more practical to factorize code in real programs. Also provide the `http_status_code` to callbacks when the request succeeded.
Fix a few bugs: correct the ordering of the callback to the UI thread, and join the thread from the UI thread after request is completed.
Intro the new `SimpleAsyncHttpRequest` which prints feedback to the console on errors. It can be used when the response from the server is ignored, or as a quick and dirty first version in the prototype.
> app.nit: update AsyncHttpRequest API, add examples and a simple implementation

- lib/libevent.nit
This PR improves what is logged on callbacks reporting an error on a socket. It prints the error code and string from the last socket error. Some errors are ignored: ETIMEDOUT and ECONNRESET.
In the future, we may want to add more expected errors to the list, ignore all of them or let the client chose with a list, I don't know. Note that `event_callback` can be specialized by the clients, so they have access to this too.
> libevent: improve "Error from bufferevent" with socket error code and name

- examples/calculator/src/calculator.nit
- lib/android/dalvik.nit
- lib/android/wifi.nit
- lib/java/base.nit
- lib/java/collections.nit
- lib/java/ffi_support.nit
- lib/java/io.nit
- lib/java/java.nit
- lib/jvm.nit
- tests/test_jvm.nit
This PR improves the documentation of the modules related to the Java FFI: `java` and `jvm`. Besides the doc itself, the name of the module `java::base` has been changed to the more meaningful `java::ffi_support`.
As a bonus, the JVM API is simplified a bit, there's one less unused class in the Android modules and a few other details have been fixed.
> Java FFI: Improve documentation of `java` and `jvm`

- contrib/benitlux/src/client/features/debug.nit
- contrib/benitlux/src/client/features/push.nit
- contrib/benitlux/src/client/ios.nit
- contrib/benitlux/src/client/views/beer_views.nit
- contrib/benitlux/src/client/views/home_views.nit
- contrib/benitlux/src/client/views/social_views.nit
- contrib/benitlux/src/client/views/user_views.nit
- examples/calculator/src/calculator.nit
- examples/calculator/src/scientific_calculator.nit
- lib/app/ui.nit
UI events, such as a button press or a check box toggle, were only sent to the observers of a control, and the control itself. For this reason, every button was watched by the window or some other container.
Propagating the events to the parents (direct and indirect) reaches the window and all of its containers. This allows for more modular code and components, and it removes the need for manually declaring the window as an observer.
> app.nit: propagate events (such as a button press) to the parents of the control

- src/semantize/typing.nit
- tests/sav/base_classid.res
- tests/sav/base_isa3.res
- tests/sav/base_isa_gen1.res
- tests/sav/base_isa_gen2.res
- tests/sav/base_isa_gen4.res
- tests/sav/base_isa_gen5.res
- tests/sav/base_isa_nullable1.res
- tests/sav/base_isa_nullable2.res
- tests/sav/nitce/base_isa_gen1.res
- tests/sav/nitce/base_isa_gen4.res
- tests/sav/nitce/base_isa_gen5.res
- tests/sav/nitce/base_isa_nullable1.res
- tests/sav/nitce/base_isa_nullable2.res
`isa` used to always adapt a local variable, even if there was strict information loss (a warning was shown but the adaptation was effective).
This caused issues for the adaptive typing system since there was no way to retrieve the original type information.
~~~nit
var a: A
a = new B
if a isa A then
else
end
~~~
The change is now that `a isa A` still cause a warning but not more do the adaptation.
Thus in the *then* branch, `a` is still a `B`.
Thus in the merge at the end of the `if`, `a` remains a `B`.
close #2202
> Filter isa adaptation

- lib/gamnit/depth/depth.nit
- lib/gamnit/depth/selection.nit
- lib/gamnit/textures.nit
- lib/glesv2/glesv2.nit
Intro the selection services for gamnit. It uses a simple color picking algorithm, drawing all the actors to the buffer, each with a unique color used to identify which actor is visible at any pixel.
This algorithm is slow, but it works out of the box with any program. It is recommended for the clients to implement their own optimized alternative adapted to their program for better performances.
The changes to the OpenGL ES wrapper let us use glGet* functions that return a vector of values.
The use of an offset may require more than one call to get the full values, but it's quite simple.
In the future, it should be extended with support for the sprites of the _flat_ API.
> gamnit: intro selection services using pixel picking

- lib/android/ui/ui.nit
- lib/app/README.md
- lib/app/examples/.gitignore
- lib/app/examples/Makefile
- lib/app/examples/http_request_example.nit
- lib/app/examples/ui_example.nit
- lib/app/ui.nit
- lib/core/exec.nit
- lib/ios/ui/ui.nit
- lib/linux/ui.nit
This PR intro a service to open a URL using the platform default browser, and an example for the UI API. The example uses most of the available controls, multiple windows and the new `open_in_browser` feature.
The changes to `core::exec` are updates for compatibility with `Text`, and some minor improvements to its doc.
> app.nit: intro `Text::open_in_browser` and example for the UI API

- lib/core/text/ropes.nit
As discussed in my thesis, 512 bytes/leaf is a nice compromise for most uses of Ropes, therefore, the current threshold is updated to better reflect this.
> lib/core: Push rope maxlen to 512 instead of 64

- src/examples/nitwebcrawl.nit
- tests/sav/nitwebcrawl.res
I do not remember why I developed this, but it works so why not publish it.
This can be a base to bench IO-bound parallel problem, or something to test nitweb.
For information, if I crawl a nitweb server on lib/core. I get 5209 entities in 1m51s real time (0m50s user time)
> nitwebcrawl: add a simple crawler for nitweb

- tests/sav/Darwin/test_loader_args5.res
> tests: add sav/Darwin/test_loader_args5.res

- lib/gamnit/tileset.nit
This PR intro `TileSet, TileSetFont and TextSprites` to gamnit, allowing to draw text from bitmap fonts via sprites. The new module reuse some code from `mnit::tileset` and Action Nitro.
> gamnit: add tileset and bitmap font support

- Makefile
- misc/docker/Dockerfile
- misc/docker/README.md
- misc/docker/full/Dockerfile
- misc/docker/hello/Dockerfile
#2181 broke the initial bootstrap because nitc was not found to build nitmd thus failed the `make man`
This PR also cleanup the dockerfiles so the root/ directory is not more used (this cause issue for non-root users)
> Improve (and fix) Docker

- contrib/benitlux/src/client/android.nit
- src/ffi/java.nit
- src/platform/android.nit
The R class is generated by the Android toolchain and acts as a static way to identify resources in Java code. The ID of each values from the `android/res` folder is sorted in a category and accessible through a static field. An example of a generated R class is shown at the bottom of this description.
This PR import the R class in all Java classes generated from the Java FFI. This creates a similar effect as having the R class in the same package. Previously, the user could not reliably import the R class manually as the package name changes between the debug and release version.
~~~
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
*
* This class was automatically generated by the
* aapt tool from the resource data it found.  It
* should not be modified by hand.
*/
package …
> Android: import the R class

- src/modelize/modelize_class.nit
`build_classes` calls itself recursively on imported modules. So, there is no point to specify that imported modules must be processed first.
> modelize_class: Remove an unnecessary pre-condition

- src/metrics/mendel_metrics.nit
Some minor fixes for the documentation of the `mendel_metrics` module.
> `mendel_metrics`: Fix documentation

- lib/popcorn/pop_config.nit
`pop_config` provide a configuration framework for Popcorn apps based on ini
files.
By default `AppConfig` provides `app.host` and `app.port` keys, it's all we
need to start an app:
~~~nit
import popcorn
import popcorn::pop_config
var opts = new AppOptions.from_args(args)
var config = new AppConfig.from_options(opts)
var app = new App
app.listen(config.app_host, config.app_port)
~~~
For more advanced uses, `AppConfig` and `AppOptions` can be specialized to
offer additional config options:
~~~nit
import popcorn
import popcorn::pop_config
class MyConfig
super AppConfig
var secret: String = value_or_default("secret", "my-secret")
redef init from_options(options) do
super
if options isa MyOptions then
var secret = options.opt_secret.value
if secret != null then self["secret"] = secret
end
end …
> lib/popcorn: introduce `pop_config` module

- lib/gamnit/android_two_fingers_motion.nit
- lib/gamnit/flat.nit
Intro a service to manipulate the perspective cameras with two fingers gestures: move the camera and the classic pinch to zoom.
This feature mainly targets the `flat` API. It should also somewhat work with `depth`,  even when the camera looks around, but the fingers won't fit precisely with a world object/layer.
> gamnit: intro pinch to zoom gesture for Android

- lib/github/api.nit
- lib/popcorn/pop_auth.nit
For now, only Github OAuth is provided.
See https://developer.github.com/v3/oauth/.
This module provide 4 base classes that can be used to implement a Github
OAuth handshake.
~~~nit
import popcorn
import popcorn::pop_auth
var client_id = "github client id"
var client_secret = "github client secret"
var app = new App
app.use("/login", new GithubLogin(client_id))
app.use("/oauth", new GithubOAuthCallBack(client_id, client_secret))
app.use("/logout", new GithubLogout)
app.listen("localhost", 3000)
~~~
Optionaly, you can use the `GithubUser` handler to provide access to the
Github user stored in session:
~~~nit
app.use("/api/user", new GithubUser)
~~~
> Popcorn auth

- src/model/model.nit
- src/rapid_type_analysis.nit
This series improves the lookup strategies:
* special fast track for the virtual type SELF
* choose to iterate on the mclassdefs instead of the mpropdefs if they are less numerous.
This mainly limit the degenerative cases that where discovered while investigating the slowdown of #2223
with nitc/nitc/nitc:
before: 0m7.168s
after: 0m6.232s
with nitpick ../contrib:
before: 0m20.928s
after: 0m19.432s
> Faster lookup

- src/model/model.nit
- src/modelize/modelize_property.nit
- src/rapid_type_analysis.nit
- src/semantize/typing.nit
This is a small cleanup of some part of the code of the model.
The main improvement is the addition of a `MErrorType` class and two somewhat related services `MType::is_ok` and `MType::is_legal_in`.
Beside a better model and better services, this changeset clean the quickfix introduced in RTA (see #2245 )
There should be no change in the overall performance.
> new class MErrorType to handle buggy types

- lib/nitcorn/nitcorn.nit
- lib/nitcorn/reactor.nit
- lib/nitcorn/server_config.nit
This PR automates assigning virtual hosts on `0.0.0.0` as the `default_virtual_host`, a fallback for all request not intercepted by other virtual hosts.
It is an imperfect temporary solution as the virtual host on 0.0.0.0:80 may receive requests from other ports, and there can be only one functional virtual host on all interfaces. A better solution would involve rewriting  `ConnectionListener::bind_to` and splitting it up in many services to keep the address and socket associated to a virtual host.
> nitcorn: support the special address 0.0.0.0

- lib/json/serialization.nit
- lib/serialization/serialization.nit
Intro a list of the attribute names to the currently deserialized object which can be used to infer the Nit type of a JSON object to deserialize. It is not the most reliable information, some objects won't have an associated attribute like the root deserialized object and collection items.
Should help for #2246.
As a bonus, this PR improves the doc to `Deserializer` mainly to mention `errors` from `deserialize`.
> json::serialization: intro `attributes_path` as support to `class_name_heuristic`

- examples/calculator/Makefile
- examples/calculator/android/res/values/color.xml
- examples/calculator/org.nitlanguage.scientific_calculator.txt
- examples/calculator/package.ini
- examples/calculator/src/android14.nit
- examples/calculator/src/android21/android/res/values/styles.xml
- examples/calculator/src/android21/android21.nit
- examples/calculator/src/android_calculator.nit
Improve the look of the Android variant for the calculator using style resources from the AOSP calculator. Also intro another variant for Android API 21+ which changes the font and deactivates the virtual keyboard.
This should also fix the calculator missing from our f-droid repository. However, I don't know yet how f-droid handles more than one APK per package...
For an idea of the result, you can take a look at the 6 different resulting calculators alongside the latest AOSP calculator: http://xymus.net/pub/calcs.pdf
> calculator: nicer Android adaptation with API 21 + variant

- lib/nitcorn/http_request.nit
- lib/nitcorn/http_response.nit
This PR makes HTTP requests and responses serializable.
I had a hard time with deserialization because of the `host` attribute that is never initialized, I removed it. Let's see what is crashing.
> Make HttpRequest and Response serializable

- lib/trees/trie.nit
The trie uses an arborescent datastructure to perform searches on a prefix.
With this version of the trie, you can link data to nodes so the trie can
be used as a kind of Map by prefix.
~~~nit
var trie = new Trie[Int]
trie["foo"] = 1
trie["fooo"] = 2
trie["foooo"] = 3
trie["bar"] = 4
trie["baz"] = 5
print trie.has_key("foo")
print trie["foo"] == 1
assert trie.has_prefix("fo")
assert not trie.has_prefix("z")
assert trie.find_by_prefix("foo") == [1, 2, 3]
assert trie.find_by_prefix("bar") == [4]
assert trie.find_by_prefix("z").is_empty
~~~
> lib/trees: introduce Trie

- lib/core/environ.nit
- lib/core/exec.nit
- lib/core/file.nit
- lib/core/kernel.nit
- lib/core/text/native.nit
- src/compiler/abstract_compiler.nit
- tests/sav/nituml_args3.res
- tests/sav/nituml_args4.res
This PR tweaks and hacks the core lib and the compiler to get a working bootstrap on Windows. After a regen of c_src, one could clone the repo and build c_src/nitc.exe using GCC on Windows with mingw or similar. There's a procedure using msys2 at <https://github.com/nitlang/nitlanguage/blob/master/pages/windows.mdwn>.
To achieve basic Windows compatibility, I applied the following algorithm:
1. For a missing C function, if there is an equivalent in `<windows.h>`, use an alternative static C implementation.
2. If it's a difference in a Nit only method, (like the path separator) add an alternative implementation selected at runtime.
3. If the difference spawns across more than one Nit method/class. Deactivate the code for Windows, replace by a no-op, and wait for a later fix hiding platform …
> Native Windows bootstrap

- share/nitweb/directives/entity/card.html
- share/nitweb/directives/entity/doc.html
- share/nitweb/directives/entity/graph.html
- share/nitweb/index.html
- share/nitweb/javascripts/entities.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/class.html
- share/nitweb/views/group.html
- share/nitweb/views/module.html
- share/nitweb/views/package.html
- share/nitweb/views/property.html
- src/web/api_feedback.nit
- src/web/web_base.nit
Cleans some misc part of Nitweb. Notable fact, replace the hover on cards by a dropdown menu with caret.
Can be seen here: http://nitweb.moz-code.org/doc/core::array
For now, the dropdown menu allows the user to swtich between signature and documentation. More contextual options in the future.
This looks quirk with the stars rating (left untouched in the new dropdown system) so still need the mouse over. Since the next PR rewrite this part, I will let this as it is.
We load the stars only when the dropdown is selected so we gain some perfs on the home page.
This PR is based on #2265
> Nitweb clean

- lib/nitcorn/http_request.nit
This PR does two things:
* The first, maybe controversial, but I removed the warning printed by nitcorn on bad post format. The reason is, I am posting a lot of raw json object to my APIs (like github and other APIs work) and I'm getting this warning a lot.
The right thing to do should be to check the format depending on the request type. But the code seem old, I'm not sure I want to rewrite it.
* Second thing: parsing body when receiving PUT requests.
Review: @xymus
> Nitcorn PUT

- contrib/shibuqam/examples/shibuqamoauth.nit
- contrib/shibuqam/shibuqam.nit
- lib/popcorn/pop_handlers.nit
Configuring a shibboleth client is a PITA.
So why not configure it once with an simple auth service that allows servers to delegate their authentication to it?
This is the point of the new server `shibuqamoauth`.
Please review because I'm not a security expert and I do not want to get to much exploitable flaws.
> shibuqam: provide a basic auth web service to simplify the use of `shibuqam`

- src/nitunit.nit
- tests/sav/nitunit_args9.res
So the tests can use annotations and other things introduced in compiler phases.
> nitunit: import frontend

- lib/popcorn/pop_tracker.nit
Easy and ready to use web tracker you can apply to your popcorn application.
The only thing you have to do is to use the tracker in your app routes:
~~~nit
var config = new AppConfig
var app = new App
app.use("/", new HomeHandler)
app.use("/products", new ProductsHandler)
app.use("customers/", new CustomersHandler)
app.use_after("/*", new PopTracker(config)) # tracker listens to /*
~~~
You can also use multiple tracker at once on different route.
All the data will be aggregated for you.
~~~nit
app.use_after("/api/*", new PopTracker(config))
app.use_after("/admin/*", new PopTracker(config))
~~~
To retrieve your tracker data use the `PopTrackerAPI` which serves the tracker
data in JSON format.
~~~nit
app.use("/api/tracker_data", new PopTrackerAPI(config))
~~~
Here some demo of what can be …
> lib/popcorn: introduce PopTracker

- lib/github/api.nit
Since repos can be deleted, the reference can be null.
> lib/github: make `PullRef::repo` nullable.

- share/nitweb/javascripts/nitweb.js
- share/nitweb/views/error.html
- src/nitweb.nit
- src/web/api_catalog.nit
- src/web/api_docdown.nit
- src/web/api_feedback.nit
- src/web/api_graph.nit
- src/web/api_metrics.nit
- src/web/api_model.nit
- src/web/web.nit
- src/web/web_base.nit
Better error handling for the nitweb API:
* the API catches all unmatched `/api/*` requests and display a JSON error. Example here: http://nitweb.moz-code.org/api/foo
* better error messages (in JSON) for all API handlers. One example here: http://nitweb.moz-code.org/api/entity/foo
Also one change in the frontend that displays 404 not found pages: http://nitweb.moz-code.org/foo
> Nitweb errors

- lib/core/README.md
- lib/github/README.md
- lib/nlp/README.md
- src/doc/doc_phases/doc_console.nit
- src/doc/doc_phases/doc_readme.nit
- src/model/model_index.nit
- src/model/model_views.nit
- src/web/api_docdown.nit
- tests/sav/nitx_args1.res
- tests/sav/nitx_args2.res
- tests/sav/nitx_args3.res
Add `model_index` inside `model_view` so importing `model_index` automatically provide an index within the view. Also migrate documentation tools to model index.
Model index is used to search mentities in commands (like `Array`, or `doc: Array`)
Improvement: nitx can no suggest entities if nothing was found.
Model index is used to render doc commands in README files (like `[[list: Array]]`, or `[[graph: Array]]`)
Improvements:
* user can use `name` or `full_name` to locate entities
* nitdoc check and suggest errors
* nitdoc check and display short name conflicts
Model index is used to render doc down inputs and benefits now from the same improvements than nitdoc (but with a different implementation).
Futur PR will migrate the quick search engine.
> Tools use model index

- contrib/github_merge.nit
The tool was fragile, crappy, and very limited.
Now it is still fragile, crappy but less limited.
A lot of new features:
* can work on other repositories than nitlang/nit
* can choose what query to list (eg label)
* fixed status info, and we can filter on it also
* can merge automatically
* and ~~much~~ some more.
All these improvement are used to enable the automatic construction of a `next` branch based on PR with some characteristics.
> Beef up github merge

- lib/json/serialization.nit
This error could arise when parsing invalid JSON strings (or non-object JSON values) and skipping the call to `deserialize`.
See @privat comment in #2291.
> json::serialization: fix reading attributes from non-objects

- src/frontend/glsl_validation.nit
Changes the following warning to an advice and raise it at each use of the annotations (instead of only once).
~~~
/nit/lib/gamnit/flat.nit:355,9--26: Warning: program `glslangValidator` not in PATH, cannot validate this shader. (glslvalidator)
""" @ glsl_vertex_shader
~~~
> frontend: make the warning on unavailable glslangValidator an advice

- contrib/mnit_test/src/test_audio.nit
- lib/android/audio.nit
- lib/app/audio.nit
- lib/linux/audio.nit
This PR removes the old `load_sound` and `load_music` services, they were replaced by lazy loading services a while back. The new services are more in line with the other asset loading services from `gamnit`.
There are also other general but minor improvements: doc updates, better names for a param and an attribute, less warnings, less casts, more consistent error messages and easier debugging.
> app::audio: remove deprecated services and other minor improvements

- lib/json/serialization.nit
- lib/serialization/serialization.nit
- src/frontend/serialization_phase.nit
- src/modelize/modelize_property.nit
- tests/sav/niti/test_json_deserialization_plain_alt2.res
- tests/sav/test_json_deserialization_plain.res
- tests/sav/test_json_deserialization_plain_alt2.res
- tests/test_json_deserialization_plain.nit
This PR fits in the ongoing work to improve deserializing from plain JSON objects.
The JSON deserialization engine no longer raises errors on missing attributes when a default value is available. Attributes may be missing because the JSON object come from a third-party API or
when loading serialized data from a previous version of the software. Default values include simple default values (`var x = 4`), lazy attributes and nullable types (which are set to `null`). This does not yet include `optional` attributes, more work would be needed.
The test/example can be activated when #2296 is fixed.
> json::serialization: don't raise errors on missing attributes with default values

- share/nitweb/directives/entity/defcard.html
- share/nitweb/directives/entity/namespace.html
- share/nitweb/javascripts/entities.js
- share/nitweb/views/doc.html
- src/model/mmodule.nit
- src/model/model.nit
- src/model/mpackage.nit
- src/web/web_base.nit
Before this PR, the namespace composition (adding html things to the MEntity::full_name) was handled by Angular. Namespaces are a pain in the nit to generate, even more when you don't have access to the model... So the solution was to delegate that work to the API.
With this PR, nitweb attach a Namespace object to each MEntity so Angular knows how to render it.
The idea is pretty simple, a namespace is an array of either:
* a string for "::", "$" ...
* an mentity reference like `Array`
* another namespace for recursive definitions
Demo is here: http://nitweb.moz-code.org/
Some examples:
* `core`: http://nitweb.moz-code.org/doc/core
* `core>`: http://nitweb.moz-code.org/doc/core>
* `core::core`: http://nitweb.moz-code.org/doc/core::core
* `core::Array`: …
> nitweb: better namespaces

- contrib/action_nitro/src/action_nitro.nit
- lib/gamnit/cameras.nit
Erroneous code at creation of the perspective matrix caused a wider than requested frustum and field of view. This caused issues in other gamnit code:
* The service `camera_to_world` had to multiply the result by 1.72 to correct the deformation.
* In `asteronits`, the world was not filling the screen, only part of it.
* In general, it created a cool but not desired wide angle lens / fisheye effect.
After the fix, some clients might have to widen the requested visible area, usually set with `reset_height`. We may have to lower the default `field_of_view_y` as it is a bit high.
> gamnit: fix field of view issues

- lib/sqlite3/sqlite3.nit
- tests/sav/test_sqlite3_nity.res
- tests/test_sqlite3_nity.nit
I thought this was lacking from the API, so now when dealing with a StatementRow, one can get a map from column name to column value.
NOTE: This is not lazy since Sqlite re-uses the StatementRow for each row returned when a select statement is sent to the database.
> StatementRow::map

- contrib/nitiwiki/tests/res/wiki1_nitiwiki_status.res
- contrib/nitiwiki/tests/res/wiki2_nitiwiki_status.res
- lib/core/file.nit
Fix `rmdir` to raise an error on failure to remove a folder, instead of on success. Also fix error management in recursive calls where some errors could be lost.
The name of the attribute `Path::last_error` is misleading with `rmdir` as it stores the first error of the last call, and it is set to `null` if there is no error (overwriting the true last error), so it very rarely contains the actual last error. Note that, `Path::last_error` has a different logic than `Stream::last_error` which does keep the last error and does not reset it. In the future, I would suggest to rename `Path::last_error` to `error` to avoid confusion or to use an array that is cleared at the beginning of each method (as it is currently done with `Path::last_error`).
> core: fix rmdir not reporting some errors

- contrib/benitlux/Makefile
- lib/md5.nit
- lib/pthreads/pthreads.nit
- src/platform/ios.nit
- src/toolcontext.nit
- tests/Darwin.skip
- tests/sav/hello_ios.res
- tests/sav/test_platform_ios.res
General fixes for the iOS support:
* Report errors on `rmdir`, this depends on the fix #2309.
* Fix release mode compilation, the path to the binary was wrong.
* Fix the ios-release rule of Benitlux to use the release mode, contact the right server, and keep the generated files to use from XCode.
* Finally silence the normal output of `xcodebuild`. This looks like a new feature of XCode 8!
* Fixed a few warnings raised by clang.
> iOS: fix compilation problems, warnings and the Benitlux ios-release rule

- lib/android/http_request.nit
- lib/android/ui/ui.nit
- lib/java/ffi_support.nit
Some small tweaks to the Android support:
* `JavaString::to_s` used to crash (at the JNI level) if the associated Java string was null. This was a counterintuitive behavior when the Nit object is non-nullable. This PR prevents this error by returning something similar to the default `Object::to_s` when the underlying Java value is null (for `JavaString` and others). This makes it crash proof, but one should still check if `JavaString::is_java_null` before using the value returned by `to_s` when an actual string is expected.
* Some Java exceptions raised by the Android implementation of `http_get` do not have a message. This PR looks through the causes of such exceptions to find the first available message.
* Also, fix `on_click & ButtonPressEvent` to be raised only when a button is …
> android: click event on button release, better errors and safer `JavaString::to_s`

- contrib/benitlux/src/client/views/social_views.nit
- contrib/benitlux/src/client/views/user_views.nit
- contrib/shibuqam/examples/shibuqamoauth.nit
- lib/nitcorn/http_request.nit
- tests/sav/test_nitcorn.res
- tests/test_nitcorn.nit
While POST data was decoded from percent encoding, GET args were not. Some clients (`shibuqam`) manually decoded that args while others (`benitlux`) hung on requests with spaces.
There is still an issue in the HTTP request parsing where request URL with a space are broken. I'm not fixing this right away because there is no current issue associated to this problem and I have a larger rewrite of nitcorn in the works that will solve this.
> nitcorn: decode GET args from percent encoding

- lib/libevent.nit
- lib/nitcorn/nitcorn.nit
- lib/nitcorn/reactor.nit
- lib/nitcorn/signal_handler.nit
- lib/signals.nit
Intercept SIGINT and SIGTERM to close the server cleanly. The first signal request a clean exit from libevent, so it waits to complete the active events before closing. The second signal reverts to the default signal handler and quits instantly. 
Fix #2294.
> nitcorn: handle SIGINT and SIGTERM

- src/ffi/pkgconfig.nit
- tests/sav/Darwin/todo
- tests/sav/error_annot_pkgconfig_alt1.res
This is an attempt to improve the error message on a missing development package. The current error stumps everyone on the first occurrence. The new version puts an emphasis on three things:
- it needs the _dev_ package, 
- a possible solution by mentioning apt-get and brew,  and
- that it may be a problem with pkg-config itself. 
I chose to mention apt-get and brew as I consider that they are the best known package manager on Linux and macOS..
> pkgconfig annotation: improve error on missing dev package

- lib/github/api.nit
Update a Github API unit test for recent changes in the remote API behavior. I couldn't find any information on this change, so it may also be a temporary problem.
This commit was originally in #2326.
> lib/github: update unit test for change in Github API behavior

- share/man/nitunit.md
- src/testing/testing_base.nit
- src/testing/testing_suite.nit
- tests/nitunit.args
- tests/sav/nitunit_args10.res
- tests/test_nitunit5.nit
When working with test suites, one can now use `NIT_TESTING_PATH` to retrieve the test suite path.
It can be used to access files based on the current test suite location:
~~~nit
class MyTest
super TestSuite
fun test_suite_path do
assert "NIT_TESTING_PATH".environ.basename == "my_test_suite.nit"
end
end
~~~
Useful for test suites based on model loading like in #2327.
> nitunit: set NIT_TESTING_PATH

- src/model/model_json.nit
- src/model/test_model_json.nit
- src/model/test_model_json.sav/test_classdefs_to_full_json.res
- src/model/test_model_json.sav/test_classes_to_full_json.res
- src/model/test_model_json.sav/test_groups_to_full_json.res
- src/model/test_model_json.sav/test_modules_to_full_json.res
- src/model/test_model_json.sav/test_packages_to_full_json.res
- src/model/test_model_json.sav/test_propdefs_to_full_json.res
- src/model/test_model_json.sav/test_props_to_full_json.res
- src/model/test_model_json.sav/test_refs_to_full_json.res
- src/web/api_metrics.nit
- src/web/api_model.nit
- src/web/web_base.nit
Was broken since #2312 
* Migrate `model_json` to new serialization API
* Add tests to `model_json` to ensure this doesn't happen anymore
* Migrate `web` package and `nitweb` to new API
@xymus a lot of serialization for you. Note: for each entity, I needed two deserialization version `full` and no full. Wasn't sure on how to handle this concern properly with your API
> Fix model_json and nitweb

- contrib/nitrpg/README.md
- lib/config.ini
- lib/config.nit
- lib/github/api.nit
- lib/opts.nit
- lib/popcorn/pop_config.nit
- lib/popcorn/pop_repos.nit
- src/nitweb.nit
We often need basic option handling in our app.
Here a minimalist proposal that covers the basics:
* options holder
* default values
* loading options from ini file
Extract from doc:
This module provides basic services for options handling in your nit programs.
The `Config` class can be used as a simple option holder and processor:
~~~nit
import config
var opt_my = new OptionString("My option", "--my")
var config = new Config
config.add_option(opt_my)
config.parse_options(["--my", "myOption", "arg1", "arg2"])
assert opt_my.value == "myOption"
assert config.args == ["arg1", "arg2"]
~~~
Instead of using basic `Config` instances, it is better to define new sublcasses
to store options and define custom services.
~~~nit
import config
class MyConfig
super Config
var opt_my = new …
> proposal: lib/config

- lib/core/bytes.nit
- lib/core/text/abstract_text.nit
Change the specification of `from_percent_encoding` so undecoded `%` are not replaced by `?`.
> lib/text: do not replace undecoded `%` by `?`

- share/nitweb/directives/ui-summary.html
- share/nitweb/javascripts/nitweb.js
- share/nitweb/javascripts/ui.js
- share/nitweb/stylesheets/nitweb.css
- share/nitweb/views/class.html
- share/nitweb/views/group.html
- share/nitweb/views/module.html
- share/nitweb/views/package.html
- share/nitweb/views/property.html
- src/doc/doc_down.nit
- src/nitcatalog.nit
- tests/sav/nitcatalog_args1.res
Automatically add a summary extracted from the README / doc contents
Also add anchors to the content of the README, so you can make links like:
http://nitweb.moz-code.org/doc/core#Methods-Implicitly-Defined-in-Sys
> nitweb: add READMEs summaries

- lib/for_abuse.nit
Simple fix of a few misuses of `trough` instead of `through`
> lib/for_abuse: Fix typos in documentation

- lib/graphs/digraph.nit
The `Graph::to_dot` function seldom produced bad dot when used on objects with special formatting in their `to_s` method.
This PR changes that by overriding the ID of a node by an Int.
There is still the concern that the new implementation might explode when used on a very large graph, there might be a better way to generate it or to escape the node's ids, but I can't find another one at the moment.
Poke @ablondin, this might interest you
> lib/graph: Fix `to_dot`

- src/web/api_docdown.nit
This PR introduces a stub feature for nitweb: autolinking entities from `span` code.
Each time nitweb renders a Markdown comment it evaluates the content of each inline `code` tag and tries to match it with the model index. If the content of the `code` tag matches a package, module, class or property, the `code` content is wrapped in a link to that entity.
Examples:
* `Object`: will be rendered as `<a href='/doc/core::Object'>Object</a>`
* `nullable Object`: will be rendered as `<a href='/doc/core::Object'>nullable Object</a>`
* `is_same_instance`: will be rendered as `<a href='/doc/core::Object::is_same_instance'>is_same_instance</a>`.
The name matching algorithm is the same as the one used to resolve short links like `[Object]` or complex directives like `[graph: core]`.
Demo: …
> nitweb: auto link entitites found in `span code`

- src/loader.nit
- src/mixin.nit
- src/model/mmodule.nit
- src/modelbuilder.nit
- src/phase.nit
- tests/sav/nitmetrics_args1.res
- tests/sav/test_test_phase_args1.res
Extends the nitc code so a phase can inject new submodules.
The main new method the this PR is `ModelBuilder::inject_module_subimportation` that must be used during the analysis on a module.
Up to now, the module hierarchy was fixed and built by the loader before any phases are run.
The basic way was: 1. load the main module, 2. load its imported modules recursively and build the hierarchy, 3. run the phases on all the loaded modules from the most general to the most specific (top-down)
Now the phases can also extends the module hierarchy while running some phases.
This cause the following changes:
* `run_phase` use a work-list (instead of a simple loop)
* new modules can pop up even for the main module of a program, so a fictive main module is always created
* conditional_importations is …
> nitc: inject importation

- lib/realtime.nit
The latest version of macOS, Sierra, defines the functions `clock_gettime` and `clock_getres` which were previously missing. This PR adds support for Sierra while preserving compatibility with El Capitan using a simple heuristic to either use the system provided functions or define them locally.
Reported-by: Marie-Pier Lessard @mplessard
> macOS: update realtime lib for Sierra

- lib/test_suite.nit
- src/testing/testing_suite.nit
- tests/nitunit.args
- tests/sav/nitunit_args11.res
- tests/sav/nitunit_args12.res
- tests/test_nitunit6.nit
- tests/test_nitunit7.nit
Before and after method were not actually called in the test suite process.
This PR enables the compilation and run of these methods.
The new behavior is: if the `before_module` test case fails, all the test cases and the `after_module` are skipped and marked as failed.
> nitunit: fix before and after methods

- lib/core/fixed_ints.nit
- lib/core/text/abstract_text.nit
- lib/core/text/fixed_ints_text.nit
- lib/core/text/flat.nit
- lib/core/text/native.nit
- lib/core/text/text.nit
- lib/ios/ios.nit
- lib/json/static.nit
- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/interpreter/naive_interpreter.nit
Unicode support was broken on 32 bits platforms and anywhere a C `long` was on 32 bits (such as 64 bits Windows). This caused issues when compiling Nit tools.
This PR modifies the critical code in order to use `UInt32` instead of `Int` to fit all the 32 bits of Unicode chars. To do so, the first commit inverts the dependency order of the modules `fixed_int` and `text` so that `text` becomes a client of `fixed_int`. Also, update how constants are declared and fix a few implicit cast warnings.
Fix Debian 32 bits support #2355 after a c_src regen.
Fix #1945 Unicode support on iOS.
Allows to bootstrap under Windows with other minor changes (for another PR).
Reported-by: Alexandre Blondin Massé <alexandre.blondin.masse@gmail.com>
> Use `UInt32` to manipulate Unicode chars and support 32 bits platforms

- lib/core/file.nit
- src/compiler/abstract_compiler.nit
- src/toolcontext.nit
This PR tweaks the generated Makefile so it works under Windows and silences the excessive warnings when casting ints to pointers, which is used to optimize `Int`, `Char` and `Bool`. And, to fix the heuristic that finds the Nit dir, this PR modifies two methods to support Windows path separator `\` and the PATH env var separator `;`.
These should be the last changes to get a working bootstrap on Windows using msys2/mingw64 tools. Once we regen c_src, you can clone and make Nit from Windows by following the first guide at: http://nitlanguage.org/windows.html Using msys2/mingw64 allows to compile native Windows apps using GNU tools, so the resulting program is an exe file that can use any Windows .dll file and show standard Windows windows.
These changes are far from fixing all issues for …
> Windows: last changes for a working bootstrap

- lib/core/stream.nit
- lib/json/serialization_write.nit
This aims to replace the dirty #2367 and might solve the underlying problem in a better way by using a Buffer instead of an Array[String] in StringWriter.
With the following pseudo-oneliner
~~~nit
import json::string_parser
import json
print args.first.to_path.read_all.parse_json.as(not null).serialize_to_json(pretty=true, plain=true).length
~~~
And the file `nit/benchmarks/json/inputs/magic.json` a 54MB json file.
Before:
* User time (seconds): 18.02
* Elapsed (wall clock) time: 13.43
* Maximum resident set size (GB): 6.09
After:
* User time (seconds): 4.26 (-76%)
* Elapsed (wall clock) time: 3.98 (-70%)
* Maximum resident set size (GB): 1.16 (-80%)
Nevertheless, 1GB of ram to process a 54MB file is still huge.
> Use a Buffer in StringWriter

- lib/json/serialization_write.nit
Changes how strings are serialized to JSON by grouping non-escaped characters in a single call to write. So if a string has no escape characters, it is written as is. This replaces the old behavior where there was a call to write for each character.
This PR addresses the same issue as #2367 and #2371 but it targets JSON string writing only. The best results are obtained when this PR is merged with #2371. On my machine, parsing and writing `magic.json`  takes the following wall clock time depending on the branch:
* master: 14s
* #2367 (char cache): 6.2s
* #2371 (buffer): 4.0s
* this PR: 4.8s
* this PR + #2371: 3.6s
> JSON: optimize writing strings

- contrib/inkscape_tools/src/svg_to_png_and_nit.nit
Inkscape changed the default DPI to 96 from 90 in order to match the CSS DPI. This change broke compatibility with our tool `svg_to_png_and_nit`. This PR updates our tool to use the new 96 DPI and work properly with the newer versions of Inkscape.
> inkscape_tools: update expected default DPI

- lib/core/exec.nit
- lib/core/file.nit
Until now, the `exec` services were implemented using the POSIX C functions `fork` and `execvp`. This PR introduces an alternative implement for Windows targets using `CreateProcess`.
The `exec` services are used by the compiler call external tools, most notably `pkg-config`. This should support more programs and tests with a dependency on native libraries. 
The new `exec` implementation will probably need some tweaking. Testing under Windows is still problematic, but `test_exec` now passes, which is a good sign.
The `fflush` on every write is far from optimal and will slow down the compiler (and others). It solves an issue where a small write to the input of a subprocess would not be received by the subprocess. The data was probably kept in the write buffer (and not in the pipe buffer). …
> Windows: implement the `exec` module using `CreateProcess`

- contrib/model_viewer/src/model_viewer.nit
- lib/app/audio.nit
- lib/core/kernel.nit
- lib/egl.nit
- lib/gamnit/README.md
- lib/gamnit/depth/particles.nit
- lib/gamnit/display_linux.nit
- lib/gamnit/egl.nit
- lib/gamnit/flat.nit
- lib/gamnit/gamnit.nit
- lib/gamnit/gamnit_linux.nit
- lib/glesv2/examples/opengles2_hello_triangle.nit
- lib/linux/audio.nit
- lib/sdl2/events.nit
- lib/sdl2/image.nit
- lib/sdl2/sdl2_base.nit
- lib/sdl2/syswm.nit
- tests/sav/error_class_glob.res
- tests/sav/nituml_args3.res
_gamnit_ update to use SDL2 instead of SDL1.2. This change brings better code portability and fixes a few known SDL1.2 limitations. This PR does not significantly change the API, asides from removing the workarounds for old limitations.
As support, this PR also:
* Adds more SDL2 events and surface services.
* Updates the `opengles1_hello_triangle` example to use SDL2 and make it compatible with ANGLE and Windows.
* Drops the _gamnit_ workarounds for the previously slow mouse move events and mouse wrap for FPS like controls.
* Fixes shader compatibility with some graphics card and driver.
* General cleanup for the `egl` module.
> gamnit: use SDL2 windows and events

- lib/ini.nit
> lib/ini: do not abort when lines does not have "="

- contrib/re_parser/Makefile
Some automatic jenkins jobs expect that it this target exists, it can be
used to generate the missing .nit files
> re_parser: add pre-build target in the Makefile

- lib/realtime.nit
Fix `realtime::Timespec` services on 32 bits systems and Windows by moving some critical code to C. This PR does not change the API. However, I have plans for a future revamp of the API to reduce the number of mallocs.
> realtime: 32 bits compatibility

- src/nitweb.nit
- src/web/api_catalog.nit
So the first user to access Nitweb does not have to wait 5 minutes for the catalog to be compiled.
> nitweb: load catalog at startup instead of first page display

- lib/json/serialization_write.nit
Fixes serialization error for array subclasses.
Be the following Nit code:
~~~nit
class Foo
super Array[String]
serialize
var foo: String
end
print (new Foo("foo")).serialize_to_json
~~~
Output before:
~~~json
{"__kind":"obj","__id":0,"__class":"Foo", "__items":, "foo":"foo"[]}
~~~
Output after:
~~~json
{"__kind":"obj","__id":0,"__class":"Foo", "foo":"foo", "__items":[]}
~~~
> lib/json: fix array serialization

- src/semantize/typing.nit
- tests/base_adaptive_full.nit
- tests/sav/base_adaptive_full_alt1.res
- tests/sav/base_adaptive_full_alt2.res
- tests/sav/base_adaptive_loop_array_1alt2_alt1.res
- tests/sav/base_adaptive_loop_array_alt1.res
- tests/sav/base_adaptive_loop_call_alt1.res
- tests/sav/base_isa_nil.res
- tests/sav/base_var_untyped_alt4.res
- tests/sav/base_var_untyped_alt5.res
Nit does not have intersection nor union types, however, the intersection and the difference operations on types are needed for a better behavior of the adaptive typing system.
Currently, the only need of type intersection and type difference is with `isa`. The previous implementation did not really implement them and only did the following:
~~~nit
var x: X
...
if x isa Y then
...
else
...
end
~~~
Now, the `then` branch, handle the merge of nullable types and the `else` branch might also be adapted.
~~~nit
var x: nullable X # where Y <: X
...
if x isa Object then
else
end
if x isa nullable Object then # warning, useless isa
else
end
if x isa Y then
else
end
if x isa nullable Y then
else
end
~~~
I do not expect that these change improve that much the expressiveness of the language. …
> typing: add services for intersecting and subtracting types

- src/parser/nit.sablecc3xx
- src/parser/parser.nit
- src/parser/tables_nit.c
This is a stub in the grammar to add intersection and union types.
* `var x: A and B`
* `var x: A or B and C or D or E`
Adding parenthesis `(A and B) or C` cause some nasty conflicts because the Nit grammar is very complex and organic (and sablecc is nowadays more a curse than a blessing).
all usage of types accept intersection and union except `new` and `isa` because LR1 conflicts with the boolean `or`.
* `x isa A or...`: shift type (`x isa A or B`) vs. reduce expr (`x isa A or true`)
This is not too much a problem because:
* intersection and union type are abstract (no `new`)
* `a isa A or B` should be the same than `a isa A or a isa B`
Note that this is only a stub: only the grammar is extended:
* there is no new AST node (`A or B` is parsed as `A`, the `B` is just dropped)
* there is …
> grammar: add union and intersection types

- lib/core/kernel.nit
- misc/docker/full/Dockerfile
- src/compiler/abstract_compiler.nit
* Add the missing SDL2 package (since #2376) to the full DockerFile.
* Fix a warning raised by the C compiler when called by niti on 32 bits platforms.
* Clean up Makefile generation and enable using environment variables to override the default C compiler, C++ compiler, CFLAGS and whether or not to use libunwind. Making it possible to change the compiler for cross compilation and to skip linking with libunwind to create binaries compatible with more GNU/Linux systems.
> Docker, portability and crosscompiling tweaks

- lib/core/environ.nit
- lib/core/exec.nit
- lib/core/file.nit
- tests/MINGW64_NT.skip
- tests/sav/test_exec.res
- tests/test_exec.nit
- tests/tests.sh
This PR further improves Windows support in the Nit standard library and testing tools:
* Improve Windows path manipulation and standardize the solution. On Windows, services working on path strings first replace all `\` by `/`. This allows sharing the main code with other OS, data copy should be limited since only the first operation on a string should update it.
All `file` services depending on the path separator should have been updated, except for `relpath`. Note that there is still no special treatment for FS root like `C:/`, so further work is needed.
* Support for Windows' PATH where the separator is `;`.
* Fix pipes left open on the parent side after `CreateProcess`.
* Intro a basic skip list for MINGW64 Windows system with projects that are either incompatible (cocoa & ios) or …
> Windows: path, PATH, and exec improvements

- lib/actors/examples/chameneos-redux/chameneosredux.nit
- lib/actors/examples/fannkuchredux/fannkuchredux.nit
- lib/actors/examples/mandelbrot/mandelbrot.nit
- lib/actors/examples/thread-ring/thread_ring.nit
Tried to follow @tremblay-guy commentaries on #2361  to improve the code of the actors examples
> Some minor fixes to actors examples

- clib/gc_chooser.c
- lib/core/gc.nit
This fixes an issue with the actor model where the GC is unable to collect cycles associated with actors objects and printing an annoying warning
Theses modifs should fix the tests in #2401 
The downside is that the finalization is no longer in topological order
> GC now collect cycles

- contrib/inkscape_tools/src/svg_to_png_and_nit.nit
Inkscape changed the default DPI at version 0.92. This PR improves `svg_to_png_and_nit` to set the default DPI according to the detected Inkscape version, 90 DPI up until version 0.92 and 96 DPI for version 0.92 and later. 
Reference: http://wiki.inkscape.org/wiki/index.php/Release_notes/0.92#Important_changes
This is a more portable solution than #2374.
> inkscape_tools: support Inkscape versions before and after 0.92

- lib/gamnit/camera_control.nit
- lib/gamnit/camera_control_android.nit
- lib/gamnit/camera_control_linux.nit
- lib/gamnit/flat.nit
- lib/gamnit/gamnit_linux.nit
- lib/sdl2/events.nit
The new service `accept_scroll_and_zoom` lets the user adjust the camera using platform specific controls. On desktop computers, the mouse wheel controls the zoom and the middle mouse button drags the world/camera. On Android, a pinch gesture controls the zoom and 2 fingers slide the scroll.
This reuse the previous `accept_two_fingers_motion` and intro an implementation for desktop computers. It will be used by, at least, Sputnit in which it will replace the current implementation which is broken since the upgrade to SDL2.
> gamnit: abstract camera scroll and zoom service

- contrib/nitin/README.md
- contrib/nitin/nitin.nit
- tests/nitin.inputs
- tests/sav/nitin.res
~~~
-->abort
1,1--5: Runtime error: Aborted
abort
^
,---- Stack trace -- - -  -
| input-1$Sys$main (1,1--5)
`------------------- - -  -
-->fun toto is abstract
-->toto
1,1--20: Runtime error: Abstract method `toto` called on `Sys`
fun toto is abstract
^
,---- Stack trace -- - -  -
| input-2$Sys$toto (1,1--20)
| input-3$Sys$main (1,1--4)
`------------------- - -  -
-->class A
...var a: String is noautoinit
...fun foo do print a
...end
-->(new A).foo
3,18: Runtime error: Uninitialized attribute _a
fun foo do print a
^
,---- Stack trace -- - -  -
| input-4$A$foo (3,18)
| input-5$Sys$main (1,1--11)
`------------------- - -  -
-->
~~~
> Nitin catches the runtime errors

- contrib/opportunity/docker/Dockerfile
- contrib/opportunity/src/opportunity_web.nit
Now that nitcorn can listen on any interface, why not having lightweight standalone web applications?
How to build?
1. install docker
2. cd nit/contrib/opportunity/docker
3. docker build --tag opportunity .
How to run?
1. docker run -d -p 8080:8080 --name  opportunity opportunity
2. xdg-open http://localhost:8080
3. docker stop opportunity
or just get it from the [hub](https://hub.docker.com/r/nitlang/opportunity/tags/)
1. docker run -d -p 8080:8080 --name opportunity nitlang/opportunity
> opportunity: official docker image

- src/highlight.nit
- src/model/mdoc.nit
- src/nitlight.nit
- src/semantize/typing.nit
Allow clients to send HTML to `new_dropdown`. Fix two regression bugs introduced by #2231: support for `CallSite` and `MVirtualType`. And as usual, also fix a few local warnings and typos.
This is used by my landing page generator script.
> highlight: give more control to clients and fix regressions

- Makefile
> Makefile: Don’t invoke `src/Makefile` twice

- lib/android/platform.nit
- lib/app/app_base.nit
- lib/app/assets.nit
- lib/gamnit/flat.nit
- lib/gamnit/gamnit.nit
- lib/linux/linux.nit
Unit tests in the gamnit module were not executed because Sys::setup exited right away when detecting NIT_TESTING. It affected all gamnit games. This PR check is a platform is bound at the beginning of `Sys::main`, allowing unit tests to run (whether they redef `main` or not).
The check is made possible by the new `bound_platform` which tells what platform is currently bound. This value can be useful in some other cases.
This is an alternative to #2394.
> gamnit: fix nitunit compatibility

- lib/core/kernel.nit
- lib/gamnit/tileset.nit
- tests/sav/error_class_glob.res
Detect non-breaking spaces in `is_whitespace`, and extend `TextSprites` to accept partial line skips, for sub/superscripts or simple half line skip.
> core & gamnit: basic support for the characters nbsp, pld and plu

- lib/gamnit/cameras.nit
- lib/gamnit/cameras_cache.nit
- lib/gamnit/flat.nit
- lib/matrix/matrix.nit
Optimize the gamnit framework to avoid excessive garbage collection and a general speedup.
Replace the use of a generic `Array[E]` to implement matrices of floats, as it caused the boxing of each floats at each access. The new custom extern class does not suffer from the boxing and allow for some optimization in C code. This structure is allocated in the Nit GC (hackishly), and doesn't need an explicit liberation. A limitation of the current solution is about the size of the floating points in C, `matrix` uses doubles and `glesv2` floats, the data is copied and cast in C code, this could be optimized further as needed.
Caching each camera matrix avoids recreating them at each frame, which was quite costly, especially for the UI camera that rarely moves. The caching logic is implemented as …
> gamnit: cache each camera matrix and avoid boxing floats in matrix operations

- lib/nitcorn/http_request.nit
Before this commit, sending `?n=9.5` to a nitcorn application using `int_arg`
caused the app to crash (see the following to_i).
> nitcorn: fix HttpRequest::int_arg

- lib/binary/serialization.nit
- lib/json/serialization_write.nit
- lib/serialization/examples/custom_serialization.nit
- lib/serialization/serialization.nit
- tests/sav/custom_serialization.res
This is an old attempt to add the possibility to have a custom serializer. The idea is that a same set of objects can be serialized in different ways if different serializers are used.
Most of what is needed to do that is already present; the main contribution of this PR is the example that tries to propose a way to do that. The example focuses on 3 simples needs:
* inject a phantom attribute.
when serializing, the custom serializer inject new attributes.
* hide a normally serialized attribute.
when serializing, the custom serializer hides some specific attributes.
* replace a full business object.
instead of serializing an attribute, the custom serializer use a different representation
> Custom serializer

- examples/extern_methods.nit
- lib/core/time.nit
Three things here:
* Introduce `Int::sleep` because of my hatred for `1.0.sleep`
* Introduce `get_microtime` because timestamp are better in microseconds
* Introduce `get_millitime` because sometimes, god forbid, we have to deal with Javascript
Also, I'm using `sys/time`, pretty sure I'm doing something that should not be in the core library.
> lib/core/time: more time related services

- lib/sha1.nit
Change receiver of Sha1 methods from String to Text since no service was specific to immutable instances, and add a sha1_is_digest method to Text, to check whether an instance matches the signature of a SHA-1 digest or not.
> Sha1 is digest

- Makefile
Forgot the call to `$(wildcard)`.
> Makefile: Fix glob patterns

- contrib/model_viewer/src/globe.nit
- contrib/model_viewer/src/model_viewer.nit
- lib/core/collection/abstract_collection.nit
- lib/gamnit/depth/depth_core.nit
- lib/gamnit/depth/more_materials.nit
- lib/gamnit/depth/more_meshes.nit
- lib/gamnit/depth/more_models.nit
- lib/gamnit/depth/selection.nit
- lib/gamnit/flat.nit
- lib/gamnit/textures.nit
- lib/geometry/points_and_lines.nit
Improve the documentation for the central services of gamnit, mainly for entities visible from gamnit.org. Also, to improve the API, remove the `Gamnit` from some class name and move a few named constuctors to factories or their own class.
> gamnit: add documentation and standardize the API

- lib/popcorn/pop_validation.nit
Add two more validators:
* URLField that ensures a field contains a valid URL (you want to redefine that regexp).
* UniqField stubs for uniq emails, logins, ids validation.
How to validate uniq field:
~~~nit
class UniqEmailField
super UniqField
var users: UsersRepository
redef fun check_unicity(v, field, val) do
var user = users.find_by_email(val)
if user != null then
v.validation.add_error(field, "Email `{val}` already used")
return false
end
return true
end
end
~~~
> Popcorn: more validators

- examples/extern_methods.nit
- lib/core/time.nit
- lib/popcorn/pop_tasks.nit
- lib/popcorn/popcorn.nit
This PR is based on #2436 
Tasks allow you to execute code in another thread than the app listening loop.
Useful when you want to run some tasks periodically.
Let's say you want to purge the `downloads/` directory of your app every hour:
~~~nit
class PurgeTask
super PopTask
var dir: String
redef fun main do
loop
dir.rmdir
3600.sleep
end
end
end
var app = new App
app.register_task(new PurgeTask("downloads/"))
app.run_tasks
app.listen("0.0.0.0", 3000)
~~~
> lib/popcorn: introduce tasks

- lib/core/text/string_search.nit
The previous use of the virtual `SELFTYPE` on a parameter of `replace` was too restrictive and caused a dynamic crash when replacing something in a  `String` by a `FlatBuffer` (for example). This PR uses the more general `Text` as the parameter type, which is already supported by the existing implementation.
The minimal case is not the most useful as doc but I've added it as a unit test anyway:
~~~
var t: Text = "hello"
assert t.replace("hello", new FlatBuffer) == ""
~~~
> core: fix dynamic error on the input type in `Text::replace`

- lib/core/stream.nit
> lib/core/stream: fix typo in doc

- src/compiler/coloring.nit
- src/compiler/test_coloring.nit
This will allow to reserve negative IDs (including 0) for special purposes.
> coloring: Only generate strictly positive IDs

- lib/opts.nit
- src/metrics/metrics_base.nit
- src/model/model.nit
- tests/base_ret_covar_int.nit
- tests/example_sorter.nit
- tests/sav/base_virtual_type_self_alt2.res
An upcoming feature will destroy this assumption.
> model: Do not assume enums to be final

- lib/dom/dom.nit
- lib/gamnit/bmfont.nit
- lib/gamnit/font.nit
- lib/gamnit/tileset.nit
The BMFont format supports packed textures, varying advance per character and even kernings. It can be generated by a number of tools, including:
* BMFont, free software Windows app, http://www.angelcode.com/products/bmfont/
* Littera, a web app, http://kvazars.com/littera/
This PR also generalizes the `Font` and `TextSprites` concepts, previously limited to tile set bitmap fonts. And add a new shortcut service to the excellent DOM parser used to parse the XML description.
The result is much nicer than what was previously available, you can see it in a preview of my latest project:
The parsing method crash easily on malformatted font description file. However, since the description file should be generated, loaded at game start and not often modified, all expected crash errors should …
> gamnit: intro support for Angel Code bitmap font

- lib/geometry/boxes.nit
- lib/geometry/points_and_lines.nit
The main change in this PR is the reimplementation of `Point::dist` and `dist2` to support 3D points, including comparing 2D and 3D points. The double dispatch logic is a bit complex but it works with any receiver.
This PR also tweaks existing services to improve the API and doc:
* Make all attributes of `Point` optional for gradual creation/space allocation. In practice, points are often created with a default value, as a kind of buffer, or with the Z axis at 0.
* Rework `BoxedArray` as a subclass of `Array` to inherit its services (incl. `remove`) while using less code.
* Move the custom `to_s` from the concrete boxes to the interfaces as it is very useful when debugging.
> geometry: implement 3D `dist` and improve API

- lib/popcorn/pop_config.nit
Introduce `app_hostname` in popcorn AppConfig.
> lib/popcorn: introduce `AppConfig::app_hostname`

- lib/android/audio.nit
- lib/app/audio.nit
- lib/gamnit/README.md
- lib/gamnit/display_linux.nit
- lib/linux/audio.nit
- lib/sdl2/mixer.nit
Intro a decent implementation of `app::audio` for desktop computers using SDL2 mixer. It supports WAV, MP3, OGG and more. The underlying SDL2 mixer bindings are minimal, they offer only the required features, more can be added as needed.
Clients of the gamnit framework will need to `apt-get install libsdl2-mixer-dev`.
> gamnit & sdl2: implement app::audio using SDL2 mixer

- lib/actors/actors.nit
- lib/actors/examples/agent_simulation/agent_simulation.nit
- lib/actors/examples/agent_simulation/simple_simulation.nit
- lib/actors/examples/chameneos-redux/chameneosredux.nit
- lib/pthreads/concurrent_collections.nit
- src/frontend/actors_generation_phase.nit
`BlockingQueue` and `ReverseBlockingQueue` classes have been removed from  `lib/actors`  and are now in `lib/pthreads/concurrent_collections` because it's a better fit for them.
Also, since the implementation of `BlockingQueue` was too coupled with actors, the actor-specific implementation was kept in `lib/actors` and renamed as `Mailbox`.
`ReverseBlockingQueue` is a fun name and could be useful for some specific cases (as it was used in `lib/actors` or for synchronization on a list of dynamic tasks for example), but was too heavy for it's purpose in the `lib/actors` module. It's been replaced with a `SynchronizedCounter`. The `wait` method of this counter is blocking until the counter value equals 0. 
There was multiple synchronization problems with the actor library : 
* The creation of …
> Actors upgrade and fixes 

- src/modelize/modelize_class.nit
- tests/sav/base_gen_final_bound.res
- tests/sav/error_class_generic_alt2.res
- tests/sav/test_gen_inh.res
- tests/sav/test_super_gen.res
- tests/sav/test_super_gen_raf.res
With class subsets, there is no bound that is useless.
> modelize_class: Remove the `useless-bound` warning

- contrib/tinks/src/client/base.nit
- contrib/tinks/src/common.nit
- contrib/tinks/src/server/server.nit
- lib/gamnit/network/client.nit
- lib/gamnit/network/common.nit
- lib/gamnit/network/network.nit
- lib/gamnit/network/server.nit
Move server discovery logic from Tinks! up to `gamnit::network` and extend existing services with more options. These new services allow for an easy discovery of local servers over UDP, as in the following example which also creates a server if none is found:
~~~nit
import gamnit::network
var servers = discover_local_servers
if servers.not_empty then
var server_info = servers.first
var server = new RemoteServer(server_info)
if not server.connect then
print_error "Failed to connect to {server_info.address}:{server_info.port}"
else if not server.handshake then
print_error "Failed handshake with {server_info.address}:{server_info.port}"
else
print "Connected to {server_info.address}:{server_info.port}"
server.writer.serialize "hello server"
server.socket.as(not null).close
end
else
var …
> gamnit::network: add server discovery via UDP

- lib/core/text/string_search.nit
Replace the first occurrence of `pattern` with `string`
~~~nit
assert "hlelo".replace_first("le", "el") == "hello"
assert "hello".replace_first('l', "")    == "helo"
~~~
> lib/core: introduce replace_first in text/string_search

- contrib/action_nitro/src/action_nitro.nit
- contrib/model_viewer/src/globe.nit
- contrib/model_viewer/src/model_viewer.nit
- contrib/tinks/assets/models/debris1.mtl
- contrib/tinks/src/client/client3d.nit
- lib/gamnit/depth/depth_core.nit
- lib/gamnit/depth/more_materials.nit
- lib/gamnit/depth/more_meshes.nit
- lib/gamnit/depth/more_models.nit
- lib/gamnit/depth/selection.nit
- lib/gamnit/display_linux.nit
- lib/gamnit/examples/template/src/template.nit
- lib/gamnit/model_parsers/obj.nit
- lib/geometry/angles.nit
- lib/matrix/projection.nit
Implement a Blinn-Phong specular lighting shader to replace the previous Lamber diffuse lighting. It creates a reflection effect either from `specular_color` (as on the shields) or `specular_texture` (as on the gold tower).
The required material attributes for the specular effect were already present but not implemented. This PR adds similar attributes for normal maps, but leave them as a TODO. The new shader is fine but not optimal, I'll probably need to rewrite it to gain some performance, support normal maps and improve normals per vertex.
Add two angles of rotation to actors for full 3D rotation with Euler angles. All rotation angles follow the right-hand rule and are consistent between the camera and actors.
Other changes:
* Intro `Cuboid` that can be created by `Boxed3d::to_mesh`.
* …
> gamnit: Blinn-Phong specular lighting, 3 axes of rotation and more

- src/metrics/detect_covariance.nit
- src/metrics/static_types_metrics.nit
- src/modelbuilder_base.nit
- src/modelize/modelize_class.nit
- src/modelize/modelize_property.nit
- src/nitni/nitni_callbacks.nit
- src/semantize/typing.nit
Only `modelize_mclass` require support for partial context. Furthermore, in
a future PR, it may need to resolve types just before modeling the class
definition (in a place where the `MClass` is available and must be used).
Also include various related cleanups.
> modelbuilder_base: Refactor the signature of `resolve_mtype*`

- tests/README.md
- tests/listfull.sh
- tests/search_tests.sh
- tests/testfull.sh
Make the list unambiguous and easy to consume by POSIX shell scripts.
> listfull.sh: Quote paths

- contrib/nitin/package.ini
the tag is used to fill the catalog, http://nitlanguage.org/catalog/p/nitin.html but the link is broken whereas https://opensource.org/licenses/GPL-3.0 works
> nitin: use GPL-3.0 instead of GPL-3

- lib/gamnit/README.md
- misc/docker/full/Dockerfile
Update gamnit README and latest-full docker for #2466.
> gamnit: fix README and docker latest-full references to the use of SDL2 mixer

- contrib/action_nitro/src/action_nitro.nit
- lib/app/http_request.nit
- lib/gamnit/bmfont.nit
- lib/gamnit/cameras.nit
- lib/gamnit/cameras_cache.nit
- lib/gamnit/depth/depth.nit
- lib/gamnit/display.nit
- lib/gamnit/display_linux.nit
- lib/gamnit/dynamic_resolution.nit
- lib/gamnit/flat.nit
- lib/gamnit/gamnit.nit
- lib/gamnit/gamnit_linux.nit
- lib/geometry/points_and_lines.nit
- lib/sdl2/events.nit
Enable dynamic window resizing on desktop computers. It follows the current behavior to preserve the virtual height of 1080 units while adapting the width to respect the window aspect ratio. This is the foolproof behavior, but clients can redef `on_resize` to configure the display as needed, or disable window resizing by setting a custom `GamnitDisplay::sdl_window_flags`.
As support, move `IPoint3d::offset` out of `gamnit` to `geometry` so it can be used by game logic (not just UI logic). And rework sprite positions derived from a camera anchor (such as `ui_camera.center` or `ui_camera.top_left`) to update them when the display is resized.
If needed, we could add a service to preserve the aspect ratio to the desired value. However, since mobile platforms are first class targets, gamnit …
> gamnit: dynamic window resize

- lib/gamnit/dynamic_resolution.nit
- lib/gamnit/flat.nit
This PR clear the drawing buffers *after* selecting the target framebuffer, even when the buffer does not change. This should fix the issue @BlackMinou was having (the color buffer not being cleared) when running Tinks! 3D or https://gitlab.com/xymus/jumpngun.
However, this does not fix a similar issue on my desktop computer and I think an issue remained with the depth buffer on @BlackMinou computer.
> gamnit: fix color buffer clearing issues on some computers

- src/metrics/codesmells_metrics.nit
- src/metrics/mclassdef_collect.nit
- src/metrics/method_analyze_metrics.nit
- src/nitsmells.nit
- tests/TestNitsmells/FeatureEnvy/featureenvy.nit
- tests/TestNitsmells/LargeClass/largeclass.nit
- tests/TestNitsmells/LongMethod/longmethod.nit
- tests/TestNitsmells/LongParameterList/longparameterlist.nit
- tests/TestNitsmells/platform/platform.nit
- tests/nitsmells.args
- tests/sav/nitsmells.res
- tests/sav/nitsmells_args1.res
- tests/sav/nitsmells_args2.res
- tests/sav/nitsmells_args3.res
- tests/sav/nitsmells_args4.res
Adding code smell detection :
- Long class
- Long method parameter list
- Long size method
- Feature envy
Adding a visitor to analyse the contents of the methods
> nitsmell : Add code smell detection

- lib/popcorn/pop_json.nit
First official use of the Goret<sup>&copy;</sup> approach.
> lib/popcorn: use GetName for deserialization process

- lib/gamnit/textures.nit
Use a checker texture to replace textures that fail to load. This replaces the previous behavior where an invalid texture name was passed to OpenGL ES which displayed it as full black.
In support, revamp the implementation of `CheckerTexture` to be only black and white and to have a size of 32 pixels by default. The new color is more neutral while being easier to spot and report by an end user (see the tower in the screenshot below). And the new size will make it easier to see than the previous 2x2 on non-scaled 2D sprites.
Also intro `CustomTexture`, a texture build programmatically by setting the color of each pixel. This can be used to create very simple textures (like the crosshair or the fuel indicator in the screenshot) or to represent end user drawings. This API is not very …
> gamnit: replace missing textures by a checker texture

- bin/nit-makepackage
- share/man/nit-makepackage.md
jenkins does not like missing manpages, even for trivial tools.
> nit-makepackage: add missing manpage

- lib/core/file.nit
Update services from `core::file` to accept any `Text` as receiver or argument. In order to avoid breaking any clients, the return type is left to `String`. However, to get better performances, future improvements could also change the return type to `Text`, and update all the clients.
> core: move file related services from `String` to `Text`

- src/compiler/abstract_compiler.nit
c02e04291807cf97228068cc5b52f453d84ab37b unexpectedly disable ccache.
Since CC is set by default [1], the ?= attempt did never assign anything [2].
The solution is to assign unless if CC is set by another mean.
This can be done thanks to the origin function [3].
[1]: https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
[2]: https://www.gnu.org/software/make/manual/html_node/Flavors.html
[3]: https://www.gnu.org/software/make/manual/html_node/Origin-Function.html
> nitc: use ccache again

- lib/core/text/flat.nit
The title says everything, basically all uses of `0xXXu8` in `core::text::flat` were replaced by their prefixed versions for better readability.
This PR will however need c_src to be regenerated for integration.
I PR this now however to make sure it is not forgotten when a c_src is later regenerated and for review purposes.
> Use prefixed chars instead of raw values

- src/frontend/frontend.nit
- src/frontend/parse_annotations.nit
A simple annotations access framework.
Useful when you only need to know if a module, class or property definition contains an annotation in its source code and you don't have a modelbuilder.
One the phase is applied one can access the annotations through the related MEntity:
~~~nit
fun is_annotated_with_foo(mentity: AnnotatedMEntity): Bool do
return mentity.has_annotation("foo")
end
~~~
I introduced a specific super class to avoid the introduction of `annotations` directly into the MEntity since the concept of annnotations is weird when talking about a MClass or a MType.
> frontend: introduce `parse_annotations` phase

- lib/gamnit/flat.nit
This PR applies a few tweaks to optimize performances of the 2D API:
* Each sprite now caches its index in the GPU buffers, replacing the use of `index_of`. This one has the largest performance gain, especially when there is a large number of sprites using the same texture.
* Cache the last sprite on which was called `needs_update` to avoid double or triple adding it to the set of sprites to update on the GPU. This provides a small but notable gain as when a sprite's X and Y coordinates are modified, it was added twice to the set.
* Use a boolean flag instead of the set `sprites_to_update` when all sprite must be updated after a buffer resize.
These changes were tested on [Dawn Arrival](https://gitlab.com/jeremlvt/dawn_arrival) and they cut about 25-50% of the computing time.
> gamnit: performance improvements for Dawn Arrival

- NOTICE
- misc/README.md
- misc/gtksourceview/nit.lang
- tests/sav/test_syntax.res
- tests/test_syntax.nit
The new definition includes:
* A more accurate and up-to-date grammar
* A more accurate style list
* A list of built-in annotations
* Heuristics for embedded languages
* Spell-checking only enabled for comments
* Styles for operators and lower-case identifiers available if needed
(but not highlighted by default)
Here are the PDF outputs of various black-on-white style schemes for `examples/syntax.nit`:
* [Classic](https://github.com/nitlang/nit/files/1109793/gtksourceview-classic.pdf)
* [Kate](https://github.com/nitlang/nit/files/1109794/gtksourceview-kate.pdf)
* [Solarized Clear](https://github.com/nitlang/nit/files/1109795/gtksourceview-solarized-clear.pdf)
* [Tango](https://github.com/nitlang/nit/files/1109796/gtksourceview-tango.pdf)
Signed-off-by: Jean-Christophe Beaupré …
> gtksourceview: Rewrite the language definition

- lib/neo4j/neo4j.nit
newer versions of neo4j seem more picky
> neo4j: fix cypher syntax for `Neo4jClient::nodes_with_labels`

- lib/gamnit/flat.nit
This PR fixes a problem when more than 16,383 sprites used the same texture, thus shared a buffer. This was caused by a `short int` overflow in the vertices indices passed to OpenGL ES. Now, large groups of sprites are simply broken up into smaller groups and buffers.
In the future, if there are too many such groups we could use a larger integer.
> gamnit: fix integer overflow when there's more than 16,383 sprites

- contrib/action_nitro/src/action_nitro.nit
- contrib/asteronits/src/asteronits.nit
- contrib/tinks/src/client/client3d.nit
- lib/gamnit/depth/depth.nit
- lib/gamnit/depth/depth_core.nit
- lib/gamnit/examples/template/src/template.nit
- lib/gamnit/flat/flat.nit
- lib/gamnit/flat/flat_core.nit
- lib/gamnit/font.nit
The use of `import gamnit::flat` will now include more services useful to most games: `Sound`, `Font`, `pressed_keys`, etc. If a project doesn't want to include them for any reason, it can still `import gamnit::flat_core` and hand pick other services.
> gamnit: refactor the `flat` 2D API to include more services by default

- lib/more_collections.nit
- lib/poset.nit
3 main methods:
* `Map::lookup_all_values` collect all values of the greaters of an element
* `Map::lookup_values` collect only the values of the most specific greaters of an element
* `MultiHashMap::lookup_joined_values` collect and join the values of the most specific greaters of an element
Since many models entities in nitc are in some poset, these services could be used
to add and retrieve metadata while automatically taking in account inheritance or importation.
> poset: add lookup services in Map to search using keys in hierarchies.

- src/frontend/code_gen.nit
- src/frontend/frontend.nit
- src/frontend/serialization_code_gen_phase.nit
- src/frontend/serialization_model_phase.nit
- src/nit.nit
- src/nitmetrics.nit
- src/nitvm.nit
- src/test_test_phase.nit
Some frontend phases generate Nit code (usually method implementations) that is ignored by some tools, including `nitpick`, `nitserial` and `nitrestful`. When running `nitpick` on WBTW, a serialization heavy project, the code generation part of `serialization_phase` uselessly took ~10% of the work time. This extra time adds up quickly as `nitpick` is invoked each time we save a file in vim.
This PR extracts some code generation phases from the main frontend. Compilers and interpreters must import the code generation phases (`frontend::code_gen`) but most others only need the main frontend (`frontend`). Analysis tools may import the code generation phases ito analyze the generated code, or import only the main frontend phases to analyze only the user code.
In this PR, only two phases have …
> frontend: run code generation phases only in engines (and nitmetrics)

- misc/vim/plugin/nit.vim
- src/doc/vim_autocomplete.nit
This PR improves the functions `:Nitdoc` and `:NitGitGrep` for easier navigation in large Nit projects.
When calling `:Nitdoc write_and_make`, or simply `:Nitdoc` with the cursor above the word `write_and_make`, or even using the recommended shortcut Ctrl-D, the preview window now lists the relevant files after the doc of the two different methods accessible from `nitc`:
~~~markdown
Simple indirection to `Toolchain::write_and_make`
* src/compiler/abstract_compiler.nit:112,2--119,4
* src/compiler/compiler_serialization.nit:22,2--38,4
Write all C files and compile them
* src/compiler/abstract_compiler.nit:154,2--155,31 (1 more)
~~~
The path format is supported by Vim, so you can move the cursor above a path and hit `gF` (goto file) to open the file at the first line. There are alternatives …
> vim plugin: list introduction and redefinition locations to goto files

- misc/gtksourceview/nit.lang
Renderings for `test_syntax.nit`:
* [Classic](https://github.com/nitlang/nit/files/1148477/gtksourceview-classic.pdf)
* [Kate](https://github.com/nitlang/nit/files/1148476/gtksourceview-kate.pdf)
* [Solarized Clear](https://github.com/nitlang/nit/files/1148474/gtksourceview-solarized-clear.pdf)
* [Tango](https://github.com/nitlang/nit/files/1148475/gtksourceview-tango.pdf)
For comparison, see #2515.
> gtksourceview: Add the missing `kwnull` context

- lib/gamnit/flat/flat_core.nit
- lib/more_collections.nit
When two sprites are overlapped, a non-opaque pixel drawn before the sprite behind it may be blended with the wrong color. The only solution is to control the draw order to ensure that sprites in the back are drawn first. However, this is hard to automate when grouping sprites in buffers to optimize the drawing of a very large number of sprites (as gamnit does). It requires to break off groups in layers and this may be very costly if the sprites move on the Z axis.
The solution it to let the programmer choose a draw order only when needed. This works pretty well in 2D games where some objects stay on the same relative depth layer.
> Example artifacts on the left, and the fixed result (with a `sprite.draw_order = 1`) on the right:
>
> …
> gamnit: control drawing order

- src/model/model.nit
- tests/sav/base_arg_default_alt1.res
- tests/sav/base_arg_default_autoinit_alt1.res
- tests/sav/base_arg_named_alt1.res
- tests/sav/base_arg_named_inherit_alt1.res
- tests/sav/base_arg_named_inherit_alt2.res
- tests/sav/base_arg_named_inherit_alt3.res
- tests/sav/base_init_basic_alt5.res
- tests/sav/base_init_combine_alt1.res
- tests/sav/base_vararg_alt2.res
- tests/sav/base_vararg_alt3.res
- tests/sav/base_vararg_alt6.res
- tests/sav/base_vararg_alt7.res
- tests/sav/base_vararg_alt8.res
- tests/sav/error_init_auto_alt2.res
Modify `MSignature::to_s` to make its output a shorter valid Nit signature. This helps readability and shortens error messages allowing them to fit more easily on a single line or within a text editor.
Example program:
~~~nit
import geometry
var b = new Box3d[Float] # <- error
~~~
Previous error message:
~~~
Error: expected 6 argument(s) for `init(left: Float, right: Float, top: Float, bottom: Float, front: Float, back: Float)`; got 0. See introduction at `core::Object::init`.
~~~
New error message:
~~~
Error: expected 6 argument(s) for `init(left, right, top, bottom, front, back: Float)`; got 0. See introduction at `core::Object::init`.
~~~
> model: group parameter types in `MSignature::to_s`

- lib/gamnit/bmfont.nit
- lib/gamnit/examples/fonts_showcase/src/fonts_showcase.nit
- lib/gamnit/font.nit
This PR adds more customization options when drawing text using `BMFont`:
* Change the size of the text with a simple attribute `TextSprites::scale`.
* Insert artificial chars to a `BMFont` using the more permissive `BMFontChar`. This way, one can set custom textures for a letter, an emojis or any character from the private use areas. 
* Add "links" to the text using Markdown-like syntax (`[my link]` or `[pretty name](internal name)`). Note that the links are not clickable by themselves. However, the client code can access the sprites representing the link to change their style or to get their position. This will work well with a rumored future feature making sprites clickable...
Notice the colored links and the smaller text box in the following screenshot of `fonts_showcase`: 
---
Once …
> gamnit: scale text, add custom characters and create links with `BMFont`

- contrib/asteronits/src/asteronits.nit
- lib/a_star.nit
- lib/gamnit/camera_control_linux.nit
- lib/gamnit/cameras.nit
- lib/gamnit/flat/flat_core.nit
- lib/gamnit/gamnit_linux.nit
Fix various bugs and issues related to gamnit :
* Expose the previously private class `SpriteSet` for clients to access `time` and set `time_mod` (as intended).
* Fix two bugs with animations: a div by zero in the shader that hid non-animated sprites on Android (a div by zero never crashes, but the return value is unspecified in OpenGL ES 2.0), and an array out of bounds error when an animation has a single frame.
* Cache `GamnitDisplay::aspect_ratio` as it appears to be a performance bottleneck.
* Fix the virtual gamepad not being interactive in Asteronits.
* `UICamera::camera_to_ui` returns a `Point3d` that can be used directly as a `Sprite::center`.
> gamnit: misc fixes

- lib/a_star.nit
- lib/gen_nit.nit
- lib/json/serialization_read.nit
- lib/serialization/serialization.nit
- src/frontend/serialization_code_gen_phase.nit
- src/nitserial.nit
- tests/sav/nitce/test_json_deserialization_safe.res
- tests/sav/niti/test_json_deserialization_plain_alt2.res
- tests/sav/nitserial_args1.res
- tests/sav/test_json_deserialization_plain.res
- tests/sav/test_json_deserialization_plain_alt2.res
- tests/sav/test_json_deserialization_safe.res
- tests/sav/test_json_deserialization_safe_alt1.res
- tests/test_deserialization.nit
- tests/test_json_deserialization_safe.nit
* Use `GetName` to better restrict the accepted static type for attributes with formal types. This should complete the protection against the injection of unexpected types through deserialization (reported by @ppepos).
* Update `nitserial` to intrude import modules with private serializable classes, instead of skipping them. Serializing private classes from the lib should probably be avoided, but at least now we support them and we can see them.
* Fix the deserialization of maps from JSON with metadata and cycles. A difference in the deserialization order could cause a reference to be read before the referenced object. This issue may still be caused by versionning, so a foolproof solution should probably be added to the JSON deserializer.
* Fix a warning in generated code, it was …
> serialization: safe formal types, fix warnings in generated code and more

- src/loader.nit
This will improve the loading time when there is a very
deep .git directory around.
> nitc: loader skip dot (hidden) directory

- lib/gamnit/display_linux.nit
- lib/linux/audio.nit
- lib/sdl2/mixer.nit
Desktop clients can now control playing sounds with the new services from SDL2 mixer. The equivalent was already implemented for Android but not GNU/Linux. The new services still need to be fully exposed in the `app::audio` API.
This PR also removes the requirement to have a working sound card to launch a gamnit game.
> gamnit audio: control sound channels and don't crash if there's no sound card

- lib/markdown/markdown.nit
> lib/markdown: fix crash of the parser when parsing unfinished refs

- src/metrics/detect_covariance.nit
- src/metrics/static_types_metrics.nit
> Nitmetric fixes

- share/nitweb/directives/entity/card.html
- share/nitweb/directives/entity/tag.html
- share/nitweb/javascripts/entities.js
- share/nitweb/views/doc/defs.html
- share/nitweb/views/doc/doc.html
- share/nitweb/views/doc/entity.html
- share/nitweb/views/doc/graph.html
- src/web/api_model.nit
- src/web/web_base.nit
The main objective of this PR is to shorten the frontend response time.
The major culprit was that the full documentation was serialized in each response.
This PR makes nitweb return only the synopsis and lets the frontend ask for the full documentation if needed.
Also uniformizes and cleans tabs for entities:
* Moved data between tabs (such as inheritance data to the inheritance tab)
* Added missing tabs for packages and groups (http://nitweb.moz-code.org/doc/core%3Ecollection%3E/defs)
Demo: http://nitweb.moz-code.org/
> Nitweb: boost response time and some improvements

- contrib/model_viewer/src/globe.nit
- lib/gamnit/depth/depth.nit
- lib/gamnit/depth/depth_core.nit
- lib/gamnit/depth/more_lights.nit
- lib/gamnit/depth/more_materials.nit
- lib/gamnit/depth/shadow.nit
- lib/gamnit/display.nit
- lib/gamnit/dynamic_resolution.nit
- lib/gamnit/gamnit.nit
- lib/gamnit/programs.nit
- lib/glesv2/glesv2.nit
Intro a basic API and the shaders for 3D actors to cast shadows. This feature is off by default, it can be activated by using a sun-like light with: `app.light = new ParallelLight`. This will require additional work to improve the performance, add more kind of lights (point, spotlight, ambient, etc.), support many lights and accept colored lights.
Many values can be tweaked to achieve the best performance tradeoff:
* `ParallelLight` is always centered on the `world_camera` to show shadows only around the player. Its attributes `width, height, depth` are in world coordinates and identify a prism where shadows are computed. Higher values show shadows further away and lower values show shadows in higher resolution.
* `App::shadow_resolution` sets the resolution of the depth texture. Higher …
> gamnit: shadow mapping

- contrib/benitlux/src/client/views/home_views.nit
- contrib/tnitter/src/tnitter_app.nit
- examples/calculator/art/icon-sci.svg
- examples/calculator/src/calculator.nit
- lib/android/data_store.nit
- lib/android/shared_preferences/shared_preferences_api10.nit
- lib/app/data_store.nit
- lib/app/examples/ui_example.nit
- lib/app/http_request.nit
- lib/app/ui.nit
- lib/ios/data_store.nit
- lib/linux/data_store.nit
- src/highlight.nit
Intro the hook `root_window` for clients to set the desired root (or home) window. It is much shorter than the previous redef of `on_create`. Plus, in very simple apps, the client can simple redef `Window` instead of subclassing it.
Refactor `data_store` structure, replacing the interface and subclasses by refinements of a single class. It follows more closely the strategy used by the UI API while not changing anything to the `data_store` API. The data store now drops potentially partially deserialized objects to avoid hard to report crash at runtime, this could be improved upon in the future as the current implementation is not ideal.
Otherwise, this PR brings general improvements to the framework influenced by the creation of [paninit.com](http://paninit.com/): revamp the documentation, …
> app.nit: easier root window selection and other misc improvements

- src/model/model_visitor.nit
> model_visitor: reject is_before and is_after as they are tests

- lib/fca/fca.nit
We use the example from https://en.wikipedia.org/wiki/Formal_concept_analysis:
~~~nit
var fc = new FormalContext[Int, String]
fc.set_object_attributes(1, ["odd", "square"])
fc.set_object_attributes(2, ["even", "prime"])
fc.set_object_attributes(3, ["odd", "prime"])
fc.set_object_attributes(4, ["even", "composite", "square"])
fc.set_object_attributes(5, ["odd", "prime"])
fc.set_object_attributes(6, ["even", "composite"])
fc.set_object_attributes(7, ["odd", "prime"])
fc.set_object_attributes(8, ["even", "composite"])
fc.set_object_attributes(9, ["odd", "square", "composite"])
fc.set_object_attributes(10, ["even", "composite"])
~~~
~~~nit
var concepts = fc.formal_concepts
for concept in concepts do
print concept
end
~~~
~~~nit
var cl = new ConceptLattice[Int, String].from_concepts(concepts) …
> lib: introduce `fca` a module for formal concept analysis

- lib/markdown/markdown.nit
> lib/markdown: fix `text` for nested markdown blocks

- lib/json/dynamic.nit
Extend `JsonValue::get` to support arrays and keys containing the '.' character.
As a general cleanup, remove services specific to parsing errors as clients should check errors only once, and update and standardize the documentation.
> json::dynamic: extend `get` to support arrays and keys with dots

- lib/popcorn/pop_tests.nit
This PR modifies the *pop-tests* so they use `NIT_TESTING_ID` to select the listening port.
This should avoid ports conflicts when testing multiple PR at the same time on Jenkins.
Let's try this!
> popcorn: pop_test uses NIT_TESTING_ID to determine test port

- share/man/nitunit.md
- src/testing/README.md
- src/testing/testing_suite.nit
- tests/nitunit.args
- tests/sav/nitunit_args11.res
- tests/sav/nitunit_args13.res
- tests/sav/nitunit_args14.res
- tests/test_nitunit10.nit
- tests/test_nitunit11.nit
- tests/test_nitunit8.nit
- tests/test_nitunit9.nit
This PR does three things:
* fixes the importation of `before_all` and `after_all` methods
* allows use of `before_all` and `after_all` methods within classes
* changes the test execution order for imported test suites
First of all, this PR fixes the behavior of nitunit with multiple test_suite importation.
Be two modules `a` and `b`:
~~~nit
module a is test
class TestA
test
end
fun setup is before_all do # important things
~~~
~~~nit
module b is test
import module a
class TestB
super TestA
test
end
~~~
In this case, because `b` does not introduce any `before_all` method, the method from `a` was not executed.
This is fixed now.
`before_all` and `after_all` can now be used inside a class definition to indicate methods that must be executed before / after all methods inside the class: …
> nitunit: some fixes and improvements for the `before_all`, `after_all` annotations

- contrib/nitcc/src/autom.nit
- contrib/nitcc/src/nitcc.nit
A NFA can be transformed to another NFA without epsilon-transition.
This is mostly useless but can make large NFA more readable.
Also add some bugfixes
> nitcc: add nfa transformation to remove epsilon

- src/doc/doc_base.nit
- src/doc/doc_phases/doc_html.nit
- src/metrics/codesmells_metrics.nit
- src/metrics/mclasses_metrics.nit
- src/metrics/mendel_metrics.nit
- src/metrics/nullables_metrics.nit
- src/metrics/rta_metrics.nit
- src/model/model.nit
- src/model/model_filters.nit
- src/model/model_json.nit
- src/model/model_views.nit
- src/model/model_visitor.nit
- src/nitdoc.nit
- src/nituml.nit
- src/nitweb.nit
- src/test_model_index.nit
- src/test_model_visitor.nit
- src/web/api_graph.nit
- src/web/api_model.nit
- src/web/web_base.nit
- tests/nitdoc.args
A list of filters that can be applied on a MEntity
By default ModelFilter accepts all mentity.
~~~nit
var filter = new ModelFilter
assert filter.accept_mentity(my_mentity) == true
~~~
To quickly configure the filters, options can be passed to the constructor:
~~~nit
var filter = new ModelFilter(
min_visibility = protected_visibility,
accept_fictive = false,
accept_test = false,
accept_redef = false,
accept_extern = false,
accept_attribute = false,
accept_empty_doc = false
)
~~~
With this, one can use temporary filters with the model visitors and views:
~~~nit
var default_filter = new ModelFilter(private_visibility)
var view = new ModelView(view, default_filter)
if view.accept_mentity(mentity) then
end
var custom_filter = new ModelFilter(public_visibility)
if view.accept_mentity(mentity, …
> Model filters: extract filters from ModelVisitor

- contrib/tnitter/Makefile
- examples/calculator/Makefile
- lib/app/examples/Makefile
- lib/app/examples/http_request_example.nit
- Fix missing Makefile dependencies by correctly using the -m options in calls to nitls. It would work without the -m for simple programs but misses some files when there are conditional importations.
- Fix crash in `http_request_example` by updating the latest app.nit UI API from #2547. Closes #2577.
- Compile the scientific desktop variant of the calculator with the `all` rule.
> app.nit: fix issues in examples and calculator

- contrib/nitin/README.md
- contrib/nitin/nitin.nit
- src/interpreter/naive_interpreter.nit
- tests/tests.sh
This hacks (by refinement) the scope and interpretation services to load and save the states of the local variables of the main method.
`nitin` is now usable for everyday usages:
~~~raw
-->var sum=0
-->for i in [0..5[ do
...print i
...sum += i
...end
0
1
2
3
4
-->print sum
10
~~~
> interactive nit: main variables are preserved

- contrib/asteronits/src/asteronits.nit
- contrib/asteronits/src/touch_ui.nit
- lib/gamnit/bmfont.nit
- lib/gamnit/depth/cardboard.nit
- lib/gamnit/depth/depth.nit
- lib/gamnit/depth/depth_core.nit
- lib/gamnit/depth/more_materials.nit
- lib/gamnit/depth/shadow.nit
- lib/gamnit/dynamic_resolution.nit
- lib/gamnit/egl.nit
- lib/gamnit/examples/fonts_showcase/src/fonts_showcase.nit
- lib/gamnit/examples/template/src/template.nit
- lib/gamnit/examples/triangle/src/portable_triangle.nit
- lib/gamnit/flat/flat_core.nit
- lib/gamnit/gamnit.nit
- lib/gamnit/gamnit_linux.nit
- lib/gamnit/textures.nit
- lib/gamnit/virtual_gamepad/virtual_gamepad.nit
Intro `create_gamnit` and `create_scene` to replace the use of `on_create` in gamnit. This change keeps separate the OpenGL setup in `create_gamnit`, from the world/menu creation in `create_scene`. This will allow support for reinitializing the OpenGL context when the EGL context is lost, which may happen on Android when the game goes in the background. It may also support creating a gamnit game separately from the main application.
Current gamnit games should still work despite the API change, but they will need updating to work with the incoming Android support.
> gamnit: distinguish between `create_gamnit` and `create_scene`

- contrib/asteronits/src/asteronits.nit
- lib/android/assets_and_resources.nit
- lib/egl.nit
- lib/gamnit/cameras.nit
- lib/gamnit/depth/depth.nit
- lib/gamnit/depth/depth_core.nit
- lib/gamnit/depth/more_materials.nit
- lib/gamnit/depth/particles.nit
- lib/gamnit/depth/shadow.nit
- lib/gamnit/display_android.nit
- lib/gamnit/display_linux.nit
- lib/gamnit/dynamic_resolution.nit
- lib/gamnit/flat/flat_core.nit
- lib/gamnit/limit_fps.nit
- lib/gamnit/programs.nit
- lib/gamnit/textures.nit
- lib/glesv2/glesv2.nit
- lib/matrix/matrix.nit
- lib/matrix/projection.nit
- lib/performance_analysis.nit
- lib/realtime.nit
This PR groups small fixes to gamnit and related packages. It is a general cleanup in preparation for optimizations to the gamnit depth 3D API.
Intro a few new services:
* `ParticleSystem::clear` to remove all live particles.
* `CustomTexture` can be modified and reloaded in GPU memory after the first call to `load`.
* Don't apply dynamic resolution to UI sprites as they are usually lightweight and any change in resolution is easily noticable.
Optimizations:
* Matrix creation and manipulation, in both gamnit and the matrix package.
* Free pixel data from both Nit and Java memory after loading them from the assets folder into the GPU memory.
* Avoids using mallocs in `realtime` services.
Fixes:
* Fix the left and right anchors of the `UICamera`.
* Fix a constant used to ask for …
> gamnit: new services and a lot of bug fixes and performance improvements

- lib/android/README.md
- lib/android/native_app_glue.nit
- lib/android/nit_activity.nit
- src/platform/android.nit
This PR extends the new Android compilation toolchain:
* Add support for adaptive icons from Android 8 Oreo (and the older `roundIcon`), see https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html. It should detect the icons structure generated by Android Studio 3.
* Tweak the GC compilation options to make it more stable and support releasing memory when the Android system sends the `onLowMemory` message.
* Don't change the app name and package/namespace when compiling in debug mode. While this allowed to easily install both the release and the debug version of the same app on a device, it could be unexpected and it was not compatible with some Google services linked to a precise package name. The old behavior can be reproduced in standard Nit code by using …
> android: adaptive icons, free memory on demand and use same package in debug mode

- tests/sav/test_jvm.res
- tests/tests.sh
this should fix the CI tests when people with international names make PR.
ref: https://github.com/gradle/gradle/issues/3117
> tests: force a utf8 locale because gradle don't like pure ascii

- lib/core/collection/abstract_collection.nit
I though these existed. They do but only for `Map`s.
I just wanted to get an optional commande line argument without having to do an if.
~~~nit
var arg2 = args.get_nor_null(1)
~~~
I'm not fan of the names, but at least they are. If someone have better. Initially, I named it `try`, like `var arg2 = args.try(1)`.
> core: add `Sequence::get_or_default` and `get_or_null`

- lib/android/audio.nit
Refactor the loading of sounds and music to use the same logic and order, and to fix trying to load invalid resource ids (the errors on 0x00000000). Update the documentation to the currently recommended usage. And close the file descriptors after use/dup.
> Android: fix issues in the audio support

- lib/core/exec.nit
This PR modifies `basic_exec_execute` to add a call to `perror` to display the error message before exiting when a fork fails.
> exec: display system error after failed fork

- src/location.nit
Before this PR, asking if `1,12--1,12` was in `1,1--2,1` returned `false`.
> location: fix located_in behavior

- contrib/action_nitro/src/action_nitro.nit
- contrib/asteronits/src/asteronits.nit
- contrib/model_viewer/src/model_viewer.nit
- lib/android/native_app_glue.nit
- lib/gamnit/android19.nit
- lib/gamnit/display_android.nit
- lib/gamnit/display_linux.nit
- lib/gamnit/egl.nit
- lib/gamnit/gamnit.nit
- lib/gamnit/gamnit_android.nit
- lib/gamnit/gamnit_linux.nit
- lib/gamnit/landscape.nit
- lib/gamnit/portrait.nit
- src/platform/android.nit
- src/platform/app_annotations.nit
Rewrite much of the Android support to better deal with system state changes. This includes handling out of order lifecycle messages, temporarily invalid OpenGL display surfaces, and recreating the OpenGL context when it is released by the system.
In practice, this PR recreates in `gamnit::gamnit_android` a better version than what is in `android::game`. The old `android::game` could probably be removed with `mnit` and a small clean up.
As a bonus:
* Into portable* services to lock the device orientation. (The iOS variant will be in another PR when #2605 is merged.)
* Ask for 4x antialiasing, it should be available on all target platforms.
* Compile Android apps using gcc, it appears to compile a more stable GC. We can probably tweak a few defines to use clang instead.
* Fix numeric …
> Gamnit: rewrite Android lifecycle support

- contrib/action_nitro/Makefile
- contrib/asteronits/.gitignore
- contrib/asteronits/Makefile
- contrib/model_viewer/Makefile
- lib/app/audio.nit
- lib/gamnit/README.md
- lib/gamnit/depth/shadow.nit
- lib/gamnit/display.nit
- lib/gamnit/display_ios.nit
- lib/gamnit/dynamic_resolution.nit
- lib/gamnit/flat/flat_core.nit
- lib/gamnit/gamnit.nit
- lib/gamnit/gamnit_ios.nit
- lib/gamnit/input_ios.nit
- lib/glesv2/glesv2.nit
- lib/ios/assets.nit
- lib/ios/audio.nit
- lib/ios/glkit.nit
- lib/pthreads/pthreads.nit
- lib/realtime.nit
- share/android-bdwgc/setup.sh
- src/platform/ios.nit
- src/platform/xcode_templates.nit
- tests/Darwin.skip
- tests/nitce.skip
- tests/sav/test_platform_ios.res
- tests/testfull.sh
- tests/tests.sh
Support iOS as a target for Gamnit games, including:
* GC on iOS and Xcode assets folder support in the compiler.
* iOS view controller and OpenGL view using the GLKit services.
* Loading of assets: sound, texture and text (and thus 3D models and fonts).
* iOS touch event and orientation change support.
* A few bug fix and tweaks to Gamnit.
* Minimal makefile rules to target iOS.
The game `asteronits` works as expected, here it is on iPad (With controls that are way too big):
Limitations:
* By default, the compiler generates an app for the simulator. To compile for a physical device, in practice, I run `nitc -m ios --compile-dir nit_compile` to generate the iOS project and view errors in Nit or in the custom Objective-C code. And then I launch Xcode with `open -a xcode …
> Gamnit on iOS

- src/doc/api/api_model.nit
- src/doc/commands/commands_html.nit
- src/doc/commands/commands_http.nit
- src/doc/commands/commands_json.nit
- src/doc/commands/commands_model.nit
- src/doc/commands/commands_parser.nit
- src/doc/commands/tests/test_commands_http.nit
- src/doc/commands/tests/test_commands_model.nit
- src/doc/commands/tests/test_commands_parser.nit
- src/doc/term/term.nit
Provides a common super class to factorize code rendering services for doc commands.
Changes:
* renamed `CmdComment::render` to `render_comment` to avoid name conflicts with multiple inheritance
* extracted `CmdCode` command to factorize code related services
* introduced new class `CmdEntityCode`, in place of the old `CmdCode` class
* updated nitx/nitweb clients
* updated tests
> doc/commands: extract CmdCode superclass

- src/compiler/abstract_compiler.nit
- src/ffi/pkgconfig.nit
- src/interpreter/dynamic_loading_ffi/on_demand_compiler.nit
- src/platform/platform.nit
- tests/sav/error_annot_pkgconfig_alt0.res
- tests/sav/error_annot_pkgconfig_alt1.res
- tests/sav/test_syntax.res
The `pkgconfig` annotation tells the compiler to use the `pkg-config` command in order to get the C compiler and linker options required to build the user C code. The availability of each package was tested twice, once at reading the annotation and once in the generated Makefile. This PR moves the first check later, with the generation of the Makefile. There is still two checks, one by the Nit compiler with a prettier output, and one by the Makefile in case it is distributed with the generated C source files.
This fixes an issue we've had when compiling for Android and iOS, where the result of the annotation was not used but still blocked the compilation if the host did not have the package. And leaving the check to the Makefile give a chance to the programmer to tweak it before the C …
> nitc: check pkg-config packages availability later

- contrib/nitcc/src/grammar.nit
- contrib/objcwrapper/src/objc_model.nit
- contrib/opportunity/src/opportunity_model.nit
- contrib/pep8analysis/src/cfg/cfg_base.nit
- contrib/pep8analysis/src/model/model.nit
- contrib/sort_downloads/src/sort_downloads.nit
- contrib/tinks/src/client/client3d.nit
- contrib/tinks/src/game/framework.nit
- lib/actors/examples/chameneos-redux/chameneosredux.nit
- lib/bitmap/bitmap.nit
- lib/bucketed_game.nit
- lib/curl/curl.nit
- lib/sax/sax_parse_exception.nit
- lib/saxophonit/lexer.nit
- src/modelize/modelize_property.nit
- tests/sav/test_attr_infer_type_alt1.res
- tests/test_attr_infer_type.nit
Extend the detection of the static type of attributes from their literal values to support three new cases:
* Simple arrays like `[0, 1, 2]` and `[new Set[Int], new Set[Int]]`. However, it does not accept arrays with an explicit type because we can't subtype/anchor at that point, as far as I know.
* Negative integers and floats. This cheats a bit as the return type of the unary - is defined in the core libary. However this should help 99.9% of the time, in particular for Nit beginners, and a workaround is to declare the attribute static type when defining a different kernel library.
* The `once` keyword.
~~~
class A
var i = -1
var f = -1.0
var a = [0, 1]
var o = once [0, 1]
var a1 = [0, 1.0, "a"] # Different types
var a2 = [0, 1: Int] # Can't reliably check subtypes
var a4 = [1+1] # …
> Infer more attribute types

- lib/gamnit/dynamic_resolution.nit
- lib/gamnit/flat/flat_core.nit
- src/astbuilder.nit
- src/compiler/abstract_compiler.nit
- src/frontend/explain_assert.nit
- src/frontend/explain_assert_api.nit
- src/interpreter/naive_interpreter.nit
- src/rapid_type_analysis.nit
- tests/nitcg.skip
- tests/nitvm.skip
- tests/sav/assertions.res
- tests/sav/base_notnull_lit_alt2.res
- tests/sav/nitunit_args9.res
- tests/sav/test_c_alt4.res
- tests/sav/test_explain_assert_alt1.res
- tests/sav/test_explain_assert_alt10.res
- tests/sav/test_explain_assert_alt11.res
- tests/sav/test_explain_assert_alt12.res
- tests/sav/test_explain_assert_alt13.res
- tests/sav/test_explain_assert_alt2.res
- tests/sav/test_explain_assert_alt3.res
- tests/sav/test_explain_assert_alt4.res
- tests/sav/test_explain_assert_alt5.res
- tests/sav/test_explain_assert_alt6.res
- tests/sav/test_explain_assert_alt7.res
- tests/sav/test_explain_assert_alt8.res
- tests/sav/test_explain_assert_alt9.res
- tests/test_c.nit
- tests/test_explain_assert.nit
- tests/test_nitunit4/test_nitunit4.nit
When an assert fails, the program prints the details of the failed expression to the console, above the stacktrace. This change makes it easier and even fun to implement methods by writing the tests first and using nitunit to debug.
The AST rewrite can explain binary comparisons (printing the expected and actual values in a similar way to JUnit's `assertEquals`), `not` and `isa` expressions, as well as the receiver and arguments sent to a method returning `Bool`. It does not explain `and` & `or` expressions as they could cause unwanted side-effects in the current implementation.
Example of a method call:
~~~
var x = 0.0
var y = 1.0
assert x.is_approx(y, 0.5)
~~~
Output:
~~~
Runtime assert: 0.0.is_approx(1.0, 0.5)
Runtime error: Assert failed (a.nit:3)
~~~
Expressions are executed only …
> Explain failed asserts for easier debugging, error reporting and TDD 

- contrib/inkscape_tools/src/svg_to_png_and_nit.nit
The regex detecting the Inkscape version was too permissive and expected 3 numbers. This made it wrongly match the revision string on Ubuntu where the version string has only 2 numbers:
`Inkscape 0.91 r13725`
Thanks @BlackMinou!
> inkscape_tools: fix Inkscape version detection on Ubuntu

- tests/Darwin.skip
- tests/sav/hello_ios.res
Update the expected result of `hello_ios` and blacklist two more tests on macOS. Both gettext and mongoc (the failure behind nitweb) are available on macOS, however, they would require some configuration.
> Tests maintenance for macOS

- lib/core/text/abstract_text.nit
- lib/html/html.nit
- share/man/nitlight.md
- src/htmlight.nit
- src/nitlight.nit
- tests/nitlight.args
- tests/sav/nitlight_args5.res
Various improprement in the whole nitlight chain.
Before: nitlight --keep-going -d tmp ../lib/ ../src
* Elapsed (wall clock) time: 28.71
* User time (seconds): 47.25
* System time (seconds): 1.05
* Maximum resident set size (Gbytes): 2.1311
After: nitlight --keep-going -d tmp ../lib/ ../src
* Elapsed (wall clock) time: 22.97 (-20%)
* User time (seconds): 34.42  (-27%)
* System time (seconds): 1.06
* Maximum resident set size (Gbytes): 1.8924 (-11%)
After + new option: nitlight --keep-going -d tmp ../lib/ ../src --no-infobox
* Elapsed (wall clock) time: 10.71 (-63%)
* User time (seconds): 14.49 (-69%)
* System time (seconds): 0.83
* Maximum resident set size (Gbytes): 1.6713 (-20%)
> Improve lib/html and nitlight

- src/compiler/abstract_compiler.nit
- tests/sav/test_catch_multi_threaded.res
- tests/test_catch_multi_threaded.nit
This PR removes some of the limitations of the `do catch` : 
* Hard-coded limit of 100 jumping environments is gone, the array is now dynamic
* The structure for managing jump environments is now lazy initialized
* Now using gcc's `__thread` specifier so that each thread has it's own jumping stack
> Make the `do catch` great again

- share/android-bdwgc/setup.sh
When compiling a Nit app for Android, a specific branch of bdwgc/libgc/boehm-gc is cloned locally. Using a shallow clone only fetches the last commit, for a faster download and to use less disk space.
Closes #2621.
> share: shallow clone bdwgc for Android and iOS

- .gitignore
nit_compile are a series of generated intermediate C files that should
not be versioned.
We therefore add them to the .gitignore to eliminate them from the
index.
> gitignore: ignore nit_compile folders and contents

- tests/tests.sh
The C.UTF-8 locale is Debian-specific and causes issues on other
platforms.
To avoid setlocale error messages, the LC_ALL export will default on C
if C.UTF-8 is unavailable on the target platform.
> tests: fix locale issue on non-Debian linux

- lib/core/stream.nit
Two things happening here, in two commits:
* the first commit moves the definition of `decoder` into Stream, and renames it to `codec` since both coding/decoding will be used by streams when dealing with String semantics.
* the second commit removes the `intrude inport ropes` from stream as this was not necessary, and performance-wise did not matter sufficiently to justify this
> No intrude rope stream

- lib/bitmap/bitmap.nit
- lib/core/exec.nit
- lib/core/file.nit
- lib/core/stream.nit
As part of the stream refactor series, this patches cleanup msgpack a bit and introduce a lower-level `read_byte` implementation on which `read_byte(s)` will rely for reading data from a source.
In the future, the lowest-level interface to read bytes, and the only one required for implementing a new stream will be the `raw_read_byte(s)` functions.
A cleanup of the current streams will be needed for this to be used properly, coming in the next few PRs.
Note: The first two commits have already been submitted under #2632, therefore disregard them for this PR.
> Read byte rewrite

- src/metrics/metrics.nit
- src/metrics/metrics_base.nit
- src/metrics/readme_metrics.nit
- tests/nitmetrics.args
- tests/sav/nitmetrics_args1.res
- tests/sav/nitmetrics_args3.res
This PR add an option `--readme` to extract metrics about ReadMe / Markdown files.
Running the following command:
~~~sh
nitmetrics --readme tests/test_prog
~~~
Will produce the following output:
~~~md
*** METRICS ***
* has_package 1
* has_readme 1
* md_lines 12
* nb_section 0
* md_blocks 14
* BlockParagraph 4
* BlockUnorderedList 1
* BlockListItem 4
* SpanCode 4
* Image 1
~~~
> nitmetrics: metrics about ReadMe files

- lib/core/file.nit
- lib/core/stream.nit
- lib/libevent.nit
- lib/socket/socket.nit
- lib/websocket/websocket.nit
More in the Stream refactor series, this commit adds a low-level byte writing method, to be re-implemented when needed. The read_bytes service can now be defined in writer only, as a wrapper to the lower-level service.
> Write byte updates

- src/nitpick.nit
The infrastructure was already in toocontext, now nitpick uses it.
> nitpick: do not warn in not explicitly required modules

- lib/socket/examples/socket_server.nit
- lib/socket/socket.nit
- lib/socket/socket_c.nit
The socket_c module contained a lot of undocumented functions and
classes, which in turn caused nitpick to be too verbous on subsequent
modules when editing.
This commit fixes all the documentation warnings left in the module.
> lib/socket: fix socket_c documentation

- contrib/nitpm_packages.txt
- contrib/oot.sh
- contrib/oot.txt
- src/nitcatalog.nit
- src/nitpm.nit
This move the packages fetched by nitpm to nitlanguage.org and use the nitcatalog infrastructure to publish and update the ini files.
The list of public packages is now in `contrig/nitpm_packages.txt` (was `oot.txt`) and new public packages can be added to the file trough PR and review by the community.
Note that there is nothing yet to check the sanity of public pagkage (nor do any long run quality assurance).
> Nitcatalog for nitpm

- share/man/nitweb.md
This PR fixes the warning thrown by check-manpages.sh for the `nitweb` tool.
> share/man: update man page for nitweb

- lib/json/README.md
- lib/json/serialization_read.nit
Rename the service `String::from_json_string` to a nicer `deserialize_json`. I believe that the old name was counter-intuitive and may explain why the method was used so rarely/never.
Add the argument `static_type` to `deserialize_json` to limit the type of objects that can be deserialized. This argument is passed directly to the JSON deserializer.
The method `deserialize_json` still prints errors to the console, so it should be used for quick prototypes or scripts.
This could make prettier and safer examples in #2655.
> json: rename and improve the quick and easy `deserialize_json`

- lib/core/text/native.nit
- tests/sav/test_memset.res
- tests/test_memset.nit
Memset is an operation used for setting bytes to a particular value.
Since it was not defined on CStrings, we add it.
> lib/core/text: add memset to `CString`

- lib/crypto/xor_ciphers.nit
- tests/sav/test_inplace_xor.res
- tests/test_inplace_xor.nit
The xor operation as defined in xor_ciphers lacked a performance-aware
version on byte sequences.
This commit adds a fast version to perform it on a CString.
> lib/crypto: add in-place xor cipher on CStrings

- src/platform/android.nit
Android NDK tools do not support the armeabi target platform anymore, breaking the compilation of all Nit app for Android. This PR removes this target, fixing our compilation issues. This platform version should not be active anywhere, it was widely replaced by armeabi-v7a.
Unless you update the Android SDK tool, compiling Nit apps for Android should still work on your machine and the CI server. However, it fails on the Nit docker, as with: 
https://gitlab.com/xymus/darpg/-/jobs/67649353
https://gitlab.com/Skyline76/memory_gamnit/-/jobs/67571796
> android: remove the deprecated armeabi target platform

- misc/docker/Dockerfile
- misc/docker/full/Dockerfile
This PR should fix the compilation of the nitlang/nit Docker which was broken since adding nitpm.
See: https://hub.docker.com/r/nitlang/nit/builds/bgtphmftqbdp9o7eqhqzn9f/
I've activated email alerts on hub.docker.com to hopefully catch these problems sooner next time.
> docker: nitpm requires libcurl, move it up from `full`

- lib/core/core.nit
- lib/core/protocol.nit
- lib/socket/socket.nit
- lib/websocket/examples/websocket_server.nit
- lib/websocket/websocket.nit
Since BufferedReader is scheduled for removal, we remove it as superclass from the TCPSocket.
As the TCPSocket will be buffered at the system-level, it is not a big problem for performance.
Note: Last commit is to be reviewed only, the others are from #2648
>  lib/socket: remove BufferedReader superclass

- lib/core/codecs/utf8.nit
- lib/core/stream.nit
With the stream refactor being developed and tested alongside, some buggy behaviours are being discovered.
This PR fixes one of such, where calling read on a dead stream caused the program to segfault.
> Fix Reader::read

- tests/Darwin.skip
The test `nitpm_arg3` exposes an output from Git. It looks like there is locale issue on the macOS CI server changing the output and breaking the tests.
Test diff:
~~~
--- sav//nitpm_args3.res	2018-04-05 22:14:54.000000000 -0400
+++ out/nitpm_args3.res	2018-05-11 02:59:58.000000000 -0400
@@ -1 +1 @@
-Already up-to-date.
+Already up to date.
~~~
I didn't find a clear cause after a quick investigation. This PR as a temporary workaround, feel free to investigate and PR a real fix!
> macOS: skip one of the nitpm tests because of locale issues

- lib/config/config.nit
- lib/github/loader.nit
- lib/markdown/nitmd.nit
- tests/sav/example_vsm.res
- tests/sav/nlp_index.res
This PR reworks some aspects of the `lib/config`:
* Add option `-?` as help
* Introduce `--stub-man` option (almost the same thing than in `ToolContext`)
* Make `nitmd` use `config` instead of `opts`
* Define a better `tool_description` for `github/loader`
> lib/config: better tool configuration

- contrib/github_merge/github_merge.nit
- contrib/github_merge/package.ini
- contrib/nitiwiki/src/nitiwiki.nit
- contrib/nitiwiki/src/wiki_base.nit
- contrib/nitiwiki/src/wiki_edit.nit
Modified two contrib projects to make then use `config`:
* `github_merge`
* `nitiwiki`
They now automatically provide the `--stub-manpage` option from `config`.
> contrib: use `config` instead of `opts`

- .gitignore
- lib/github/Makefile
- share/man/Makefile
- share/man/nitpackage.md
- src/nitpackage.nit
This PR adds two new features to `nitpackage`:
* `--check-makefile`: check Makefiles existence for packages and executable modules
* `--gen-makefile`: create Makefiles for packages and executable modules
As example I added new Makefiles (4f948e3) to all lib/ project if none was found.
I also updated some Makefiles from my projects (dbacfc0).
Please only consider the 4 last commits as the rest belongs to #2652, #2653, #2656 and #2657.
> nitpackage: create and check Makefile

- .gitignore
- contrib/github_merge/man/github_merge.man
- contrib/nitiwiki/man/nitiwiki.man
- contrib/nitiwiki/man/wiki_edit.man
- lib/github/Makefile
- lib/github/man/loader.man
- lib/markdown/man/nitmd.man
- share/man/Makefile
- share/man/nitpackage.md
- src/nitpackage.nit
This PR adds two new features to nitpackage:
--check-man: check manpages existence and content for packages and executable modules
--gen-man: create manpages for packages and executable modules
As example I added new manpages (91b9839) to `lib/markdown` and `lib/github`.
Please only consider the 6 last commits as the rest belongs to #2652, #2653, #2656, #2657 and #2662.
> nitpackage: generate and check manpages

- .gitignore
- contrib/brainfuck/Makefile
- contrib/github_merge/Makefile
- contrib/github_search_for_jni/Makefile
- contrib/header_keeper/Makefile
- contrib/inkscape_tools/Makefile
- contrib/memplot/Makefile
- contrib/neo_doxygen/Makefile
- contrib/nitester/Makefile
- contrib/nitin/Makefile
- contrib/nitiwiki/Makefile
- contrib/nitrpg/Makefile
- contrib/refund/Makefile
- contrib/rss_downloader/Makefile
- contrib/sort_downloads/Makefile
- lib/github/Makefile
- share/man/Makefile
- share/man/nitpackage.md
- src/nitpackage.nit
I applied `nitpackage --gen-makefile` (#2662) on contrib:
* generated Makefile for projects without any (76a17aa)
* replaced some existing Makefiles with their generated counterpart (a95be1e)
* manually merged generated rules into existing Makefiles (3b85ec3)
Please consider only these commits as the rest of them belongs to another PRs.
> contrib: generate Makefiles with nitpackage

- src/doc/commands/tests/test_commands_md.nit
> src/doc/commands: fix test class name for `commands_md`

- share/man/nitpackage.md
- src/model/mpackage.nit
- src/nitpackage.nit
This PR adds the option `--check-readme` to the `nitpackage` tool so it can check for existence of README.md files in packages.
> nitpackage: check existence of README.md files

- lib/core/text/abstract_text.nit
Fix and clean doc units from `abstract_text`.
Also added back ticks around deprecated code examples.
Closes #2403.
> lib/core: Fix text tests

- src/testing/testing_doc.nit
- tests/sav/nitunit_args1.res
When docunits are simple (just statements), a single module is generated for all.
Unfortunately, when docunits contains classes or importations, a specific module must be generated for each one of them.
Compiling all these module takes most of the nitunit elapsed time.
This PR tries to compile these non-simple modules at once, thanks to nitc that features invoking it with multiple programs.
Testing with `nitunit lib/popcorn/README.md`
Before:
* cold ccache: 1m3,832s
* hot ccache: 0m23,063s
After:
* cold ccache: 0m44,517s (-30%)
* hot ccache: 0m17,778s (-23%)
> Nitunit: mass compile non-simple docunits

- contrib/benitlux/src/server/benitlux_controller.nit
- contrib/nitiwiki/src/wiki_edit.nit
- contrib/nitrpg/src/web.nit
- contrib/opportunity/src/opportunity_controller.nit
- lib/core/stream.nit
- lib/nitcorn/file_server.nit
- lib/nitcorn/http_response.nit
- lib/nitcorn/reactor.nit
- lib/popcorn/pop_handlers.nit
- tests/sav/test_nitcorn.res
- tests/test_nitcorn.nit
This PR allows to send binaries (and whatever writable document) as bodies in nitcorn's responses.
The reduced use of buffers and copies should also reduce the pressure on the GC and make things faster.
Embrace, extend and extinguish #2703
> Changed nitcorn HTTPResponse body type to Writable

- src/model/model_filters.nit
- tests/sav/nitmetrics_args1.res
Introduce two new model filter options: `is_broken` and `is_generated`.
Nothing new here, only using already defined attributes.
> model_filter: introduce `is_broken` and `is_generated` filters

- lib/core/text/abstract_text.nit
Remove the escaping to ASCII hex value for the `=` char in `escape_to_mk`. It doesn't appear to be necessary, it was not documented and it breaks `nitls` support for `nitpm` packages.
Here's the error raised by `make` when it can't parse an escaped `=`.
~~~
make: *** No rule to make target '/home/xymus/.local/lib/nit/gamnit?3ddepth-vbos/lib/gamnit/bmfont.nit'
~~~
> text: escape_to_mk should not escape =

- src/compiler/separate_erasure_compiler.nit
This fix test_new_native.nit with a more strict compiler
> nitce: do not forgot to autoadapt in native_array_instance

- share/nitweb/directives/entity/card.html
This PR shows the full name of a MEntity in all Nitweb cards.
Example:
Closes #2365.
> nitweb: show full name in mentities cards

- share/nitweb/directives/ui/search-field.html
- share/nitweb/views/catalog/person.html
- share/nitweb/views/search.html
This PR replaces accesses to key `total` by `count` in all Nitweb views.
So the display in not broken.
> nitweb: fix access to query results count

- lib/trees/bktree.nit
This PR introduces a new kind of tree: the BKTree.
This data structure can be used to speed-up the comparison of a string and a collection of strings with Levenshtein distance.
See https://dl.acm.org/citation.cfm?id=362003.362025 for more details.
> lib/trees: introduce BKTree

- lib/vsm/vsm.nit
- src/indexing/code_index.nit
- src/indexing/tests/test_code_index.nit
This PR introduces a new Index based on VSM: CodeIndex, which can be used to retrieve pieces of code from a code query.
Model entities are indexed by their ANode and vectorization is based on model usage such as:
* modules importation                                      
* classes spcialization and refinement                     
* methods calls and refinements                            
Example:                                                   
~~~nit
var index = new CodeIndex(toolcontext)                     
for mentity in mentities do                                
index.index_mentity(mentity)                             
end                                                        
var matches = index.match_code("print \"Hello, World!\"")  
for match in matches do …
> src/indexing: Introduces CodeIndex

- src/doc/api/api_docdown.nit
- src/doc/commands/commands_base.nit
- src/doc/commands/commands_catalog.nit
- src/doc/commands/commands_http.nit
- src/doc/commands/commands_parser.nit
- src/doc/commands/tests/test_commands.nit
- src/doc/commands/tests/test_commands_catalog.nit
- src/doc/commands/tests/test_commands_graph.nit
- src/doc/commands/tests/test_commands_http.nit
- src/doc/commands/tests/test_commands_json.nit
- src/doc/commands/tests/test_commands_json.sav/test_cmd_mentities.res
- src/doc/commands/tests/test_commands_model.nit
- src/doc/commands/tests/test_commands_parser.nit
- src/doc/commands/tests/test_commands_usage.nit
- src/doc/term/term.nit
- src/doc/term/tests/test_term.nit
- src/model/model_collect.nit
- src/model/model_filters.nit
- src/model/model_index.nit
This PR allows the DocCommands to use ModelFilter.
With this, one can setup the filter used by a command from:
* The commands programmatic Nit interface
~~~nit
var filter = new ModelFilter(accept_test = false)
var cmd = new CmdParents(model, main, filter, mentity_name = "MyEntity")
~~~
* The string interface through the CommandParser
~~~raw
[[parents: MyEntity | no-test]]
~~~
* The HTTP interface
~~~raw
/children/MyEntity?no-test=true
~~~
> src/doc/commands: use filters

- lib/core/text/abstract_text.nit
- lib/core/text/fixed_ints_text.nit
While doing the Advent of Code 2018 in Nit, I encountered a file with numbers prefaced with a plus (+) sign. The to_i of Text wasn't able to handle that kind of input so I added it.
The PR add handling of prefacing + signs with the current - sign implementation. Also added the same logic to is_int so that assert can work. Added new tests in the documentation to show normal usage.
Signed-off-by: Hugo Leblanc <dullin@hololink.org>
> lib/core: handling of plus (+) sign when using to_i with Text objects

- misc/docker/ci/Dockerfile
- misc/docker/ci/README.md
This prepares a new image that we will use for continuous integration.
Basically, it is a lot of stuff required by tests, libs and contribs of nit, but without nit
> docker: add image for continuous integration (without nit)

- tests/base_autocast.nit
- tests/sav/base_autocast_alt2.res
Versions of gcc between bellow 6.4.1 and 7.3.1 failed to compile
correctly the generated C.
So this changes the Nit, so the C can be compiled with buggy gcc versions.
Cf https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85244 for details
> tests/base_autocast: workaround a gcc bug

- lib/github/api.nit
- lib/popcorn/pop_repos.nit
- tests/gitlab_ci.skip
- tests/tests.sh
When run is a containerized environment, some tests may behave differently.
This prepares some special cases for them.
Cf #2732
> tests.sh: special case when running in gitlab_ci

- lib/curl/curl.nit
- lib/curl/extra.nit
- lib/neo4j/neo4j.nit
- lib/popcorn/pop_auth.nit
- tests/test_curl.nit
This PR brings 2 main changes:
* The handle to a Curl request is now kept by the `CurlRequest` instances, instead of being shared by all requests. This makes it possible to execute concurrent HTTP requests.
* Intro two new services on `Text` to execute simple HTTP requests. While these new services are useful to simple scripts, if more control is needed you should still use `CurlHTTPRequest`.
`Text::http_get` makes a GET request and returns the response body.
`Text::http_download` makes a GET request and saves the response body to a file.
> curl: fix concurrent requests and intro shortcut services for scripts

- .gitlab-ci.yml
- lib/android/README.md
- misc/docker/ci/Dockerfile
- share/android-bdwgc/setup.sh
- tests/gitlab_ci.skip
Add android test and build to gitlab-ci. This also fixes some issues.
Note: the version of the android tools are not the most recent. Trying to update the android toolchain to a more modern one should be done in another PR.
Prof of concept: https://gitlab.com/nit/nit-ci/-/jobs/164255403/artifacts/browse/apk/
> gitlab-ci: add android

- .gitlab-ci.yml
- contrib/nitrpg/src/game.nit
- contrib/nitrpg/src/test_helper.nit
- contrib/nitrpg/src/web.nit
- lib/github/loader.nit
- lib/mongodb/mongodb.nit
- lib/neo4j/neo4j.nit
- lib/popcorn/README.md
- lib/popcorn/examples/mongodb/example_mongodb.nit
- lib/popcorn/pop_repos.nit
- lib/postgresql/postgres.nit
- misc/docker/ci-local/README.md
- misc/docker/ci-local/docker-compose.yml
- misc/docker/ci/Dockerfile
- tests/gitlab_ci.skip
- tests/test_neo.args
- tests/test_neo4j.nit
- tests/test_neo4j_batch.nit
- tests/test_postgres_native.nit
- tests/test_postgres_nity.nit
Testing nit with various services is a PITA.
The previous solution was to test them on localhost and requires that the services are available and configured on each test node (it is not always as easy as it seems).
Another problem with `localhost` is that testing within docker is complex as running multiple services in a single container is discouraged.
Here, we propose to simply move the service from localhost to specific hostnames.
This is to be the current "good" practice and is supported out-of-the-box bu various CI infrastructure including gitlab-ci.
> Ci: move services to specific hostnames

- contrib/benitlux/src/client/android.nit
- lib/android/NitActivity.java
- lib/android/activities.nit
- lib/android/assets_and_resources.nit
- lib/android/bundle/bundle.nit
- lib/android/intent/intent_api10.nit
- lib/android/nit_activity.nit
- lib/android/service/NitService.java
- lib/android/service/at_boot.nit
- lib/android/service/service.nit
- lib/android/shared_preferences/shared_preferences_api10.nit
- lib/android/shared_preferences/shared_preferences_api11.nit
- lib/android/ui/ui.nit
- lib/java/NitObject.java
- lib/java/ffi_support.nit
- src/c_tools.nit
- src/compiler/abstract_compiler.nit
- src/compiler/compiler_ffi/light.nit
- src/ffi/cpp.nit
- src/ffi/extra_java_files.nit
- src/ffi/java.nit
- src/ffi/light_ffi.nit
- src/ffi/objc.nit
- src/interpreter/dynamic_loading_ffi/on_demand_compiler.nit
- src/platform/android.nit
- tests/gitlab_ci.skip
- tests/test_ffi_java_annot_files.nit
This PR improves the type safety of the Java FFI and fixes a bug with pointers to Nit objects at the same time.
* The main change is the introduction of the Java class `NitObject` used as a general type for Nit objects referenced from Java code. It replaces the use of a simple `int` holding the pointer value, which was the source of the Java FFI bug.
* Change internal pointers to Nit object to use the Java primitive types `long` instead of `int`, addressing to the same pointer bug. Only low-level services should still use `long` this way, in this case it is the support for Android that relies mostly on the FFI with C.
* Change the annotation `extra_java_files` to accept the full name of Java classes (package + class) instead of the path to the Java source file. The compile still looks for …
> Java FFI: use class NitObject for references to Nit objects from Java

- misc/docker/ci/Dockerfile
Or else gradle fails with an exception
> ci: nitlang/nit-ci docker image runs in UTF8

- .gitlab-ci.yml
- misc/jenkins/check_manpages.sh
- tests/tests.sh
Add 3 CI jobs for macOS, equivalent to `build_tools`, `test_some` and `test_full_nitcs`. They are executed by a shell executor on a macOS host, Nit Gitlab repos should have a such a runner with the tag `macos`. The new jobs are similar enough to the GNU/Linux versions that they can share the same script.
This PR also fixes 3 problems with macOS portability:
* Workaround for the error with kqueue on libevent and nitcorn clients.
* Set `sed -E` explicitly in `check_manpages.sh` for portability with macOS.
* Download bdwgc in the CI docker image, to prevent `test_full_nitcs_macos` to fail on `hello_ios` because it downloads bdwgc at compilation and prints to the test output. This will require regenerating the official Docker image.
> CI: macOS jobs for Gitlab CI

- lib/core/bytes.nit
Adding the redef of the `has` method  to take care of the negative numbers
Signed-off-by: Florian Deljarry <deljarry.florian@gmail.com>
> lib/core/bytes: Add a redef of has method

- lib/core/collection/abstract_collection.nit
- lib/core/stream.nit
- tests/sav/test_file_read3.res
- tests/test_file_read3.nit
The logic behind LineIteraor (and the contracts of the iterators methods) was broken because of a bad management of the cache.
Instead of solving it locally, this PR introduces a simple CacheIterator abstract class with the correct behavior and simplify LineIteraor by using it.
> Fix LineIterator

- lib/github/loader.nit
- lib/logger/logger.nit
- lib/logger/package.ini
- lib/popcorn/README.md
- lib/popcorn/pop_logging.nit
- lib/popcorn/pop_tracker.nit
- src/nitweb.nit
Create a new `Logger` with a severity level threshold set to `warn_level`:
~~~nit
var logger = new Logger(warn_level)
~~~
Messages with a severity equal or higher than `warn_level` will be displayed:
~~~nit
logger.error "Displays an error."
logger.warn "Displays a warning."
~~~
Messages with a lower severity are silenced:
~~~nit
logger.info "Displays nothing."
~~~
`FileLogger` can be used to output the messages into a file:
~~~nit
var log_file = "my.log"
logger = new FileLogger(warn_level, log_file, append = false)
logger.error("An error")
logger.info("Some info")
logger.close
assert log_file.to_path.read_all == "An error\n"
log_file.to_path.delete
~~~
Each message is associated with a level that indicate its severity.
Only messages with a severity equal to or higher than the logger …
> Introduce `Logger`, a simple yet powerful logging system

- contrib/nitiwiki/src/wiki_base.nit
- lib/config/config.nit
- lib/github/loader.nit
- lib/ini/README.md
- lib/ini/ini.nit
- lib/ini/package.ini
- src/doc/commands/commands_ini.nit
- src/loader.nit
- src/nitpackage.nit
- src/nitpm.nit
This version follows more closely the INI specification (https://en.wikipedia.org/wiki/INI_file) and adds some improvements to the API.
Spec changes:
* Allow `#` and `;` for comments
* No more sections nesting as by the spec (which actually change nothing see below)
API changes:
* Renaming `ConfigTree` -> `IniFile` (as it's no more a "tree")
* No more coupling with a file path, use utility methods `load_string`, `load_file`, `write_to`  instead
* Ability to iterate keys, values, sections and section content
* Ability to create `IniSection` by hand
* `IniFile` and `IniSection` implements `Map[String, nullable String]`
The biggest change is that sub-sections are now flattened.
Before, with the following ini:
~~~ini
[section1]
key1=value1
[section1.section2]
key2=value2
~~~
You would get …
> Follow the INI specification

- .gitlab-ci.yml
- doc/manual/.gitignore
- doc/manual/Makefile
- doc/manual/attribute.md
- doc/manual/basic_type.md
- doc/manual/class.md
- doc/manual/constructor.md
- doc/manual/genericity.md
- doc/manual/makedoc.sh
- doc/manual/method.md
- doc/manual/module.md
- doc/manual/nitlanguage.sty
- doc/manual/nitreference.tex
- doc/manual/structure.md
- doc/manual/syntax.md
- doc/manual/variable.md
- doc/manual/virtual_type.md
The manual is slowly bit rotting in the wiki (the disclaimer in http://nitlanguage.org/manual/ and the link to the very old issue  #761 is not a nice thing to have).
The idea is to move back the documentation in the main repository so that PR that enhance the language should also update the manual.
We could add checks to ensure that new AST element or annotations implies some update in the manual.
It is what is currently done with the manpages of the tools, and they are quite complete and up to date.
> Move back manual to the main repo

- .gitlab-ci.yml
- README.md
- src/Makefile
Since #2615 we broke the initial build according to the documentation since nitpm (picnit) requires libcurl.
To minimize the number of doc to update I just moved `nitpm` to the "more" set of tools and documented their requirements.
I also added a CI job to avoid future failures (note: I'm not sure how to adapt it on other docker-less platforms).
> Update basic requirements and document them

- src/doc/commands/tests/test_commands.nit
- src/doc/templates/tests/test_json_model.nit
- src/doc/templates/tests/test_json_model.sav/test_modules_to_full_json.res
- src/frontend/test_frontend.nit
- src/indexing/tests/test_code_index.nit
Sometimes we need to test things related to a model and it's not easy to do this with NitUnit since creating
a model by hand is tedious.
With the `TestModel` abstract suite it's easier:
```nit
module my_test is test
import test_frontend
class MyTest
super TestModel
test
redef var test_src = "path/to/files"
fun my_test is test do
assert test_model.mmodules.length == 1
end
end
```
> Introduce `test_frontend`

- .gitlab-ci.yml
When there is no change in watched nit files, the job `nitunit_some` failed.
> fix ci nitunit some

- .gitlab-ci.yml
- contrib/nitcc/src/autom.nit
- contrib/nitcc/tests/t
Since #2573, some nitcc tests failed on a self-check (because the trim function did not correctly remove tags on trimmed nodes).
The bug was benign and easily fixable, but the subversion of the expectation was that the script kind of forgot about correctly reporting the error (an error message was printed but a success error code was returned). So the whole CI job was a success as failed tests where unreported.
Reported-by: Florian Deljarry <deljarry.florian@gmail.com>
> fix nitcc assert failure and nitcc continuous integration

- lib/core/text/abstract_text.nit
- src/compiler/abstract_compiler.nit
Add a little improvement of the abstract_compiler to generate a Float value by the usage of the `value` and not the `n_float`.
Add the float conversion in exponential hexadecimal notation.
```
assert 12.345.to_hexa_exponential_notation    == "0x1.8b0a3d70a3d71p+3"
assert 12.345.to_hexa_exponential_notation.to_f == 12.345
```
Take into account the scientific notation for the display.
> abstract_compiler: Replace the use of `n_float` by the `value`

- lib/mongodb/mongodb.nit
The test assumed the query would return in some order when it is not.
Added a "$sort" stage to the pipeline to avoid miss index asserts.
This PR fixed gitlab-ci test pipeline.
Signed-off-by: Louis-Vincent Boudreault <lv.boudreault95@gmail.com>
> mongodb: Fixed failing test for `aggregate` method.

- lib/core/text/u16_string.nit
This module is meant to ease the use of complex string operations provided by the ICU library. The module provides a wrapper for ICU's string structure : `UChar *` as well as conversion fucntions to/from `String` and `CString`
- In order to convert a `String` to a `U16String`, the string must be converted to a `CString` first. Since `CString`'s are null temrinated, `U16String`'s also have to be null terminated and cannot have embedded termination characters.
- I am having some issues with DocUnits blocs thus there are no tests in the comments at the moment.
- I added an other `new` operator to the `CString` class which only returns a `null` string
> Wrapper of ICU's UTF-16 encoded strings and conversion

- .gitlab-ci.yml
In parallel, a new Gitlab Runner tagged "windows" was added. This new test only builds the project.
> Adding a Windows build test

- lib/graph/digraph.nit
- src/catalog/catalog.nit
- src/doc/commands/tests/test_commands_catalog.nit
- src/doc/static/static_structure.nit
- src/model/mmodule.nit
- src/model/mpackage.nit
- src/nitcatalog.nit
- src/nitdoc.nit
- src/nitweb.nit
- src/nitx.nit
Added a `mpackage_importation_hierarchy` graph to keep the hierarchy of packages. The packages relations are defined when the `set_imported_mmodules` is called. 
This pr is related to the programming by contract. The objective is to determine when the use of a contract is necessary in a given context.
Note in this graph all the packages are in relation with themself.
example for all nitc package hierarchy :
This pr has a dependency with the #2784
> model: Add `mpackage` importation hierarchy

- lib/functional/functional_gen.nit
- lib/functional/functional_types.nit
- src/compiler/abstract_compiler.nit
- src/interpreter/naive_interpreter.nit
- src/semantize/typing.nit
- tests/syntax_callref.nit
Extended the functional type hierarchy to include RoutineRef type (aka function pointer).
Added type resolution on callref expression :
```
import functional
fun toto(x: Int) do print x
var x = &toto
assert x isa ProcRef1[Int]
```
> Callref types

- src/astbuilder.nit
- src/test_astbuilder.nit
- tests/nitcg.skip
- tests/niti.skip
- tests/nitvm.skip
- tests/sav/test_astbuilder.res
- tests/sav/test_astbuilder_args1.res
- tests/test_astbuilder.args
- tests/test_astbuilder/test_astbuilder.nit
- Now all the nodes of the ast is cloneable. Currently just a part of node have an implemented clone method.If we clone a node by default (not implemented) the program abort and print the following message: `The clone method is not implemented for ATestNode class.`. Currently the library is in **test** phase. You can have "maybe" some bug with the clone.
- Add a method to make the creation of a callsite easier.
Currently i am working on a test to make sure the result clone is the same as the original.
> astbuilder: First implementation of clonable for ast nodes

- .gitlab-ci.yml
- doc/manual/attribute.md
- doc/manual/constructor.md
- doc/manual/method.md
- doc/manual/module.md
- doc/manual/structure.md
- doc/manual/variable.md
Since the manual is now back in the repository, just use niunit to check the example.
Some examples needed to be updated
* renaming things to avoid conflicts
* using real expression and statements (and not placeholders)
* add `nitish` for example with explicit static or dynamic errors
> nitunit the manual

- lib/core/collection/sorter.nit
Fixed a bug where quick_sort could access out of bound element when `to` argument smaller or
equal to 0.
var xs = [1]
default_comparator.quick_sort(xs) # assertion failed
var xs = [1]
default_comparator.quick_sort(xs)
assert xs == [1] # true
Signed-off-by: Louis-Vincent Boudreault <lv.boudreault95@gmail.com>
> Fixed quick_sort when array is length 0 or 1

- .gitlab-ci.yml
This should fix recent CICD issues
> gitlabci: no auth for postgress in tests

- src/frontend/serialization_model_phase.nit
- src/modelize/modelize_property.nit
This pr split the `build property` method into several methods. The objective is to be able to build the entities of the model (read, write...) more independently according to the current state. The construction of the signature was also split for the same purpose.
> modelize_property: Split the build_property method of AAttrPropdef

- src/semantize/typing.nit
Add a way to type an `AExpr` individually.
In my case this method is used in order to type expressions provided for the `old()` in ensures contract.
> typing: Add `do_typing` on AExpr

- src/modelize/modelize_property.nit
Add a way to associate a `nclassdef` with its `mclassdef` without verification.
Currently, to attach an AClass with an MClass, you must use the `build_property` method which performs all the checks and builds the representation in the model. Thanks to the Nitbuilder which facilitates the construction of entities, we find ourselves in a case where we can build the representation of a class in the model and then build the corresponding ast. It is therefore necessary to provide a service to associate the both elements.
> modelize_property: Add `unsafe_add_mclassdef2nclassdef`

- src/modelbuilder_base.nit
Definition of ANode as nullable. When you create entities manually there is not necessarily a current attachment point (in the ast). It is therefore more practical to provide a service with the ANode which can be null.
In addition, the `fun error (n: nullable ANode, text: String)` method that will be called already handles this case.
> modelbuilder_base: Define ANode as nullable

- src/contracts.nit
This pr integrate: 
- Minor documentation changes
- Addition of the `in_contract` attribute to disable verification of contracts when we are already in verification.
- Improved signature management
This pr depends of #2815 #2816 #2817 #2820
> Contract refactoring

- src/compiler/abstract_compiler.nit
- src/compiler/global_compiler.nit
- src/compiler/separate_compiler.nit
- src/compiler/separate_erasure_compiler.nit
- src/contracts.nit
- src/nit.nit
- tests/sav/nit_args9.res
This pr introduces a new hook method in the execution of the `process_nmodule_after_phases` phases. This method makes it possible to analyze each module again after the execution of all phases in order to benefit from the information of the whole program.
This method is useful in the context of contracts. Example:
```nit  
module b
redef class A
redef fun foo
is
ensure(result > 2)
do
return 2
end 
end
var a = new A
a.bar
```
```nit
module a
class A
fun foo: Int do
return 1
end
fun bar do
self.foo
end
end
```
Actually, when you call the foo property in the bar method, no contract is called, while a postcondition was added by refinement in the `b` module. In fact it was not possible to call the contract face because it was not yet introduced during the analysis of module `a`. It is now …
> phase: Introduction of new hook method

- src/contracts.nit
- tests/contracts_null_parameter.nit
This pull request fixes a bug when the contract is used with a `null` argument omitted.
> Contract: Fix null argument error 

- CONTRIBUTING.md
- README.md
- doc/manual/basic_type.md
- doc/manual/class.md
- doc/manual/constructor.md
- doc/manual/method.md
- doc/manual/module.md
- doc/manual/nitreference.tex
- doc/manual/structure.md
- doc/manual/variable.md
- src/metrics/mclassdef_collect.nit
- src/metrics/method_analyze_metrics.nit
- src/test_test_phase.nit
This PR is fairly basic and only contains the following changes:
- Corrected various sentence structures, typos and text formatting across several markdown pages (language doc, README, etc.)
Note: There are a few sections I would rewrite differently to sound more professional/neutral and to include more details about how the language behaves in certain cases, but I felt like it was outside of this PR's scope.
> doc: fixed some typos and other misc. corrections

- contrib/nitcc/src/grammar.nit
- contrib/nitcc/src/nitcc.nit
This draw runnable pure LR0 automation that should scale because there is no much annotation.
Here an example with tests/not_slr.sablecc. The conflicting state, with two actions, is red
> nitcc: add LRAutomaton::to_dot_lr0

- src/astbuilder.nit
- src/contracts.nit
- src/frontend/explain_assert.nit
- src/semantize/typing.nit
First, a helper interface, `TypeContext`, is extracted from `TypeVisitor`
Then `CallSiteBuilder` is created and used.
> New class and facility CallSiteBuilder

- doc/manual/virtual_type.md
This takes the better manual documentation from the nit website.
> Replace Virtual type documentation with updated version.

- src/astbuilder.nit
- src/contracts.nit
- src/examples/module_fictive.nit
- src/examples/module_injected.nit
- src/ffi/header_dependency.nit
- src/nit.nit
- src/parser/parser_nodes.nit
- src/toolcontext.nit
- tests/nitcg.skip
- tests/niti.skip
- tests/sav/module_fictive.res
- tests/sav/module_injected.res
This fix small bugs and add a full example of a synthetic module that prints 42
> Improve the usability of ASTBuilder

- contrib/nitin/nitin.nit
- src/interpreter/naive_interpreter.nit
- src/semantize/typing.nit
Some low-hanging-fruit optimizations in the interpreter. Most are simple caching.
The improvements are impressive for microbenches
```
$ ./difftime.sh nit ./nit fib.nit 28
+ nit fib.nit 28
317811
User time: 6.19
+ ./nit fib.nit 28
317811
User time: 2.08
Gain: 66.397
```
But less impressive for more complex programs
```
$ ./difftime.sh nit ./nit nit.nit ../tests/base_simple3.nit
+ nit nit.nit ../tests/base_simple3.nit
1
2
3
4
5
6
7
8
9
10
User time: 2.42
+ ./nit nit.nit ../tests/base_simple3.nit
1
2
3
4
5
6
7
8
9
10
User time: 1.96
Gain: 19.008
```
> niti: cache anchor_to and some other optimizations
